### ISSUE TITLE
Date of Birth Bug[BUG] 

### ISSUE THREAD

**Issue by akhilkareemta** [AmruthPillai/Reactive-Resume#1001]
**Describe the bug**

When i entered my Date of birth as November 24,1992.. it shows one day before, ie., Nov 23,1992. 

Its the same when i tried with other dates in november.

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'rxresu.me'
2. Click on 'login'
3. Scroll down to 'enter date of birth'

**Expected behavior**

When entering a number, It should display that exact number.

**Screenshots**
screenshot taken and attached

![image](https://user-images.githubusercontent.com/113323924/189567027-e4848361-540e-4c05-9e10-6f5d911ee204.png)

**Desktop (please complete the following information):**

- OS:  Windows
- Browser  Brave
- Version 

**Additional context**

**Comment by AmruthPillai** [comment]
@akhilkareemta Could you re-edit the date now, and check if this issue still occurs? I made some updates in the latest release (v3.6.6), but I'm having a hard time trying to replicate the issue.
