### ISSUE TITLE
[BUG] When choosing a different language, the dates are change correctly on the app but  when downloaded, the date remain in English

### ISSUE THREAD

**Issue by DOLAN-STAP** [AmruthPillai/Reactive-Resume#1003]
It's simple, I switch from English to French in "Settings" and on the website the dates changed correctly (example : "Feb 2021" -> "févr. 202" ; "Aug 2021" -> "août 2021"...), but when I exported the resume in pdf, the file downloaded had the English dates ("Feb 2021" instead of "févr. 2021")

- OS: Windows 8.1
- Browser Chrome
- Version v3.6.5 (written at the bottom of the website)

**Comment by AmruthPillai** [comment]
This should be fixed in v3.6.6
