### ISSUE TITLE
[BUG]  Import From Reactive Resume json v2 does not work

### ISSUE THREAD

**Issue by Robertschv** [AmruthPillai/Reactive-Resume#1008]
I have my CV saved with rxresu.me, I export my CV as a .json, and then I tried to re-import as .json v2, it doesn't work. The CV just says "undefined undefined"

I tried with .json "v1" and it works, but not the v2.

![grafik](https://user-images.githubusercontent.com/62678042/191759650-e913c2cb-0934-46b9-bf4e-cc39a7a8b597.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version 104

**Comment by indivisionjoe** [comment]
Same issue here...

**Comment by Robertschv** [comment]
Now there is no 'JSON v1' anymore, just 'JSON' and 'JSON v2 from v2'.

So no more v1, just v3 and v2. That's why it doesn't work like before.

I am going to close this issue.
