### ISSUE TITLE
[BUG] Markdown not working for Summary of Leafish template

### ISSUE THREAD

**Issue by AymaneBoukrouh** [AmruthPillai/Reactive-Resume#1010]
Markdown is not working for the Summary section of the Leafish template. 

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Open an existing resume or create a new one
2. Click on Leafish template
3. Type a markdown syntax in Summary section, for example bold text \**text here**
4. Check the Summary section in the actual resume

Error:
![Screenshot 2022-09-26 at 17-11-00 test Reactive Resume](https://user-images.githubusercontent.com/49211158/192327255-a8d113cc-9c29-4aef-9197-b5627a133dcc.png)

Excepted behaviour: 
![Screenshot 2022-09-26 at 17-11-17 test Reactive Resume](https://user-images.githubusercontent.com/49211158/192327230-fa973df7-1cc7-46e2-b39d-902ea0327ede.png)

- OS: Manjaro 22.0.0 Sikaris
- Browser: Firefox
- Version: 104.0.2

**Comment by homahsn** [comment]
I have the same problem, I didn't fix yet

**Comment by AmruthPillai** [comment]
Should be fixed as of v3.6.7
