### ISSUE TITLE
[BUG] On Clicking enter while filling the form, entire website is getting re-loaded.

### ISSUE THREAD

**Issue by jaichaturvedi88** [AmruthPillai/Reactive-Resume#1024]
**Describe the bug**

On Clicking enter while filling the form the page is getting re-loaded.

**Product Flavor**

- [ ] Managed (https://rxresu.me)

**To Reproduce**

1. Open any form to enter data. Let's say interests form. 
2. Type the name of interest
3. Press enter
4. Entire page will be reloaded.

**Expected behavior**

After pressing enter post filling the form, the data should be submitted, instead the page is getting reloaded.

**Comment by kmkhant** [comment]
Hi there, I just fixed the Interest Form locally, I will submit pull request soon. Thanks for the info
