### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by akshbswas98** [AmruthPillai/Reactive-Resume#1027]
**Describe the bug**
The date of birth day part decreases by -1 on downloading. 

**Product Flavor**
https://rxresu.me/biswa.akash.ab/akash-biswas
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Go to date of birth section
2. Click on download as pdf
3. Scroll  to DOB

**Expected behavior**
The date of birth day tag should show the proper day on the downloaded resume as seen on the preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/64808720/194736157-9d7bcc1e-3aec-4970-a006-8a8fe8f945c0.png)
![image](https://user-images.githubusercontent.com/64808720/194736170-5dd7a18d-7dd6-4243-b08c-4dfcc4a8c16b.png)

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by akshitarora921** [comment]
Can I work on this?

**Comment by AmruthPillai** [comment]
> Can I work on this?

Sure, of course :)

**Comment by cocoonkid** [comment]
Came here to report the same.

Happens in the managed version as well (https://rxresu.me/)!

Thanks for fixing this.

**Comment by pranathnaik** [comment]
is this issue fixed?

**Comment by akshitarora921** [comment]
@pranathnaik Still working on it
