### ISSUE TITLE
[BUG] Hyperlink in the Login modal

### ISSUE THREAD

**Issue by SSHSRN** [AmruthPillai/Reactive-Resume#1028]
**Describe the bug**

**Product Flavor**

- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to [this website](https://rxresu.me/)
2. Click on the login button.
3. Hover over the 
```
If you don't have one, you can create an account here.

In case you have forgotten your password, you can recover your account here.

``` 
region.
5. You can notice that there is no hyperlink over the "**here**" part which should be the case in general.
For example, in scenarios like "Forgot your password? click **here** to reset it", the hyperlink is set at the word here and I expected the same in this website too, but that was not the case.

**Expected behavior**

Hyperlink when mouse hovers over the word **here** too.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Microsoft Edge

**Comment by SSHSRN** [comment]
Kindly assign me this issue so that I can fix the bug.

**Comment by AmruthPillai** [comment]
> @AmruthPillai Can I work on this?

Sure, give it a shot :) Would like to see this implemented too.
