### ISSUE TITLE
Can't open an old resume [BUG] 

### ISSUE THREAD

**Issue by Oliverxll** [AmruthPillai/Reactive-Resume#1043]
**Describe the bug**

I'm simply just trying to open the resume as per usual.
The last time I opened it from my phone, using Samsung Browser, I didn't edit anything so I doubt that had any effect on it.

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

Open a resume that's only 7 days old.

**Expected behavior**

To just open my resume.

**Screenshots**

![image](https://user-images.githubusercontent.com/31373796/196010039-0fde9f50-8492-4e17-82fe-0cd03fc137a2.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser Microsoft Edge, I also attempted with Google Chrome with same result.
- Version Latest as of 16/10/2022 (DD/MM/YYYY)

**Comment by AmruthPillai** [comment]
Yes, there was a small issue in the last release and had to push a patch overnight. Sorry for the inconvenience. It should be all fixed now. Thank you for raising an issue in time :)
