### ISSUE TITLE
[BUG] Uploading a non-ZIP file causes server to crash

### ISSUE THREAD

**Issue by marzooqahmed944** [AmruthPillai/Reactive-Resume#1048]
**Whenever I upload a non-zip files in the LinkedIn import section, it crashes the server**

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Go to 'dashboard'
2. Click on 'Import From External Sources'
3. In Import from LinkedIn section, click Upload ZIP Archive button.
4. Upload a file that is not a ZIP
5. See the error in the logs
6. If you reload, the server throws a 504.

**Expected behavior**

Give us an error that the file type is incorrect.

**Desktop (please complete the following information):**

- OS: Windows 10 21H2 Build 19044
- Browser Chrome
- Version 3.6.8+1

**Comment by AmruthPillai** [comment]
Thank you for making me aware of the issue. It is a problem, I agree, but it is unclear why this occurs in the first place. The NestJS service, and the function have clearly been surrounded by a try-catch to catch any and all errors that could arise from the import process, but it still seemed to have crashed the server.

If anyone has any suggestions, please do let me know.
