### ISSUE TITLE
unable to login [BUG] 

### ISSUE THREAD

**Issue by saviodsouza** [AmruthPillai/Reactive-Resume#1065]
**Describe the bug**

 The site rxresume.me appears to be partially down as of the following are working....
- Google login
- native site login
- native site registration

Even a browser logined few days ago can't access the app or resumes created in the past

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'rxresu.me'
2. Click on 'Login or Register'
- Try to login or register

**Expected behavior**

Login should work like before

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by AmruthPillai** [comment]
This should be fixed now, sorry for the inconvenience.
