### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ks9794** [AmruthPillai/Reactive-Resume#1066]
**Unable to login**

Unable to login via google one tap API. 

**Product Flavor**

- [ ] Managed (https://rxresu.me)

**To Reproduce**

1. Go to the website on google chrome.
2. Click on Login.
3. Click on sign in as.
4. Enter credentials and try.

**Expected behavior**

Would login to my account on the website.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by AmruthPillai** [comment]
This should be fixed now, sorry for the inconvenience.
