### ISSUE TITLE
[FEATURE] Ability to only write the year must be added.

### ISSUE THREAD

**Issue by K2adir** [AmruthPillai/Reactive-Resume#1071]
When adding job experience, the UI does not accept only the year. It requires full format XX/YY/ZZ.
Sometimes, we just want to provide the year we started and not the exact date. 

I hope you consider it. 

thank you for such a great tool.

**Comment by AmruthPillai** [comment]
You can enter 01/01 and just the year, and on the settings (right sidebar), you can set the global date format to just display the year. Let me know if this works out for you :)

**Comment by ovizii** [comment]
> You can enter 01/01 and just the year, and on the settings (right sidebar), you can set the global date format to just display the year. Let me know if this works out for you :)

Oh, so this setting is only for “displaying” the date, and does not apply for the backend where we edit/input dates (i.e. birthday, education, etc.)?

![image](https://user-images.githubusercontent.com/837902/221179065-da76d204-5cf9-4cfa-9b60-d13d017cfe4a.png)
