### ISSUE TITLE
[BUG] Formatting issue

### ISSUE THREAD

**Issue by el-kr4k3n** [AmruthPillai/Reactive-Resume#1078]
**Describe the bug**

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Open the template "Oxyn" (Probably with other templates too but I am having issue with this one so I mentioned this template)
2. After adding the Summary section and the Work Experience section, the format is different as it was previously (Attaching some screenshot below).

**Expected behavior**

The expected behaviour is that my text (summary and bullet points) should cover the entire width of the page and not just half of it, I tried finding if I can format it somehow, but unable to find the setting for it. Please help :)
Also the bullet points were black, there is no option to change it too 👎 

**Screenshots**
Expected (This is how my previous cv was formatted in same template)
![image](https://user-images.githubusercontent.com/71029596/201863607-504075b2-a964-443f-8fd2-876e1c2ad15f.png)

Current behaviour(Same template)
![image](https://user-images.githubusercontent.com/71029596/201863992-b1d0c42d-6a19-4eeb-bcc9-3e685a65f1ab.png)

**Desktop (please complete the following information):**

- OS:  Windows 11
- Browser  Chrome
- Version  Version 107.0.5304.107 (Official Build) (64-bit)

**Additional context**

**Comment by Muchori** [comment]
Experiencing the same issue also with other template.

**Comment by arashsm79** [comment]
Check out [this comment](https://github.com/AmruthPillai/Reactive-Resume/issues/1070#issuecomment-1313911022) from issue #1070 for a quick fix. You can also add
```css
.markdown {
    color: #<your-hex-value>;
}
```
to change the color of the text (and bulletins) inside markdown boxes.

**Comment by el-kr4k3n** [comment]
Thank you for replying and for fixing it! :)
