### ISSUE TITLE
[BUG] Format error tried to get it right 

### ISSUE THREAD

**Issue by sasukeuchicha** [AmruthPillai/Reactive-Resume#1085]
**Describe the bug**

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'create resume'
2. Choose the template 'Onyx'
3. Write a summary

**Expected behavior**

The lines of summary breaks near the middle instead it should break at the extreme right

**Screenshots**

The summary breaks at the middle of the page as well as work experience 
![InkedReactive Resume Minor Bug1](https://user-images.githubusercontent.com/32739586/202419813-3cdbb267-e0ce-4024-936c-3e178d314c23.jpg)

but shown in the resume template is as follows
![image](https://user-images.githubusercontent.com/32739586/202420027-74a061ac-5a1a-454f-a1ab-2264a49852db.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: NA 

**Additional context**

**Comment by tryallthethings** [comment]
Hello! I tried to reproduce this, but for me, it looks exactly like it should. See https://rxresu.me/tryallthethings/1085 (Demo data with Onyx template)
Could you please clear your browser cache and try again? Did you maybe add anything unusual (special characters, markdown formattig) in the markdown?

**Comment by sasukeuchicha** [comment]
Hey it works good now. I checked this issue next day right after reporting the bug. I thought someone fixed it. Thank you
