### ISSUE TITLE
currently one header suppose skills in the reactive resume is not being able to split into two parts so that it appears exactly on a A4 size paper , rather it extends the page size to cover all points in the skills section. Will be really thankful if you can add this feature in this sesction

### ISSUE THREAD

**Issue by sagarrastogi29** [AmruthPillai/Reactive-Resume#1086]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atsaloli** [comment]
@AmruthPillai This is a duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/1834  Could we please close it to increase visiblity into open issues?
