### ISSUE TITLE
Ability to display single date for things that have ended

### ISSUE THREAD

**Issue by sonatuzun** [AmruthPillai/Reactive-Resume#1096]
**Is your feature request related to a problem? Please describe.**

I want to use YYYY date format for my resume but it looks ugly for education and projects  that lasted for less than a year (eg: 2017-2017)

Ps: I'm a new grad and I don't remember the specific dates for many of my projects so YYYY format works for me

**Describe the solution you'd like**

If the start and end dates are the same only show one date.

eg:
start date: 2017
end date: 2017
shown: 2017

I think the display date should be considered while determining if the dates are same.

eg: 
if the YYYY format is used 01/01/2017 should be considered same as 08/07/2017
if DD/MM/YYYYY is used instead they won't be considered same

**A clear and concise description of any alternative solutions**

filling out the end date only could display a single date

eg: 
start date: null
end date: 2017
shown: 2017

This might require additional explanation to the users. Might be bad to clutter the interface for a feature that would benefit so few.

**Comment by AmruthPillai** [comment]
I like the idea, and your approach to the solution. Let me look into implementing it soon and it should be in the next release :)

**Comment by AmruthPillai** [comment]
@sonatuzun Went with the above solution. In the next releases, all you would need to do is set the start date and end date to the same date :)
