### ISSUE TITLE
[BUG] : Not able to downlod PDF

### ISSUE THREAD

**Issue by zeba7792** [AmruthPillai/Reactive-Resume#1098]
**Describe the bug**

not able to download pdf since yesterday

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by zeba7792** [comment]
![2022-11-24_115126](https://user-images.githubusercontent.com/118959350/203709453-9166adb1-8bdd-4c78-ba3d-eedecd001f25.jpg)

**Comment by AmruthPillai** [comment]
The issue should be fixed now, sorry for the delay and inconvenience.

**Comment by zeba7792** [comment]
Thank you for your help 😊
