### ISSUE TITLE
[BUG] Profile links do not work in the generated PDF files

### ISSUE THREAD

**Issue by iperx** [AmruthPillai/Reactive-Resume#1112]
**Describe the bug**

Profile links for the Gengar template are inactive in the generated PDF.
The text of the profile links in the Gengar template is always white, regardless of the color scheme. (it either has something to do with the considering issue or is another issue)

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Create a new resume
2. Choose the Gengar template
3. Add any profile in Profiles section (the color of the profile link will be white for any color scheme)
4. Press Export PDF button
5. Open created PDF. The link for the profile does not work.

**Expected behavior**

The link is active in the created PDF file, and the text of the profile link changes depending on the color scheme of the template.

**Screenshots**

Adding a new profile
<img width="571" alt="Creation" src="https://user-images.githubusercontent.com/64926051/204053422-3f99aec0-5304-4b60-a0c7-0437a764e96d.png">

The link is inactive in the generated PDF file (pay attention to the cursor)
<img width="324" alt="Inactive" src="https://user-images.githubusercontent.com/64926051/204053430-a88fd870-5c0c-498b-a149-85032faf4b7f.png">

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser Google Chrome
- Version 107.0.5304.122 (latest)

**Additional context**

Thank you!

**Comment by tryallthethings** [comment]
Can confirm this issue in two templates (Castform and Gengar) that use `textClassName` from `DataDisplay`. See #1114 for potential fix.

**Comment by Ketsueki2b** [comment]
Before exporting in PDF (everything is toggle on!):
![image](https://user-images.githubusercontent.com/23507138/204438773-27276aa0-1b47-45c8-b7d8-853aaf435549.png)

After the PDF export:
![image](https://user-images.githubusercontent.com/23507138/204440053-4bd433cb-3aac-42cc-8d27-8479c66de1e4.png)

In my case, my experiences are generated in blank but only with Gengar, Castform and Glalie templates.

I'm still able to see my experience once generated in PDF from any other template.

PS: we can read my full name but it's ok ;)
