### ISSUE TITLE
[BUG] Other dates are not working as intended

### ISSUE THREAD

**Issue by TheJordanDev** [AmruthPillai/Reactive-Resume#1116]
**Describe the bug**
Last month I posted a similar issue about how the date of birth was displayed as a day before when downloading PDFs, this issue is now gone (thanks) but it seems like more dates are actually affected by this problem.

**Product Flavor**

- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
When I enter a date for a certificate the preview is fine but when downloading the PDF the date is one day before.
*Again, I'm in France if it helps*

**Expected behavior**
The date should be the same in the preview and in the pdf

**Screenshots**
![image](https://user-images.githubusercontent.com/55529456/204099260-21eabbf8-c64b-4593-8c32-611b9633c709.png)

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by nopol10** [comment]
Want to point out that this happens to both the dates on each section as well as date of birth for me

**Comment by TheJordanDev** [comment]
bump

**Comment by AmruthPillai** [comment]
This issue should be fixed as of [v3.6.17](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.17).

**Comment by TheJordanDev** [comment]
Yeah, about that, at least for me, when using the [website](https://rxresu.me/)  it is still off when rendering the PDF.

PDF:
![PDF](https://user-images.githubusercontent.com/55529456/211223207-89a1b7ed-7792-464b-8151-08c551f07af4.png)

Website:
![Website](https://user-images.githubusercontent.com/55529456/211223225-f52db5e6-dd6b-4968-9ff8-3ad4ed3f5cc1.png)

The birthdate is fine though.

Just so you have all informations: I'm in France. Like the last [issue](https://github.com/AmruthPillai/Reactive-Resume/issues/1061#issue-1426074317) I posted said, it may be because of timezone differences when my browser shows me the dates on the page it is in UTC+1, whereas the server where the render is made (I assume the US) is in UTC-5 so this might be why.

*Sorry to

**Comment by TheJordanDev** [comment]
Okay so, after some investigation I found out that I had to rewrite all my dates in inputs to get them to work when rendering.
