### ISSUE TITLE
[FEATURE] Make an desktop app for offline resume creation

### ISSUE THREAD

**Issue by nobaraos12** [AmruthPillai/Reactive-Resume#1119]
**Is your feature request related to a problem? Please describe.**

An offline desktop app 

**Describe the solution you'd like**

an desktop app for linux, windows and mac

**Describe alternatives you've considered**

there are only paid alternatives

**Additional context**

If you make an linux app first it should be appimage so it's portable, then flatpak with flatpak submission, windows and mac support would also be good

**Comment by tryallthethings** [comment]
Hello! 
I doubt that this can be easily achieved without rewriting major parts of the code (if at all). 
But you can already host your own instance offline on your machine with Docker. See https://docs.rxresu.me/source-code/docker for the instructions.

**Comment by kwuite** [comment]
@tryallthethings This is possible by wrapping the entire application with Electron and then it should be distributable on every operating system.

**Comment by AmruthPillai** [comment]
> @tryallthethings This is possible by wrapping the entire application with Electron and then it should be distributable on every operating system.

Not exactly. Yes, the app can be wrapped into an electron package and run anywhere, but it would still need some way to connect to the server (for account creation, downloading the PDF etc.)

Like @tryallthethings said, the best way to accomplish this right now is to host the application locally. This would be the closest thing to running the app on offline mode.

**Comment by nobaraos12** [comment]
it doesn't need to create an account it can be localized
