### ISSUE TITLE
[Feature] contributing to add new features 

### ISSUE THREAD

**Issue by abdelrahmanahmed** [AmruthPillai/Reactive-Resume#112]
Awesome idea and implementation, i was wondering if it is possible to contribute and add new feature (more templates for example or some customization to the current one). I will open an issue first before submitting anything for sure :D

**Comment by AmruthPillai** [comment]
Hey there @abdelrahmanahmed!

It makes me ecstatic and filled to the brim with joy when I see people from across the world willing to use the app itself, much less contribute to it. Thank you so much for showing interest in developing this further. You can take up any change you want on the app, and if you see any issues crop up on GitHub, you can work on those as well once you've assigned it to yourself.

Right now, the whole system of creating templates is a bit too complicated even for me, cause things just keep moving around and around, it's not static. You can take a stab at it by looking at the templates folder and going through the code. It's not really that difficult, just a lot of boilerplate code.

Some other ways you can contribute are by translating the app, which I think you've already done by adding Arabic to the mix. Thanks to you, PR #116 has been merged to add Arabic to the app.

You're helping out as much as you can and that's great. I really appreciate all the efforts, it means so much to be. The only thing left would be to spread the word as much as you can, to those who are in need of a refresh in their resume. 

Thank you so much for the support :)
