### ISSUE TITLE
Docker image build bug

### ISSUE THREAD

**Issue by alperensayar** [AmruthPillai/Reactive-Resume#1125]
Whn i try to run docker compse file with build code
i got this error
![image](https://user-images.githubusercontent.com/56897887/205461365-65372272-e6e3-4be3-8d20-c0c13bf4a49d.png)

**Comment by AmruthPillai** [comment]
Could you try again now, this error should be resolved.
Otherwise, please consider using the Gitpod method that's introduced now.
