### ISSUE TITLE
Support for Extended Markdown Syntax

### ISSUE THREAD

**Issue by omarzd** [AmruthPillai/Reactive-Resume#1132]
Can we have support for Extended Markdown Syntax? That includes emojis and other features as shown in [this page](https://www.markdownguide.org/cheat-sheet#extended-syntax).

**Comment by AmruthPillai** [comment]
Working on this currently. In a future update, you should be able to add any kind of markdown styling to your resume. You can even add mathematical notations using KaTeX.

<img width="776" alt="Screenshot 2022-12-17 at 10 14 34 AM" src="https://user-images.githubusercontent.com/1134738/208234899-143c3ba3-b76a-4292-b9b7-413b2918e07c.png">
