### ISSUE TITLE
[FEATURE] Ability to hide specific elements like we can hide sections

### ISSUE THREAD

**Issue by Luk164** [AmruthPillai/Reactive-Resume#1142]
**Is your feature request related to a problem? Please describe.**
My manager likes this software but she would like to be able to turn off different sections depending on the customer the resume is presented to. For example only showing relevant experiences or skills.

**Describe the solution you'd like**
Same icon as we already have to hide sections but for each individual entry.

**Describe alternatives you've considered**
Nothing really comes to mind.

![image](https://user-images.githubusercontent.com/30559213/208454972-f55d9e64-dfe4-4161-9e16-61cf2b71a0ab.png)

**Comment by oneilldt** [comment]
I'm also looking for this enhancement.

**Comment by ChristianVaughn** [comment]
Just adding on to say this would be a great feature. When trying to apply for different positions it would be nice to just have all the projects, or work experience in one resume then toggle some of them on or off. Would be easier than we don't have to make multiple projects with duplicate data

**Comment by klosedan** [comment]
I'm also looking for this enhancement.

**Comment by AmruthPillai** [comment]
This will be one of the features in the upcoming overhauled version, among other things :)

**Comment by sepsol** [comment]
+1

**Comment by AmruthPillai** [comment]
![Screenshot_20240329_215551_Chrome](https://github.com/AmruthPillai/Reactive-Resume/assets/1134738/af05b51e-70d1-4d22-9172-0f403f4c5c67)

Right clicking, or long pressing (on mobile), on the item should give you a toggle "Visible" which would allow you to enable disable specific row items.

**Comment by Luk164** [comment]
@AmruthPillai No, you misunderstood. That option has been there before this ticket was created. What I meant is toggling visibility on each individual entry, as in for example hiding a specific college instead of the whole education section.

**Comment by AmruthPillai** [comment]
> @AmruthPillai No, you misunderstood. That option has been there before this ticket was created. What I meant is toggling visibility on each individual entry, as in for example hiding a specific college instead of the whole education section.

That's exactly what the above screenshot demonstrates. I invite you to try the app, right click on an individual entry, like a college, and you should be able to hide/show the item.

**Comment by Luk164** [comment]
> meant

Ok, I am stupid, I was trying it on phone to see the latest change and I thought your response was showing the three dot menu. Thank you very much!
