### ISSUE TITLE
[BUG] Pdf exports whitespaces instead of images

### ISSUE THREAD

**Issue by romadryud** [AmruthPillai/Reactive-Resume#1152]
**Describe the bug**

Hi, when I try to export pdf I have whitespace instead of profile photo, but it's appearing in app page and in pdf link preview.

**Product Flavor**

- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Upload profile photo
2. Export pdf

**Expected behavior**

Image must be appear instead of whitespace.

**Desktop (please complete the following information):**

- OS: macos 13.0.1 (22A400)
- Browsers:
- - Arc (0.81.2)
- - Microsoft Egde (108.0.1462.54 (Official build) (arm64))
- - Google Chrome (108.0.5359.124 (Official Build) (arm64)) 

**Additional context**

I've tried to export it to json and open image url, but seems I missing some credentials like exporter.

https://cdn.rxresu.me/uploads/20400/55054/1651680927417.png

![image](https://user-images.githubusercontent.com/19193036/209677397-9c8f652e-256b-4127-a651-0fddecb89a88.png)

**Comment by romadryud** [comment]
Also when I try to export in incognito it's works again.

**Comment by AmruthPillai** [comment]
This issue should be fixed as of [v3.6.17](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.17), but I'd still keep an eye out as I was not sure what actually caused it to be sure.
