### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Hemazyn** [AmruthPillai/Reactive-Resume#1154]
Could not download image with the resume also.
[RxResume_PDFExport_hemazyn_myresume_1672219932.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/10318648/RxResume_PDFExport_hemazyn_myresume_1672219932.pdf)
[RxResume_PDFExport_hemazyn_myresume_1672219666.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/10318649/RxResume_PDFExport_hemazyn_myresume_1672219666.pdf)

**Comment by AmruthPillai** [comment]
This issue should be fixed as of [v3.6.17](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.17), but I'd still keep an eye out as I was not sure what actually caused it to be sure.
