### ISSUE TITLE
Add icons for Codeberg and Mastodon

### ISSUE THREAD

**Issue by andywenk** [AmruthPillai/Reactive-Resume#1163]
Thanks a lot for Reactive-Resume. It's awesome!

I added two links to `Profiles`where no icon is available yet. It would be cool if you add them:

Mastodon - https://joinmastodon.org/
Codeberg - https://codeberg.org/

 Thank you very much

**Comment by AmruthPillai** [comment]
The new icons should be available as of [v3.6.17](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.17).

**Comment by andywenk** [comment]
Wow awesome. Are you also upgrading the web application? I use it there ... Thanks again for that cool service 😊

**Comment by AmruthPillai** [comment]
@andywenk Yes, the web app get updated to the latest version automatically when I make a GitHub release here :) The managed web app would always be my main priority.

**Comment by andywenk** [comment]
awesome - thanks so much! ;-)
