### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BhumikGangwani** [AmruthPillai/Reactive-Resume#1177]
**Describe the bug**

The create account form does not submit for me.

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:  macOS
- Browser  safari
- Version 

**Additional context**

**Comment by AmruthPillai** [comment]
The issue was that the error message was not being displayed on the app, this should be fixed with this commit https://github.com/AmruthPillai/Reactive-Resume/commit/5024c19f87d942b5ded833a2b8b514f18999013d and should be available on the app soon :)
