### ISSUE TITLE
[BUG] Resume layout does not match preview

### ISSUE THREAD

**Issue by wiryadev** [AmruthPillai/Reactive-Resume#1186]
**Describe the bug**

Resume has two column layout instead of single column like in previews. So the next item is shown below, not beside.

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

Choose Onyx style

**Expected behavior**

I expect it to be single column like in this previews.
<img width="508" alt="Screen Shot 2023-01-16 at 21 36 41" src="https://user-images.githubusercontent.com/26060382/212710272-76518a1b-6bde-40cb-803b-57c805ce736e.png">

**Screenshots**

<img width="481" alt="Screen Shot 2023-01-16 at 22 14 45" src="https://user-images.githubusercontent.com/26060382/212711429-684a7ee6-30e7-4fa6-8fa5-1471235fdbc4.png">

**Comment by AmruthPillai** [comment]
You would need to change the number of columns for your section to match with the screenshot's layout. You can do this with the option button below each section, as shown in the screenshot below.

<img width="282" alt="Screenshot 2023-01-18 at 9 39 51 PM" src="https://user-images.githubusercontent.com/1134738/213289778-5b265537-ecfc-4f26-8bf8-a9116cebdcc1.png">
