### ISSUE TITLE
[FEATURE] Date of work experience without day

### ISSUE THREAD

**Issue by kaname-png** [AmruthPillai/Reactive-Resume#1191]
**Is your feature request related to a problem? Please describe.**
Determining the exact start and end date of a work experience is a bit difficult.

**Describe the solution you'd like**
Only be able to enter the month and year of the work experience.

**Describe alternatives you've considered**
Put the month and year together with the 1st of each month, which is not the best.

**Additional context**
Nop.

**Comment by cfelicio** [comment]
Good suggestion!

**Comment by AmruthPillai** [comment]
Right now, you can select the start and end date of your work experience, but change the date format in the right sidebar settings. You should be able to find this in the resume settings section of the right sidebar, near app language.

Hope that resolves your issue :)
