### ISSUE TITLE
Let user set the Image Size for the Resume

### ISSUE THREAD

**Issue by aka-0x4C3DD** [AmruthPillai/Reactive-Resume#1205]
**Is your feature request related to a problem? Please describe.**

It's frustrating to set the image size using CSS. 

**Describe the solution you'd like**

Therefore, it would be helpful if image size settings could be added, which is easy to use. 

**Describe alternatives you've considered**

As a CSS comment, add how to set the height & width of the Resume Image.

**Additional context**

![Screenshot 2023-01-29 at 09-14-25 Comprehensive-General Reactive Resume_change](https://user-images.githubusercontent.com/93938476/215303861-e56bc3f6-a2a1-4736-a89a-c1d5152bfd6f.png)
I want the red pointer box width to equate with the blue pointer width, while maintaining the aspect ratio of the picture.

**Comment by AmruthPillai** [comment]
Looks like you already found the feature, but for future reference for anyone looking for this, you can already do this inside the Photo Filters dialog :) 

<img width="437" alt="Screenshot 2023-01-30 at 8 42 26 AM" src="https://user-images.githubusercontent.com/1134738/215416784-77cd5293-0590-451a-97ee-d6b5ae290b37.png">
