### ISSUE TITLE
[FEATURE] Can we please get more control over the display of the address?

### ISSUE THREAD

**Issue by ovizii** [AmruthPillai/Reactive-Resume#1237]
**Describe the solution you'd like**

Currently, if I fill in all address fields, they are simply separated by a comma and placed inside a SPAN tag, so we have no control in which order to put the fields nor can I style them or separate them to have the different components of the address on different lines.

**Comment by Nikotine1** [comment]
+1

**Comment by tim-the-arcane** [comment]
+1

I also think this is a must have for international usage.

In other countries, for example Germany, there is a different standard for the order or general appearance of address elements:

1. Street
2. ZIP code
3. City
4. Region is redundant mostly, it's a rather small country and the ZIP code is enough
5. Country
