### ISSUE TITLE
[Bug] Missing "new line" space after paragraph

### ISSUE THREAD

**Issue by julianxhokaxhiu** [AmruthPillai/Reactive-Resume#125]
**Describe the Bug**
Hi, in the Description field when you type something like:
```
dsfsdfdsf

dsfdsfdsF
```
it creates two paragraphs with no bottom margin between them. Is it possible to add that? There is no possibility to have a visual separation between those otherwise.

**Reproduction**
Steps to reproduce the behaviour:
1. Go to Work Experience
2. Click on Add Work Experience
3. Paste in the Description field this:
```
dsfsdfdsf

dsfdsfdsF
```
4. See right render.

**Expected Behaviour**
A space between paragraphs is present.

**Screenshots**
![image](https://user-images.githubusercontent.com/1237070/79856556-ca5ed100-83cc-11ea-9e34-95f6d2668979.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional Context**
Feel free to ping me anytime if you need more information.

Thank you in advance,
Julian

**Comment by AmruthPillai** [comment]
Hey there @julianxhokaxhiu!

This is a common problem that people face with markdown, it bugged me a lot the first time I found out about it too. Thank you for raising an issue about this.

To put spaces between two lines of text, you just need the right amount of spaces and new line characters. Let me explain with an example:

```
sdadsasd<space><space> 
&nbsp;<space><space> 
asdasdasd
```

Two spaces at the end define a new line in Markdown. As for the second line, you are basically putting an empty character, and again a new line. This will give you the layout you are looking for.

Hope that helps :)

**Comment by julianxhokaxhiu** [comment]
Ah true! I totally forgot about that trick, I'm used to write Markdown so much here on my repos that I forgot about the HTML syntax.

Thank you for the fast response :) And great job!

**Comment by AmruthPillai** [comment]
Haha, yes, they have not made it easy to remember.
And you're welcome, glad I could help in time :)

Thank you so much for supporting the project!

**Comment by netvl** [comment]
@AmruthPillai I believe that two spaces at the end of a line is actually a different thing than paragraphs separation.

Basically, in Markdown you have paragraphs mapped to `<p>` HTML tags, while the two spaces thing map to `<br>`:

```
some paragraph

another paragraph

text with two spaces  
and next line
```

```html
<p>some paragraph</p>
<p>another paragraph</p>
<p>text with two spaces<br>and next line</p>
```

Line break and paragraph are different things: usually paragraphs have much larger separation between them than lines with a line break between them. You can see it right here, on GitHub:

---

This is one paragraph.

This is the second paragraph.

This is a paragraph  
with a newline inside it.

---

It would be really great if rxresu.me supported both line breaks and paragraphs :)
