### ISSUE TITLE
[Feat] Font size option

### ISSUE THREAD

**Issue by manikantag** [AmruthPillai/Reactive-Resume#13]
Having Font size option will be a great feature

**Comment by AmruthPillai** [comment]
This is not that easy, as the fonts within the page itself are all detached from one another, referenced from the main CSS stylesheet. I did try implementing it but seems like there would be a bigger change required to do something this dynamic. Maybe this can be expected in later stages of development, but not right now.

**Comment by manikantag** [comment]
No problem. Thanks
