### ISSUE TITLE
[BUG] Clicking outside of modal doesn't save section data

### ISSUE THREAD

**Issue by mickeymaddula** [AmruthPillai/Reactive-Resume#1301]
**Clicking outside of the modal after filling in section data should be able to save the entered data**

As someone who has just written up a huge content in the summary section, if the user clicks anywhere outside of the popup it closes and the data is lost. Since the data is already entered by the user, it could be retained and can avoid lost content for users who forget to click on the Edit_SECTION button at the bottom of the popup.

**Product Flavor**

- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
1. Go to the resume editor page
2. Click on either of the sections to edit to open the modal window
3. Enter relevant information
4. Click outside of the popup
5. Observe the edited section does not show the updated or entered information

**Expected behavior**

If the user has entered added data into the text fields or updated it from the previous data, clicking outside of the modal popup must retain the entered data.

**Attachments**
![Screen Recording 2023-04-28 at 5 25 40 PM](https://user-images.githubusercontent.com/15098263/235258031-8e4a9174-3aa1-406b-82ee-820d5a2144b2.gif)

**Desktop**
- OS: MacOS
- Chrome

**Comment by Jubair70** [comment]
hey @AmruthPillai,
Do you think if the accidental close of the modal is prevented, then it will be good enough for resolving the issue?

**Comment by mickeymaddula** [comment]
That should work too right?

**Comment by AmruthPillai** [comment]
Yes, that could work. I didn't implement modals that way only because it felt a bit too restrictive. But it should be possible to add the `keepMounted` prop to the BaseDialog component to achieve this behaviour.
