### ISSUE TITLE
[BUG] Blank first page on exporting PDF

### ISSUE THREAD

**Issue by SuryaNMenon** [AmruthPillai/Reactive-Resume#1341]
I hadn't had any issues using the platform over the last week but today when I made some changes and attempted to export the pdf, the first page keeps appearing as blank. Page header with personal information persists, but everything else that's put into the first page of the layout just vanishes and there's just empty blank space. No matter what I tried to edit and/or remove from the resume, this issue persisted.

![firefox_QSplbGaHF1](https://github.com/AmruthPillai/Reactive-Resume/assets/10463932/324bb730-548e-4f2a-acba-2ef11765ba45)

For reference, this first page is supposed to contain my professional experience, education, skills and projects. Note that I have blurred some information in the header for privacy reasons. This issue seems to happen only on the Leafish template - other templates work just fine.

**Comment by ParkerTzh** [comment]
too, this problem is too serious

**Comment by hamzon** [comment]
I had the same error I just had to change models for it to work.

**Comment by SuryaNMenon** [comment]
> I had the same error I just had to change models for it to work.

Were you able to get the pdf in Leafish to work? Or did it only work on other models?

**Comment by anoop0567** [comment]
Hi @SuryaNMenon, have you found any workaround for this issue?

**Comment by SuryaNMenon** [comment]
> Hi @SuryaNMenon, have you found any workaround for this issue?

Unfortunately no. I haven't looked into the issue myself and was hoping that it'd be fixed in an update but the issue still persists. @AmruthPillai if you could look into this it'd be great!

**Comment by SuryaNMenon** [comment]
@anoop0567 @ParkerTzh Just tried exporting a PDF and seems that the issue has been fixed!

**Comment by surajatsmollan** [comment]
Is seems to be happening again in v3.8.4 with "Onyx" template. When I add another page, the "Work Experience" sections doesn't render on the page. Although it seems to be working fine if I make it multiple column section.
Any workarounds for that?

**Comment by surajatsmollan** [comment]
UPDATE: I was able to fix this by shortening some content. I experimented on public url and when content goes out of it's page container the content disappears.
