### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by TheDevelolper** [AmruthPillai/Reactive-Resume#1344]
In my experience recruiters often want résumés to be in word format 🤦🏽(I know right?), yeah I know word can open PDF files! 
Anyway... it would be great if there were a docx export feature.

**Comment by AmruthPillai** [comment]
It's a highly requested feature, but currently, just not in the scope of the project as the Microsoft formats are not open-source, and thus harder to recreate without hacking our way through. If that changes, maybe this can be considered :)
