### ISSUE TITLE
[FEATURE] Remove 'day' portion from dates

### ISSUE THREAD

**Issue by salesp07** [AmruthPillai/Reactive-Resume#1346]
In most resumes, the exact day of a date is not important, only month and year are. Few people remember the exact day they started or finished a project / school / job, and this information is not relevant to employers. Plus, it makes the date take too much space in the title row.

**Current implementation**: June 08, 2022 - July 09, 2023
**Proposed implementation**: June 2022 - July 2023

**Comment by AlexTu2** [comment]
You could set the date format for the whole resume, this may not be what you want, we should have individual customization.

Go to settings in the bottom of the right side bar > Date > choose one without days

![image](https://github.com/AmruthPillai/Reactive-Resume/assets/6798052/6c5a4728-e7df-4129-a9b0-554378b2ccef)

**Comment by salesp07** [comment]
That's quite helpful actually, I didn't know about that configuration. Cheers!
