### ISSUE TITLE
[BUG] - Private resumes are publicly downloadable.

### ISSUE THREAD

**Issue by bigmancallum** [AmruthPillai/Reactive-Resume#1370]
**Describe the bug**

A resume is publicly downloadable with the link even if it is private.

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Create a resume.
2. Toggle off "Is Publicly Accessible?"
3. Copy the link of the resume.
4. Follow the link and press "Download PDF".

**Expected behavior**

If a resume is private, then it should not be downloadable if you aren't the owner.

**Screenshots**

![Screenshot_2023-06-21-00-17-06-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AmruthPillai/Reactive-Resume/assets/47284263/8fd80a9a-09ca-4e4c-ba62-c4fa62a38fb3)
![Screenshot_2023-06-21-00-18-48-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AmruthPillai/Reactive-Resume/assets/47284263/39935778-92e1-470f-87ee-b8b353762afd)
![Screenshot_2023-06-21-00-20-45-29_3aea4af51f236e4932235fdada7d1643](https://github.com/AmruthPillai/Reactive-Resume/assets/47284263/faecbb93-fdb1-4fa4-97ba-443c9019bbe2)

**Desktop (please complete the following information):**

- OS: Android 13
- Browser: Google Chrome
- Version: 3.7.5

**Comment by AmruthPillai** [comment]
Ah, interesting. The page you saw with the download PDF button shouldn't even be visible.
Will look into this over the weekend, thank you for bringing it up!

**Comment by bigmancallum** [comment]
> Ah, interesting. The page you saw with the download PDF button shouldn't even be visible. Will look into this over the weekend, thank you for bringing it up!

Any update on this?

**Comment by AmruthPillai** [comment]
This should be fixed now.
