### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by smitvalture** [AmruthPillai/Reactive-Resume#1373]
[myCV.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/11881314/myCV.pdf)
**Describe the bug**
While I download the PDF the first-page information is not shown in PDF.

**Product Flavor**

- [ ] Managed (https://rxresu.me/valture16/smit-valture)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'Sharing > export'
2. Click on 'PDF'
3. Check the downloaded file
4. See the error

**Screenshots**
<img width="349" alt="Screenshot 2023-06-27 165407" src="https://github.com/AmruthPillai/Reactive-Resume/assets/73837907/59ef0e5c-8b05-4dcf-8013-944fd300492d">

**Desktop (please complete the following information):**

- Windows 11
- Chrome

**Comment by iamargus95** [comment]
> Hey @smitvalture, Could you please check if this error exists or not as your provided link does not show the bug ? Thanks!

The bug is present only on the leafish template. I think the creator of the issue changed the template to something else.

**Comment by AmruthPillai** [comment]
This issue should be fixed now, as of v3.8.3.
