### ISSUE TITLE
Not really sure if this is a bug or not "no matching manifest for linux/amd64"

### ISSUE THREAD

**Issue by dlover25** [AmruthPillai/Reactive-Resume#1389]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Self-Hosted

### Current Behavior

Trying to do a pull for the current version of RXResume (using docker compose) on a ubuntu VM on Proxmox. It's been running and upgrading fine. But this time, the Postgres image and the Server image pull great. but when it gets to the client, I receive this. Suggestions?

jammyserver:~/docker/rxresume$ sudo docker-compose pull
Pulling postgres ... done
Pulling server   ... done
Pulling client   ... pulling from amruthpillai/reactiv...

ERROR: for client  no matching manifest for linux/amd64 in the manifest list entries
ERROR: no matching manifest for linux/amd64 in the manifest list entries

**Comment by ymage** [comment]
Duplicate for #1385
