### ISSUE TITLE
[Feature] Ability to reorder skills

### ISSUE THREAD

**Issue by netvl** [AmruthPillai/Reactive-Resume#139]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to reorder the individual items in the "skills" section. The only way to do it is to manually copy-paste text across multiple fields, which is quite inconvenient.

**Describe the solution you'd like**
Something like handles for moving items up and down, or buttons like in other sections, would be really nice to have.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AmruthPillai** [comment]
Working on this. Should be available in the next update.

**Comment by AmruthPillai** [comment]
This has been implemented :)
