### ISSUE TITLE
[Bug] Can't create account on selfhosted offline instance

### ISSUE THREAD

**Issue by najibk** [AmruthPillai/Reactive-Resume#1390]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Self-Hosted

### Current Behavior

It's all in the title, I was expecting the account creation to work on a self-hosted instance and not need internet connection.
The app starts as expected without an issue

### Expected Behavior

The account creation should work offline

### Steps To Reproduce

restrict the app access to offline mode and try to create an account

**Comment by najibk** [comment]
Never mind, it was a configuration issue on my side. I'm closing this.

**Comment by chrispe-lab** [comment]
What was the config change you made to make it work?

**Comment by najibk** [comment]
if I remember correctly, it was a configuration issue with the database or the client, just make sure you can connect to all of them with the provided url you set up
