### ISSUE TITLE
[Bug] Social links not working

### ISSUE THREAD

**Issue by sauravJ14** [AmruthPillai/Reactive-Resume#1394]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Self-Hosted

### Current Behavior

whenever I download pdf form of resume the social links doesn't work whenever i hover over those links it wont show  option to access attached website 
it only happens to theme castform

**Comment by VanBrugg3n** [comment]
Same issue on https://rxresu.me

Same theme.

Tested on chrome and firefox.

**Comment by Shailesh-Kumar-01** [comment]
Facing same issue

**Comment by AmruthPillai** [comment]
Which template are all of you using? Probably needs a fix in some specific one, would be helpful to know which one :)

**Comment by Shailesh-Kumar-01** [comment]
I am using 'Gengar' template. Please fix it.
@AmruthPillai

**Comment by VanBrugg3n** [comment]
> Which template are all of you using? Probably needs a fix in some specific one, would be helpful to know which one :)

Castform. The same as the author of this issue.

**Comment by maelchiotti** [comment]
Same with Gengar

**Comment by 0xYoyo** [comment]
Castform. Website and social links don't work.

**Comment by 0xYoyo** [comment]
Hey @AmruthPillai is there an estimate for a fix on this? Or a work around we can do manually to fix it? 
Thanks!

**Comment by klosedan** [comment]
I face same issue with Gengar template

**Comment by mrodus** [comment]
Same issue with Gengar

**Comment by rishikanttwr** [comment]
The issue still exists in Gengar
