### ISSUE TITLE
Not having profile photo in Castform theme still rendering placeholder

### ISSUE THREAD

**Issue by manikantag** [AmruthPillai/Reactive-Resume#14]
When I don't give any profile photo URL, Castform theme is still rendering a placeholder image and a circle around it. None of the other themes are showing that.

![image](https://user-images.githubusercontent.com/317299/77824807-50b82800-712b-11ea-9cb8-a0f6b542cb9e.png)

**Comment by AmruthPillai** [comment]
This has been fixed in #15, thank you so much.

**Comment by manikantag** [comment]
Thanks for the quick fix
