### ISSUE TITLE
Getting blank image after downloading the resume

### ISSUE THREAD

**Issue by prashanthm10** [AmruthPillai/Reactive-Resume#140]
Hi,

Initially, I was able to download resume properly. But now when I am trying to download the resume, it is giving a blank page. Also if I bring down the quality to less than 60% it always gives a blank image when trying to view the resume after downloading.

**Comment by AmruthPillai** [comment]
I faced that too right now, just once, then I cleared the browser cache and refreshed the page. Everything seemed to start working again. If this is still happening, could you try clearing the cache? Any indicators that might help me recreate the issue on my end?

**Comment by prashanthm10** [comment]
Ya it was infact the cache issue. Working fine for me now.

Thanks for your help.

**Comment by AmruthPillai** [comment]
Awesome :) Glad I could help!
