### ISSUE TITLE
[Bug] PDF Exporting as One Page

### ISSUE THREAD

**Issue by brycekinsey** [AmruthPillai/Reactive-Resume#1402]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Self-Hosted

### Current Behavior

When downloading/exporting a PDF of my resume, it is just downloading as one long page. It displays fine as one long page on the computer, but it causes printing issues.

### Expected Behavior

The exported/downloaded PDF is automatically separated into the appropriate page sizes (letter in my case). Each page of the resume would then print.

### Steps To Reproduce

1. Create multi-page resume using the Glalie template.
2. Try to download or export the resume.
3. It will show in your PDF viewer as one page, and when trying to print isn't able to be adjusted to print as separate pages.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Anything else?

- Using the self-hosted version, which I setup using Docker today.
- This is the only issue I have noticed so far (after initial setup and minor troubleshooting).
- Thank you in advance for your help! If we can get this working, it would be a life saver!
- If you need a copy of the PDF file, please let me know and I can send it separately since it contains private information.

**Comment by mrfenyx** [comment]
I would really love if this got fixed or if anyone knew of a workaround.

**Comment by nagarajc85** [comment]
I agree with @mrfenyx , it would look much better if split into multiple pages.

**Comment by AmruthPillai** [comment]
This feature already exists. It's just that automatic pagination is not possible with the current code infrastructure. You can manually create new pages and move your sections to specific pages.

Here is a screen recording describing how this can be done:
https://app.usebubbles.com/6R3k8insqoNwhmXJwdyHnF/how-to-create-a-multi-page-resume-on-reactive-resume

**Comment by nagarajc85** [comment]
@AmruthPillai same section like experience which takes more than one page does not move to second page when it exceeds a page length. I think this is what you meant by pagination is not possible.

**Comment by AmruthPillai** [comment]
@nagarajc85 In this case, I usually suggest users to break down their work experience section into two seperate sections. One can use the original Work Experience section on the left. You can also create a new custom section, call it Work Experience and add the remaining experiences under there. Then, simply move the new section to a new page.

**Comment by nagarajc85** [comment]
thanks this works like a charm

**Comment by brycekinsey** [comment]
Oh wow, thank you @AmruthPillai ! I completely overlooked that option!

**Comment by brandondb1** [comment]
I understand that creating a new section is a possible solution, however it doesn't seem like you can move content between sections, which means that if you change the layout, you need to manually recreate the content in the new section.
Assuming one recreated the content in a new section, as soon as you change template again you would have to go through the process all over again (of deciding which pieces of content to move according to where physical pages might break while not having big gaps) - this kind of eliminates the value of the templating.
I guess you could put one work experience/education/whatever per section, but then the layout becomes very complex.
