### ISSUE TITLE
[Notice] Sunsetting v1 and v2 editions of the app

### ISSUE THREAD

**Issue by AmruthPillai** [AmruthPillai/Reactive-Resume#1415]
Due to increasing and recurring costs from Google Cloud, I would have to take down the Version 1 and Version 2 editions of the application that live on https://v1.rxresu.me/ and https://v2.rxresu.me/ respectively.

I plan to take down the servers on 1st September 2023, so if you have any data on the earlier versions, please migrate it over to the latest version on https://rxresu.me/ as soon as you can.

The current version will remain unchanged, and is still actively supported. It will have no effect on these changes.

Thank you to the 400,000+ people using the app! 🙏

**Comment by husayt** [comment]
I have been using the app  and have years worth of data. I  missed this notice. @AmruthPillai is it possible to restore the app for some day to allow to download the data? Or just providing data export will do.

I appreciate the costs are high, but maybe just leaving the app in readonly mode for few more months would be a good idea. There are many more users of the app, who wouldn'r know of this notice

**Comment by kylethedeveloper** [comment]
Sad news. I have been using v2 still because templates were better in my opinion. I will try to host v2 by myself, I can share that if I succeed.

Thanks for your product!
