### ISSUE TITLE
[Bug] Design breaking into two column

### ISSUE THREAD

**Issue by Samrat-Saha-Sammy** [AmruthPillai/Reactive-Resume#1417]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I am trying to create a resume from the template but it seems the current content is been broken into two column instead of a single column. 

![Untitled-1](https://github.com/AmruthPillai/Reactive-Resume/assets/4963559/adaf18f1-d9ae-49b5-be8b-5e0dff584008)

I guess it's due to the inline `grid-template-columns`

![Untitled-2](https://github.com/AmruthPillai/Reactive-Resume/assets/4963559/d8fb20d6-a87f-4c52-b3df-a40e11b4cc46)

**Comment by xdxddxd** [comment]
Have you tried changing the columns below the category?
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/38227342/1cdc900c-9f20-4a74-be49-6f9bf0965c33)

**Comment by Samrat-Saha-Sammy** [comment]
Yes, it fixed. Sorry for marking it as bug.
