### ISSUE TITLE
[Feature] Add a Date option "YYYY.MM"

### ISSUE THREAD

**Issue by doutv** [AmruthPillai/Reactive-Resume#1419]
### Is there an existing issue for this?

- [x] Yes, I have searched the existing issues and it doesn't exist

### Feature Description

I want to add a Date option "YYYY.MM", which is used widely in China.
E.g. `2023.1 - 2023.8` in the working experience section.

I think it is pretty easy to add this option, like in this commit https://github.com/AmruthPillai/Reactive-Resume/commit/82bf44daa24422156779e9b38d3dc695176eaa09 .

Thanks for your great contributions to this project. I never use another Resume Website since I meet this.

**Comment by AmruthPillai** [comment]
Thank you so much for the kind words :) I've pushed a PR to add these date formats now, it should be available in the app in the next release which should be soon.

**Comment by doutv** [comment]
wow, so quick!

Thanks again!
