### ISSUE TITLE
[Bug] Top of photo cropped out

### ISSUE THREAD

**Issue by Aadithya-V** [AmruthPillai/Reactive-Resume#1432]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

The top 1/5th of the uploaded photo automatically and erroneously gets cropped out. This behaviour occurs only recently (and not a few months ago).

Error occurs in- pre-existing resume, newly created resumes and on reupload of photo.

### Steps To Reproduce

Click upload on a new resume and upload a passport sized photograph.

### What browsers are you seeing the problem on?

Chrome

**Comment by AmruthPillai** [comment]
This is because images are expected to be of square aspect ratio. Right now, I do not have a way to change the aspect ratio of an image, but you could make use of online tools that allow you to resize/crop/fill an image and output it in square shape that can be uploaded to Reactive Resume.
