### ISSUE TITLE
Experiencing difficulty logging in with Google Account and accessing the shared Resume URL.

### ISSUE THREAD

**Issue by ravikrishnudu** [AmruthPillai/Reactive-Resume#1435]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Unable to Login and accesses Resume, showing  Internal Server Error Page

### Expected Behavior

User should have access to login by google account

### Steps To Reproduce

Go to the above link  https://rxresu.me/dashboard,
try to access the Resume

### What browsers are you seeing the problem on?

Chrome

**Comment by doutv** [comment]
Same issue

**Comment by brother-ran** [comment]
Same issue.

**Comment by saptakds** [comment]
Facing the same issue

**Comment by ravikrishnudu** [comment]
Fixed, Now it's working

**Comment by ravikrishnudu** [comment]
I wanted to express my gratitude for your prompt assistance. I'm pleased to inform you that the issue regarding logging in with my Google Account and accessing the shared Resume URL has been successfully resolved. Your swift response and effective resolution are greatly appreciated. Thank you for your support!
