### ISSUE TITLE
[Bug] Web-App returns "Internal Server Error"

### ISSUE THREAD

**Issue by Schusti91** [AmruthPillai/Reactive-Resume#1436]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

It's not possible to access the web-app anymore - it throws "Internal Server Error" on every click which is not on the static landing page.

### Steps To Reproduce

1 Go to https://rxresu.me
2 Click on one of the Screenshots

### What browsers are you seeing the problem on?

Chrome

**Comment by AmruthPillai** [comment]
Restarting the server to get it running again. Unfortunately, I am not sure what the cause of the issue is, probably someone trying to bring down the server or something as I see some huge spikes in traffic. Will try to keep restarting as often as I can when this issue crops up.

**Comment by Schusti91** [comment]
Thanks man - I was editing some huge CV, that can't be the issue or? 🤪
Where can I donate $10 for your efforts?

**Comment by AmruthPillai** [comment]
Haha, no, that's completely alright. You should be able to build a big a CV as you would like. Just some pesky folks who want to stress test the application illegally.

Any and all donations are very much welcome as they go directly to supporting the project :)
You can donate here: https://www.paypal.com/paypalme/amruthde 
Thank you!
