### ISSUE TITLE
[Bug] Internal Server Error

### ISSUE THREAD

**Issue by mojo-jojo-7** [AmruthPillai/Reactive-Resume#1448]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Whenever I try to open a resume from my dashboard, it gives 500 Internal Server Error

### What browsers are you seeing the problem on?

Firefox

**Comment by doutv** [comment]
Same issue

**Comment by vishnuidiot** [comment]
same issue

**Comment by Tazarkour** [comment]
same issue

**Comment by Smuger** [comment]
Same
<img width="1511" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/10279901/d4a13db9-c34d-471e-a20d-f9652133f913">

**Comment by KarlGhartler** [comment]
Same and I get this same error when I try to use the password reset link, ugh

**Comment by Equationzhao** [comment]
same

**Comment by AmruthPillai** [comment]
Sorry folks, I was travelling and couldn't check this out. Restarted the server and it should be back up online now.

**Comment by manudeli** [comment]
@AmruthPillai Internal Server Error reoccured🥲
