### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dxfan227** [AmruthPillai/Reactive-Resume#145]
**Describe the Bug**

**Reproduction**
After running the app on my localhost:3000 ( displays fine) I followed the NPM BUILD commoand and it error....then I tried NPM RUN BUILD and the build folder was created.

that index fine only display a blank white page. There is HTML in the page. but it just doesn't render. 

Can anyone help me understand what I may have done wrong?

**Comment by dxfan227** [comment]
Okay I think I may have localized the issue, being the path not set to the correct subdirectory during build. it says I should edit "homepage" field in package.json but I dont see that in the json file.

**Comment by dxfan227** [comment]
please mark as solved, was able to add the homepage field to package.json and it built with the proper paths.

**Comment by AmruthPillai** [comment]
Glad you were able to sort this one out. Thank you for sharing the solution, it might help others as well who come across this issue. Thank you so much for using Reactive Resume :)

**Comment by dxfan227** [comment]
No problem.

So I was wondering, is there any way/ is it allowed. to white label this in any way? We would never charge anyone to use this web based app, but would love for our logo/phone number to be on it at the. top for our customers to always be able to call us if they need help.

also things like the "?" help button, they link out to the official documentation. would love for it to be to our own, which we could use to help guide the user on not just the technical side of of using the app, but also some teqnie and tips for content that we provide.

**Comment by AmruthPillai** [comment]
@dxfan227 You can do absolutely anything you would want to do with it :) The MIT License allows you to make anything off of Reactive Resume, change it, rebrand it, even monetize on it. It only asks for one thing, which is to give credit to me on the app.

Another suggestion I would add is, ask the company to sponsor (not money) information to the app and build on this itself, I am very much open to integrating ideas such as showing tips/tricks from renowned sources on building resumes. Of course, you wouldn't be able to rebrand the app itself, but you could link the posts to a blog under your company's brand :)

**Comment by dxfan227** [comment]
I have a few follow up questions for you I hope you would be kind enough to address.

1. You mention in documentation that you will be releasing new templates as you have time.....how does that work if the build folder is on my website? Do I need to redownload, rebuild, & re-upload? Or does it somehow update on it's own?

2. What files should I start with to poke around on if I want to try and edit some of the interface visually? Like adding a logo, changing to the popup on the help button etc.?

4. Are there any files that run off your own server/3rd party server or is everything done on mine? I notice things like G-static links that it pulls in, is that controlled by you? or google? what if it changes, does that app just break on my end.

5. I also noticed a google tag manager link.....should this be taken out? Is it your analytics?
<script src="https://www.googletagmanager.com/gtag/js?l=dataLayer" async=""></script>

3.  Can you elaborate a little bit on your last request? You say I couldn't re-brand it, but in the opening sentence you say we can........ I appreciate your guidance on this. I tried to email you directly upon my initial post. I'm not sure if you received it or not.
