### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by dxfan227** [AmruthPillai/Reactive-Resume#146]
Possible to get a inline formatting option, many users may be unfamiliar with HTML/Github markdown code.

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Standard Markdown Editor/WYSIWYG

**Comment by AmruthPillai** [comment]
This makes the UI a bit cluttered, going against my vision of keeping the app as minimal as possible. I'll keep this open for a short while so that others can weigh in and you could provide a few scenarios where you feel this would be worth implementing as well.

**Comment by dxfan227** [comment]
Thank you, look forward to hearing what others might have to say.

The use case would be for any non technical user to be able to apply style to their resume. Opening it's accessibility to a much wider audience. As you might know, I help people find jobs and help them with their resume's. I would love to be able to walk then through creating their resume with this tool. however most of these users are NOT software developers or tech savvy. 

This would allow them to make basic markdown changes in their resume like BOLD, Italic, Bullet Points..... very similar to the current text box I;m typing in git hub right now

see example here - https://imgur.com/C67sMdv

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
