### ISSUE TITLE
[Bug] saved resume doesn't exist anymore. 

### ISSUE THREAD

**Issue by vnodpangul** [AmruthPillai/Reactive-Resume#1461]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Hi,
 I had resume in my account which doesn't exist anymore. When I login, it is a blank account now. Could someone take a look?

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by sonatuzun** [comment]
I experienced the same thing :(

**Comment by AmruthPillai** [comment]
That's surprising, I haven't messed around with any of the existing architecture (yet, waiting for the weekend to release the new version).

I also just logged into my personal account and could see that my resumes created months ago are still available.

Could you please email me your username at hello[at]amruthpillai[dot]com and I will take a look at what's wrong? :)

**Comment by sonatuzun** [comment]
They all came back after I re-uploaded an exported resume json. I assume it might be a simple refresh issue (the database needs poking to know we're still there?). I can still e-mail you my username if it'd help for investigating the issue
