### ISSUE TITLE
[Bug] This app in docker mode have to mutch BUG !!

### ISSUE THREAD

**Issue by xorgxx** [AmruthPillai/Reactive-Resume#1466]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

to mutch unstable !!! i give up !!! tanks

**Comment by wilotas** [comment]
Something similar from my side. Suddenly, RESUME Server can not connect to database.

Is there any problem causing this app not stable?

**Comment by wiebereu** [comment]
I don't think you will get any answer from the creator. He don't care, but he will do if you pay i guess. For more than 1 year i reported that i cannot make the app secure by putting a certificate for the app. I never got any response about this issue. I think that the creator deliberately configure the app in a way that you can only use it locally and not by a domain name. The moment i configure traefik to be able to only access the app through a https connection it stop working. With stop working i mean i can not log on and i cannot register.  Some people think that if something is opensource then you have no right to a good working app.

**Comment by xorgxx** [comment]
So **big faker** this guy !! app is big joke TO AVOID
