### ISSUE TITLE
[Feature] Full page size and locale translation on Glalie template

### ISSUE THREAD

**Issue by afboteros** [AmruthPillai/Reactive-Resume#147]
**Is your feature request related to a problem? Please describe.**
It would be great if the left bar of the profile information on Glalie template, which i found to be the best template for me, has the height of the page container in order to print correctly on default letter size on Chrome browser save to PDF, to achieve this i modified the css this way:

`style={{ backgroundColor: `rgba(${r}, ${g}, ${b}, 0.1)`, height: `29.7cm` }}`

On line 284 on Glalie.js file, this height is the same as page on index.css file.

Another issue i found on this template is that the translation is not applied for Profile information inside the square (Phone number, Email Address), this titles are specified in english on the .js file on lines 61 and 62, so in my case i needed those titles in Spanish so i had to change them on code. It would be great if this titles changed according to the translation specified. Also it would be great on this template that in case no address is specified the material icon of the house gets hidded.

Thanks for this amazing software.

**Comment by AmruthPillai** [comment]
This has been implemented with #152 :) Please try it out and let me know if you are able to print the Glalie template with a stretched out background now.
