### ISSUE TITLE
[Internal Server Error] <sever seems to be down again?>

### ISSUE THREAD

**Issue by KarlGhartler** [AmruthPillai/Reactive-Resume#1486]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

"Internal Server Error" displaying when trying to load my previously saved resumes, along with some broken images. I think this happened a few weeks ago or a month back so I presume it means you're not at your PC or something. Please find a way to restart the server remotely when you leave because it's making it a headache when I'm trying to adjust my resume for a job opening.

Thanks.

### Expected Behavior

I expect it to work as normal instead of getting a blank page that says "Internal Server Error"

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by AmruthPillai** [comment]
The issue should be resolved now.
