### ISSUE TITLE
Improving UI of the home page

### ISSUE THREAD

**Issue by Kritika30032002** [AmruthPillai/Reactive-Resume#1490]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

UI can be improved to make  user friendly and easy understandable

**Comment by AmruthPillai** [comment]
The new v4 version I'm working on should improve the home page and the overall application, so this is very much in scope :) Will provide some more details more closer to release.
