### ISSUE TITLE
[404] <Internal server error>

### ISSUE THREAD

**Issue by gonzoknows** [AmruthPillai/Reactive-Resume#1496]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Internal server error when accessing resume

### Expected Behavior

to work

### Steps To Reproduce

1. login
2. go to resume
3. internal server error

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by JoaoHiga** [comment]
I was writing my resume when it ocurred. Waiting the solution patiently!

**Comment by adisat456** [comment]
same problem

**Comment by AmruthPillai** [comment]
Should be resolved now.
