### ISSUE TITLE
[Bug] Exporting PDF in non-native language still shows "present" on fields with date selectors

### ISSUE THREAD

**Issue by tostesdaniel** [AmruthPillai/Reactive-Resume#1498]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

When opting for another language, in my case Brazilian Portuguese, exporting a resume shows dates like (2023 - present) instead of (2023 - presente).

### Expected Behavior

"present" word in any field that has a date selector should be translated properly for ongoing experiences.

### Steps To Reproduce

1. Set language to Brazilian Portuguese
2. Input some experience
3. (Optional) Set date format as YYYY
4. Set Start date as 01/01/2023 and leave finishing date empty.
5. Export resume as pdf
6. "present" word is in English still

### What browsers are you seeing the problem on?

Firefox

**Comment by tostesdaniel** [comment]
Closed for now as I can't reproduce it consistently. Also noticed changing languages makes document not to download in the right language sometimes - maybe that's what caused it.

**Comment by nikolaspaci** [comment]
Hello,
Same issue on my side , i set the language in French but when I export to pdf, date are in English. But in the website it's in French.

**Comment by nikolaspaci** [comment]
I think that the language chosen by the user is not well persisted in the database, because if I restart the application several times, it reverts to English. And maybe when exporting to pdf, the code checks which language is defined in the database.

**Comment by tostesdaniel** [comment]
Maybe that's something by those lines, yes. I found out that trying multiple times can solve the issue, but I can't seem to reproduce it consistently. Recently it's been working great.

**Comment by okuzlu** [comment]
I have this issue also. Tried it several times but it always shows in downloaded pdf "present". Language is not English
