### ISSUE TITLE
Language issue when converting to pdf

### ISSUE THREAD

**Issue by lm1999mz** [AmruthPillai/Reactive-Resume#1523]
Hello,

I created my CV in German and I'm really enjoying it. However, once I convert it to pdf, the German word "heute" turns into "present", therefore I currently can't use the CV I created. Is there any way to fix this issue without having to wait for an update of the site? 

Thanks a lot for your help and work!

**Comment by AmruthPillai** [comment]
Sorry for the inconvenience. I am aware of this bug and many other issues related to the date library, but right now all my efforts are being put into the new release. Unfortunately, there is no workaround at this time. But I do believe the new version of the app should solve all your issues and help you discover a lot more features.
