### ISSUE TITLE
Download Failed 

### ISSUE THREAD

**Issue by rhasan2903** [AmruthPillai/Reactive-Resume#1535]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Hey, I created my resume, but can't download it. It shows an error. I also tried on many other devices but it is not working as expected. 

### Expected Behavior

It should download as pdf

### Steps To Reproduce

1. Create resume
2. click on download button
3. error

### What browsers are you seeing the problem on?

Chrome

### Anything else?

 
![Anmerkung 2023-11-13 234248](https://github.com/AmruthPillai/Reactive-Resume/assets/150747933/21ab85cc-4d7f-4e2e-916e-f786ffbf73a2)

**Comment by Himal-Marasini** [comment]
Did anyone already fixed this issue ?

**Comment by AmruthPillai** [comment]
Yes, this should be fixed now.
