### ISSUE TITLE
[Feature] "Skill bar" for Skills (like Languages have)

### ISSUE THREAD

**Issue by Nightreaver** [AmruthPillai/Reactive-Resume#154]
**Is your feature request related to a problem? Please describe.**
I'd like to have skill ratings and not just the skills name

**Describe the solution you'd like**
Add an option to add a "skill level" like the ones on "Languages" section

**Describe alternatives you've considered**
nothing else to consider, i assume

**Additional context**
some people like to have a broader overview over your skills/experiences, and they want to know your expertise level (ie beginner to expert)
this should help make things clear right from the start

**Comment by BrunoElo** [comment]
A very essential enhancement.
I have seen many other resumes with such feature

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.

**Comment by yairEO** [comment]
Hi, I want the opposite: I want `skills` section with optional rating system, because I do not want to be "forced" into rating my own skills
