### ISSUE TITLE
Break Page - Split the page 

### ISSUE THREAD

**Issue by prajwal3104** [AmruthPillai/Reactive-Resume#1543]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and it doesn't exist

### Feature Description

When the first page is filled, the entire section's remaining content would automatically shift to the next page, creating a new page rather than stretching all the content onto one page upon export, even when it exceeds the designated break line. It seems this feature may be missing or not functioning as expected.

**Comment by AmruthPillai** [comment]
It's working as expected. The creation of a new page and deciding what sections should go into the new page is more of a manual process. You decide whether to keep everything in a single page (even if it exceeds A4) or if you want to create a new page.

The line break indicator is just (as it says so) an indicator that the page ends here.

You can create a new page and move sections into it by using the Layout block on the right sidebar.
