### ISSUE TITLE
[Bug] <it's not working>

### ISSUE THREAD

**Issue by KatarzynaChmielecka** [AmruthPillai/Reactive-Resume#1544]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I can't login.

### Steps To Reproduce

Try login.

### What browsers are you seeing the problem on?

Chrome

**Comment by KatarzynaChmielecka** [comment]
After login i can't open project.

**Comment by onlyonebeerleft** [comment]
Can confirm, in a logged in session after pressing "Go to app" it loads indefinitely

**Comment by yosoyuva** [comment]
Same for me i'm getting an error 524 when trying to access the dashboard

**Comment by Readus-01** [comment]
same here, also threw this error on one install
{"statusCode":404,"timestamp":"2023-11-18T02:46:55.212Z","path":"/"}

**Comment by darthwalsh** [comment]
I'm seeing ERR_TOO_MANY_REDIRECTS: `GET https://rxresu.me/` responds `301 Moved Permanently` with a looped: `Location: https://rxresu.me/`

**Comment by AmruthPillai** [comment]
I am currently running a migration to the latest version, and so the app would be down for a while.
https://reactive-resume-migration.netlify.app/

But I'm working day and night to make sure it comes through!
