### ISSUE TITLE
Display section data in list

### ISSUE THREAD

**Issue by maazali123** [AmruthPillai/Reactive-Resume#1545]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and it doesn't exist

### Feature Description

I have built my resume and it displays all the sections' data in a grid of two columns, I want it to show the data in the list format. I have explored the options but there is no option that would enable the list format.

**Comment by AmruthPillai** [comment]
There's a button to set the number of columns for each section right below the list, as seen in the screenshot here. Setting the number of columns to 1 would display every item as a list, as you intended.

![Screenshot 2023-11-20 at 8 28 14 AM](https://github.com/AmruthPillai/Reactive-Resume/assets/1134738/bb6a7aba-4542-4866-baaf-1041855cab36)
