### ISSUE TITLE
[Feature] overall Flexiblity

### ISSUE THREAD

**Issue by Nightreaver** [AmruthPillai/Reactive-Resume#155]
**Is your feature request related to a problem? Please describe.**
I am struggling a bit with overall flexibility. Everything is named explicitly, and has a fixed position, which might be good in most cases, for some its not.

**Describe the solution you'd like**
split the page in 2-3 sections, it sidebar content and "main" content. 
You have few options per column you can chose from, and fill with what you need.

option for "side bar" column:
* generic "languages" box, has Title (text), Name (text), Level (text), Rating (graphic, can be defined with template)
* generic "skills" box, has Title and Name only, single item per row ( depends on theme)
* generic "text" box (Objective), has Title and Text
* profile box, current is pretty good already
* "personal information" box, has Title, "Key", "Value", option for and icon per item

options for main column box can be:
* generic education (current is good) box
* generic work experience (current is good) box
* "Honors & Awards" is technically "Certifications" - so should be pretty generic already
* references is good (could be either side or main column)

So the overall idea is, that you have a choice of these "boxes", some of them can be either side, main or side column (you can chose through small switch or template only) and you can fill them with content. If you want to add another content box that is like the "languages" box, you can just add it to the sidebar, name it and fill it with content.
If you need 5 more of them, just add 5 more ....

You might also want to add a way to chose the sorting per column, so one can rearrange the content boxes in case box 2 should be before box 1, or vice versa

While totally see a reason to have some boxes to be very specific (like Personal Information) other don't need to be. 

What if I need a "Projects" box in the main column? None available, but adding one box named "Projects" doesn't make sense either, what if someone else needs 2 "project boxes" ? 

To current style might be beginner friendly (beside have to use markdown) is also very limiting.

And for starters you can have a starting layout with already predefined boxes they only need to fill out without have to dig all the way through by adding these boxes manually and naming them.

**Describe alternatives you've considered**
Don't see alternatives yet

Thats just my first thought - maybe I' not the target audience ;)

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
