### ISSUE TITLE
[Bug] The S3 storage file call seems not right?

### ISSUE THREAD

**Issue by martadinata666** [AmruthPillai/Reactive-Resume#1562]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

The url fetched for image preview, like photo or maybe files, not include the bucket.
```
  body-parser:urlencoded body already parsed +0ms
  prisma:client  Prisma Client call: +42s
  prisma:client  prisma.user.findUniqueOrThrow({
  where: {
    id: "clpb085f600004c67ibsnx0jz"
  },
  include: {
    secrets: true
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "User",
  "action": "findUniqueOrThrow",
  "query": {
    "arguments": {
      "where": {
        "id": "clpb085f600004c67ibsnx0jz"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true,
      "secrets": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +42s
  prisma:client  Prisma Client call: +4ms
  prisma:client  prisma.user.update({
  where: {
    email: "dedyms@pm.me"
  },
  data: {
    name: "dedyms",
    picture: "",
    username: "dedyms",
    locale: undefined
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "User",
  "action": "updateOne",
  "query": {
    "arguments": {
      "where": {
        "email": "dedyms@pm.me"
      },
      "data": {
        "name": "dedyms",
        "picture": "",
        "username": "dedyms"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +3ms
  express:router dispatching PUT /api/storage/image +17s
  express:router query  : /api/storage/image +1ms
  express:router expressInit  : /api/storage/image +0ms
  express:router cookieParser  : /api/storage/image +0ms
  express:router corsMiddleware  : /api/storage/image +0ms
  express:router helmetMiddleware  : /api/storage/image +0ms
  express:router jsonParser  : /api/storage/image +0ms
  body-parser:json content-type "multipart/form-data; boundary=----WebKitFormBoundary2xxPudUBLbIftoPq" +0ms
  body-parser:json skip parsing +0ms
  express:router urlencodedParser  : /api/storage/image +0ms
  body-parser:urlencoded content-type "multipart/form-data; boundary=----WebKitFormBoundary2xxPudUBLbIftoPq" +0ms
  body-parser:urlencoded skip parsing +0ms
  prisma:client  Prisma Client call: +17s
  prisma:client  prisma.user.findUniqueOrThrow({
  where: {
    id: "clpb085f600004c67ibsnx0jz"
  },
  include: {
    secrets: true
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "User",
  "action": "findUniqueOrThrow",
  "query": {
    "arguments": {
      "where": {
        "id": "clpb085f600004c67ibsnx0jz"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true,
      "secrets": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +17s
  ioredis:redis write command[10.0.30.2:6379]: 0 -> set([ 'user:clpb085f600004c67ibsnx0jz:storage:pictures:clpb085f600004c67ibsnx0jz', 'http://192.168.0.2:9000/clpb085f600004c67ibsnx0jz/pictures/clpb085f600004c67ibsnx0jz.jpg' ]) +56s
  express:router dispatching PATCH /api/user/me +1s
  express:router query  : /api/user/me +0ms
  express:router expressInit  : /api/user/me +0ms
  express:router cookieParser  : /api/user/me +0ms
  express:router corsMiddleware  : /api/user/me +0ms
  express:router helmetMiddleware  : /api/user/me +0ms
  express:router jsonParser  : /api/user/me +0ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +0ms
  body-parser:json parse body +1ms
  body-parser:json parse json +0ms
  express:router urlencodedParser  : /api/user/me +0ms
  body-parser:urlencoded body already parsed +0ms
  prisma:client  Prisma Client call: +1s
  prisma:client  prisma.user.findUniqueOrThrow({
  where: {
    id: "clpb085f600004c67ibsnx0jz"
  },
  include: {
    secrets: true
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "User",
  "action": "findUniqueOrThrow",
  "query": {
    "arguments": {
      "where": {
        "id": "clpb085f600004c67ibsnx0jz"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true,
      "secrets": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +1s
  prisma:client  Prisma Client call: +3ms
  prisma:client  prisma.user.update({
  where: {
    email: "dedyms@pm.me"
  },
  data: {
    name: undefined,
    picture: "http://192.168.0.2:9000/clpb085f600004c67ibsnx0jz/pictures/clpb085f600004c67ibsnx0jz.jpg",
    username: undefined,
    locale: undefined
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "User",
  "action": "updateOne",
  "query": {
    "arguments": {
      "where": {
        "email": "dedyms@pm.me"
      },
      "data": {
        "picture": "http://192.168.0.2:9000/clpb085f600004c67ibsnx0jz/pictures/clpb085f600004c67ibsnx0jz.jpg"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +3ms


```

### Expected Behavior

I assume this should load correctly with bucket name included `http://192.168.0.2:9000/bucketname/clpb085f600004c67ibsnx0jz/pictures/clpb085f600004c67ibsnx0jz.jpg`. The files itself uploaded to correct bucket. 
```
❯ tree ./resume/
./resume/
└── clpb085f600004c67ibsnx0jz
    ├── pictures
    │   └── clpb085f600004c67ibsnx0jz.jpg
    │       └── xl.meta
    └── previews
        └── clpb2jw000001h8p4e6s25gom.jpg
            └── xl.meta

5 directories, 2 files

```

### Steps To Reproduce

Upload pictures, any kind.

### What template are you using?

None

**Comment by AmruthPillai** [comment]
@martadinata666 I'm not understanding the question all too well. What error are you facing?

**Comment by martadinata666** [comment]
let take example im uploading a profile picture.
![2023-11-23-193401_1126x432_scrot](https://github.com/AmruthPillai/Reactive-Resume/assets/2433562/470a8af5-88dc-474c-aaa5-6fccb5a1518c)

The correct URL should be `http://192.168.0.2:9000/resume/clpb085f600004c67ibsnx0jz/pictures/clpb085f600004c67ibsnx0jz.jpg`, `resume` is the bucket name.

**Comment by AmruthPillai** [comment]
I see. I have updated the `.env.example` file to reflect this now. Basically, you should append the bucket name to the STORAGE_URL if you are using `minio`. The reason for this is most managed S3 environments provide you a single URL specific to a bucket, which does not contain the bucket name.

To fix this, open up your `.env` and change the `STORAGE_URL` variable from `http://192.168.0.2:9000` to `http://192.168.0.2:9000/resume` where `resume` is the bucket name.

**Comment by martadinata666** [comment]
Thanks, it working, there are some usage issues. but the app still polishing, so I will wait a bit.

**Comment by AmruthPillai** [comment]
Please do let me know how I can make the process better.

I'm also planning to write docs for the self-hosting guides. Did you plan on self hosting it locally or on a virtual private server? Do you plan on accessing the project with IP addresses, or through a public domain name? This information will benefit me greatly when writing the documentation :)

**Comment by martadinata666** [comment]
There are two things that I noticed right away.
First, the picture of the resume will affect the profile picture also profile picture will affect the resume picture which I think should be a separate thing. As a resume we may use different photos.
Second, the resume preview not regenerating after modification and the page reload/refresh will trigger the regeneration.

About hosting, I usually host locally, but with the help of `cloudflare tunnel` I made it access outside the world. But some resources such as s3 won't be available outside word, it became like this.
![2023-11-23-213910_838x870_scrot](https://github.com/AmruthPillai/Reactive-Resume/assets/2433562/9c2a920d-045b-441c-899d-ef3e75c3f905)
I think that the application should proxy the image source.
`http://192.168.0.2:9000/bucketname/.../bla.jpg`  become `https://example.com/pictures/.../bla.jpg`. Following PUBLIC_URL env I guess.

**Comment by martadinata666** [comment]
Yes, there are so many considerations in software engineering. Let's see how users will react to new versions and decide by what to do next.

Oh about the resume thing. Is this intended? Should the resume page picture follow the resume image rather than the profile image?
![2023-11-24-081428_842x260_scrot](https://github.com/AmruthPillai/Reactive-Resume/assets/2433562/1c337f18-1d64-42b1-a780-223bc193851b)
