### ISSUE TITLE
[Translation] Differentiate between date and date range

### ISSUE THREAD

**Issue by tryallthethings** [AmruthPillai/Reactive-Resume#1564]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

There is currently no differentiation between a specific date and a date range. In the English version it is just called date. 

### Expected Behavior

Different sections in the resume have different uses for the date field. For education or work experience, a date range makes sense. For publications or certificates, a singular date is usually used. From what I can see, the field is just a text field that the user can fill with any data. For clarification purposes, I propose to change the description from "Date" to "Date or date range" to make the intended use a bit clearer. In English this isn't as much of an issue, but other languages might need a clarification here.

### Steps To Reproduce

1. Edit any section of the resume that includes a date field

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by AmruthPillai** [comment]
I like the approach of naming the field "Date or Date Range" to be more descriptive. I was only worried about how it might be translated to other languages if I were to go deeper into describing every label/field.

Right now, I'm a bit swamped with migrations and users complaining about their resumes missing. But I'd say this is a `good first issue` if anyone is willing to take a look at creating a PR.
