### ISSUE TITLE
[Bug] LOST all my data???

### ISSUE THREAD

**Issue by lucaoskaique** [AmruthPillai/Reactive-Resume#1565]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

LOST all my data???

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by jonwtech** [comment]
My resume has also disappeared

**Comment by edoardotavecchio** [comment]
That's the same for me too. It seems like it created a whole new account instead of logging me into my previously created one (it asked me for email verification again and I lost all my data).

**Comment by AmruthPillai** [comment]
There were some complications with the migration, but rest assured, your data is safe and backed up. I have still not officially completed the migration process.

But if you do need access immediately, please drop me an email with your Reactive Resume email (or better yet, your resume ID or slug) and I can figure out why the resume didn't get migrated.

**Comment by lucaoskaique** [comment]
> There were some complications with the migration, but rest assured, your data is safe and backed up. I have still not officially completed the migration process.
> 
> But if you do need access immediately, please drop me an email with your Reactive Resume email (or better yet, your resume ID or slug) and I can figure out why the resume didn't get migrated.

UFA!!!!! 😮‍💨😮‍💨

thx, for letting us know @AmruthPillai  <3
