### ISSUE TITLE
[Improvement] On Dashboard options menu missing in Grid View on Resume 

### ISSUE THREAD

**Issue by anuuu16** [AmruthPillai/Reactive-Resume#1568]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Options are missing in grid mode
<img width="1392" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/25295394/ce3efa8d-10cc-457f-af96-79c7c5c0c8cf">

### Expected Behavior

There should have been the Option menu in Grid mode also

### Steps To Reproduce

1. Go to Dashboard
2. Switch the Grid View
3. See the Options Menu is not there

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by AmruthPillai** [comment]
@anuuu16 The context menu should appear when you right-click on a card.

**Comment by anuuu16** [comment]
We can give 3dots after the title on Card as well,
In the Browser mostly people don't use the right-click on items.
