### ISSUE TITLE
[Technical Request Help] Updating the app

### ISSUE THREAD

**Issue by dxfan227** [AmruthPillai/Reactive-Resume#157]
Sorry for the newb question.

I have been making edits in the app, then running the build command, and uploading the new build file to my server for deployment.

1. is this necessary? Is there a better way to be doing that?

2. IF you push updates for the app, how do I "get" them without losing all of my "custom" code?

sorry for such a basic basic question.

**Comment by AmruthPillai** [comment]
@dxfan227 A better way would be to set up something called CI/CD or just CD in this case, which stands for Continuous Deployment/Delivery. You can use services like Netlify, GitHub Pages, or Vercel to host the built site and keep it running.

If you would like to pull in the latest changes into your own fork, all you need to do is create a pull request with my `master` branch as the source to the `master` branch of your fork as the destination. There might be a few conflicts, but if you haven't made too many changes, it shouldn't be a problem. You can keep your code updated through this method at all times.
