### ISSUE TITLE
[Bug] Builder distorted for screen size 1024+ . min-width is missing.

### ISSUE THREAD

**Issue by anuuu16** [AmruthPillai/Reactive-Resume#1573]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

For screen resolution 1024+(width) Styling is not good.
<img width="1035" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/25295394/76c3f003-b8aa-4c29-8bac-07e6559a870f">

### Expected Behavior

It should auto-adjust the sidebar width. min-width need to be defined.

_No response_

### Steps To Reproduce

1. set screen size width 1024
2. Check the Left bar, Some items are hidden

### What template are you using?

None

**Comment by AmruthPillai** [comment]
The sidebar is actually resizable (drag and drop on the edge of the sidebar on either side), so you could resize the panel depending on your screen size.
