### ISSUE TITLE
[Bug] Enter button is closing the popup

### ISSUE THREAD

**Issue by anuuu16** [AmruthPillai/Reactive-Resume#1576]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

<img width="743" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/25295394/03d6928e-338a-4b8e-8e5a-acedf6172278">

### Expected Behavior

The modal should remained open

### Steps To Reproduce

1. Go to editor
2. Add and experiencece 
3. In Model click the enter button

### What template are you using?

None

**Comment by AmruthPillai** [comment]
This should be solved in the next update, although I wasn't able to reproduce the issue exactly.
