### ISSUE TITLE
[Bug] Data lost after the latest update 

### ISSUE THREAD

**Issue by MiloJiang** [AmruthPillai/Reactive-Resume#1579]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

It seems only the English data has been saved. I lost my data in Chinese. 

### Expected Behavior

All my resume data can be found in dashboard

### Steps To Reproduce

1. Login
2. Open the resume dashboard.

### What browsers are you seeing the problem on?

Chrome, Safari

### What template are you using?

None

**Comment by AmruthPillai** [comment]
The migration is still running, and probably will be running for a couple of hours (more than 450,000 resumes to process). So if your resume isn't there right now, please wait, I'm working as hard as I can :)
