### ISSUE TITLE
[Feature] Expand section row, if sibling section is not in use

### ISSUE THREAD

**Issue by technokami** [AmruthPillai/Reactive-Resume#158]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
If two sections normally share a "row" in a template, and one section is disabled it would be nice to continue the used section into the unused space.

**Describe alternatives you've considered**
I have tried removing the heading from the section I don't need, but it causes the text to shift up to be level with the other sections heading

**Additional context**
Screenshot 1 is what I would like to have. 2 is what happens currently is using both sections and removing the header. 3 is what happens with one section in use

![1](https://user-images.githubusercontent.com/20519797/81721160-71271200-944d-11ea-9bb4-ca4fd4b30eb6.png)
![2](https://user-images.githubusercontent.com/20519797/81721162-72583f00-944d-11ea-83f3-530d4f98369a.png)
.![3](https://user-images.githubusercontent.com/20519797/81721559-0924fb80-944e-11ea-876c-fb8b708a16ac.png)

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
