### ISSUE TITLE
[Bug] Health check fails because blog.rxresu.me is down

### ISSUE THREAD

**Issue by samuraicow** [AmruthPillai/Reactive-Resume#1581]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

When attempting to build this in Docker, I get the following error in my logs: 
`ERROR [HealthCheckService] Health Check has failed! {"app":{"status":"up"},"docs":{"status":"up"},"database":{"status":"up"},"blog":{"status":"down","message":"getaddrinfo ENOTFOUND blog.rxresu.me"}}`

### Expected Behavior

Health check should pass.

### Steps To Reproduce

Deploying a stack via Portainer. Error happens when trying to launch the server container.

### What template are you using?

None

**Comment by AmruthPillai** [comment]
The previous version is out of the release cycle and the latest image points to v4. You can try setting up the new version locally. It should be much much easier than how the older version was to self-host.

**Comment by dbffm** [comment]
same here. 
I wanted to deploy new release V4 via docker. 
But I get `ERROR [HealthCheckService] Health Check has failed! {"app":{"status":"up"},"docs":{"status":"up"},"database":{"status":"up"},"blog":{"status":"down","message":"getaddrinfo ENOTFOUND blog.rxresu.me"}}`
When removing that healthcheck section in docker-compose file I get the message that there is a missing healthcheck configuration. 
Has anything changed here in that configuration with V4?

**Comment by AmruthPillai** [comment]
The error you are getting is still from v3, not from v4, because there are no calls back to home in the docker image anymore. Please ensure you are pulling the `latest` tag from Docker Hub or GitHub Container Registry.

**Comment by dbffm** [comment]
thanks for your quick answer. 
Indeed - I was pulling `reactive-resume:server-latest` and `reactive-resume:client-latest` which point to V3. 
I will try to migrate my docker-compose file based on [this example](https://github.com/AmruthPillai/Reactive-Resume/blob/main/tools/compose/simple.yml).
