### ISSUE TITLE
[Bug] Markdown not working anymore

### ISSUE THREAD

**Issue by andy-vdg** [AmruthPillai/Reactive-Resume#1583]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Similar to: [1489](https://github.com/AmruthPillai/Reactive-Resume/issues/1489 )

Prior to V4 I could have images via markdown in any item. 
This used to work: 
`![ICP](https://www.gugten.com/uploads/3/8/9/8/3898211/495810148.png)`
Now it doesn't anymore. 
This was quite handy as it allowed me to place images in different parts of the resume. 
Also text formatting like `**Bold**` used to work and now just shows as text

### Expected Behavior

It should render Markdown and load the image not just output the markdown code. 

### Steps To Reproduce

Create an item. 
Add markdown image
Save

### What template are you using?

None

### Anything else?

*Edit Expanded to all Markdown not just for images.

**Comment by AmruthPillai** [comment]
Markdown, once typed, should work. You can also add images, or a lot more things using the new rich text editor.

The reason markdown doesn't work as-is since migrating is because I cannot manipulate or migrate any of the specific resume data of a user (for obvious security/privacy reasons).

**Comment by andy-vdg** [comment]
Sorry but it does not work for me. I can use the rich text editor to correct things like links and bold etc. but typing markdown or adding images do not work. There also doesn't seem to be a place to be able to add images via the rich text editor. 

And - again - why not build a small migration tool? The beauty of your tool is that all data exists in a structured format so changing date formats or moving data from markdown to whatever your new rich text editor supports should be fairly straight forward.
