### ISSUE TITLE
[Bug] OpenAI API calls don't seem to work

### ISSUE THREAD

**Issue by andy-vdg** [AmruthPillai/Reactive-Resume#1584]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I keep getting this error:
<img width="340" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/19990167/7192a15e-ffc5-4aae-8e7b-7b0e460403fe">

When I check my API key on platform.openai.com it shows as never used
<img width="736" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/19990167/c68ca5f7-6972-4cc6-9694-6338f6241067">

### Steps To Reproduce

Followed the instructions [here](https://docs.rxresu.me/product-guides/enabling-openai-integration)
Click on Improve Writing
Error message pops up. 

### What browsers are you seeing the problem on?

Microsoft Edge

### What template are you using?

None

**Comment by AmruthPillai** [comment]
As the error states, I believe this is related to your OpenAI account and your billing information. Nothing to do with Reactive Resume.

**Comment by andy-vdg** [comment]
Sorry - I still believe this is a problem on your end. 

<img width="380" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/19990167/56fa72a3-d10b-46f5-998f-1d7e8bb007f1">

<img width="173" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/19990167/73beae5c-353e-4699-b673-b865c939c816">

**Comment by AmruthPillai** [comment]
Yes, now this is actually an issue with the OpenAI integration on my end. Will look into this and make sure it's fixed in the next update. Will post further updates on #1586.
