### ISSUE TITLE
[Bug] OpenAI intergration is not working 

### ISSUE THREAD

**Issue by hoferbeck** [AmruthPillai/Reactive-Resume#1586]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

When you click on a button to execute a AI Action following Error Occurs:
![grafik](https://github.com/AmruthPillai/Reactive-Resume/assets/30021673/5f842a56-59e1-41cc-94f2-5ff03ced562d)
"Oops, the server returned an error.
404 This is a chat model and not supported in the
v1/completions endpoint. Did you mean to use v1/ch ..."

### Expected Behavior

get text by OpenAI

### Steps To Reproduce

click on any AI related button

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### What template are you using?

Chikorita

**Comment by andy-vdg** [comment]
Related to my request [here](https://github.com/AmruthPillai/Reactive-Resume/issues/1584)
