### ISSUE TITLE
 [Bug] <No longer able to add bullets or numbered lists to text>

### ISSUE THREAD

**Issue by FujinNiazi** [AmruthPillai/Reactive-Resume#1588]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I saw that in the current version markdown isn't supported. But the above the field there are option to highlight, italisize and so on but there isn't any opption for numbererd lists or bullets

### Expected Behavior

I should be able to make numbered lists.

### Steps To Reproduce

Try to make numbered lists on any text.

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Rhyhorn

**Comment by AmruthPillai** [comment]
@FujinNiazi

https://github.com/AmruthPillai/Reactive-Resume/assets/1134738/a428fbec-87c2-437c-9d3b-f901c037dd81

**Comment by andy-vdg** [comment]
OMG... so it is actually a UI problem with your rich text editor toolbar. There is no scrollbar visible and it's really hard for me to actually make it appear when I try. But I see most controls are there. Any chance you could make that a LOT more visible?

**Comment by krankos** [comment]
I have the same issue here. To be able to scroll I have to use the inspect element tool to have a mobile view and  drag

**Comment by FujinNiazi** [comment]
Oh I totally missed that.
Thanks for the help!
