### ISSUE TITLE
[Feature]  request for old template 

### ISSUE THREAD

**Issue by sauravJ14** [AmruthPillai/Reactive-Resume#1589]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Can we get some of old templates back I don't remember name for template but I got screenshot for reference 
![Screenshot 2023-11-25 230105](https://github.com/AmruthPillai/Reactive-Resume/assets/88983642/759cfe69-9e59-42c3-91ce-41af058d1905)

**Comment by AmruthPillai** [comment]
Will definitely take it up and include this template, and more very soon. Will prioritize bringing back all the old templates, as I've had multiple requests about that.

**Comment by sauravJ14** [comment]
> Will definitely take it up and include this template, and more very soon. Will prioritize bringing back all the old templates, as I've had multiple requests about that. 

Is there any estimated time that you can provide when these templates will be back 
Thankyou

**Comment by andy-vdg** [comment]
Yes please - my old template disappeared as well.

**Comment by AmruthPillai** [comment]
Working on it as we speak.
