### ISSUE TITLE
[Help] How to ensure the application is running when deployed using docker in local system 

### ISSUE THREAD

**Issue by rajeshkumargp** [AmruthPillai/Reactive-Resume#159]
I have followed the steps specified here https://docs.rxresu.me/deployment/#docker. 

After `docker pull`,  I executed `docker run amruthpillai/reactive-resume` . 

I can find the application  is up when examined `docker ps`.

How to access the web application locally . ?

Also, please provide steps on how  to run in local system for deployment.

Steps I have followed: 
1. `docker pull amruthpillai/reactive-resume`
2. Run using the command `docker run -p 80:8000 amruthpillai/reactive-resume:latest` using port forwaring.

Accessing from browser:
With port 80 and With port 8000: I made below calls. 
1. Tried for accessing `localhost.com`  
1. http://127.0.0.1:8000/50x.html  (after checking nginx.conf.d)
1. http://localhost:8000/50x.html

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
