### ISSUE TITLE
[Feature] The possibility to disable new sign ups.

### ISSUE THREAD

**Issue by ektorasdj** [AmruthPillai/Reactive-Resume#1592]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Hello and thank you for this great tool!
In reactive resume v3 i was able to stop new sign ups by using the env variable PUBLIC_FLAG_DISABLE_SIGNUPS=true (That way i could avoid unwanted users creating accounts).
Its not possible in version 4 right now.
I will really appriciate if you find some time to implement this in reactive resume v4.
Thank you!

**Comment by ektorasdj** [comment]
@AmruthPillai Hello, Thank you for looking into it and implementing it!
Unfortunately it still doesnt work for me.
I have updated the docker image to 4.0.2 and added the new env variable  VITE_DISABLE_SIGNUPS=true but i am still able to create accounts as before.

**Comment by AmruthPillai** [comment]
Just out of curiosity, are you creating accounts with email or GitHub/Google?

When the env variable is set to true, it would basically show an alert on the register page that signups are disabled and also hides the email signup flow.

I tested it on the production instance too and works as expected, probably might need to pull and restart the services so that the new variables get refreshed.

**Comment by ektorasdj** [comment]
Hello! Did you maybe find anything wrong with my config?
I am still not able to disable signups even after repulling/recreating everything.
Thank you

**Comment by ValorVie** [comment]
I also encountered the same issue, and according to my research, as explained on https://vitejs.dev/guide/env-and-mode.html, Vite applications behave differently when loading environment variables in NODE_ENV=production and NODE_ENV=development.

When NODE_ENV=production, the default environment variables during build time are not overridden by subsequent environment variable settings. I confirmed this behavior by adding ENV VITE_DISABLE_SIGNUPS="true" in the dockerfile during the Build Image stage.

However, when I set NODE_ENV=development, setting VITE_DISABLE_SIGNUPS="true" in docker-compose also works normally.

**Comment by mariushosting** [comment]
@AmruthPillai Same issue here.
Still not be able to disable user registration with the following environment:

VITE_DISABLE_SIGNUPS: true

**Comment by kgotso** [comment]
@AmruthPillai i think based on the Vite limitation on only supporting build time variables, this should be exposed as a backend query. So at runtime the client should query the backend on whether or not sign up are allowed.

**Comment by Eurotimmy** [comment]
Hi @AmruthPillai, thank you for this app!
I can't disable the signup / create account by using "VITE_DISABLE_SIGNUPS: true" either.

**Comment by ValorVie** [comment]
For me, I just need to git clone this project, and then add the VITE_DISABLE_SIGNUPS="true" environment variable during the build stage in the Dockerfile. After using this modified Dockerfile to build the image, I can disable signup when NODE_ENV=production.
<details>

<summary>Dockerfile example</summary>

```dockerfile
...
# --- Build Image ---
FROM base AS build

ENV NX_CLOUD_ACCESS_TOKEN=$NX_CLOUD_ACCESS_TOKEN
ENV VITE_DISABLE_SIGNUPS="true"

COPY .npmrc package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build
...
```

</details>

**Comment by kiddalpha** [comment]
Any update on this?  It's completely unusable if we can't disable public account creation.

**Comment by CharlesDerek** [comment]
If you go to the ./apps/server/src/auth/auth.controller.ts on the back end.
After verifying the desired accounts (so only those can login)..
comment out the post logic for the back end:
```
  @Post("register")
  async register(@Body() registerDto: RegisterDto, @Res({ passthrough: true }) response: Response) {
    const user = await this.authService.register(registerDto);

    return this.handleAuthenticationResponse(user, response);
  }
```
--> to -->
```
/*
  @Post("register")
  async register(@Body() registerDto: RegisterDto, @Res({ passthrough: true }) response: Response) {
    const user = await this.authService.register(registerDto);

    return this.handleAuthenticationResponse(user, response);
  }
*/
```

So that even if someone manipulates the front end it can't add a new account.

Further i'd recommend adding some firewall logic so that the public facing endpoints can't send any requests to the other ports/services indirectly.
