### ISSUE TITLE
[Bug] Inconsistency in Language Options

### ISSUE THREAD

**Issue by felix-seifert** [AmruthPillai/Reactive-Resume#160]
In the tab _Settings_, one could choose the displayed language. In the dropdown list, several languages are offered. The first word is the name of the language in English. It is debatable whether English spelling the best way to show the language because non-natives might not know how their own language is spelled in English.

Nevertheless, the more severe issue is what is written in the parentheses. It is not clear what should be written their: Should it be the name of the language in their native spelling or should it be the name of the country where the language originates in its native spelling?

My suggestion is to clarify this issue first. Then, the displayed language options could be corrected according to the previous clarification.

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
