### ISSUE TITLE
[Bug] Or not a bug? Interesting generated titles for CVs

### ISSUE THREAD

**Issue by andy-vdg** [AmruthPillai/Reactive-Resume#1608]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Why is RXResume calling me names?
<img width="335" alt="image" src="https://github.com/AmruthPillai/Reactive-Resume/assets/19990167/b7429013-2b3c-4c7b-9501-a6870d72abb8">
🤣 😆 

### What template are you using?

None

**Comment by AmruthPillai** [comment]
Hahaha. Well. You got some of the unfortunate names. Probably should add a filter, but it's also fun 😅 This isn't some corporate politically correct project.

This is indeed a randomly generated title. When creating a resume, you can click on the magic wand icon to generate a name. Keep clicking on it to cycle between different names, to choose one less insulting 😅
