### ISSUE TITLE
[Bug] Language Changes Do Not Change All Tabs

### ISSUE THREAD

**Issue by felix-seifert** [AmruthPillai/Reactive-Resume#161]
When another language than _English (US)_ gets/is already selected, lots of words are displayed in the selected language. However, the names of the tabs on the left side do not change; they are still displayed in English. Furthermore, the button _Delete_ does not change its label and is still displayed in English (e.g. within _Certifications_ or _Languages_).

**Comment by The-Inamati** [comment]
I have the same issue in Portuguese. All the fields of the profile remain in English and I have no way of editing them. Can you tell me where is the file I can edit to correct this?

**Comment by felix-seifert** [comment]
Actually, you could change them during runtime (except _Profile_). In each tab on the left is a text field behind the tick. If you change the text in this field, also the tab label will change. However, these fields keep whichever text you put in there and the translation doesn't change it.

**Comment by felix-seifert** [comment]
The option to translate the delete button might exist now. However, the translations have to be included because till now, no translation of the delete button is visible.

Might it be possible to also add an automatic translation of the tab texts or is it better to let the user do this manually?
