### ISSUE TITLE
Saved Resume Database/Data issue. Latest changes will automatically restore to previous version. Then it will be restored back after 24 hours.

### ISSUE THREAD

**Issue by malcolmlucian** [AmruthPillai/Reactive-Resume#1626]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

Latest changes to resume will automatically restore to previous version (And latest changes will be lost). Then it will be restored back after 24 hours. This causes loss of effort in resume creation. Now this is second time this is happening again and I have lost the current changes to the resume I did. My guess it could be possible issue in data sync in between active/passive servers that save database. Kindly look into this as other users might be facing same issue but not knowing how to report the issue. I created github account just to report this issue. Thanks

### Expected Behavior

The latest changes should be there so that users should not need to start all over again. As it takes time to work on resumes.

### Steps To Reproduce

1) Open RX Resume website https://rxresu.me/
2) Go to Dashboard
3) Enter username and password
4) Click on "Resumes" above settings to see all saved resumes.
5) Edit a resume for 3 to 4 hours. then wait for sometime and it will be restored to old version as if no changes were made.
6) Wait for 24 hours with an hope that it be restored or start working again on resume from scratch.

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by malcolmlucian** [comment]
### Found a work Around ###

For the Resumes that I couldn't see the latest changes. I created a duplicate of that resume and I could see the latest changes in the duplicate copy. Found a work around. But definitely this need your help to look into it.

@AmruthPillai sir, you are a gem as you have created a wonderful tool for the community. Thanks once again! 💯

**Comment by gautam-jha** [comment]
Facing the same issue, latest duplicate copy did not helped it was kind of similar
