### ISSUE TITLE
Run the app locally without having to install pnpm on the host machine

### ISSUE THREAD

**Issue by AndreaPi** [AmruthPillai/Reactive-Resume#1628]
[CONTRIBUTING.md ](https://github.com/AmruthPillai/Reactive-Resume/blob/86430bb14351942f380bb496f76f41c601b4da71/CONTRIBUTING.md) shows how to run the app locally using Docker. However, it requires installing `pnpm` **AND** the project dependencies (with `pnpm install`) in the host machine. I don't want to do either: I use Docker, because I don't want to install anything locally, but only inside a Docker image. Could you provide a Dockerfile to build a Docker image, which I could spin with `docker compose`? Thanks

**Comment by AmruthPillai** [comment]
Of course, this compose example demonstrates exactly what you are asking for: https://github.com/AmruthPillai/Reactive-Resume/blob/main/tools/compose/simple.yml

**Comment by AndreaPi** [comment]
Thanks, @AmruthPillai, this works really well.
