### ISSUE TITLE
[Bug] GitHub markdown doesn't work in Objective section of Castform template

### ISSUE THREAD

**Issue by InfraRepo** [AmruthPillai/Reactive-Resume#163]
**Describe the Bug**
I am trying to insert a bullet (* in markdown language) in "Objective" section but it actually doesn't have any impact on what's displayed.

**Reproduction**
1. Create new CV
2. Select Castform template
3. Go to "Objective" section
4. Insert * some text

**Expected Behaviour**
seeing a bullet in the text

**Screenshots**
![image](https://user-images.githubusercontent.com/65193550/82117698-31746900-9772-11ea-9469-75e4d489e7a2.png)

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
