### ISSUE TITLE
[Bug] Improper flow of information on PDF

### ISSUE THREAD

**Issue by BrunoElo** [AmruthPillai/Reactive-Resume#164]
**Describe the Bug**
When saving as PDF, the "Awards and Honour" section shifts to a new page leaving a large blank space before it in the flow of information.

**Reproduction**
Steps to reproduce the behaviour:
1. Fill the details of the "work experience" section to occupy about half the page
2. Fill the details of the "awards and Honour" section to occupy more than half the page
3. click on the printer icon to print or save as PDF

**Expected Behaviour**
I expected a normal flow of the information in the resume document during and after saving the PDF.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/25552096/82119359-b2812f80-9775-11ea-816f-d8989e7eb477.JPG)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Additional Context**
This is happening with the "Awards and Honour" section
It's as if the software expects all information to be on a page...any overflow of information in a section may shift the entire section to a whole new page.

**Comment by BrunoElo** [comment]
@AmruthPillai I'm really hoping that this issue can be resolved as I'm left with no choice but to submit a resume with that gap in it. 😭
Please help.

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
