### ISSUE TITLE
[Bug] Since update to latest version, login does not work and no error is provided. 

### ISSUE THREAD

**Issue by bytenerd** [AmruthPillai/Reactive-Resume#1644]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

When I attempt to login at https://rxresu.me/ with my account creds (email and password), then hit the Sign In button, the screen flashes briefly but does not log in. The email and password fields are reset to defaults. I have tried both username and full email address which I know to be correct as they are stored and previously used (days prior) from a password manager. I have also used the password reset path and still get the same result after resetting the password. I've also tried InPrivate mode which I think eliminates any potential cookie or Extension issue. Same result. 

### Expected Behavior

Prior to the update, authenticating would take me to my resumes. 

### Steps To Reproduce

1. Go to https://rxresu.me/
2. Choose "Get Started" button
3. Enter email and password
4. Choose "Sign in"

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What template are you using?

None

**Comment by damnitrahul** [comment]
Hey @bytenerd login is working fine for me. Can you try logging in via Incognito mode?

**Comment by bytenerd** [comment]
I just tried again using Incognito mode in Chrome, and also InPrivate in Edge. Both have same result as I described in the bug. As I noted, it worked fine prior to the recent version upgrade but then stopped working after the upgrade. I just tried to reset my password again, same result. My hunch was potentially a bug with password character handling so I tried resetting my password using special characters and also without special characters, and also tried both 12 and 8-character lengths. None change the outcome. I'm happy to coordinate a debug tracing session if that would help?

**Comment by chunkycarrie** [comment]
I'm facing same issue. I've used to log in with nickname and password, but with update it isn't possible anymore? Tried to reset the password few times, log in using same Google account via "or continue with Google" but no luck so far, every time I get
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/76202076/2c0a6598-2c26-415e-b2f0-32e5f5f408a9)

**Comment by joogoo** [comment]
Same issue here while trying to login with my email and password.
I did a password reset, and achieved to do it, so my account looks to be valid, but I'm not able to connect anymore.
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/11720743/079a0d79-e636-451a-914f-29236f0f817f)

**Comment by moxw** [comment]
Facing the same issue.

**Comment by chunkycarrie** [comment]
@AmruthPillai is there any chance to get my account backup at least so I can host old version locally?
Wrote You an email but no answer so far.

**Comment by chunkycarrie** [comment]
@AmruthPillai still have same error, is it possible to have a backup/export of my account to at least not lose data?

**Comment by chunkycarrie** [comment]
Guys, try to log in once again, worked for me (email+password)

**Comment by AmruthPillai** [comment]
I'm glad you got it to work again, great news :)

Yes, custom CSS has been a bit of a rabbit hole that I'm not able to get it to work correctly, but you should see this feature soon on upcoming versions. 

It's mostly about allowing all inner components and sections to be accessible through the DOM selector in the most code-reusable way.
