### ISSUE TITLE
[Feature] Add a Projects section

### ISSUE THREAD

**Issue by ShubhamVerma1811** [AmruthPillai/Reactive-Resume#165]
**Describe the solution you'd like**
Add a Project section where we have a Project name, its description and add a link that takes us to the live demo of the project.

**Comment by BrunoElo** [comment]
For the link aspect, you can use markdown formatting to add it in description.

**Comment by ShubhamVerma1811** [comment]
> 
> 
> For the link aspect, you can use markdown formatting to add it in description.

Yeah that works, but there is no Project section for that.

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
