### ISSUE TITLE
[Feature] Automatic CV Generation Option with ChatGPT

### ISSUE THREAD

**Issue by juliandaz11** [AmruthPillai/Reactive-Resume#1658]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

it would be fantastic to have the ability to generate the CV Headline, Summary, Experience, Skills, and Interests automatically with ChatGPT, simply by entering the professional sector.

**Comment by AmruthPillai** [comment]
It's more of a prompt to be created than a feature. I've already described how you can rewrite a resume using ChatGPT in the docs: https://docs.rxresu.me/product-guides/use-chatgpt-to-rewrite-your-resume

You would just have to rephrase the prompt to do what you want it to do.
