### ISSUE TITLE
[Feature] Ability to add GitHub and LinkedIn url at the top header .

### ISSUE THREAD

**Issue by ShubhamVerma1811** [AmruthPillai/Reactive-Resume#166]
**Describe the solution you'd like**
At the top header where we have our phone number, website and mail id, Add the option to add GitHub and LinkedIn URL too.

**Comment by Jacalz** [comment]
I agree. Would be a really wonderful feature to have 👍

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
