### ISSUE TITLE
PDF exports dont contain text or clickable links

### ISSUE THREAD

**Issue by mporam** [AmruthPillai/Reactive-Resume#169]
**Describe the Bug**
Not sure if this is a bug or the way it was intended but the PDF export gives a PDF image, rather than rendered text. this means you cannot copy text from the file, or make links clickable. Unfortunately, this makes the tool pretty unusable for the real world.

**Reproduction**
Steps to reproduce the behaviour:
1. Create a CV with links/text in
2. Click on PDF download button center bottom
3. Open PDF in any PDF program
4. Realise you cannot click links or highlight text

**Expected Behaviour**
Text should be rendered as text to the PDF. suggest changing PDF export library being used, or adjusting the settings of the current one.

**Desktop (please complete the following information):**
 - OS: all of them
 - Browser: all of them

**Additional Context**
N/A

**Comment by BrunoElo** [comment]
@mporam did you click the diskette icon or the printer icon? The diskette icon exports an image-like file in PDF like the one you described while the printer icon exports actual PDF files which has all characteristics of a PDF file... including what you desire.

**Comment by felix-seifert** [comment]
However, do we need the diskette icon then? Ideally, the diskette icon would open a save dialogue and save the resume not as an image but as a rendered text (like via the print option).

**Comment by wei** [comment]
Diskette has the ability to export an unconstrained pdf which is the advantage over print. However, not having selectable text and links is a major drawback that I only discovered after submitting an application. Are there major difficulties generating pdfs with actual text? 😃

**Comment by janjagusch** [comment]
just noticed that there is a info message when using the :floppy_disk: save.

> This export method makes use of HTML canvas to convert the resume to an image and print it on a PDF, which means it will lose all selecting/parsing capabilities. If that is important to you, please try printing the resume instead, using Cmd/Ctrl + P or the print button below. The result may vary as the output is browser dependent, but it is known to work best on the latest version of Google Chrome.

i personally did not notice that when saving my resume (my bad! :sweat_smile:). maybe that warning could be bold or highlighted somehow?

**Comment by kptawesome** [comment]
> maybe that warning could be bold or highlighted somehow?
Yes that would be nice. I'd even like a modal popped between the click event and the actual download.

**Comment by mporam** [comment]
Sorry only just seen the responses here. I see what you mean about using the print button. The UX of that is very confusing, as it's not printing it's saving that I want to achieve. The message in the save popup is quite technical and not clear or obvious especially for non-devs. Perhaps some tooptips to explain this would be better? Certainly some explanation is needed to show that the print icon is actually for saving as a rendered PDF

**Comment by Mordax** [comment]
Just jumping in here to say that certain templates (Like Pikachu) don't render correctly with the print to pdf options, and when doing the microsoft print to pdf which does render correctly is still unclickable.

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
