### ISSUE TITLE
[Feature] Prevent losing everything with one click

### ISSUE THREAD

**Issue by thomasgroch** [AmruthPillai/Reactive-Resume#171]
**Prevent losing everything with one click**
I get frustrated when filling out a huge form and accidentally press a button and lose everything without warning.

**Solution I would like**
On the "Actions" menu, "Load Data" and "Reset" button should have a simple confirmation dialog.

**Alternative solution**
It may not be necessary to have a full dialog, just a second confirmation click would be enough.

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
