### ISSUE TITLE
[Feature] Optional "start date" of my work experience

### ISSUE THREAD

**Issue by thomasgroch** [AmruthPillai/Reactive-Resume#172]
**Optional date on work experience**
I don't like it when the tool forces me to fill in the "start date" and "end date" of my work experiences.

Ex.:
```
Start Date: ""
End Date: "2015"
Result: " - 2015"
```

**Solution I would like**
In the "Work Experience" section I would like it to be possible to fill in only the "End Date" leaving "Start Date" empty.
```
Start Date: ""
End Date: "2015"
Result: "2015"
```

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
