### ISSUE TITLE
[Feature] Ability to fill the form in split screen mode

### ISSUE THREAD

**Issue by thomasgroch** [AmruthPillai/Reactive-Resume#173]
**Ability to fill the form in split screen mode**
I imagine that like me, many people would like to fill out the form with their current curriculum open on half of the screen.

**Solution I would like**
Toggle side menus visibility would be nice, but I would also like to see only the left menu to focus on filling in the information.

**Alternative solution**
It may not be necessary to have a full dialog, just a second confirmation click would be enough.

**Current behavior screenshot**
![file 1](https://user-images.githubusercontent.com/67318/82738042-613fe580-9d0b-11ea-85f6-2d68e03cb8cf.png)
_Example of my screen._

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
