### ISSUE TITLE
[Feature] <title>page limit

### ISSUE THREAD

**Issue by link-hao** [AmruthPillai/Reactive-Resume#1731]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Provides paging function, so that when the resume needs to be printed, it will not be all on one page, which will appear too small and blurry.

**Comment by AmruthPillai** [comment]
Please read the docs, I've written a guide about this here: https://docs.rxresu.me/product-guides/creating-a-multi-page-resume.

**Comment by TasStef** [comment]
IT would be better if this was an automatic adjustment via toggle switch
