### ISSUE TITLE
[Bug] Documentation: Entire `source-code` folder is missing from the published output

### ISSUE THREAD

**Issue by yozlet** [AmruthPillai/Reactive-Resume#1732]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

In the `docs` branch, the entire `source-code` folder doesn't seem to be included in the published site [`docs.rxresu.me`](https://docs.rxresu.me/). This section seems useful and should be included.

### What template are you using?

None

**Comment by yozlet** [comment]
I'm guessing that much of the content in `source-code` needs updating for v4. I'm happy to do a little work on that if it'd be valuable, just let me know.

**Comment by AmruthPillai** [comment]
Please check the `docs` branch.
