### ISSUE TITLE
why dont use useCallback and useMemo functions?

### ISSUE THREAD

**Issue by PuddingJoker** [AmruthPillai/Reactive-Resume#1739]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Mainly a personal question of mine, why not use these react optimization methods?

**Comment by AmruthPillai** [comment]
@PuddingJoker I'm not an expert in caching or in React by any means, but from what I've understood about useCallback and useMemo were that they are to be used in resource intensive actions, for example, when you type/submit a series of numbers and you have to process it through some sort of long algorithm (something bruteforce), so you expect it to take a few ms.

I just didn't have any use-cases where I run any resource intensive code like that within the app. It seemed okay to have a few unnecessary re-renders for the sake of reactivity, as long as the app didn't seem laggy, and it's quite a small application so you wouldn't need to cache that aggressively IMO.
