### ISSUE TITLE
Reset button does not work

### ISSUE THREAD

**Issue by tttruc** [AmruthPillai/Reactive-Resume#174]
After finished creating Resume, I used Reset button to reset data but it does not work. I found workaround: refresh browser then try to reset again, it cleared data successfully.

Please help fix.

**Comment by AmruthPillai** [comment]
@tttruc Are you still facing this issue in the new update?

**Comment by tttruc** [comment]
@AmruthPillai , Yes, I'm still facing this issue with https://rx-resume.web.app/. Please let me know how to check the new update. Many thanks.

**Comment by halilcakar** [comment]
I believe this is now working. I've just used Reset button and it does work @tttruc

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
