### ISSUE TITLE
[Bug] Downloaded PDF have issue(s) with Typography options (Hide Icons & Underline Links)

### ISSUE THREAD

**Issue by Samrat-Saha-Sammy** [AmruthPillai/Reactive-Resume#1750]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

[_Note_] All Templates are affected. 

**Typography > Options > Hide Icons**

When the `Hide Icons` toggle option is enabled, the icons (eg. inside the header section @ icon, location icon etc. ) should not be visible or in other words should be hidden. 

**Inside Builder Preview**: Works as expected and looks fine (icons toggle visibility)
**Inside Downloaded PDF**: Not Working as properly as displayed in Builder Preview before download. When the `Hide Icons` toggle is disabled or Not hiding icons, it works. But when the toggle is enabled or hides the icons, the icon placeholders take a blank space, resulting in an unexpected User Interface Design. 

**Typography > Options > Underline Links**

When the `Underline Links` toggle option is enabled, the links (eg. inside the header section phone no., email etc. ) should be underlined. 

**Inside Builder Preview**: Works as expected and looks fine (links toggle underline)
**Inside Downloaded PDF**: Not Working as properly as displayed in Builder Preview before download. When the `Underline Links` toggle is disabled or Not underlining links, it works. But when the toggle is enabled or the user needs to underline the links, it is missing, resulting in unexpected behaviour. 

**Bug Demo** 

![Demo](https://github.com/AmruthPillai/Reactive-Resume/assets/4963559/b3d67096-948d-4a44-a778-d8e6117037df)

### Expected Behavior

**Typography > Options > Hide Icons**
**Inside Downloaded PDF**: When the toggle is enabled or hides the icons, the icon placeholders should not take a blank space. 

**Typography > Options > Underline Links**
**Inside Downloaded PDF**: When the toggle is enabled or the user needs to underline the links, then respected links should be displayed as underlined.

### Steps To Reproduce

1.  Open [rxresu.me](https://rxresu.me) in Browser
2.  Login with credentials
3.  Go to `Dashboard` Page
4.  Click on `Create a new resume`
5.  Click on the dropdown icon beside the `Create` button and click `Create Sample Resume` 
6.  Click on the newly created sample resume to open in editor/builder
7.  Navigate to `Typography Section` from the right sidebar
8.  Scroll down to the options section
9.  Toggle Options
10.  Navigate to `Export` from the right sidebar
11.  Click on `PDF` to Download as a PDF file.

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Azurill

**Comment by abizek** [comment]
This is working from v4.0.9 cc: @AmruthPillai
