### ISSUE TITLE
[Feature] Latvian language

### ISSUE THREAD

**Issue by CodeExplorer123** [AmruthPillai/Reactive-Resume#1766]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Hello, 
Could you please add Latvian as a language, I'd like to contribute to it.
 
Thanks!

**Comment by AmruthPillai** [comment]
Thank you for the interest to contribute. Sorry that I didn't have Latvian in the list already, but I've made sure to add it now.
You should be able to contribute translations here: https://crowdin.com/project/reactive-resume/lv
