### ISSUE TITLE
[Feature] Add Chinese Language Support

### ISSUE THREAD

**Issue by Ramboo-han** [AmruthPillai/Reactive-Resume#1783]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

I am proposing the addition of **Chinese language support** to the Reactive Resume project. This enhancement is significant for several reasons:

Expanding User Base: There is a substantial number of Chinese-speaking users globally, and providing support for the Chinese language would make the project more accessible to them. By doing so, we can significantly expand the user base and enhance the project's global reach.

Inclusivity: Adding Chinese language support aligns with the project's goal of being more inclusive and accommodating to users from different linguistic backgrounds. It ensures that the project can cater to a wider audience, promoting diversity and inclusion.

Market Demand: There's a noticeable demand for resume-building tools that support Chinese, given the large job-seeking population and the growing number of professionals in China and Chinese-speaking regions looking for employment opportunities both locally and internationally.

Competitive Advantage: By offering Chinese language support, Reactive Resume can distinguish itself from other resume-building tools that do not provide this option. This feature can serve as a competitive advantage, attracting users who specifically require resumes in Chinese.

User Experience: For Chinese-speaking users, navigating and utilizing the tool in their native language would significantly enhance usability and satisfaction. It would also reduce the likelihood of misunderstandings or errors that can occur when users are forced to use the tool in a second language.

To implement this feature, we could start by translating the UI elements, templates, and documentation into Chinese. Community contributions and feedback from Chinese-speaking users could be invaluable in ensuring the quality and accuracy of the translation.

I believe that adding Chinese language support is a crucial step forward for the Reactive Resume project. It will not only meet the current demands of a significant user demographic but also position the project as a leader in accommodating the diverse needs of its global user base.

Thank you

**Comment by AmruthPillai** [comment]
![Uploading Screenshot 2024-03-10 at 11.09.23 AM.png…]()

**Comment by AmruthPillai** [comment]
The app is already available in both Chinese Simplified. I'm still actively looking for translators who can improve the language support. They can do so here: https://translate.rxresu.me/

![Screenshot 2024-03-10 at 11 09 23 AM](https://github.com/AmruthPillai/Reactive-Resume/assets/1134738/085d25ce-a915-4a62-8ac8-a93460cf70d1)
