### ISSUE TITLE
How do I update the default template?

### ISSUE THREAD

**Issue by justpankajdotcom** [AmruthPillai/Reactive-Resume#1792]
*This is not a bug/feature request.*

Hi everyone, 

I need some help with updating default selected template when running locally.

The default template that is selected is `rhyhorn`, but I would like to change it to say `pikachu`. 
How can I do that?

I tried updating the schema like this  - 

```

libs/schema/src/metadata/index.ts

// Schema
export const metadataSchema = z.object({
  template: z.string().default("pikachu"), --> Changed
  layout: z.array(z.array(z.array(z.string()))).default(defaultLayout), // pages -> columns -> sections
  css: z.object({
    value: z.string().default(".section {\n\toutline: 1px solid #000;\n\toutline-offset: 4px;\n}"),
    visible: z.boolean().default(false),
  }),


//Default metadata

export const defaultMetadata: Metadata = {
  template: "pikachu", ---> Changed.
  layout: defaultLayout,
  css: {
    value: ".section {\n\toutline: 1px solid #000;\n\toutline-offset: 4px;\n}",
    visible: false,
  },

```

I then migrated prisma and restarted via `pnpm run dev`

But still the default template is coming as `rhyhorn`. 

Any help appreciated.

**Comment by justpankajdotcom** [comment]
Can someone help me with this? Thanks.

**Comment by justpankajdotcom** [comment]
I have been able to resolve this issue. The problem was with triggering wrong docker-compose. I was triggering the wrong docker-compose. Thanks daniel @danieleverest  for offering your help. Really appreciate it.

**Comment by danieleverest** [comment]
💯
