### ISSUE TITLE
[Feature] Allow search Simple Icons on Profiles

### ISSUE THREAD

**Issue by LitoMore** [AmruthPillai/Reactive-Resume#1800]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Currently, the Simple Icons input will send a request to `cdn.simpleicons.org` every time press the key. It's not a good practice sending too many 404 requests.

It would be good to create a searchable dropdown for showing all icons. Here is a similar thing: https://litomore.github.io/simple-icons-figma/. And it's source code is at https://github.com/LitoMore/simple-icons-figma

We could update the UI to use a [Popover](https://www.radix-ui.com/themes/docs/components/popover) on the icon and remove the input field.

**Comment by Rash-Hit** [comment]
@AmruthPillai .. will it be fine .. if i implement debouncing for this issue ?? if yes then please assign this issue to me

**Comment by AmruthPillai** [comment]
Honestly, for the sake of quicker reactivity, it's fine to hit a few 404s before reaching the correct URL. There's no harm in this.

**Comment by LitoMore** [comment]
There are bunch of requests on this UI. And it's consuming the Vercel resource of https://github.com/LitoMore/simple-icon-cdn rapidly. You may reach the rate limit in a short time.

Better to use a debounce for web requests to keep your stability.

**Comment by AmruthPillai** [comment]
@LitoMore Ah, I'm sorry. I had no idea that you were one of the maintainers of Simple Icons. Has this app caused so much of a hassle for you guys at Simple Icons? Just surprised by the reach is all. So sorry about that. Thank you so much for all your work with maintaining the icon library. Hope it's not been too much trouble.

If it's okay to share, I'd be curious to know how much of the traffic on Vercel for the CDN was from rxresu.me?

@Rash-Hit Feel free to come up with a solution for debouncing the requests made to the Simple Icons CDN. (300-400 ms should do, I think). Will assign the ticket to you :)

**Comment by LitoMore** [comment]
> If it's okay to share, I'd be curious to know how much of the traffic on Vercel for the CDN was from rxresu.me?

I can't see this due to we're using Vercel's free plan.

BTW, I can help to create a dropdown for your when I have time. So that users can preview icons in a list.

**Comment by Rash-Hit** [comment]
@AmruthPillai migrations command not working , can you please help ??

**Comment by LitoMore** [comment]
@Rash-Hit Please check if your step 4 is correct.

See https://github.com/AmruthPillai/Reactive-Resume/blob/main/CONTRIBUTING.md#4-fire-up-all-the-required-services-through-docker-compose

**Comment by Rash-Hit** [comment]
@LitoMore , yes containers are up and running

**Comment by LitoMore** [comment]
@Rash-Hit Alright. Then we may need @AmruthPillai to help out.

**Comment by AmruthPillai** [comment]
@Rash-Hit It looks like your Postgres is not reachable from the server. Do you have the same env variables set up on the compose file and the .env file?

**Comment by Rash-Hit** [comment]
@AmruthPillai sir i have changed the postgres url . migrations are working .. but now facing some issues regarding proxies ..
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/73944177/1b3d38b1-8379-4c59-bc42-a636c9162af8)

**Comment by Rash-Hit** [comment]
@AmruthPillai @LitoMore 
i think there is some issue with my machine , i've tried with codespaces and its working fine 
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/73944177/8ac4837e-b926-4dc8-be39-5f727934618f)
