### ISSUE TITLE
Sometimes Resume Fetches Old Changes And Then Latest Changes are Lost 

### ISSUE THREAD

**Issue by Rash-Hit** [AmruthPillai/Reactive-Resume#1802]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

It is very irritating when u visit the web and see that last changes were not there , instead resume are showing .. previous to previous changes .. 

It is happening not very frequently , but whenever this happen .. It feels like not worth it at all to do the changes again 

Here is the proof .. 
-------------
this is my dashboard  showing changes  ( and the main thing is , updatedAt showing correctly but not showing the correct updated changes)
https://rxresu.me/anubhav.rashit/web-dev

And this is the pdf I've downloaded when i did the changes at the same time 
[Resume.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/14548698/Resume.pdf)

-------------
 Please match the projects section in bottom of resume at both the places 
I've updated the sections from 3 projects to 4 .. but still dashboard showing very old changes 

----
Let me know any other details required regarding this ...

### Expected Behavior

Needs to show the latest changes . not only previous changes 

### Steps To Reproduce

Not sure how to reproduce the behavior . But this happened with me many times  

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by AmruthPillai** [comment]
Should be fixed now.
