### ISSUE TITLE
Website is not working: Giving 404 error

### ISSUE THREAD

**Issue by Vikrug2213** [AmruthPillai/Reactive-Resume#1803]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

![image](https://github.com/AmruthPillai/Reactive-Resume/assets/139533915/e947d039-e789-4e52-af99-782bf3b735d8)

### Expected Behavior

Website should be open clearly

### Steps To Reproduce

Open the website https://rxresu.me/

### What template are you using?

None

**Comment by nihal-here** [comment]
Yes, I'm facing the same issue as well.

**Comment by DaKheera47** [comment]
Same issue, testing from UK

**Comment by dnh33** [comment]
same issue

**Comment by cvyl** [comment]
Facing same issue from NL

**Comment by whoisnaisu** [comment]
same issue here

**Comment by AmruthPillai** [comment]
Hey folks, sorry for the 404.
It's quite late here, but looking into the issue right now.

**Comment by cvyl** [comment]
> Hey folks, sorry for the 404. It's quite late here, but looking into the issue right now.

Could it have anything to do with your recent commit? Or is the server itself at fault?

**Comment by AmruthPillai** [comment]
@cvyl The server is at fault, it keeps maxing out it's specs. Running `htop` shows the servers have a 100% memory usage almost all day every day. I have a two server Docker Swarm setup for this, and both of them get overwhelmed with requests some times.

**Comment by AmruthPillai** [comment]
It's back online now 🟢 

Thank you everyone for the helpful messages and emails, for bringing this to my attention.

**Comment by cvyl** [comment]
@AmruthPillai ah, thank you for clarifying!
