### ISSUE TITLE
[Bug]<Font subset and Font variants not working>

### ISSUE THREAD

**Issue by jagrutipixel** [AmruthPillai/Reactive-Resume#1805]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I cannot use the Font subset And font variants options; it directs me to a random page, and when I press back, it takes me to the home page.

### Expected Behavior

A working Font Subset and variants option to choose fonts.

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Rhyhorn

### Anything else?

-

**Comment by AmruthPillai** [comment]
@jagrutipixel Ah, I see. This is related to one of `cmdk`'s new breaking changes (https://github.com/pacocoursey/cmdk/issues/230#issuecomment-1986220383) to enforce CommandList, but it seems I have forgotten to add it over here. Thank you for raising the issue, will look into a fix ASAP.
