### ISSUE TITLE
Issue related to photo url

### ISSUE THREAD

**Issue by Vrushali1007** [AmruthPillai/Reactive-Resume#181]
I am unable to upload image using photo URL. Its better that instead of image url try just to upload it.

**Comment by AmruthPillai** [comment]
@Vrushali1007 Having to upload an image would require a server implementation and a storage to store images, which beats the purpose of complete privacy in the app. I haven't faced any problems having uploaded the image to imgur.com and grabbing the direct link (*.jpg), this works without any problem, maybe you could try that?
