### ISSUE TITLE
Do Page break when download in PDF

### ISSUE THREAD

**Issue by Vikrug2213** [AmruthPillai/Reactive-Resume#1811]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

You gave the line when an A4 page is ends but don't get the different pages in PDF after download. We only get all the info in single looooong page. It would be great if there is different A4 pages after one is filled completely. 
I saw that you gave a manual option to do that but that won't work is one section(for eg. experience section) is too long, that only work on different sections.
This feature would be great, make easy to read to recruiter.

**Comment by AmruthPillai** [comment]
You can follow this guide on how to create multiple pages of your resume: https://docs.rxresu.me/product-guides/creating-a-multi-page-resume

As for allowing a single section to be split up into multiple pages, I'm afraid the only option right now is to be able to split up your section (by creating a new custom section, or renaming an existing one), copy some of the items to the new one and move the new section to a new page using the Layout sidebar.
