### ISSUE TITLE
Upgrade browserless from v1 to v2?

### ISSUE THREAD

**Issue by theschles** [AmruthPillai/Reactive-Resume#1817]
https://github.com/AmruthPillai/Reactive-Resume/blob/11953af70038936556faf6705788aeedce822c92/tools/compose/development.yml#L44

Hi all,

I just realized the Docker Compose files specify `browserless/chrome:1.61.0-puppeteer-21.4.1`.

[Since January 2024, Browserless is no longer supporting v1.  It's all v2 from here.](https://github.com/browserless/browserless/blob/main/MIGRATION-2.0.md)

Thus asking: when it would be appropriate to upgrade browserless to v2?

**Comment by AmruthPillai** [comment]
The latest update to Reactive Resume is now on browserless v2.
