### ISSUE TITLE
Why are we using nrwl/ci's Github actions?

### ISSUE THREAD

**Issue by theschles** [AmruthPillai/Reactive-Resume#1818]
https://github.com/AmruthPillai/Reactive-Resume/blob/11953af70038936556faf6705788aeedce822c92/.github/workflows/lint-build.yml#L27

and

https://github.com/AmruthPillai/Reactive-Resume/blob/11953af70038936556faf6705788aeedce822c92/.github/workflows/lint-build.yml#L42

Use `nrwl/ci`'s Github Actions in the Lint Build...[which is throwing warnings](https://github.com/theschles/Reactive-Resume/actions/runs/8345318240) because [the versions of those actions use NodeJS 16 -- which is deprecated.](https://github.com/nrwl/ci/blob/81f119483401ffde8275edf4c089b42e24b92cf4/.github/workflows/nx-cloud-main.yml#L95)

Why exactly are we using a completely different project's Github Actions?

**Comment by radiovisual** [comment]
This repository is an [Nx monorepo](https://nx.dev/), and `nrwl` is one of the scopes owned by Nx. The action you see is [Nx's / Nrwl's recommended way to hook your project up to the Nx Cloud](https://github.com/nrwl/ci/tree/main).
