### ISSUE TITLE
[Feature] Request to add Cambria font

### ISSUE THREAD

**Issue by ishaanbhimwal** [AmruthPillai/Reactive-Resume#1822]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

I really require this font. Would be helpful if it could be added. Thanks!

**Comment by ishaanbhimwal** [comment]
@AmruthPillai Any updates?

**Comment by AmruthPillai** [comment]
Google Fonts unfortunately doesn't support this font specifically, as with most system fonts, and it's hard to embed the font to the PDF if it's not available globally as a hosted service. Right now, this is not planned but hopefully in the near future I can find another solution to get rid of the dependency from Google Fonts.
