### ISSUE TITLE
Euro Pass logo is not visible after downloading Euro Pass Resume 

### ISSUE THREAD

**Issue by rashidmakki** [AmruthPillai/Reactive-Resume#1825]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I have created resume and selected euro pass template. The template is working fine but when I export in pdf format Euro pass logo was not visible instead alternate text was visible.
![euro_pass_issue](https://github.com/AmruthPillai/Reactive-Resume/assets/52795057/cd9392ff-4f33-4643-b00a-2e83306b92f2)

### What template are you using?

None

**Comment by abizek** [comment]
Not getting the sample resume's profile picture either.
 
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/91976421/8edc2f78-1d95-4afc-b99e-3a6d68889e6b)

This is working as expected locally but https://rxresu.me cannot fetch the images from Imgur. Maybe Imgur has rate-limited the server? @AmruthPillai

**Comment by AmruthPillai** [comment]
@abizek it could be. Could you add these images to the public folder and reference them locally?

**Comment by abizek** [comment]
@AmruthPillai Can do. But I'll only add the Europass logo to public assets for now cause I don't want to mess with the resume schema just to support John Doe's picture :smile:. PR coming shortly.
