### ISSUE TITLE
[Feature] Collapse/hide sidebars in Resume Builder

### ISSUE THREAD

**Issue by nyadav810** [AmruthPillai/Reactive-Resume#1827]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

I don't use the right sidebar much since I've finalized my resume, but I do use the left sidebar and want to see the Artboard at the same time when the browser window is not very large.

I work on one monitor and have a job description open next to Resume Builder, so I would like to save some space by collapsing the right sidebar.

This is a wonderful tool! If I get some time I'll try to open a pull request for this feature.

**Comment by AmruthPillai** [comment]
You should be able to resize the sidebar by pressing and holding the edge of the left or right sidebar and closing it all the way. You can also click on the buttons on the top (header bar) to close the sidebars.

**Comment by nyadav810** [comment]
@AmruthPillai Thank you for the response! Neither option you suggested worked for me in Brave or Firefox (video shown is Firefox). I can't pull the resize button all the way to the right, nor is there a clickable element in the header of the sidebar

https://github.com/AmruthPillai/Reactive-Resume/assets/6948383/188e80dc-7c27-40b6-8f30-c426f5212abf
