### ISSUE TITLE
[Bug] Markdown style doesn't work in OBJECTIVE section

### ISSUE THREAD

**Issue by bryannsi** [AmruthPillai/Reactive-Resume#183]
When using the themes: _Gladie, Castform_ the markdown style don't work.
For example
![image](https://user-images.githubusercontent.com/9477700/84073914-e9bab900-a98e-11ea-9878-3dbf2a1b7802.png)

**Comment by AmruthPillai** [comment]
Fixed by @SHENG-X in #184 :)
Thank you!
