### ISSUE TITLE
[Feature] Change the resume slug

### ISSUE THREAD

**Issue by gcleaves** [AmruthPillai/Reactive-Resume#1833]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

I would like to change the slug of an existing resume.

P.S. RxResume is pretty freakin' awesome!

**Comment by AmruthPillai** [comment]
Right now, duplicating the resume would allow you to pick a new name and slug while maintaining the same resume data and styling. Would that approach work?
