### ISSUE TITLE
[Bug] Sidebar is not stretching to the full height

### ISSUE THREAD

**Issue by JKamsker** [AmruthPillai/Reactive-Resume#1847]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

![grafik](https://github.com/AmruthPillai/Reactive-Resume/assets/11245306/2d6440ea-abda-48f2-8b2f-a46b85f6db2e)
The sidebar does not stretch

### Expected Behavior

The sidebar should stretch from top to bottom

### Steps To Reproduce

1. Select Chikorita
2. Enter some text, but not enough to fill the page
3. The sidebar is not the full length

### What browsers are you seeing the problem on?

Firefox

### What template are you using?

Chikorita

**Comment by prithvi5481** [comment]
Can you please assign this issue to me as it seems it needs a small change in styling. Can give min width of 100% and this would work probably.

**Comment by JKamsker** [comment]
@prithvi5481 I mean, feel free to fork and pr a solution

**Comment by AashishSinghal** [comment]
I have raised fix PR (here)[https://github.com/AmruthPillai/Reactive-Resume/pull/1891]
