### ISSUE TITLE
[Feature] Add ability to import a local photo

### ISSUE THREAD

**Issue by Jacalz** [AmruthPillai/Reactive-Resume#185]
**Is your feature request related to a problem? Please describe.**

I would like to add a photo to my resume, but I am not happy with the fact that I need to add it using a website link. It doesn't feel correct from a privacy standpoint to need to have photos of yourself always available on some website out there.

**Describe the solution you'd like**
It would be better to have the option of pressing a button and importing a local photo from the file-system. Simple and useful way for adding a photo if it isn't on the website.

**Describe alternatives you've considered**
Non really. This is what the feature request is about :)

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
