### ISSUE TITLE
[Feature] Template with samples

### ISSUE THREAD

**Issue by rrjanbiah** [AmruthPillai/Reactive-Resume#188]
**Is your feature request related to a problem? Please describe.**

Initially, the view is completely blank. So, not getting a real feel about how it will look like. The template image when opened in new window has better look and feel; but it is still not very helpful.

**Describe the solution you'd like**

#162 When JSONResume support is added, there are multiple opportunities... In that ecosystem, there are multiple tools, including exporting LinkedIn profile to JSON, multiple design templates, etc So, a sample resume can easily be imported (as you do with templates now). https://standardresume.co/examples has many examples tailored to different designations.

**Comment by rrjanbiah** [comment]
Now only noticed the "Load demo data" option. Still keeping it open as more samples/examples as in https://standardresume.co/examples may be better

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
