### ISSUE TITLE
[Bug] Session Timeout

### ISSUE THREAD

**Issue by ghost** [AmruthPillai/Reactive-Resume#1887]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

Session timeout creates a user to still be able to interact with reactive resume but then doesn't save progress and you aren't technically logged in.

### Expected Behavior

To be able to stay logged in and make edits

### Steps To Reproduce

1. use arc browers
2. use windows 11
3. login to reactive resume
4. edit a resume
5. stay on the resume for 30 ish minutes
6. you will notice edits won't save
7. refresh page
8. you will be prompted to login again

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Kakuna

### Anything else?

Logs can be requested with instruction.

**Comment by Seantourage** [comment]
I believe this is the same as this reported issue:

https://github.com/AmruthPillai/Reactive-Resume/issues/1884

**Comment by AmruthPillai** [comment]
This issue should be resolved as of this release https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v4.1.2.
