### ISSUE TITLE
[Bug] can't export pdf

### ISSUE THREAD

**Issue by x1aoAi** [AmruthPillai/Reactive-Resume#1898]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

pdf export returns 404 error

### Expected Behavior

downloaded successful

### Steps To Reproduce

no responese

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by AmruthPillai** [comment]
Please check some of the other issues that talk about this problem. It mostly has to do with network configuration in your docker compose and setting the ENV variables correctly.
