### ISSUE TITLE
"postcss is not recognized command" When Run this project on local machine

### ISSUE THREAD

**Issue by GarvPHP** [AmruthPillai/Reactive-Resume#193]
When I will try to deploy this project on my local machine (Win 10, XAMPP SERVER). This error is comming when NPM START command is run. PLease help or suggest the necesary steps to install or run  this project.

**Comment by SHENG-X** [comment]
Try ```npm install*``` first then  ```npm start```

**Comment by AmruthPillai** [comment]
@GarvPHP There's a detailed guide on how to install and build from source on your local machine here in the documentation: https://docs.rxresu.me/building-from-source/#building-the-app

Hope that helps! :)
