### ISSUE TITLE
[Bug] Issuer Name printed double in CHIKORITA

### ISSUE THREAD

**Issue by Vishnu-add** [AmruthPillai/Reactive-Resume#1934]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

The issuer name is printed double in CHIKORITA template

### Expected Behavior

The issuer name should be printed once in CHIKORITA template

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Chikorita

**Comment by AusSecPaul** [comment]
Specifically under the Certifications section.
