### ISSUE TITLE
[Bug] in Pikachu, Gengar template address doesn't show up

### ISSUE THREAD

**Issue by RobbenP** [AmruthPillai/Reactive-Resume#194]
The first two address lines don't show in the Pikachu and Gengar templates. In the other templates they do show.

**Comment by AmruthPillai** [comment]
This is expected behavior, mainly cause the design of the resume is meant to have only the city/country where you reside, not the entire address. You can read more about this here: https://www.indeed.com/career-advice/resumes-cover-letters/should-you-put-your-address-on-your-resume

**Comment by RobbenP** [comment]
Maybe add a tooltip or something somewhere to explain this? I'm perfectly fine with this behaviour, but I had to look through to code to find why my address wasn't showing (I used only line 1 and 2)

**Comment by AmruthPillai** [comment]
Agreed, I realize that I should've used line 1 instead of line 3 for better UX. Will implement that very soon. Thank you for letting me know :) I hope you still find using Reactive Resume helpful. Thank you for the support.

**Comment by RobbenP** [comment]
I really like Reactive Resume! I find this a great project. It livens my resume a lot and it is opensource and selfhostable. Kudos to you for making this!
