### ISSUE TITLE
Not able to download resume 

### ISSUE THREAD

**Issue by pinkichauhan014** [AmruthPillai/Reactive-Resume#1947]

**Comment by AmruthPillai** [comment]
The app is currently under maintenance, running into server load issues. It'll be back shortly.

**Comment by pinkichauhan014** [comment]
Thankyou for your revert.

**Comment by youngrichu** [comment]
A work around I have found is disconnecting the wifi and connecting back then hard reloading.

**Comment by hknoener** [comment]
> A work around I have found is disconnecting the wifi and connecting back then hard reloading.

That's nice, it's works for me as well, thanks for sharing
