### ISSUE TITLE
[Bug] Cannot download PDF or review public resume

### ISSUE THREAD

**Issue by hamzakat** [AmruthPillai/Reactive-Resume#1952]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

I built yesterday a resume and i was able to download it successfully. Now, it is not possible at all to download the PDF and reviewing the public resume is buggy (sometimes works, sometimes not) 

### What template are you using?

None

**Comment by hamzakat** [comment]
It's working now (perhaps rebooting the server made it working again 😄)

**Comment by AmruthPillai** [comment]
Yes, the servers are really struggling to meet demands. If anyone reading this is keen on supporting the project, please consider donating so that I can rent better servers 🙏
