### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by JSDevUno** [AmruthPillai/Reactive-Resume#1954]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

when i click pdf download, it just go another blank page 

### What template are you using?

None

### Anything else?

cant download pdf

**Comment by sasukeuchicha** [comment]
yeah i am facing the same issue

**Comment by jingjiecb** [comment]
any solutions?

**Comment by Floppa2003** [comment]
Same issue.

**Comment by AmruthPillai** [comment]
Unfortunately, there's nothing I can do given the available resources. I have already maxed out the server to what I can afford to, even with the donations 😞 There are just a lot of people using the app (about 40-50k in any given day) and that causes a huge load on the chrome service, making for longer wait times and server crashes.

**Comment by hknoener** [comment]
Would it be possible to create a queue/async job and send it later then?

**Comment by AmruthPillai** [comment]
I've implemented the aforementioned solution as a fallback, to this issue, in this commit https://github.com/AmruthPillai/Reactive-Resume/commit/767573ce6d520ee5e484859d390ced9646dd3e17. I don't think it would solve the load problem outright, but it could at least do some help.

**Comment by FlameBreather28** [comment]
I am also facing the same issue .

until the issue gets resolved what you  can do it make the resume public and then visit the link and download it using (Ctr +P) and remove the margins . 

hope this works for other people .

**Comment by vasuadari** [comment]
Why not use github actions to generate the pdf?

**Comment by ratnadeep007** [comment]
Was facing same issue tried running on local same on main branch. Tried tag 4.1.6 and its working but couldn't import json.

**Comment by AmruthPillai** [comment]
@ratnadeep007 Please pin the browserless/chrome version to v2.13.0. The issue was not related to Reactive Resume.
