### ISSUE TITLE
[Bug] Unable to Download my resume

### ISSUE THREAD

**Issue by a-sad-dan** [AmruthPillai/Reactive-Resume#1955]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

Unable to download my resume. Only a blank page is opening (about:blank) on download link click. Checked with both the links (menu and sidebar) and with firefox browser and chromium. JSON download is working as expected.

### Expected Behavior

Download pdf on click

### What browsers are you seeing the problem on?

Firefox, Chrome

### What template are you using?

Azurill

**Comment by AmruthPillai** [comment]
Closing as a discussion about this is already underway here: https://github.com/AmruthPillai/Reactive-Resume/issues/1954#issuecomment-2165021696
