### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by 1312chwdp** [AmruthPillai/Reactive-Resume#1956]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

Wont let me export PDF

### What browsers are you seeing the problem on?

Firefox

### What template are you using?

None

**Comment by sunyu-ing** [comment]
can not export pdf

**Comment by AmruthPillai** [comment]
Closing as a discussion about this is already underway here: https://github.com/AmruthPillai/Reactive-Resume/issues/1954#issuecomment-2165021696
