### ISSUE TITLE
[Bug]Unable to donwload resume

### ISSUE THREAD

**Issue by Abhijith236** [AmruthPillai/Reactive-Resume#1958]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

Unable to download resume.It goes to a new blank tab instead 

### Expected Behavior

Should have started the download of resume

### Steps To Reproduce

Click export
Click download

### What browsers are you seeing the problem on?

Firefox

### What template are you using?

Bronzor

**Comment by AmruthPillai** [comment]
Closing as a discussion about this is already underway here: https://github.com/AmruthPillai/Reactive-Resume/issues/1954#issuecomment-2165021696
