### ISSUE TITLE
Can't download resume pdf shows blank

### ISSUE THREAD

**Issue by ANIKETKOCHHAR** [AmruthPillai/Reactive-Resume#1960]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

can't dowlnoad resume pdf

### Expected Behavior

seemless download of the resume

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Chikorita

**Comment by alainpaulinn** [comment]
I have the same issue

**Comment by sstathatos** [comment]
I have the same issue!

**Comment by mosivito** [comment]
Same issue as well.

**Comment by roshanabdullah** [comment]
yes I am having this issue....

**Comment by AmruthPillai** [comment]
@roshanabdullah Please pin the browserless/chrome version to v2.13.0. The issue was not related to Reactive Resume.
