### ISSUE TITLE
[Bug] <title>Problems with PDF Export

### ISSUE THREAD

**Issue by hechevar** [AmruthPillai/Reactive-Resume#1961]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

I started two days ago whith Reactive Resume, but now that I wanted to make update modifications, I detected two issues:

1. I cannot generate the PDF format that you export in Letter, it appears only in A4. For printing issues.
2. Today when I wanted to export to PDF again, it doesn't do it and it simply sends me to a blank screen, but it doesn't download the file

I hope for your collaboration to help me repair this problem.

### Expected Behavior

That I can generate my Resume in PDF, and that it can be output in Letter size

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

### Anything else?

None

**Comment by masumeee** [comment]
Same Here facing downloading issues.

**Comment by kamalnath2003** [comment]
Same with me

**Comment by twong-sea** [comment]
Me as well.

**Comment by hechevar** [comment]
I already tried again, but now the system indicates that It is a Server Error because it cannot find the Resume

**Comment by hechevar** [comment]
No, in fact I don't understand what generating a Public URL is, but this tool must work, because it worked yesterday. I need to generate the PDF and send it to the contractor.

**Comment by twong-sea** [comment]
Thank you for fixing!
