### ISSUE TITLE
Question - How do accounts work on a self hosted instance?

### ISSUE THREAD

**Issue by jamess60** [AmruthPillai/Reactive-Resume#1977]
Hi 

Just deployed a self hosted instance. When hitting the web interface, I am prompted to create an account / login. 

1. I dont have SMTP configured so cannot get the verification email - is this an issue?
2. If I wanted to share this with friends, is there a way to create the accounts for them through an admin interface?
3. Is there a way to disable new signups? - This would be a security issue if opened up to the web

**Comment by weighsone** [comment]
1. This is just to verify their email for password resets. The account will work without verifying. 
2. Just use /auth/register. No real need to make the accounts for them. There is no admin interface that I'm aware of
3. If you are hosting with docker, set the environment variable: DISABLE_SIGNUPS: true
