### ISSUE TITLE
Experience dates are truncated in the PDF no matter which font I choose 

### ISSUE THREAD

**Issue by istavrakakis** [AmruthPillai/Reactive-Resume#201]
<img width="191" alt="image" src="https://user-images.githubusercontent.com/67468110/85857834-43aae380-b7c3-11ea-9bd4-eb1deaeaea53.png">

**Comment by istavrakakis** [comment]
This should read (11/2008 - 10-2009)

**Comment by istavrakakis** [comment]
This happens with all dates in Experience, and it also happens when I write full dates as in "November 2008".

**Comment by AmruthPillai** [comment]
I've seen this on Safari and Firefox for some reason. Could you try the same on Chrome or Edge? It should solve your issue temporarily.
