### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by enriquevoss** [AmruthPillai/Reactive-Resume#206]
There is multiple things that could be better.

I will list them accordingly. 

1. The Option to create a cover letter in the same design after creating your CV.
2. Add your own sections, or add standard missing sections such as : Volunteering, Organisations, Projects (very important to showcase your work), Courses & Conferences, Causes that you support.
3. Add skill categories such as Industry Knowledge, Tools and Technologies, Interpersonal Skills, Other Skills so that the skill section is not overloaded.
4. 3 Top Skills that stand out.
5. The ability to add icons for Social media like linkedin facebook etc. 
6. The ability to add icons to schools and work.

If all of these get added i think there will be no better Resume/CV builder available! +

Great Job!

Sincerely, Leonardo Voss. 

![image](https://user-images.githubusercontent.com/65925443/87192472-d5077300-c2f6-11ea-925f-28aec1e22645.png)
![image](https://user-images.githubusercontent.com/65925443/87192490-de90db00-c2f6-11ea-980d-577cb60b9317.png)

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
