### ISSUE TITLE
[Bug] <title>Delete an item from skills container

### ISSUE THREAD

**Issue by jayesh-0786** [AmruthPillai/Reactive-Resume#2067]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

editing an resume 

### Expected Behavior

delete option should be there for an specific item 

### Steps To Reproduce

1) create resume template
2)create multiple items in skills section
3)try to delete an item from skills section which is default

### What browsers are you seeing the problem on?

Microsoft Edge

### What template are you using?

Ditto

**Comment by AmruthPillai** [comment]
Right click on the item to hide or delete an individual item.
