### ISSUE TITLE
[Download as PDF] I am unable to download the PDF

### ISSUE THREAD

**Issue by VanshSh** [AmruthPillai/Reactive-Resume#2105]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

- Issue 1:
So whenever  I click on this link button (in below image) it should copy the public resume link. Which it is not doing and just copying the undefined for me
![image](https://github.com/user-attachments/assets/aed8bfd3-17e2-4d0e-adec-d971c1aab4cd)

- Issue 2:  
   Even if I copy the link from the sidebar and then open that link then link works but when i click the `Dowanload as PDF ` button it does not download anything in fact just return the empty white browser tab.
   
 Here is my Public link : https://rxresu.me/vanshsharma9354/vansh-sharma

### Expected Behavior

- Issue 1:
So whenever  I click on this link button (in below image) it should copy the public resume link.
![image](https://github.com/user-attachments/assets/aed8bfd3-17e2-4d0e-adec-d971c1aab4cd)

- Issue 2:  
   Even if I copy the link from the sidebar and then open that link then link works but when i click the `Dowanload as PDF ` button it should download the resume  PDF
   

### Steps To Reproduce

-  For Issue 2: 
1.  Open this link:  https://rxresu.me/vanshsharma9354/vansh-sharma 
2.  The click on the Download as PDF button
3. You will see nothing gets downloaded just empty white browser tab

- For Issue 1:
1. I am facing that while Resume edit is open
2. Click on the Link button as shown in the above Image 1 and it copies the undefined

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by jdhill777** [comment]
Hello, I see you closed this item as completed, however I am getting the exact same error in my environment. Can you tell me how you were able to resolve this issue?

**Comment by VanshSh** [comment]
> Hello, I see you closed this item as completed, however I am getting the exact same error in my environment. Can you tell me how you were able to resolve this issue?

@jdhill777 
Step 1: Go to your public link which you might get easily from the right side bar

Step 2: Press Ctrl + P and then you can save.

NOTE: But issue still exists
