### ISSUE TITLE
UI Issue and repo link

### ISSUE THREAD

**Issue by banuteja029** [AmruthPillai/Reactive-Resume#215]
*Font-size
*Horizontal line after every block
*Link is not getting added 
* unable to download

**Comment by AmruthPillai** [comment]
@banuteja029 Could you provide some more insight into what issues you are facing?

**Comment by banuteja029** [comment]
Thanks AmruthPillai for reply

I made my resume using your website it's really cool to use
i found some UI issues
1. Unable to change the font size
2. In projects whenever I'm trying add my GitHub repo link it's not showing
on resume
3. Please add one for an extra field where some users want to add there own
details like for extra circular activities there is no field to add it
Thank you sorry if I'm wrong this is my first time I'm writing issue......
