### ISSUE TITLE
PDF Version export - Site not found

### ISSUE THREAD

**Issue by Pobek** [AmruthPillai/Reactive-Resume#216]
# Scope

type - bug

## Problem

When you choose to export as PDF, you get a pdf without the right content. Instead, you get "Site not found" error from Firebase.
Link to imgur image reference: https://imgur.com/ayPfWBz

**Comment by AmruthPillai** [comment]
Oh, that is completely my bad. I seem to have forgotten a step during my production release. 
This should be working again in a few minutes. Really sorry about that. Thank you for raising the bug and letting me know.
