### ISSUE TITLE
[Feature] Adding in Icons for Social Media Websites

### ISSUE THREAD

**Issue by LeonY1** [AmruthPillai/Reactive-Resume#217]
First, I wanted to tell you how great this Resume builder is! I've tried a couple and they're not as nice as this one.

### Icons for Social Media Websites

I think it would be a nice touch to add icons for social medias. It would also make the user status easier to tell without having to explicitly tell which social media platform is being used. If it's not part of the default list, you can always add it as a form of text like how it currently is.

**Comment by AmruthPillai** [comment]
Hey @LeonY1!

Thank you so much for writing up an issue for this so we can get this addressed. Really means a lot that you are using Reactive Resume. Thank you so much for taking the time to make it better.

Right now, there are social media icons added to few of the templates like Onyx, Pikachu and Gengar.

<img width="1313" alt="Screenshot 2020-07-18 at 8 40 12 PM" src="https://user-images.githubusercontent.com/1134738/87855584-fe4b8300-c936-11ea-916c-0d817a9ea9b0.png">

All you need to do is enter the name of the social network in the "Network" field, then it would parse the name and get the appropriate icon. Does this not show up for you?

**Comment by LeonY1** [comment]
Yes I see them. Sorry about this.

**Comment by AmruthPillai** [comment]
It's quite alright :) Thank you so much!
