### ISSUE TITLE
[Bug] Celebi Web View Cuts off based off only the left column

### ISSUE THREAD

**Issue by LeonY1** [AmruthPillai/Reactive-Resume#218]
![Screenshot 2020-07-18 10:21:50](https://user-images.githubusercontent.com/14265005/87855845-9d915b80-c8e0-11ea-9dcd-2c973685bc24.png)

Let me know if you need more information like browser/OS.

**Comment by AmruthPillai** [comment]
@LeonY1 Thank you so much Leon! :) Noticed the issue, and it's now fixed. You should be getting the update in a few minutes. If you don't see the changes, just refresh your cache and reload the site again :) I do hope this helps you out!
