### ISSUE TITLE
In PDF links are not working

### ISSUE THREAD

**Issue by sabesansathananthan** [AmruthPillai/Reactive-Resume#221]
when we download the pdf file. links inside the pdf file are not working. (e.g: Mail address, Website)

**Comment by AmruthPillai** [comment]
Hey there, this does seem to work for me? I've attached a PDF of mine generated from the app below, and I see that the links are clickable. If they aren't for you, might I suggest using a different PDF viewer? I opened it directly on Chrome.

[RxResume-lv7oaa.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/4943202/RxResume-lv7oaa.pdf)
