### ISSUE TITLE
Be able to reorganize categories

### ISSUE THREAD

**Issue by KeronCyst** [AmruthPillai/Reactive-Resume#222]
For example, in the sidebar of Pikachu and other templates, I would like **Certifications** to be right under **Email Address**, with **Skills** and **Hobbies** being at the bottom. I'm not sure of how to move entire sidebar sections, though.

**Comment by AmruthPillai** [comment]
You can use the Layout section on the right sidebar to move sections across or within blocks. For what you are asking, all you need to do is drag and drop the Certifications to the top of Block 1 and Skills and Hobbies can go right under that. Here are a few screenshots that might help:

<img width="401" alt="Screenshot 2020-07-19 at 9 21 27 AM" src="https://user-images.githubusercontent.com/1134738/87866606-7cdd0a80-c9a1-11ea-90ac-a69a752d34cb.png">

<img width="678" alt="Screenshot 2020-07-19 at 9 21 45 AM" src="https://user-images.githubusercontent.com/1134738/87866608-7f3f6480-c9a1-11ea-9ab4-b452afcc3cff.png">
