### ISSUE TITLE
Pikachu template: omitted Education date still shows "( - )"

### ISSUE THREAD

**Issue by KeronCyst** [AmruthPillai/Reactive-Resume#223]
In Pikachu (and possibly other templates), it would be nice if "( - )" was completely hidden if you choose to hide your education dates.

**Comment by AmruthPillai** [comment]
Well, technically start date is a required field, so it would not be possible to create Work/Education list item without a start date. Do let me know if this is something you would like to see change?

My reasoning for making it required was that I had read a few best practices for resumes and it said that it's suggested to add dates to everything, and also arrange them chronologically. This app does do a bit of hand holding here, trying to suggest to the user, that this is a best practice. But let me know what you think about this :)
