### ISSUE TITLE
Possibility to add non-US dating format

### ISSUE THREAD

**Issue by gluntn2** [AmruthPillai/Reactive-Resume#228]
I keep trying to write dates as DD/MM/YYYY, but the formatting seems only to support MM/DD/YYYY. Is there any chance this could be a setting? I reckon some people also would like to write in YYYY/MM/DD.

**Comment by AmruthPillai** [comment]
@gluntn2 The date on the forms are not really controlled by the site, they are controlled by the browser, which I think would look at your computer's locale and set the format. For instance, on my computer, I see this format for dates:

<img width="286" alt="Screenshot 2020-07-19 at 4 06 09 PM" src="https://user-images.githubusercontent.com/1134738/87872863-e1b45700-c9d9-11ea-9f25-062ed52058c6.png">

You just might need to change the locale of your computer from the default one to something that follows your country's locale format :)

**Comment by gluntn2** [comment]
That's very weird, my computer is very European. But thanks for your quick response!
