### ISSUE TITLE
Feature Request/Bug: Left and Right pane should be callapsable especially left pane as it overlaps the resume

### ISSUE THREAD

**Issue by AbhishekKumar1208** [AmruthPillai/Reactive-Resume#232]
Left pane overlaps the resume and the user probably can't see 10-15% of the resume. Refer to the screenshot.

![image](https://user-images.githubusercontent.com/47590329/87876256-762bb300-c9f4-11ea-86bf-72e01a3698e0.png)

**Comment by AmruthPillai** [comment]
@abhiajax I've pushed out a new update now that *might* fix this problem. Could you let me know if this helped you?

**Comment by AbhishekKumar1208** [comment]
Hey, I can see the resume completely now. 
However, I did notice that the draggable elements are spilling out of the two grids in the Layout section on the Right Pane. I am not sure if this was the case before your fix.

**Comment by AmruthPillai** [comment]
> Hey, I can see the resume completely now.
> However, I did notice that the draggable elements are spilling out of the two grids in the Layout section on the Right Pane. I am not sure if this was the case before your fix.

Oh, that's a part of the design :) I let it be that way so that it is easier for people to read the whole layout name. Glad the issue is resolved for you. Thank you so much for actively helping to make the app better ♥️
