### ISSUE TITLE
Adding more options in regards to spacing and sizing. Custom templates?

### ISSUE THREAD

**Issue by gluntn2** [AmruthPillai/Reactive-Resume#233]
Would it be possible to add more functionality for bigger margins in the resume? I find the default margins being too small, and the text (for smaller resumes) being way too small. Might be able to fix this myself, if the functionality is desired.

Maybe even add support for custom templates, or editing the ones that exist.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
