### ISSUE TITLE
Months are not translated

### ISSUE THREAD

**Issue by MeisterLLD** [AmruthPillai/Reactive-Resume#235]
Months names (january, february etc...) are not translated and stay in English no matter what language is chosen. I could not find them in the json files.

**Comment by AmruthPillai** [comment]
You are right, this is an open issue. This is because the dates are handled by a library called momentjs. I will keep this open until I get this fixed :) Thank you so much for raising this issue.

**Comment by AmruthPillai** [comment]
@MeisterLLD This has been fixed in the latest update :)
