### ISSUE TITLE
Adding custom "blocks" ?

### ISSUE THREAD

**Issue by ttben** [AmruthPillai/Reactive-Resume#238]
Hi there!

Thanks a lot for your tough work! It is much appreciated and the result is astonishing!!
Quick question: I am a researcher, and I have _publications_. How can I add custom "blocks" (such as awards for instance)?
Is it possible even if it is out-of-the-scope of the JSONResume schema?

Thank you again!

**Comment by AmruthPillai** [comment]
Hey there! :)

Thank you so much, I did think about adding a Publications section initially. I can add that right now :)

The logic to add custom sections is a bit more difficult. I did try, but it was beyond me. For now, what you could do is just change the heading of "Certifications" or any other section that you might not use to Publications and use it that way. I'll add the Publication section as soon as I have the time.

**Comment by shriaas2898** [comment]
Hey, I was also trying to find a way for adding a custom block, which I understand now can be tricky. So instead is it possible to add a feature for replicating blocks and changing the heading? Even a simple one like an objective block can be used to make any section.

**Comment by vineetmimrot** [comment]
@AmruthPillai I have tried changing the certification to publication and when I added content in it, then it overflows into main section i.e. Education/Project columns.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
