### ISSUE TITLE
Customize skills level

### ISSUE THREAD

**Issue by SophieMdl** [AmruthPillai/Reactive-Resume#241]
Thank you for your work, very nice tool !
I would like to contribute by transforming select skills level by a simple input, this would allow more flexibility and all langages support.
What do you think ?

**Comment by SophieMdl** [comment]
https://github.com/AmruthPillai/Reactive-Resume/pull/251

**Comment by AmruthPillai** [comment]
Thanks for the PR, this has been merged to production now :)

**Comment by SophieMdl** [comment]
Thank you for merging :) I don't see it on online, do you know when it will be deployed in production ? Thanks ! 😊

**Comment by AmruthPillai** [comment]
You might need to refresh your cache. Still trying to figure out how to uncache all these sites :)
