### ISSUE TITLE
The New Version doesnt work at all for me. 

### ISSUE THREAD

**Issue by enriquevoss** [AmruthPillai/Reactive-Resume#243]
![image](https://user-images.githubusercontent.com/65925443/87960473-a044aa00-cab4-11ea-9126-b385ea7d4e14.png)

**Comment by AmruthPillai** [comment]
I'm still trying to figure out responsiveness... but for now, I'd just ask to use it on a standard 16:10 ratio window size :) Will update once I find a solution to this. Thank you.
