### ISSUE TITLE
Alignment issues with the template viewer

### ISSUE THREAD

**Issue by Tenelia** [AmruthPillai/Reactive-Resume#248]
![RXResume issue](https://user-images.githubusercontent.com/26970760/88019983-709dac80-cb5d-11ea-892a-71a7791eadef.JPG)

**Comment by Tenelia** [comment]
All of the templates have this issue. My friends have reported the same across various devices and browsers, so I'm unsure what's causing it.

**Comment by AmruthPillai** [comment]
Still trying to recreate this, could you please share your screen resolution?

**Comment by kristophrk** [comment]
I have the same issue - except it cuts off the first 2 letters of my name and everything under it I can't see either.

For reference I've tried Chrome and Firefox in both Windows and Linux.

My monitor is 1920x1080

Hope this helps!

**Comment by Tenelia** [comment]
Same. 1920x1080

**Comment by kristophrk** [comment]
Interesting tho - when I used my macbook it looked just fine.  I believe it is also 1920x1080 but I have it scaled to the smallest setting (meaning everything is smaller so more fits on the screen)

**Comment by qiandongyq** [comment]
It is something related this
![image](https://user-images.githubusercontent.com/24208956/88826448-c47c4700-d196-11ea-8075-e57524e07db9.png)

**Comment by a-thug** [comment]
Same. 3008x1692

It seems to cut off the text if it goes over resolution 1680.
https://github.com/AmruthPillai/Reactive-Resume/blob/87e3ebfaa80de3c64f49916c21efdb3f3db850a4/src/components/builder/center/Artboard.js#L36
