### ISSUE TITLE
Company Link field in Work experience seems to be required.

### ISSUE THREAD

**Issue by Bwise1** [AmruthPillai/Reactive-Resume#249]
the Company link does not allow submission if the website link is not added, but the field was not marked as required.

**Comment by AmruthPillai** [comment]
@Bwise1 That's mainly cause there's a http:// there, so the field is not empty. If you removed the http://, you can keep it empty and submit the form. I'll update the app to make sure the http:// doesn't show up there in the first place. It's quite misleading.

**Comment by Bwise1** [comment]
ok

**Comment by AmruthPillai** [comment]
This has been fixed in the latest v2.1.0 update :) Thank you for reporting!
