### ISSUE TITLE
Resumés of deleted accounts are still accessible and resumés are public by default.

### ISSUE THREAD

**Issue by michael-JJ** [AmruthPillai/Reactive-Resume#253]
_**I have only tested this with the "Sign in Anonymously" method.**_

I noticed that the resumés are publicly accessibly via `rxresu.me/r/<id>` by default (even before clicking the share button).  This is in my opinion a **privacy and security problem** since resumés contain names, emails addresses, phone numbers, addresses and school/work history.

The resume is also still accessibly after deleting the rxresu account. Maybe this is related to an error message I got after deleting my account, which also openend the "Log In With Google" dialog. According to the source code, that dialog should only open after the account deletion when it throws an exception.

The toast message in the finally block shouldn't say that all the data has been deleted successfully, since the finally block will also be executed when there's an problem with the deletion.

![image](https://user-images.githubusercontent.com/36151123/88200426-699e9900-cc46-11ea-93d1-a6b3ec33ebcd.png)
![image](https://user-images.githubusercontent.com/36151123/88199595-59d28500-cc45-11ea-8cff-2e5c9bf15b5c.png)

**How to reproduce:**
1. Log in with "Sign in Anonymously".
2. Create a new resume.
3. Go to the resume you just created.
4. Change some values, for example first name to "test123" so you can later verify that this is indeed the same resume.
5. Copy the resume id in the url bar.
6. Go to `rxresu.me/r/<id_from_previous_step>` on a different browser or device. The resume is even accessibly on a device that has never visited rxresu.me and because we used the anonymously login method it can't possible link your Google account.
7. Delete the resume.
8. `rxresu.me/r/<id>` is still accessible.

I would suggest to fix the account deletion feature to correctly delete the user's data (for anonymous accounts). And I would also suggest to not make all resumés public by default, make it public after the "Share Your Resume" button has been clicked.

**Comment by AmruthPillai** [comment]
Thank you for bringing this to light. I had set up a Firebase Extension to do just this, so that immediately after a user deletion, it would call a function to delete the corresponding resume, but I guess it didn't work as expected. So I wrote my own cloud function to do the same.

I ran through the same steps you did, and it should be cleared now.
This has been fixed with the latest update v2.1.0 :)
