### ISSUE TITLE
hyperlink in resume

### ISSUE THREAD

**Issue by o-pooja-o** [AmruthPillai/Reactive-Resume#259]
I am facing an issue with links in my resume.
One of my frds have them in resume and its clickable but not in mine.
Can you help me fix this hyperlink issue with my resume

**Comment by AmruthPillai** [comment]
May I ask, what PDF viewer you are using, as some viewers often strip all hyperlinks for security reasons?

**Comment by o-pooja-o** [comment]
First of all thanks for replying back Mr. Pillai.
I solved this issue after trying a different approach.
When I downloaded my resume with actions tab, save as pdf option, It wasn't
showing hyperlinks.
But my friend suggested that I should download resume from the print or
save option given upon the resume itself with an icon.
After that hyperlinks were active on my resume.

**Comment by AmruthPillai** [comment]
Sounds great, glad you got that resolved and I hope this helps anyone else also facing the same issue :)
All the very best, and thank you for using Reactive Resume!
