### ISSUE TITLE
Make the required areas optional

### ISSUE THREAD

**Issue by sammjainn** [AmruthPillai/Reactive-Resume#261]
I do not want to indicate skill proficiency but am unable to do so. Also in education, there is no option to mention just the year (not the entire date) or to not mention the date at all.

**Comment by AmruthPillai** [comment]
This should be possible now with the latest version (v2.1.1). Please do let me know if there's anything else I can do to make Reactive Resume better :) Thank you so much for reporting!

**Comment by binyamin** [comment]
@AmruthPillai same issue happening for me, with skills section.
