### ISSUE TITLE
[bug] Error when I try to import json resume

### ISSUE THREAD

**Issue by SophieMdl** [AmruthPillai/Reactive-Resume#262]
I've got an error when I try to import my json resume : `Invalid data : should be an array`.

I investigated a little bit, it seems the data assignation in the function `on_import_jsonresume` (ResumeContext.jsx) is not like the json data structure (made with the app)

**Comment by AmruthPillai** [comment]
This is mostly because your JSON Resume might not be in the valid schema format. I test it against the official schema that's available here: https://github.com/jsonresume/resume-schema. You can test your resume against this validator: https://www.jsonschemavalidator.net/

**Comment by SophieMdl** [comment]
It's weird because my CV data were exported by the app (on json format). I'll check the schema, thank you

**Comment by LongJohn-Silver** [comment]
The same thing happened to me, I tried to import my .json (which I created on RxRs before the big make over) and it crashes, it shows me a black screen and nothing happens. ElementaryOS Hera.

**Comment by djaX220s** [comment]
> This is mostly because your JSON Resume might not be in the valid schema format. I test it against the official schema that's available here: https://github.com/jsonresume/resume-schema. You can test your resume against this validator: https://www.jsonschemavalidator.net/

Hi, I am having the same issue. I exported my file on one device, creating a file as expected but when i try to import on another device i get this error. 

The only difference is that the machine i used to write the Resume on was not authenticated (anon login) and the detination computer is logged on using my google account. 

Please can you investigate?

**Comment by AmruthPillai** [comment]
This should be fixed with the latest version v2.1.2 :) Please do let me know if the issue persists. Thank you for reporting!
