### ISSUE TITLE
Bug? Blank screen presented on various actions

### ISSUE THREAD

**Issue by djaX220s** [AmruthPillai/Reactive-Resume#263]
Hi,

New user and, firstly, it is great and has great potential. Please continue to develop. 

When I first build my Resume it looks fine, I can change the colours, etc. and adjust the impact of the font by using block code easily. 

The issues I'd like to see investigated are as below. The platforms I'm using are: 
1. Microsoft Surface Laptop, Ubuntu 19.10, latest patched. Custom Kernal to fix some issues with the hardware.  Chrome Version 83.0.4103.116 (Official Build) (64-bit)
2. OnePlus 6T mobile phone running latest android OS and Chrome as a browser

The first issue was trying to simply print from chrome, nothing but a blank screen displays. Something does appear however when I choose to print a single page PDF and is saved to the device. 

Second issue us at random times the screen will just go blank after adding a section such as a project, hobby, etc. I have to refresh the page to get it to work. 

On one occasion the app caused Chrome to crash completed and through a system error and I had to recover. Unfortunately, I didn't think to keep the details of any panic or software issue. I will next time.

**Comment by AmruthPillai** [comment]
This should be fixed now, could you please refresh your cache and verify that your version number of the site is v2.1.1. You would be able to check the version on the bottom of the right sidebar, below the About section. Thank you so much for the detailed reporting, it helped a lot.

**Comment by djaX220s** [comment]
Thanks for looking into it, confirmed as fixed. I posted a follow up to an issue i'm experiencing with export / import of JSON CV. Someone else reported the issue but i just wanted to let you know i'm also seeing the same.
