### ISSUE TITLE
Spanish does not fully work

### ISSUE THREAD

**Issue by LongJohn-Silver** [AmruthPillai/Reactive-Resume#264]
When I select Spanish as my language there are two things that are not translated, which are Phone (Teléfono) and Email (Correo Electronico).

**Comment by AmruthPillai** [comment]
Please feel free to raise a Pull Request by editing the [es.json](https://github.com/AmruthPillai/Reactive-Resume/blob/develop/src/i18n/locales/es.json) file with the changes you feel should be in there and I'll get it merged ASAP :)
