### ISSUE TITLE
broken link after conversion to pdf

### ISSUE THREAD

**Issue by Melandel** [AmruthPillai/Reactive-Resume#265]
hello, I have this in my json file:

```json
	"profile": {
		"website": "https://melandel.github.io/resources/"
	},

```

After converting to pdf, when trying to click on the link, the URL it tries to send me to is the following: `https//https//melandel.github.io/resources/`. Note that the colon character `:` disappeared, rendering the link broken, yet the text displayed is correct.

Can you reproduce this bug? Is it easy to fix?

**Comment by AmruthPillai** [comment]
Thanks for reporting this, it's now fixed with v2.1.1 :)

You can verify the version of your app by checking the bottom of the right sidebar:
![image](https://user-images.githubusercontent.com/1134738/88617983-907d2500-d0b5-11ea-8a55-1b13a61a015b.png)
