### ISSUE TITLE
Photos won't load on Résumé

### ISSUE THREAD

**Issue by Anacoder1** [AmruthPillai/Reactive-Resume#266]
Hi, incredible work building the webapp.

I had an issue, which is that the photos won't get loaded into the résumé, even when they are less than 2 MBs in size.
Could you look into it?

**Comment by Spontex59** [comment]
Hi !

Just to tell that I have the exact same issue : my picture is 48,0 Ko ( 286 in Width by 388 in Height ) 

I can select it and there is no error message at any time but the picture won't appear.

Thank's

**Comment by AmruthPillai** [comment]
Hey there, this has been fixed :) Please do let me know if the problem persists.
