### ISSUE TITLE
Blank PDF while saving resume as PDF

### ISSUE THREAD

**Issue by K0ple** [AmruthPillai/Reactive-Resume#268]
Incredible work on the app!
I have recently encountered a bug where when i try to save my resume as a pdf (not print), either as unconstrained or single A4 option, a blank resume pdf while is saved.

**Comment by jeroenim0** [comment]
Same here with Brave and FireFox

**Comment by AmruthPillai** [comment]
This is fixed now in v2.1.3, please let me know if the issue persists :) Thank you.

**Comment by justinr1234** [comment]
@AmruthPillai Still seeing this, 2.5.5
