### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by zombiejes** [AmruthPillai/Reactive-Resume#277]
Hey there. I used Resume RX to rewrite my resume this morning and upon completion, the website went blank. I tried reloading the page, and the site seems to just hang when trying to open my resume. I can access the site and sign, and can even see my resume listed...but when attempting to open my resume page- nothing happens. I have tried both Firefox and Brave Browsers with the same results.

**Comment by AmruthPillai** [comment]
I think this should be fixed in the latest release v2.1.4 :) Hope this helps. Please do let me know if the problem persists.
