### ISSUE TITLE
Resume reloading in browser fails and gives a black screen

### ISSUE THREAD

**Issue by jeroenim0** [AmruthPillai/Reactive-Resume#278]
Both Firefox and Brave seem not to reload the resume that was created. 
When you go back to the start page or if you change the template i get a black screen
Import a backup works fine, and is a workaround. 
But something does not work right.

System: Linux 
Browsers tested: Firefox and Brave

**Comment by AmruthPillai** [comment]
Closing as issue is a duplicate of #268
