### ISSUE TITLE
Celebi template cuts top part of profile picture off

### ISSUE THREAD

**Issue by jeroenim0** [AmruthPillai/Reactive-Resume#279]
The template Celebi my photo I upload gets the top part cut off..
I tried a few crops and almost got it right but I guess it should show the full picture

**Comment by AmruthPillai** [comment]
That is the expected design actually. In the Celebi template, the photo is more of a landscape than a square, which changes up the design that most people see on resumes. So you would have to crop your photo or pick a landscape photo that would suit for this :)

**Comment by ricardok1** [comment]
Can this be adjusted when uploading?
