### ISSUE TITLE
Saving pdf issue

### ISSUE THREAD

**Issue by mybubbles** [AmruthPillai/Reactive-Resume#280]
[RxResume_1596360941424.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/5011913/RxResume_1596360941424.pdf)
loading part of profile image and nothing else when trying to download/save pdf

**Comment by AmruthPillai** [comment]
Could you give me some more information on what is causing this, also whether you are on the latest version of the app?

**Comment by mybubbles** [comment]
I was using the browser version (chrome).
No idea what caused it, it's worked fine up until now and I had done nothing different.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ChristianVaughn** [comment]
I also am having the same issue. All i did was go to the https://rxresu.me/ and imported my resume json then attempted to save it as a pdf
[RxResume_1597332622930.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/5069939/RxResume_1597332622930.pdf)

**Comment by AmruthPillai** [comment]
@ChristianVaughn Oh, wow. That should **definitely** not happen. Will look into it, I'm still able to print single/multi page resumes on my end. Maybe it's a specific template? Could you give me some more information on what templates/settings you've used? Which method of exporting did you choose, print via browser or the external print methods?

Oh, and also... thank you so much for your donation <3 It really means a lot when someone contributes to keep this project running.

**Comment by ChristianVaughn** [comment]
I think I found the issue. My browser still had the pre v2 version of the site cached, and was loading that instead of the new one. I was able to do a empty cache and hard refresh to get to the new site, but then trying to load my json doesnt work, and a normal refresh takes me back to the old version of the site.
