### ISSUE TITLE
Can't see full document while editing resume in Chrome (Ubuntu)

### ISSUE THREAD

**Issue by sindhuvahinis** [AmruthPillai/Reactive-Resume#281]
![RxResume-Issue](https://user-images.githubusercontent.com/56774226/89134420-1b658180-d4f3-11ea-9602-eca281e79b9d.png)

**Comment by bmitchinson** [comment]
+1 on chrome, brave, and safari :(

**Comment by arijiipee** [comment]
I have three displays. Resolutions 1366x768 (16:9), 2 pcs 1920x1200 (16:10). This same problem is on display with resolution 1920x1200. When I move the Reactive resume to the display of 1366x768 and refresh the page I can see the full document preview. On this display the Templates column Layout blocks section has some overlapping. 

![image](https://user-images.githubusercontent.com/57941356/89500005-9f588b80-d7c9-11ea-931a-333f3344a729.png)

Linux Mint DE with chromium, chrome
///ari

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
