### ISSUE TITLE
Documentation site appears to be down

### ISSUE THREAD

**Issue by tpansino** [AmruthPillai/Reactive-Resume#282]
https://docs.rxresu.me/

Looks like there's no DNS record for `docs.rxresu.me` anymore.

```
$ dig docs.rxresu.me

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> docs.rxresu.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24235
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;docs.rxresu.me.			IN	A
```

**Comment by AmruthPillai** [comment]
The documentation has been taken down mainly cause it pertains to the old version, not the new one. I haven't written a brief documentation for this one, but everything is on the README.md :)

**Comment by tpansino** [comment]
Thanks for the response, and for the project.

Is there an option for hosting the project which doesn't require Firebase? I've been trying to use [this Docker image](https://hub.docker.com/r/amruthpillai/reactive-resume) which it looks like you made, but without documentation I don't know how to configure it. Is Docker not a supported platform anymore?
