### ISSUE TITLE
Text-overflow on UI and PDF

### ISSUE THREAD

**Issue by ttben** [AmruthPillai/Reactive-Resume#286]
Hi there!

When I type a long text, the text overflows in the UI and this overflow happens in the generated PDF too!

Here is a picture of it, notice the horizontal scrollbar..
![Annotation 2020-08-04 131829](https://user-images.githubusercontent.com/6167712/89287924-14568480-d655-11ea-8c4b-c0ddfe13cd25.png)

I tried multiple themes but that seems useless.
Do I need to wipe something? Enable an option? Write less? ^^

Thank you in advance!

**Comment by ttben** [comment]
The text overflows appears when your write somewhere a long word (here todo)
Whitespaces will fix the issue.

Sorry, this is not as strong as an issue as I originally thought

**Comment by leonardosegurat** [comment]
+1 to this issue.
While it is unlikely longer words will be needed, and such cases can be worked around trough adding a space, this workaround does not work for email addresses.

This is problematic for the References section, as longer emails can be common depending on company email policies and domains (e.g. complete.name@company.com.mx).

See attached example
![image](https://user-images.githubusercontent.com/21146125/110358863-6fdd5c00-8002-11eb-8106-93f7752e6738.png)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
