### ISSUE TITLE
Bug? Markdown doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [AmruthPillai/Reactive-Resume#287]
Hi, i'm using the Onyx theme as i like the cleaner profile it provides. However when i reach the "Summary" section it states it supports  markdown and gives a link to the basic syntax. 

I have tried using the html tags '<*h1*>Text</*h1*>', all the way through to h6 but this doesn't seem to influence the style or weight of the text. 

If i use the hash (#) sign i can see that the text changes to a new line but still no change in weight etc. 

In addition, i can't seem to create carriage returns in the text block areas of summary. i've tried '<*br /*>' but no joy. 

I've had to put asterix in to stop the board from formatting the headers correctly, ironically :)

**Comment by djaX220s** [comment]
Hi Amruth, sorry to push but wondering if you've had a chance to look at this one?

@AmruthPillai

**Comment by KeronCyst** [comment]
You're not supposed to use HTML. It uses Git markdown, not HTML.

But anyways, even markdown isn't fully working for me either. I'd like to embed links into some of my text. @AmruthPillai plz!

**Comment by dmiquel** [comment]
I am using github markdown but line breaks don't seem to work.
https://gist.github.com/shaunlebron/746476e6e7a4d698b373

**Comment by BryanQuigley** [comment]
Are there any sections where the markdown works as expected? I haven't found one, myself. (We could see what that does differently)

I too just want line breaks or headings.

**Comment by mpagels** [comment]
@BryanQuigley, @dmiquel, @fonziemedia
I found a solution in #125 that worked for me:

> To put spaces between two lines of text, you just need the right amount of spaces and new line characters. Let me explain with an example:

```
Line 1<space><space> 
&nbsp;<space><space> 
Line 2
```` 
> Two spaces at the end define a new line in Markdown. As for the second line, you are basically putting an empty character, and again a new line. This will give you the layout you are looking for.
