### ISSUE TITLE
Issue with translation

### ISSUE THREAD

**Issue by brianalysson** [AmruthPillai/Reactive-Resume#289]
First of all, thanks very much for this amazing tool.
The issue I want to report is the following: when you don't add an specific "end date" to something, the program assumes it's a current activity/job, so it will display "start date - present". The thing is I can't find "present" on any of the strings available here https://crowdin.com/project/reactive-resume.
The word "present" translates to "presente" in portuguese, so having it as it is makes it look like a typo, as if it's missing one letter.
![image](https://user-images.githubusercontent.com/69292359/89494472-a01efc80-d78c-11ea-9ac8-41d8c92e253b.png)

Sorry to bother you with that, but it is all about the details, right?

Thanks again, best wishes,
Brian

**Comment by AmruthPillai** [comment]
I've added the key in i18n/Crowdin, and also translated it in multiple languages using Google Translate. If you find that it's wrong, you can send in a correction on Crowdin :) Thank you so much for reporting this issue.

**Comment by brianalysson** [comment]
Thanks for the quick response!
I'm not sure it is working as intended though. When English is selected, "Present" shows up normally in the resumé, but if you try any other language, it only displays a "-".
Sorry for the trouble, let me know if you need anything translation related (english to portuguese).
Thanks again!

________________________________
De: Amruth Pillai <notifications@github.com>
Enviado: sábado, 8 de agosto de 2020 00:37
Para: AmruthPillai/Reactive-Resume <Reactive-Resume@noreply.github.com>
Cc: brianalysson <brianalysson@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AmruthPillai/Reactive-Resume] Issue with translation (#289)


I've added the key in i18n/Crowdin, and also translated it in multiple languages using Google Translate. If you find that it's wrong, you can send in a correction on Crowdin :) Thank you so much for reporting this issue.
