### ISSUE TITLE
Docker Hub not updated

### ISSUE THREAD

**Issue by T-h-o-m-a-s** [AmruthPillai/Reactive-Resume#290]
Please update the Docker Hub file to latest github version.
(If I am not mistaken, there should be an option for auto updates too)

**Comment by AmruthPillai** [comment]
I haven't dockerized the v2 version of the app yet. Seeing as to how much dependency it has on Firebase, I was wondering whether it would still be useful as a self hosted alternative. But feel free to dockerize the app and send a pull request if you think it's open to self hosting :)
