### ISSUE TITLE
List new line not getting properly intended

### ISSUE THREAD

**Issue by 4shutosh** [AmruthPillai/Reactive-Resume#294]
Using the markdown * or - adds a bullet point (unordered list) in order to make lists in some description.
But the line is not getting properly intended.
This issue is not template specific.
Example Screenshot
![Screenshot from 2020-08-07 10-44-07](https://user-images.githubusercontent.com/53831987/89611729-87513c80-d89b-11ea-9b05-5df588ac6d61.png)

* An example line An example line An example line An example line An example line An example line An example line An example line (It should be below the text where it started not the bullet point)

Reactive-Resume is definitely an amazing website to make resumes! 🎉

**Comment by AmruthPillai** [comment]
This should be fixed in the latest update :) Thank you for reporting!
