### ISSUE TITLE
Regarding Experience 

### ISSUE THREAD

**Issue by ishanpathak0690** [AmruthPillai/Reactive-Resume#299]
Hi AmruthPillai,
You made Amazing Product But i found little issue while i tried After Entering 3 Experiences i am not able to enter 4th Might be you can Solve it as soon as possible

Thanks 
Ishan
Business Analyst

**Comment by AmruthPillai** [comment]
Looking into this. Thank you for bringing it up.

**Comment by AmruthPillai** [comment]
Should be fixed now, thank you for reporting! :)
