### ISSUE TITLE
Json file import failing

### ISSUE THREAD

**Issue by bimalmaan** [AmruthPillai/Reactive-Resume#300]
Nothing showing on uploading Json file resume. I created json file with previous version of Rx resume.

**Comment by AmruthPillai** [comment]
I haven't implemented a clean way to import resumes made with RxResume v1, right now it imports only the JSONs made from this base version. If that causes a problem, you could still use v1 right now, it hasn't gone anywhere. You can access it from https://v1.rxresu.me/ :)
