### ISSUE TITLE
Setting date in List causes 'Rendered more hooks than during the previous render' error

### ISSUE THREAD

**Issue by robert-w-gries** [AmruthPillai/Reactive-Resume#301]
I've been running into the following error while running the development server:

```
Uncaught (in promise) Error: Rendered more hooks than during the previous render.
    React 5
    useTranslation useTranslation.js:52
    formatDateRange index.js:29
    List List.js:44
    List List.js:36
    React 18
    _callee$ DataModal.js:70
    tryCatch runtime.js:45
    invoke runtime.js:274
    method runtime.js:97
    Babel 2
react-dom.development.js:14980
```

The problem is that hooks are [meant to only run in the top level of React function components](https://reactjs.org/warnings/invalid-hook-call-warning.html#breaking-the-rules-of-hooks). As a workaround, I commented out the `useTranslation()` hook, which fixes the issue:

```diff
diff --git a/src/utils/index.js b/src/utils/index.js
index 156daef..8cfcd0c 100644
--- a/src/utils/index.js
+++ b/src/utils/index.js
@@ -27,14 +27,14 @@ export const formatDate = ({ date, language = 'en' }) => {
 };

 export const formatDateRange = ({ startDate, endDate, language = 'en' }) => {
-  const { t } = useTranslation();
+  // const { t } = useTranslation();
   const start = `${dayjs(startDate)
     .locale(language.substr(0, 2))
     .format('MMMM YYYY')}`;

   const end = dayjs(endDate).isValid()
     ? `${dayjs(endDate).locale(language.substr(0, 2)).format('MMMM YYYY')}`
-    : t('shared.forms.present');
+    : 'Present';

   return `${start} - ${end}`;
 };
```

**Comment by AmruthPillai** [comment]
Could you suggest many any other alternatives to using the Translation here? Maybe passing it to the function from the calling component might help?

**Comment by robert-w-gries** [comment]
>Maybe passing it to the function from the calling component might help?

Yeah I think this is the way to go. You already call the `useTranslation()` hook [here](https://github.com/AmruthPillai/Reactive-Resume/blob/develop/src/components/builder/lists/List.js#L24), just get a reference to the `t` function in that line and pass it down to `formatDateRange()`

**Comment by AmruthPillai** [comment]
This should be fixed now, thanks to @robert-w-gries for the PR! :)
