### ISSUE TITLE
Exporting to PDF doesnot work

### ISSUE THREAD

**Issue by CrestNiraj12** [AmruthPillai/Reactive-Resume#302]
Clicking on both export options just gives loading... and nothing happens

**Comment by Radikad** [comment]
same issue, 

console shows 


Access to fetch at 'https://us-central1-react-resume-312db.cloudfunctions.net/printResume' from origin 'http://mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Radikad** [comment]
@CrestNiraj12  see the console and if there is an error. 
1. first you have to deploy functions to firebase 
2. if you're getting the same behaviour even once you've deployed, check the status on firebase functions. 
     if you're getting an error like memory limit exceeded 
this will solve your problem https://github.com/AmruthPillai/Reactive-Resume/issues/310

**Comment by DineshSolanki** [comment]
@CrestNiraj12 the issue should be fixed now, if it does, close the issue.
