### ISSUE TITLE
New issue with the word "present"

### ISSUE THREAD

**Issue by brianalysson** [AmruthPillai/Reactive-Resume#304]
It seems like adding "present" to translatable strings has broken something. In English, "present" still shows when you don't select an end date. For every other language, it'll only display "-" instead of the proper added translation.

Just reporting the issue here in case the email reply wasn't the best way to communicate (or went to spam).

**Comment by AmruthPillai** [comment]
Seems to be working right now?

![image](https://user-images.githubusercontent.com/1134738/94983334-620d4180-055f-11eb-9b69-cfe641567085.png)
