### ISSUE TITLE
Resume display not mobile friendly?

### ISSUE THREAD

**Issue by thisstillwill** [AmruthPillai/Reactive-Resume#306]
Apologies if already resolved, but viewing a hosted resume on a mobile device seems to cut off part of the document. Are there any plans to adjust this to improve the ui experience on mobile?

### Interface widescreen (looks as intended)

<img width="1792" alt="Screen Shot 2021-04-13 at 3 33 47 PM" src="https://user-images.githubusercontent.com/51719073/114610515-00483580-9c6e-11eb-9e9f-360803d3153c.png">

### Interface narrowed (layout not responsive)

<img width="737" alt="Screen Shot 2021-04-13 at 3 34 13 PM" src="https://user-images.githubusercontent.com/51719073/114610764-48ffee80-9c6e-11eb-8950-0fc387a8d217.png">

### Shared Resume (resume cut off)

<img width="612" alt="Screen Shot 2021-04-13 at 3 34 48 PM" src="https://user-images.githubusercontent.com/51719073/114610929-7482d900-9c6e-11eb-90a9-0bd6bb752db6.png">

## Thoughts
-  I think the shared resume could be fixed by just scaling/zooming out when the screen is narrowed (as in maintain the aspect ratio and lower the size on narrow screen widths)
    - I'd give it a crack myself if I wasn't busy with schoolwork 🤕
- Again, this problem is relatively minor. This is a seriously cool app, and I'm still using it so that should count for something in the end

**Comment by AmruthPillai** [comment]
Open to accept PRs related to this. Responsiveness is not my strong suit :(

**Comment by deepaktatineni** [comment]
A few screenshots would be helpful IMO.

**Comment by disstillwill** [comment]
> A few screenshots would be helpful IMO.

@deepaktatineni Agreed, I just updated the issue with some screenshots to illustrate things.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
