### ISSUE TITLE
Website field without http(s):// prepends external URL.

### ISSUE THREAD

**Issue by RijulGulati** [AmruthPillai/Reactive-Resume#307]
When website field is filled without http:// or https:// , the input URL is prepended with an external URL.
Example: If I input website as ````google.com```` or ````www.google.com````, the hyperlink generated in CV becomes ````localhost:8000/app/builder/google.com```` and ````localhost:8000/app/builder/www.google.com```` respectively. 

(CV generated from https://rxresu.me/ prepends https://rxresu.me/r/ - example: https://rxresu.me/r/www.google.com)

Since this is a website field, I think it's safe to prepend http:// to website entries. This way, every properly configured https:// website will be redirected to https:// equivalent. I'd like to work on this, once the approach is final as to what needs to be done.

**Comment by VivekThazhathattil** [comment]
work around for this problem would be to open the pdf file in a text editor (i used vim)  and search and remove the string "https://rxresu.me/r/ " from the file.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
