### ISSUE TITLE
Page disappears and few more issues

### ISSUE THREAD

**Issue by marcos9454** [AmruthPillai/Reactive-Resume#309]
Hi Amruth,
The product is awesome but has few critical issues.
1. When I import a json resume that I made in previous version. It fails and shows blank screen.
2. When I add education, the page turn blank and changes not done.
3. Font size cannot be changed.

**Comment by smerth** [comment]
I am working on a version installed on firebase.  I deployed the gatsby build version.

I noticed two things:
1. the page does go blank when adding an education item. in my case, after refreshing the page the education item is there.
2. before refreshing the page I noticed a react minification error. 

I will try and look into this more on develop build locally and see what I report.

**Comment by AmruthPillai** [comment]
This should be fixed now, thank you for reporting and using Reactive Resume! :)
