### ISSUE TITLE
Update Docker Hub with V2

### ISSUE THREAD

**Issue by technokami** [AmruthPillai/Reactive-Resume#311]
Docker Hub still relies on v1. Please update to include V2. Thanks

**Comment by ryanmac8** [comment]
Any update of docker V2?

**Comment by vchatela** [comment]
> Any update of docker V2?

V2 of the application. Meaning same version as the one online

**Comment by AmruthPillai** [comment]
I've updated Docker Hub with the latest version of the app :)

https://hub.docker.com/layers/93116771/amruthpillai/reactive-resume/latest/images/sha256-6fe3cfea4ac780d19040f9a18fb24d75e06b77e2427302d9165b07ef08addefc?context=explore
