### ISSUE TITLE
Start Date for Work Experience is not verified like End Date is

### ISSUE THREAD

**Issue by mackaaij** [AmruthPillai/Reactive-Resume#313]
If I enter a start date like 3 March 2020, I cannot save the work experience. Same with 03-03-2020. 03/03/2020 does seem to work. The Javascript console does show an error:

`TypeError: The value of field could not be cast to a value that satisfies the schema type: "date". `

I noticed the End Date is validated and returns an error in the user interface.

Note: the placeholder for a date is "6th August 208" (with the typo in the year).

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
