### ISSUE TITLE
Support multiple job titles in one work experience item

### ISSUE THREAD

**Issue by rifelpet** [AmruthPillai/Reactive-Resume#315]
Its common to have multiple job titles throughout tenure at a company. Sometimes it makes more sense to have a single summary for those jobs, so rather than having multiple work experience items it would be nice to have a single item with multiple job titles and date ranges. something like this:

```md
### Work Experience

## Company Name
#### Latest Job Title          Jan 2020 - Present
#### Previous Job Title        Jan 2019 - Jan 2020

Summary
```

**Comment by Jack-Storment** [comment]
Hey Peter, I am trying to work with the owner of the repository to resolve this issue. Which platform is best to message you if we have any questions about the bug? Thanks, Jack

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
