### ISSUE TITLE
Page goes blank when adding a new item

### ISSUE THREAD

**Issue by epdejager** [AmruthPillai/Reactive-Resume#317]
I'm using chrome Version 84.0.4147.135 (Official Build) (64-bit) on MacOS Mojave (10.14.6 (18G103) and every time I add a new item on the resume (e.g. work experience) the page goes blank and I have to refresh. Sometimes the items I've entered then go missing and I have to redo them.

**Comment by VitorBarbosa** [comment]
I'm getting the same thing on Firefox 80 on Windows 10 (2004).

**Comment by adityag81** [comment]
Yep. Same here.

**Comment by Radikad** [comment]
getting the same error.

**Comment by Radikad** [comment]
hi @epdejager , @VitorBarbosa, @adityag81 
I've found the error and a way to avid it. 

in the below files there is a prop called **hasDate**

/src/components/builder/left/sections/Education.js
/src/components/builder/left/sections/Work.js

by commenting that you can avoid the errors. (this is not a fix but a way to avoid) 

```
       <List
        //hasDate
        path={path}
        event={event}
        titlePath="institution"
        textPath="field"
      />
```

hope this help.

**Comment by Seancon1** [comment]
Still receiving this issue. It seems almost any new section or change in the resume results in having the application go blank, requiring a refresh.

**Comment by Radikad** [comment]
@Seancon1 did you comment **hasDate** on the above sections and check?

**Comment by AmruthPillai** [comment]
This should be fixed now :)
