### ISSUE TITLE
[Feature] Login with LinkedIn option to auto fill the information

### ISSUE THREAD

**Issue by theajr** [AmruthPillai/Reactive-Resume#32]
Filling forms is a boring process, especially when you are filling the same data repeatedly. 
So I would like to propose a feature here so that the user can log in with LinkedIn profile and information will be auto-filled.

**Comment by EmaSuriano** [comment]
+1

**Comment by AmruthPillai** [comment]
I feel like this would go against my ideology of having the app completely offline, as in, not allowing it to make any API calls or OAuth calls. I might consider parsing the LinkedIn PDF, but it would have to be done in the browser and I'm not aware of the libraries that can do that.

It is definitely one of the features I'm looking to consider, but not essentially having a Sign in with LinkedIn button approach. For now, I'll be closing this issue, and once I've done some more research on it, I'll reopen it with updates :) 

Thank you so much for your feedback, it really helps make the product better and better :)
