### ISSUE TITLE
[FEATURE REQUEST] Show/hide box on items such as work experience

### ISSUE THREAD

**Issue by ilangleben19** [AmruthPillai/Reactive-Resume#323]
I use different sets of work experience, awards, skills, etc. depending on where I'm applying. I'd love to be able to add all my experience/everything to one CV file, and to have a checkbox to show/hide each item. This would allow me to easily generate a specific set of items on a CV without having to duplicate one big template and manually remove items.

Thanks, great software! :)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
