### ISSUE TITLE
windows10 pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by xihadandan** [AmruthPillai/Reactive-Resume#324]
windows10 
node -v 12.16.2
npm -v 6.14.4
git branch -a  develop

pngquant failed to build, make sure that libpng-dev is installed

**Comment by AmruthPillai** [comment]
I do not have a Windows machine to build this, could someone take up this issue to see what dependencies need to be added so that it builds on both Unix and Windows machines properly?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
