### ISSUE TITLE
App is great but can't change font size

### ISSUE THREAD

**Issue by WilsonNet** [AmruthPillai/Reactive-Resume#325]
Great app, thanks for sharing, but I really think it would benefit from an option to edit the font size.

**Comment by vijay-yadav-3** [comment]
When can we expect this feature. ??
PS. Great App

**Comment by rpolley** [comment]
Going to take a stab at this.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
