### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by thanp** [AmruthPillai/Reactive-Resume#327]
hi,

I am having problem with import from .json file.
It doesn't work.

**Comment by AmruthPillai** [comment]
It only supports JSON imports from Reactive Resume v2 and JSONResume.org, not other formats :)

**Comment by thanp** [comment]
The JSON file is from Reactive Resume v1 and when i try to import to v2 it freezes. I guess i have to write my resume again on Reactive Resume v2.
Thank you for answering.

**Comment by ChristianVaughn** [comment]
So our only solution is to make our resumes from scratch to get then
working properly?
