### ISSUE TITLE
Issue while adding new  experience

### ISSUE THREAD

**Issue by Abhilash9423** [AmruthPillai/Reactive-Resume#331]
while clicking on the add experience button the web page is blanking out

**Comment by adityag81** [comment]
Same here.

> 
> 
> while clicking on the add experience button the web page is blanking out

**Comment by Radikad** [comment]
same for me too.

**Comment by Radikad** [comment]
hi @Abhilash9423 , @adityag81 

I've found the error and a way to avid it. 

in the below files there is a prop called **hasDate**

/src/components/builder/left/sections/Education.js
/src/components/builder/left/sections/Work.js

by commenting that you can avoid the errors. (this is not a fix but a way to avoid) 

```
       <List
        //hasDate
        path={path}
        event={event}
        titlePath="institution"
        textPath="field"
      />
```

hope this help.

**Comment by robert-w-gries** [comment]
@Radikad your workaround works because there's an issue with how the dates are formatted. See #301

**Comment by AmruthPillai** [comment]
This should be working now. Thanks to @robert-w-gries for the fix :)
