### ISSUE TITLE
[Question] Questions about the Firebase usage

### ISSUE THREAD

**Issue by bannisdale** [AmruthPillai/Reactive-Resume#333]
Hi there!

Every now and then, I'm looking for projects that I can host myself to replace old ones. In this case, I'm not planning to strictly replace something – other than my old Latex templates. ;-)

The instructions for an installation look simple enough, but when I "researched" Firebase, I realized that a) it's from Google and b) can't be self-hosted.

So I guess I have two kinds of questions:
1. Which data is sent to Firebase at what points of the resume creation?
2. Is there a way to get this working without Firebase? Maybe with an alternative that has similar API endpoints that I can install on my server? Any other way I'm currently not thinking of?

I'm not meaning to be unthankful for a project that looks really good, but I'm also trying to set my stuff up the best way I reasonably can. :D

Thanks in advance!

**Comment by robert-w-gries** [comment]
I'd recommend using v1 ReactiveResume since it can be self-hosted without Firebase and can be brought up quickly using Docker: https://hub.docker.com/r/amruthpillai/reactive-resume

I also find it has less issues and more features.

**Comment by AmruthPillai** [comment]
The v2 of this project heavily depends on Firebase and it's Realtime Database + Authentication to function. This was crucial to a lot of people I have spoken to about this project where they wanted the ease of being able to edit on any computer they log on to. Plus, there were some technical issues I had faced with making PDFs in the browser. Now, with Cloud Functions, it's a lot easier.

Like @robert-w-gries suggested, if using G services is a problem, you can always use the v1 version of Reactive Resume found at https://v1.rxresu.me. :)
