### ISSUE TITLE
Request for Miscellaneous: 2-column division

### ISSUE THREAD

**Issue by KeronCyst** [AmruthPillai/Reactive-Resume#334]
It would be great if there was a checkbox to split every other element added to a category in the main body across two columns (would save space for my particular setup on some of the templates)!

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
