### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by I-Johnson** [AmruthPillai/Reactive-Resume#335]
When I wanted to delete something that I don't want in my resume website was stuck and I had refresh the website again and again. It was happening frequently

**Comment by Radikad** [comment]
@I-Johnson if the error comes only while deleting **Work Experience**, **Education** I can help you to avoid the problem.

**Comment by AmruthPillai** [comment]
This should be fixed now. Thank you so much for reporting and using Reactive Resume! :)
