### ISSUE TITLE
Adding work experience causes the page to go blank

### ISSUE THREAD

**Issue by NathanielRudenberg** [AmruthPillai/Reactive-Resume#336]
When entering some data into the work experience field, clicking the "add experience" button causes the entire webpage to go blank. I have to refresh to get back into the app. Sometimes, the data I submitted is saved, sometimes it isn't.

Encountered on Chrome 85.0.4183.121

**Comment by ttben** [comment]
Indeed, same behavior here.
This is a severe bug as I didnt find any workaround yet...

**Comment by robert-w-gries** [comment]
Pretty sure this is related to #301
