### ISSUE TITLE
Unable to open a new resume when logged in as anonymous

### ISSUE THREAD

**Issue by adix149** [AmruthPillai/Reactive-Resume#338]
**index.js:50 GET https://source.unsplash.com/featured/400x600 net::ERR_CONNECTION_RESET**
(anonymous) @ index.js:50
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.js:49
(anonymous) @ DatabaseContext.js:45
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ DatabaseContext.js:43
(anonymous) @ DataModal.js:69
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ DataModal.js:47
onClick @ DataModal.js:94
o @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
lt @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
L @ react-dom.production.min.js:287
W @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Gt @ react-dom.production.min.js:69
KqkS.t.unstable_runWithPriority @ scheduler.production.min.js:19
jl @ react-dom.production.min.js:122
F @ react-dom.production.min.js:287
Yt @ react-dom.production.min.js:68
asyncToGenerator.js:6 Uncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ DataModal.js:47
onClick @ DataModal.js:94
o @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
lt @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
L @ react-dom.production.min.js:287
W @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Gt @ react-dom.production.min.js:69
KqkS.t.unstable_runWithPriority @ scheduler.production.min.js:19
jl @ react-dom.production.min.js:122
F @ react-dom.production.min.js:287
Yt @ react-dom.production.min.js:68

**Comment by AmruthPillai** [comment]
Should be fixed now, thank you for reporting and using Reactive Resume! :)
