### ISSUE TITLE
Export Resume to Single Page and Multi Page is stuck with Loading message and Print Resume is showing blank page

### ISSUE THREAD

**Issue by arkarmintun1** [AmruthPillai/Reactive-Resume#342]
When I finished preparing my resume on rxresu.me, I tried to export to pdf. When I click on 'Single Page Resume' or 'Multi Page Resume, the buttons changed to 'Loading...' and nothing happened. So, I tried to click on the 'Print Resume' button. When I click on it, only blank page keep showing.

**Comment by JonasMht** [comment]
I've got exactly the same issue as you !

**Comment by hamzawinix** [comment]
same issue

**Comment by arkarmintun1** [comment]
When I try on `https://v1.rxresu.me/`, export to pdf is working. Although project section is not included in the provided link.

**Comment by JonasMht** [comment]
See Rithvik-Reddy's workaround:
https://github.com/AmruthPillai/Reactive-Resume/issues/346#issuecomment-703254472

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
