### ISSUE TITLE
A bookmarklet for printing the resume in the browser

### ISSUE THREAD

**Issue by mohammed-io** [AmruthPillai/Reactive-Resume#345]
Hey @AmruthPillai and everyone who worked on awesome product.

Because I've seen some issues regarding printing and exporting, so I made a quick little bookmarklet to allow the resume to be printing without going back to the server or showing a blank screen.

Also it can be used to fix the original printing issue.

Hope this helps.

https://gist.github.com/mohammed-io/acae461995663455cbbdde9c878e8613

Regards,

**Comment by AmruthPillai** [comment]
Thank you for the help! 👍 

Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
