### ISSUE TITLE
cant download the resume

### ISSUE THREAD

**Issue by hamzawinix** [AmruthPillai/Reactive-Resume#346]
whenever I click export either as single or multi page the button freezes

**Comment by Rithvik-Reddy** [comment]
One work around is that you can open the link that shares your resume, and then click print page. You can save it as PDF from there.

**Comment by JonasMht** [comment]
> One work around is that you can open the link that shares your resume, and then click print page. You can save it as PDF from there.

This is a clever workaround, thanks for sharing it !

**Comment by mohammed-io** [comment]
Or use https://github.com/AmruthPillai/Reactive-Resume/issues/345

**Comment by EsmailELBoBDev2** [comment]
Yup i can tell the same, when i click on the button i get 
[rxresu.me-1601854998576.log](https://github.com/AmruthPillai/Reactive-Resume/files/5324636/rxresu.me-1601854998576.log)

**Comment by EsmailELBoBDev2** [comment]
> One work around is that you can open the link that shares your resume, and then click print page. You can save it as PDF from there.

sadly my PDf is too big and i want it to be one page only so any ideas?

**Comment by ashwin2020** [comment]
> One work around is that you can open the link that shares your resume, and then click print page. You can save it as PDF from there.

when you share the link of the resume, it doesn't show print option.

**Comment by EsmailELBoBDev2** [comment]
> > One work around is that you can open the link that shares your resume, and then click print page. You can save it as PDF from there.
> 
> when you share the link of the resume, it doesn't show print option.

(you click ctrl+p on chrome to print)

**Comment by ashwin2020** [comment]
If printed from the link , the page is cut from the middle and we dont get a single page resume, kindly fix the bug of exporting

**Comment by EsmailELBoBDev2** [comment]
Yes i mean that, thats why i said 
> sadly my PDf is too big and i want it to be one page only so any ideas?

**Comment by ashwin2020** [comment]
> Yes i mean that, thats why i said
> 
> > sadly my PDf is too big and i want it to be one page only so any ideas?

Then what to do if its of two page and is being cut from between

**Comment by EsmailELBoBDev2** [comment]
I tried to search online how the site did it but found no results

**Comment by klkl9** [comment]
> If printed from the link , the page is cut from the middle and we dont get a single page resume, kindly fix the bug of exporting

you need to change from landscape to portrait

**Comment by ashwin2020** [comment]
It is already in portrait mode, the lower half is being cut

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
