### ISSUE TITLE
Unable to download as single page or multiple page.

### ISSUE THREAD

**Issue by ritheshg06** [AmruthPillai/Reactive-Resume#347]
Not sure what change went in recently tried to download my resume after making some changes but the download as a single page and multiple pages is just showing up as loading forever. Please fix it at the earliest. Thank you.

**Comment by PostIt59** [comment]
Browser Inspector throw the following when the export as single or multipage buttons are clicked
```
index.cjs.js:72 Uncaught (in promise) Error: internal
    at new t (index.cjs.js:72)
    at index.cjs.js:193
    at e.<anonymous> (index.cjs.js:745)
    at tslib.es6.js:212
    at Object.next (tslib.es6.js:142)
    at a (tslib.es6.js:97)
t @ index.cjs.js:72
(anonymous) @ index.cjs.js:193
(anonymous) @ index.cjs.js:745
(anonymous) @ tslib.es6.js:212
(anonymous) @ tslib.es6.js:142
a @ tslib.es6.js:97
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ ExportModal.js:43
o @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
lt @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
L @ react-dom.production.min.js:287
W @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Gt @ react-dom.production.min.js:69
KqkS.t.unstable_runWithPriority @ scheduler.production.min.js:19
jl @ react-dom.production.min.js:122
F @ react-dom.production.min.js:287
Yt @ react-dom.production.min.js:68
```

**Comment by ritheshg06** [comment]
Hi Amruth Pillai,

Thank you for replying, not sure what that mean I am more into the
infrastructure side of things than towards JS. Could you please let me know
if the issue is on my side?

Thanks,
Rithesh

**Comment by EsmailELBoBDev2** [comment]
@ritheshg06 i think it's from your side, because multiple people reporting same issue

**Comment by ritheshg06** [comment]
From my side? Are you sure?

**Comment by EsmailELBoBDev2** [comment]
I think...

#350 #349 #347 (*this one*) #346 #342 #302 #345

**Comment by EsmailELBoBDev2** [comment]
@ritheshg06 oh my god, i just realized now what "Author" means xD

Very sorry, i thought you was the owner of the project

**Comment by ritheshg06** [comment]
Uhmmm I am just a user, so was scratching my head if many are reporting the
same issue why is it that they are saying issue is on my side? Cos even
others are facing it right? I am just a user like you, who is on the same
boat.

**Comment by EsmailELBoBDev2** [comment]
I'm sorry, i thought Author was like the creator of the repo. thats why i said it's your problem (the dev) got what i mean?

**Comment by EsmailELBoBDev2** [comment]
@AmruthPillai help! (*please*)

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)

**Comment by ritheshg06** [comment]
Sure will do it tomorrow

**Comment by EsmailELBoBDev2** [comment]
it kinda take time to export but FINALLY it does so i guess its a win, thanks :+1: `AmruthPillai`

**Comment by AmruthPillai** [comment]
Yes, the time it takes is quite normal. Cloud Functions take a few seconds to boot up, and the actual script itself takes time. Would love to see any PRs for improving this, but I've tried to do it to the best of my knowledge :)

Thank you so much for sticking through the difficult times. I don't get enough time to work on this as my full time job is very demanding. Because of the donations I get from this project, I keep coming back to this knowing that people are really being benefited by this. I do hope there won't be any more big issues so that I can focus on working on newer templates soon 💯

**Comment by EsmailELBoBDev2** [comment]
I swear if i know something from this i would help, but my problem. when it comes to big projects like this, it really get messy and i can't help so all i can do translations/report bugs and/or ideas
