### ISSUE TITLE
Export of resume is not happening.

### ISSUE THREAD

**Issue by ashwin2020** [AmruthPillai/Reactive-Resume#349]
I have created my resume and exporting it , but it keeps showing loading and nothing else, both for single and multipage this problem is taking place, even for print resume it is downloading an empty page.

**Comment by PostIt59** [comment]
Check this solution : https://github.com/AmruthPillai/Reactive-Resume/issues/346#issuecomment-703254472 ;)

**Comment by ashwin2020** [comment]
still not happening, please look into it and fix it, need an updated resume urgently

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
