### ISSUE TITLE
Print to PDF prints the sections into multiple pages

### ISSUE THREAD

**Issue by ganesh3** [AmruthPillai/Reactive-Resume#35]
**Describe the Bug**

**Reproduction**
Steps to reproduce the behaviour:
1. Go to 'Actions'
2. Click on 'Print'
3. Select 'Print to PDF'
4. PDF saved
5. Open PDF
6. Header of the template which is the picture and objective section is in one page whereas all other sections are on page 2. On page 1, post the header section, its a blank page that appears.

**Expected Behaviour**
Should print all sections one after the other on a page

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]

**Comment by AmruthPillai** [comment]
Merged into #41
