### ISSUE TITLE
Can't export any of the 2 versions

### ISSUE THREAD

**Issue by AncutaG** [AmruthPillai/Reactive-Resume#350]
I used to export my resume 2 weeks ago, but when I tried again after something that I have modified, I can't anymore. I cleared my cache so I am not sure if it's a problem from my side or something similar. Thank you.

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
