### ISSUE TITLE
I can't embed my CV link into my website

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [AmruthPillai/Reactive-Resume#352]
Everytime i try to insert <iframe> tags with your website link (my cv link) it show blank page and after asking i knew it's x-frames thing so any ideas?

**Comment by AmruthPillai** [comment]
Not really sure about that, there shouldn't be any issues embedding the resume link into an `iframe`, but they are known to be blocked by many browsers nowadays due to security concerns. You could maybe export a PDF and display the PDF directly? Clicking on it can redirect to the web link?

**Comment by EsmailELBoBDev2** [comment]
Yes thats the problem in the other issue, i stated that we can't export pdfs (thats why i wanted to make it into iframe)
