### ISSUE TITLE
Unable to export to pdf

### ISSUE THREAD

**Issue by jjasmnie** [AmruthPillai/Reactive-Resume#354]
When I click the multi-page/single-page buttons, no export happens

**Comment by T-h-o-m-a-s** [comment]
Me too

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
