### ISSUE TITLE
Exporting to pdf doesn't work anymore.

### ISSUE THREAD

**Issue by klkl9** [AmruthPillai/Reactive-Resume#355]
I've been using your app for the past couple of months and it has been very useful. Over the past few days when I tried updating my resume and exporting the updated one to pdf, it would just say loading, and nothing gets downloaded. I tried different devices, and different accounts, and still doesn't work. This website is really good and I would hate to lose all my data on it.
Thank you very much.

**Comment by shaikyounus** [comment]
Same Problem

**Comment by AmruthPillai** [comment]
Should be fixed in the latest update v2.2.0 :)

You can check the version you're on at the footer of the right sidebar.

![Screenshot 2020-10-10 at 12 37 10 PM](https://user-images.githubusercontent.com/1134738/95648502-55f02980-0af5-11eb-8ea2-bd2fc5428f07.png)
