### ISSUE TITLE
Download Is not working

### ISSUE THREAD

**Issue by karanoza** [AmruthPillai/Reactive-Resume#361]
Hello Amruth,

        - I created the resume format for my colleague but the download option is not working.
         - Also It unable to show the preview on print on browser window screen
         -I attach the SS for your reference 

![print window](https://user-images.githubusercontent.com/50609276/96362781-56b83980-114d-11eb-89cf-924b870c0486.png)
![rx download issue](https://user-images.githubusercontent.com/50609276/96362782-57e96680-114d-11eb-9812-c0edac2e7c98.png)

**Comment by easterneas** [comment]
I can reproduce the print preview problem (blank page) as well, though I still can download the PDF of the resume.

**Comment by DineshSolanki** [comment]
@karanoza which browser?
