### ISSUE TITLE
Line Break not working, I Tried everything written on the markdown page. Can someone tell me, How to do this?

### ISSUE THREAD

**Issue by raj007champ** [AmruthPillai/Reactive-Resume#362]

**Comment by vikasmulaje** [comment]
Reproducible to me as well v2.2.1

**Comment by Kapot** [comment]
I had the same problem. A double space at the end of the line works for a linebreak, but if you want an empty line it's not working with just 2 spaces, you need to add a character. I found a 'hidden' character to force this. Just add this character + 2 spaces and an empty line will appear. Cant post the character here, [so here is the link](https://emptycharacter.com/).
