### ISSUE TITLE
Support for categorization of skills

### ISSUE THREAD

**Issue by sgcuber24** [AmruthPillai/Reactive-Resume#363]
Hello,

It would be great if the skills could be categorized under multiple subheadings. 

Eg. 
**Programming Languages**: C++, Java, Python, JavaScript
**Frameworks and Libraries**: ReactJS, Tensorflow, Keras.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
