### ISSUE TITLE
Per file language setting

### ISSUE THREAD

**Issue by MaximeChretien** [AmruthPillai/Reactive-Resume#364]
Is it possible to apply a different language setting to each file ?
It's useful when you have both a resume in your mother tongue and in English.

This will apply to section names and dates at least.

Thanks for taking in account this request.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
