### ISSUE TITLE
Still can open in edit mode

### ISSUE THREAD

**Issue by easterneas** [AmruthPillai/Reactive-Resume#366]
Hi, I recently got the issue where other users can still open the resume in edit mode (i.e. `https://rxresu.me/app/builder/<resume_id>`).

Though the update process can't be done by unauthorized user (threw `Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied` in console), but I think it would be better if the app shows the actual error to unauthorized user that the user doesn't have the permission to view the resume in edit mode.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
