### ISSUE TITLE
Firebase-Function not working

### ISSUE THREAD

**Issue by the-manohar** [AmruthPillai/Reactive-Resume#367]
After downloading this file , when i use my firebase credentials in .env and start the project . But the firebase is not working . it shows this error.

Error: Missing permissions required for functions deploy. You must have permission iam.serviceAccounts.ActAs on service account
rx-resume@appspot.gserviceaccount.com.

To address this error, ask a project Owner to assign your account the "Service Account User" role from this URL:

**Comment by HristovCodes** [comment]
You also need to go to your firebase console and enable everything required for the project to run like: Authentication, Storage, Realtime Database and so on.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
