### ISSUE TITLE
Bad French translation of Present

### ISSUE THREAD

**Issue by marinang** [AmruthPillai/Reactive-Resume#368]
Cadeau is a 🎁  in French x), Présent is the correct translation.

https://github.com/AmruthPillai/Reactive-Resume/blob/f2b74caa7c45721c4503ddf08fda032d7b05f5ef/src/i18n/locales/fr.json#L12

**Comment by AmruthPillai** [comment]
Got it, updated this on commit d4816291b47f1b8bc0de7705d5dac3a38f0cb73d. Thank you for raising the issue.
