### ISSUE TITLE
Don't Require Exact Date

### ISSUE THREAD

**Issue by demonspork** [AmruthPillai/Reactive-Resume#369]
I'm trying to enter in general work experiences that I don't have specific start or end dates, just the years. Currently I can either leave out the dates completely or I have to fill in a full date. Same issue with Education. Being able to define just a year or just a month+year instead of requiring exact dates is ideal.

Slightly related, I came across the V1 resume before I read more about the project and just jumped right in and used it. Then when I read more into it I decided to switch to v2, the JSON I created in V1 won't import to V2. Could it be that I am using only partial dates and the import is validating the dates? I even explicitly used the word "Present" in the end date for my current job in V1, but I notice that V2 puts it automatically when there is no end date.

**Comment by KeronCyst** [comment]
I agree: it would be great if Education omits the "( - )" if zero dates or only one date is provided. Currently I have to edit it out in Acrobat DC.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
