### ISSUE TITLE
Export Resume not working

### ISSUE THREAD

**Issue by amit-bhadra** [AmruthPillai/Reactive-Resume#383]
Exporting to single page, multipage is not working for my resume.

When I go to the preview link and press Cmd + P, then the content of the resume overflows from 1st page to 2nd page.

**Comment by HristovCodes** [comment]
Can you provide an example?

**Comment by amit-bhadra** [comment]
https://rxresu.me/r/hxk2k6

Try this one I created. cmd + P, makes the content overflow to 2nd page.

**Comment by HristovCodes** [comment]
The only problem I could find is that when converting to pdf the new document has slightly bigger side margins which lead to unexpected behavior. The resume you provided is on the verge of overflowing and this small margin difference causes some of the text to wrap sooner than it is supposed to as seen in the screenshots.
- Pdf: 
![pdf](https://i.imgur.com/p6dE4h2.png)
- Your resume:
![resume](https://i.imgur.com/VfT57lo.png)

To fix this could you try shortening just that part and see if the issue persists?

**Comment by AmruthPillai** [comment]
@HristovCodes Could you try exporting as single page/multi page now?
