### ISSUE TITLE
Now everything is center-aligned

### ISSUE THREAD

**Issue by MarionMoseby** [AmruthPillai/Reactive-Resume#387]
With the lastest update, the document export becomes centered, instead of having the text align left, which IMHO is prettier
Is there a chance you could revert this situation, or at least make it configurable?

**Comment by tathurma** [comment]
I am also having the same issue.

**Comment by lucky2sachin** [comment]
Same issue here. Please let us know how to manually left align the content or fix this problem.

**Comment by afkcodes** [comment]
@AmruthPillai this is a bit problematic. Please look into this I need to apply by tomorrow but this issue is centering every element/section.

**Comment by lucky2sachin** [comment]
@afkcodes well, if you want then it's easy to edit with LibreOffice. Try it, thank me later for now cuz it's emergency for ya.

**Comment by afkcodes** [comment]
@lucky2sachin sure will try

**Comment by therocketmohammed** [comment]
The option PDF Download specifically the "Single Page Resume" The left alignment looked great, but it seems the application has changed now to middle alignment, which looks wierd! Please check my attached screenshot

[https://i.imgur.com/N5EpKGw.png](https://i.imgur.com/N5EpKGw.png)

**Comment by AmruthPillai** [comment]
Really sorry about this. Trying to figure out why this is happening, but there's not really any recent code change that made this alignment issue crop up. Do raise a PR if you feel you have a fix for this issue and we can get it pushed on priority.

**Comment by aslicode** [comment]
Issue still persists

**Comment by afkcodes** [comment]
@aslicode he never told its fixed.

**Comment by AmruthPillai** [comment]
In the process of fixing it, seems to be working locally. Will update when it's working alright on production.
If you experience some downtime right now with printing, it should be because I'm testing stuff. Sorry for the inconvenience :(

**Comment by AmruthPillai** [comment]
This has been fixed now from version 2.3.3 🎈 

Please do consider sharing and spreading the word about Reactive Resume on Twitter or by donating to the support of this project on https://www.buymeacoffee.com/AmruthPillai, it would mean a lot. Thank you so much for your patience.
