### ISSUE TITLE
Alignment issue upon export as pdf

### ISSUE THREAD

**Issue by akinlex** [AmruthPillai/Reactive-Resume#392]
After export on pdf, the alignment of all section become centralized making it look messy and doesn't look like it is on the app builder (left-aligned).
![Untitledr](https://user-images.githubusercontent.com/38322749/101396709-072ff780-38cc-11eb-8aa4-a2172476ec39.png)

**Comment by MarionMoseby** [comment]
Duplicate of #387, although your title is better, maybe I should change the title on #387

**Comment by AmruthPillai** [comment]
Fixed now, as of 2.3.3: https://github.com/AmruthPillai/Reactive-Resume/issues/387#issuecomment-741533829
