### ISSUE TITLE
[BUG] Printing the document adds extra blank spaces at the top and bottom

### ISSUE THREAD

**Issue by aslicode** [AmruthPillai/Reactive-Resume#395]
After trying to print the exported document regardless of what page type I select it adds extra top or bottom spaces. Can we make it so that all of the page is used during printing. I'll attach pics to better show before and after printing issue.
(I wanted to print resume in A4 format but couldn't do so properly without having those blank spaces.) Before Printing
![before printing](https://user-images.githubusercontent.com/71381657/101634356-9238fb00-3a4e-11eb-98d4-5ef1372b6399.PNG) after printing 
![after printing](https://user-images.githubusercontent.com/71381657/101634370-99600900-3a4e-11eb-9a32-f9fc6ea1e12e.PNG)

**Comment by aslicode** [comment]
any fixes???

**Comment by AmruthPillai** [comment]
Are you trying to use the browser print method or export PDF method? Also, which browser are you using? On both counts, I'm able to get a A4 resume no matter how short the content is.

![image](https://user-images.githubusercontent.com/1134738/102003323-c270ea00-3d2b-11eb-83cf-a85af0b29ad6.png)

**Comment by AsLi-IN** [comment]
> Are you trying to use the browser print method or export PDF method? Also, which browser are you using? On both counts, I'm able to get a A4 resume no matter how short the content is.
> 
> ![image](https://user-images.githubusercontent.com/1134738/102003323-c270ea00-3d2b-11eb-83cf-a85af0b29ad6.png)

no  im not trying to use browser print method (Also im using chrome browser). Im using export option, the problem does not occurs when you export the pdf, it occurs when I'm trying to print the pdf. Also when I try to use browser method it looks like this :
![browserp](https://user-images.githubusercontent.com/71381657/102005302-ca398a00-3d3d-11eb-90eb-8cafd6c370a7.PNG)

**Comment by AmruthPillai** [comment]
@aslicode So the print CSS isn't all that clear while on the builder mode. This is why even the export function, it relies on visiting your resume's public sharable link which looks like `https://rxresu.me/r/:resumeID`. You can try visiting this link and then trying browser print method, you should have better results. Also, for the margins, while printing you can set Margins to **None** on the Chrome Print Dialog to make it fit perfectly.
