### ISSUE TITLE
[Feature] Telegram & Skype icons

### ISSUE THREAD

**Issue by pmsoltani** [AmruthPillai/Reactive-Resume#396]
Would you please add icons for [Telegram](https://telegram.org) and [Skype](https://www.skype.com)? When I added them in the network section, the result looked like this:
![image](https://user-images.githubusercontent.com/25427031/101687983-8ebe6780-3a80-11eb-8cb9-ff5571f47e52.png)

Also, while I'm talking about Skype, I tried to add a URI like this: `skype:username?chat` (according to [this](https://docs.microsoft.com/en-us/skype-sdk/skypeuris/skypeuris) guide), but the form prevented me, saying that it's not a valid URL (which I guess it isn't):
![image](https://user-images.githubusercontent.com/25427031/101688456-523f3b80-3a81-11eb-84a2-c08e20fe24ef.png)

As a workaround, I exported the resume to json and edited it directly. I can confirm that upon importing the modified json file, the link does work as intended. However, it would be better if the application form would allow typing URIs.

Last, but not least: @AmruthPillai you are awesome 😎💪🚀

**Comment by AmruthPillai** [comment]
No, you're awesome, for making Reactive Resume better and better with your feedback.

I've taken up your suggestion and removed URL validation on this field, and also added the Telegram and Skype icons to the mix. You should be able to do what you need directly from the app as of v2.3.4 now :)
