### ISSUE TITLE
Export to PDF failure on Opera

### ISSUE THREAD

**Issue by brandonsaldan** [AmruthPillai/Reactive-Resume#399]
## Expected Behavior

Successful export to PDF

## Current Behavior

Displays error message `"The cloud function is running into some trouble, please try again later or use the browser print feature."`

Resume was successfully exported using Google Chrome, but is still broken on Opera. (Does not seem to be a local network issue).

## Steps to Reproduce

1. Create a resume using Opera Browser
2. Select "Export" under "Export Your Resume"
3. Select "Single Page Resume" under "Download PDF"

## Environment
Windows 10 Pro 1909
Opera 72 (VPN off)

## Relevant Screenshots
![image](https://user-images.githubusercontent.com/26472557/101971436-55603600-3bff-11eb-823f-a0574f6f4f6a.png)

**Comment by saberzuko** [comment]
I am using Chrome, and I am also facing the same issue.

**Comment by brandonsaldan** [comment]
> I am using Chrome, and I am also facing the same issue.

Exporting on Chrome worked for me, but since Opera is also based on Chromium this leads me to think the bug is caused by it in some way.

I just tested exporting in Firefox and it worked. It isn't Chromium based so it should probably export fine for you (or anybody else having this bug) in the meantime.

**Comment by saberzuko** [comment]
I tried exporting in Firefox still facing the same issue
