### ISSUE TITLE
Ability to hide address section if blank?

### ISSUE THREAD

**Issue by harleykin** [AmruthPillai/Reactive-Resume#408]
Hey there!  I'm really enjoying playing around with this app.  I found it while looking for resume builders for my kid.  The only thing I've found so far that irks me is that if the address is not filled out, the heading still shows.  Can that be removed if its child fields are blank?  I don't ever put my home address on my resume ... someone once got my address from a copy of my resume in the past and just showed up where I lived!  Lesson learned.  :)

**Comment by DineshSolanki** [comment]
This feature is already there, Which template/theme are you using?

**Comment by harleykin** [comment]
Hrm, maybe I'm not seeing it then?   I'm using Gengar.

**Comment by DineshSolanki** [comment]
@harleykin only onyx and Pikachu hides address header, your suggestion is good though.

**Comment by harleykin** [comment]
@DineshSolanki Thanks, I can edit the PDF for now.  This is a great app, I'm glad I found it!  👍

**Comment by AmruthPillai** [comment]
This has been fixed from version 2.4.3 :) You should be able to see address on every template now and it's also optional, so keeping all address fields empty would remove the heading too. Hope this helps, and thank you for kind words 🙏🏻  😄
