### ISSUE TITLE
Browser Compatibility Issues

### ISSUE THREAD

**Issue by DineshSolanki** [AmruthPillai/Reactive-Resume#409]
Track browser compatibility issues here. for better management and more chance of fixing.
#402 #399 #383 #361

**Comment by saberzuko** [comment]
I am also facing the same issue with exporting my Resume and I am getting these errors
![Screenshot from 2021-01-18 23-25-18](https://user-images.githubusercontent.com/20773048/105001502-b6d8a900-59e4-11eb-904c-71990f02ae20.png)
