### ISSUE TITLE
auth/invalid-api-key

### ISSUE THREAD

**Issue by ndaringer** [AmruthPillai/Reactive-Resume#416]
Immediately getting a black screen when it loads up after the last update. I am using docker.

![image](https://user-images.githubusercontent.com/207518/103292860-b38d6700-49bc-11eb-845f-b1b0e98a882b.png)

**Comment by mlapaglia** [comment]
same issue here, does this have something to do with firebase?

**Comment by AmruthPillai** [comment]
Yes, this is related to Firebase. You need to have a `.env` file with proper credentials in the root of the project when building the app.

**Comment by ndaringer** [comment]
Sorry. I misspoke. I'm using dockerhub. Do I still need to create the .env?

**Comment by mlapaglia** [comment]
Same, where does the `.env` need to be if I'm running the container?

**Comment by mrbiggmd** [comment]
Same problem here.  Please advise.  Thank you.

**Comment by AmruthPillai** [comment]
Sorry about the late reply.

Yes, `.env` is needed even when running through Docker.
You would need to manually add this file to the filesystem, or copy it within dockerfile
(you can use `COPY --from=builder .env /app/.env`)

The .env should look like this, but filled:
```env
FIREBASE_APIKEY=""
FIREBASE_APPID=""
FIREBASE_AUTHDOMAIN=""
FIREBASE_DATABASEURL=""
FIREBASE_MEASUREMENTID=""
FIREBASE_MESSAGINGSENDERID=""
FIREBASE_PROJECTID=""
FIREBASE_STORAGEBUCKET=""
```

Alternatively, you can also use this method: https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers Haven't tested it this way, but no reason it shouldn't work as it just copies host ENVs to the container machine. Please do let me know if that resolves the issue :)
