### ISSUE TITLE
When downloading resume, paper size gets mangled

### ISSUE THREAD

**Issue by PMilstone** [AmruthPillai/Reactive-Resume#417]
When I download my resume the pdf is abnormally long compared to a sheet of paper. I know there are different size standards across the world but maybe implementing a setting to have different sizes of paper would suffice? Before it is exported the size seems normal but post export it's longer than usual.

**Comment by sudo-kaizen** [comment]
@PMilstone Are you using the `Print Resume` option or the `Download` option?
