### ISSUE TITLE
[Bug] Error building on Windows

### ISSUE THREAD

**Issue by lgwapnitsky** [AmruthPillai/Reactive-Resume#42]
PS C:\temp\Reactive-Resume> npm run build C:\temp\Reactive-Resume\

> reactive-resume@1.0.0 prebuild C:\temp\Reactive-Resume
> npm run css:prod

> reactive-resume@1.0.0 css:prod C:\temp\Reactive-Resume
> postcss src/assets/tailwind/tailwind.src.css -o src/assets/tailwind/tailwind.css --env production

> reactive-resume@1.0.0 build C:\temp\Reactive-Resume
> NODE_ENV=production react-scripts build "C:\temp\Reactive-Resume\"

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactive-resume@1.0.0 build: `NODE_ENV=production react-scripts build "C:\temp\Reactive-Resume\"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactive-resume@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Larry G Wapnitsky\AppData\Roaming\npm-cache\_logs\2020-03-31T15_38_44_307Z-debug.log

**Comment by lgwapnitsky** [comment]
nvm.  edited json file and fixed

**Comment by AmruthPillai** [comment]
Hey there, glad you got that fixed on your own :) For anyone else facing issue with building on windows, this is a pretty common error as `NODE_ENV=production` is a Unix command.

Here's a StackOverflow answer on how you can fix this issue:
https://stackoverflow.com/a/9250168/1248133

I will fix this in the package.json for the future where it runs a different command when building on Windows :) Thank you for your feedback and reporting!
