### ISSUE TITLE
Separating firebase code from the rest

### ISSUE THREAD

**Issue by directionx-ca** [AmruthPillai/Reactive-Resume#421]
Is it possible to easily add an option to not use firebase at all(not store data) or at least make the app work without login(even without anonymous login)?

**Comment by TaylorWatson** [comment]
+1 to this. There's an unraid docker container yet I'm suppose to link it with firebase?

**Comment by AmruthPillai** [comment]
The previous version of this app was completely free from all storage options. You could continue to use that if you would prefer that :) It is also hosted on https://v1.rxresu.me/

https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v1

**Comment by mahmor93** [comment]
Tried to install the v1 but getting error
