### ISSUE TITLE
HTTPS/SSL Blocked causing invalid API error

### ISSUE THREAD

**Issue by sdiver78** [AmruthPillai/Reactive-Resume#424]
Getting two errors, believe they are related, though not certain. 

1. "Service workers can only be used over HTTPS, or on localhost for development" 
2. "{code: "auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly.", a: null}" 

Deploying with Docker template from that SelfhostedPro at https://github.com/SelfhostedPro/selfhosted_templates, which defines this Docker config:
```
  {
    "type": 1,
    "title": "Reactive-Resume",
    "name": "reactive-resume",
    "description": "A one-of-a-kind resume builder that's not out to get your data. Completely secure, customizable, portable, open-source and free forever.",
    "logo": "https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/reactiveresume.png",
    "image": "amruthpillai/reactive-resume:latest",
    "categories": [
      "Other",
      "Tools"
    ],
    "platform": "linux",
    "restart_policy": "unless-stopped",
    "ports": [
      "80/tcp"
    ],
    "volumes": [
      {
        "container": "/usr/src/app",
        "bind": "/portainer/Files/AppData/Config/ReactiveResume"
      }
    ]
  },
```

To fix, seemingly need to enable SSL on the Docker image, ie, latest version, which might then fix the blocked API call, or need to provide a valid API key. 

Appreciate any pointers and suggestions?

**Comment by Shadow58624** [comment]
Also having these errors

**Comment by mlow** [comment]
SSL isn't really necessary in the docker image, you could just put it behind a reverse proxy that performs SSL termination - separation of concerns.

Re. the invalid API key, see discussion in #436

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
