### ISSUE TITLE
Addition of Custom section

### ISSUE THREAD

**Issue by saberzuko** [AmruthPillai/Reactive-Resume#425]
Hey Amrut,
I enjoyed your Resume builder. But if there were an option of adding custom blocks, that would be great. I spent time using your app to build my resume but later realized that there is no section for Publications, and I didn't have any alternative, which will be a placeholder for the Publication section.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Comment by OMGtechy** [comment]
[posting here because it's still the first thing that comes up on Google for me]

For those wanting to have a free-form section, best I found was using an additional Summary section with a custom title - it gives you just a text box to write in which allows for things not covered elsewhere.
