### ISSUE TITLE
Feature request: Allow drag & drop in the skill section

### ISSUE THREAD

**Issue by DannyFeliz** [AmruthPillai/Reactive-Resume#428]
Hi, 

It would be nice if we could drag & drop the skill, so we don't spend too much time reordering each skill by clicking the **^** and **v** arrows as shown in the following video. 

![drag](https://user-images.githubusercontent.com/5460365/105224405-85222800-5b33-11eb-8a90-730ed9178594.gif)

BTW I love this project; I just started supporting it in buymeacoffee.com

**Comment by gianantoniopini** [comment]
I'll work on this.
