### ISSUE TITLE
Reactive give black screen on all my browsers

### ISSUE THREAD

**Issue by wiebereu** [AmruthPillai/Reactive-Resume#432]
I reinstall the container several times but i can't get a normal screen. The moment launch the app in a browser the screen turns black. I tried it on different browsers but the results are the same. The screen is going into darkmode within 2 seconds. It happens after the last update of 2 or 3 weeks ago. I run the app as a docker container on my Synology NAS. I also restarts my Synology and restart Docker but till now the same results.  **black screen**

**Comment by AmruthPillai** [comment]
Similar to #430, please take a look at this comment: https://github.com/AmruthPillai/Reactive-Resume/issues/430#issuecomment-766369580 :)
