### ISSUE TITLE
Website not appearing on Work Experience

### ISSUE THREAD

**Issue by Koichisama** [AmruthPillai/Reactive-Resume#439]
Despite filling up my work experience details with an URL (link to my website) it does not appear at all on the page, while when filling an URL with Projects it works perfectly. Am I doing something wrong?

**Comment by mrinmaydhar** [comment]
Don't forget to add `https://` before the website URL. It's a bug, I think. It cannot handle links without protocols prepended.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
