### ISSUE TITLE
This is not formatting correctly 

### ISSUE THREAD

**Issue by kellyksveinson** [AmruthPillai/Reactive-Resume#440]
it's always a last minute situation, I'm trying to apply for a tech job first in a while and i was hoping to show off using a slick website to show off my resume and now I need to use a different one, need this by Friday and now I'm scrambling.

its not formatting correctly, using Firefox on Ubuntu 20.04
https://rxresu.me/app/builder/0z5zzw
![2021-02-01_20-29 Resume](https://user-images.githubusercontent.com/78395152/106543973-66754700-64cc-11eb-9696-0e06211a1d65.png)

Thank you

Kelly

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
