### ISSUE TITLE
Request to make option field

### ISSUE THREAD

**Issue by yahilmadakiya** [AmruthPillai/Reactive-Resume#441]
In skills section we have field to add level of that skills. Can we have that field optional?

![Screenshot 2021-02-02 at 3 23 33 PM](https://user-images.githubusercontent.com/11607839/106583083-b1459c00-656a-11eb-8ad0-27aea21a6160.png)

**Comment by AmruthPillai** [comment]
Relevant PR for this change: https://github.com/AmruthPillai/Reactive-Resume/pull/442

**Comment by yahilmadakiya** [comment]
Thanks for your quick response.
