### ISSUE TITLE
Use document thumbnail for resume preview

### ISSUE THREAD

**Issue by binyamin** [AmruthPillai/Reactive-Resume#444]
The current preview image for the resume (on the dashboard) is unrelated to the resume content. If there needs to be a preview image, it should probably mean something. Suggestion: use a library such as puppeteer to capture an image of the resume. That would make sense as a preview image.

**Comment by AmruthPillai** [comment]
@binyamin Yes, I had kept the unrelated image that's served from Unsplash as a placeholder. While I could implement something like puppeteer to screenshot the latest preview of the resume, it would significantly increase server costs given the current traffic the site is bringing in. I chose to let it go so as to not put me in a position where I would have to aggressively ask for donations :)

**Comment by binyamin** [comment]
@AmruthPillai That makes a lot of sense. I have another suggestion: Create default thumbnails for each theme/color, or one for all the themes/colors. It's hard to see them closely enough to tell the difference, anyway.
The reason I'm pushing this is that the current image is totally unrelated. From a UI/UX perspective, it seems unnecessary.

**Comment by HotBlack77** [comment]
Would it be possible to add a tag for each CV, saying what job it was targetet for and show this ón the dashboard?
Ideally one might even be able to associate a URL to the job posting or copy past in the job description and have it displayed in some nice way? 
(The use case here is that when making lots of CVs for different jobs, its nice to have a little more info about what a given CV was for, than what can be stuffed into the title)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
