### ISSUE TITLE
import is not working

### ISSUE THREAD

**Issue by prasanna8332** [AmruthPillai/Reactive-Resume#445]
I have previously used your app and I am greatly impressed, I have downloaded the resume and tried reopening using the import option, it is not working

**Comment by dmiquel** [comment]
Same, when I import JSON into a new cv it displays a black screen.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
