### ISSUE TITLE
Images missing from pdf

### ISSUE THREAD

**Issue by geekypenguin** [AmruthPillai/Reactive-Resume#446]
The profile image is missing when saving to pdf in all templates. 
Image works with print to pdf but other layout features brake then

**Comment by dchakro** [comment]
Same for me. The Saved PDF is missing the profile image.

**Platform info:**

Installation: Docker container (host OS Debian Buster).
Browser: Safari 14.0.2 (MacOS Big Sur)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
