### ISSUE TITLE
Not able to export

### ISSUE THREAD

**Issue by lennon3-coder** [AmruthPillai/Reactive-Resume#452]
![Screen Shot 2021-02-09 at 6 49 32 PM](https://user-images.githubusercontent.com/78829667/107443857-8e396000-6b07-11eb-953e-be7f947ae2f2.png)

Not able to export. When going to print, the resume is cut off on the sides.

**Comment by HotBlack77** [comment]
Same here, cant export using the single or multi page feature and when I print, I simply get a vertical strip of the CV.

**Comment by AmruthPillai** [comment]
@HotBlack77 Could you share some more information about which browser you are using? I'm not completely sure why, but the browser has some differences in the way it's calling the cloud function, or downloading the file. Your diagnosis could prove helpful to me in solving this :)

**Comment by HotBlack77** [comment]
I was trying on a slighlt earlier version of chrome, but today both chrome (version 89.0.4389.82) and Edge (89.0.774.45) work fine. Hwoever, there is quite a long delay between clicking export and the download of the PDF starting (som sort of user feedback during this might be helpful).
