### ISSUE TITLE
Supporting "Present" as the End Date for Work Experience

### ISSUE THREAD

**Issue by yijia-zhan** [AmruthPillai/Reactive-Resume#461]
It looks like there's no way to support "Present" as the End Date for Work Experience in https://rxresu.me/. 

But it's supported with https://rx-resume.web.app/. 

Which leads to the question, which URL is the real app?

**Comment by AmruthPillai** [comment]
@yijia-zhan It is https://rxresu.me, but if you might have visited the app earlier, you might have a cached version of the older app. To remedy this, just [clear site data](https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/) to always fetch the latest version.

**Comment by yijia-zhan** [comment]
@AmruthPillai Thanks! Back to the original question then, do you know if there's support for "Present" as the End Date for Work Experience?

**Comment by AmruthPillai** [comment]
@yijia-zhan Yes, there should be :) You just need to ensure you don't add an "End Date" and it would, by default, display "Present".
