### ISSUE TITLE
[Feature Request] Ability to use CV elements in multiple CVs

### ISSUE THREAD

**Issue by HotBlack77** [AmruthPillai/Reactive-Resume#465]
I do quite a bit of freelance work, where for each job I often need to produce a custom CV. Reactive-Resume with its ability to let you have a large number of different CVs is great for this, but it is frustrating that for each CV I create I need to either make a new one from scratch and copy over the data I need, or I need to duplicate an existing one and then adjust the information in it. 

I would love to see a feature where one first creates a master CV with all the info one has, e.g. all the jobs, projects and certificates one has ever done. Then when creating a CV all one would have to do is pick what elements are a good fit for the specific CV one is trying to generate. Obviously edits to the master data should flow to the specific CVs, so that if you correct a typo in the master data, then the all the CVs that reference that field all get the new data. 

Would this be possible? This sort of feature does not seem to exist in any online CV tool.

**Comment by AmruthPillai** [comment]
It's quite an interesting idea, to be able to copy over data from one resume to another. I did try to justify this issue by adding the Duplicate function, but like you said, it would be an issue when you have to update a block of information that has been duplicated over 'x' times.

The automated solution you are talking about is akin to systems like GitHub (or Git itself), called version control. And to be honest, it's way above my league and I just wouldn't know where to begin 😄 

For a simpler solution, I do think it should be possible to add a context menu in each section where one of the options is to "Copy from existing", which would open a modal that allows you to select the name of the resume to copy data from. I can see this being implemented easily, and also solving the solution, albeit with a bit of manual work... but baby steps 🍼 

What are your thoughts on this approach?

**Comment by HotBlack77** [comment]
I was thinking of something a little simpler than the full complexity of GitHub. Wouldnt it be enough to simply split things in to 2 main components. A new component focused on inputting and maintaining data e.g. listing all the different jobs you had with profile pictures, name, all associated contacts, location etc. The second components would be basically whats already there but with some of the data input removed so you could focus just on setting out the layout on the given CV. Ideally the each CV could be associated with a url maybe even a copy of the job description you were applying for, perhaps even a cover letter. I realise this would be a significance to the current codebase but atleast fo rmy use-case this would be absolutely amazing.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
