### ISSUE TITLE
Multipage CV breaks akwardly across pages

### ISSUE THREAD

**Issue by HotBlack77** [AmruthPillai/Reactive-Resume#467]
If one creates a new CV using the demo data and then exports it as a multipage pdf, the page breaks are not very appealing. The pages simply breaks mid-line and continues on the next sheet. I know this is a very hard issue to get perfect (see how much work LaTeX puts into this), but could something slightly better be done?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!

**Comment by anseenivasan** [comment]
we still see this issue in v3 release.

**Comment by jordantrizz** [comment]
Still see this in the latest release. Should a new issue be opened? Can this feature be sponsored?
