### ISSUE TITLE
Missing section of position of responsibility

### ISSUE THREAD

**Issue by himakkshi-17** [AmruthPillai/Reactive-Resume#469]

**Comment by himakkshi-17** [comment]
Please customize to add any section so that it will be an awesome open source ahead to be used !
Great Work :)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
