### ISSUE TITLE
Fonts are not  working with Cyrillic.

### ISSUE THREAD

**Issue by EmerickGrimm** [AmruthPillai/Reactive-Resume#471]
All writings on Cyrillic looks same (with all fonts)  https://ibb.co/G2rNH1w

**Comment by HristovCodes** [comment]
@AmruthPillai can I take on this issue?
Many of my irl friends use this app to make their resume and they all complain about this missing feature.
I was thinking:
1. Add a new section to the sidemenu with Cyrillic supported fonts.
2. Add few more fonts to the fonts section that support Cyrillic 

Which one would be better in your opinion 1 or 2?

**Comment by HristovCodes** [comment]
Update just tested the fonts and it turns out most of them work just fine.
The only ones that don't work are:
- Lato
- Titillium Web

6 out of 8 fonts is plenty customization, so in my opinion we can close this. No new fonts are needed for this reason.

**Comment by EmerickGrimm** [comment]
> Update just tested the fonts and it turns out most of them work just fine. The only ones that don't work are:
> 
>     * Lato
> 
>     * Titillium Web
> 
> 
> 6 out of 8 fonts is plenty customization, so in my opinion we can close this. No new fonts are needed for this reason.

Screenshots I made right now:

https://ibb.co/P1vs5L6
https://ibb.co/bLghNJT
https://ibb.co/3fjdkV2
https://ibb.co/KVtXWZn
https://ibb.co/nMdBdMC
https://ibb.co/b2WQtDn
https://ibb.co/6Wfknb3
https://ibb.co/RpV4kyG
