### ISSUE TITLE
Spamming `Create Resume` button creates multiple new resumes. Fix also mentioned.

### ISSUE THREAD

**Issue by ceoshikhar** [AmruthPillai/Reactive-Resume#476]
# Demo of the bug
![rxresume-bug](https://user-images.githubusercontent.com/62669971/113472332-2d336600-9480-11eb-9f1e-fa9360abab41.gif)

# Where this bug exists
It was a little confusing for me to figure out how the `Create Resume` modal was working but AFAIK `Create` and `Edit` resume is a part of `src/modals/DataModal.js`. 

https://github.com/AmruthPillai/Reactive-Resume/blob/8628ca5475e4ae79bc28fe70d61f8cca32b4f0dd/src/modals/DataModal.js#L94

I am pretty sure, the fix is very simple - 
original: `onClick={() => onSubmit(values)}`
solution: `onClick={() => !loading && onSubmit(values)}`

We just don't call `onSubmit(values)` if `loading` is true. @AmruthPillai I can create the PR with the fix if you also think this is the solution for the bug and assign this issue to me.

**Comment by ceoshikhar** [comment]
@AmruthPillai I would love to contribute to this project. Let me know if the solution is correct and I will do the PR ASAP.

**Comment by AmruthPillai** [comment]
> @AmruthPillai I would love to contribute to this project. Let me know if the solution is correct and I will do the PR ASAP.

The solution seems like a good one, do raise a PR for the same and we can check tests running. I'll try it out once before deployment and push it in the next release :)

**Comment by ceoshikhar** [comment]
On it!
