### ISSUE TITLE
The exporting issue investigated

### ISSUE THREAD

**Issue by dbarenholz** [AmruthPillai/Reactive-Resume#487]
## Description
There is a CORS error when trying to export using the "Single Page Resume" or "Multi Page Resume" button **but only on an edited CV -- somewhat? Read the rest**.

**Related issues**:
https://github.com/AmruthPillai/Reactive-Resume/issues/484 https://github.com/AmruthPillai/Reactive-Resume/issues/483 https://github.com/AmruthPillai/Reactive-Resume/issues/452 https://github.com/AmruthPillai/Reactive-Resume/issues/438 (proof that self-hosting does not influence the behaviour!) https://github.com/AmruthPillai/Reactive-Resume/issues/409 (similar attempt at an overview of issues) https://github.com/AmruthPillai/Reactive-Resume/issues/402 https://github.com/AmruthPillai/Reactive-Resume/issues/399 https://github.com/AmruthPillai/Reactive-Resume/issues/383 https://github.com/AmruthPillai/Reactive-Resume/issues/361 

## Screenshots
![error-msg-UI](https://user-images.githubusercontent.com/25849034/116876466-cfc83b80-ac1c-11eb-842e-aae8128afdc3.png)
![error-msg-console](https://user-images.githubusercontent.com/25849034/116876093-3436cb00-ac1c-11eb-8eee-3a7a54fc6a48.png)

## Investigation notes
My initial thought was that this was a browser issue, however loading the default data in a brand-new CV on Firefox (not chromium based) and Edge (chromium based) both worked as expected, and downloaded the PDF. So, the issue is related to the **content** of the resume, in some way! 

I initially thought the issue was that the link to the image pointed to `firebasestorage` (what you get after uploading) as opposed to `imgur` - this does not turn out to be the case.

Next, I switched themes, and then exporting no longer works, and shows the things under Screenshots. 

HOWEVER: I thus expected following steps to be a minimal example of the issue;
1. Go to `https://rxresu.me/app/dashboard`
2. Create a new resume with some name (I called mine `new_fresh_CV`)
3. Open the newly created resume.
4. Click on the  "Load Demo Data" button (twice) to populate it with demo data.
5. Switch theme to Onyx.
6. Go to export > single page.

But for some reason this worked. Then, changing the image resulted again in the erroneous behaviour as shown under Screenshots.

I currently don't have more time to spare, and I can use the workaround (going to `https://rxresu.me/r/<resume-id>` and printing from there to PDF) so for me personally this is probably all time I will dedicate to this issue, but hopefully someone can pick this up seeing how Reactive Resume is BY FAR the best online resume builder I've used.

**Comment by gianantoniopini** [comment]
@dbarenholz Good investigation. I will look into this issue.

**Comment by dbarenholz** [comment]
Sorry to say, but this issue (at least on rxresu.me) has NOT been fixed. Will still be using the workaround I posted above. 

Please see below image for the error in the console when clicking on export > single page. 

![image](https://user-images.githubusercontent.com/25849034/120920026-05998d80-c6bd-11eb-8379-04b54bfc733a.png)

**Comment by gianantoniopini** [comment]
@dbarenholz Sorry to hear that the export is still giving you errors.
I've just tried the export (single page) using the app on rxresu.me (so not running the app locally) multiple times and it always worked for me. I've also tried changing template and using different images and again the export worked.
In order to try and reproduce the error, are you following the same 6 steps detailed in your first comment and then changing the image? If so, have you also perhaps tried uploading different images?

**Comment by dbarenholz** [comment]
I was not following the same steps as detailed in my first comment; I simply opened my resume and attempted to export, which resulted in a failure. I have since spent 3 hours on my Sunday afternoon and remade my CV with Figma so that I can more easily change things and export things. As such, I do not plan on further investigating this issue as I will no longer be using the tool!
