### ISSUE TITLE
Multipage Resumes do not have a header footer for page breaks

### ISSUE THREAD

**Issue by AyushG3112** [AmruthPillai/Reactive-Resume#497]
Sample:

<img width="524" alt="Screenshot 2021-05-23 at 1 48 21 AM" src="https://user-images.githubusercontent.com/21307931/119239790-f9fc8180-bb68-11eb-9c02-3c13be5de403.png">

I've tried multiple templates and they have a common issue that when the content breaks to the next page, there is no space for header and footer which looks weird.

**Comment by AyushG3112** [comment]
Seems to be caused by https://github.com/AmruthPillai/Reactive-Resume/blob/develop/src/styles/global.css#L65, which applies a global `0` margin to all prints.

**Comment by froilainhaeckse** [comment]
duplicates #467
