### ISSUE TITLE
[Bug] Resume Top Needs Fullscreen

### ISSUE THREAD

**Issue by felix-seifert** [AmruthPillai/Reactive-Resume#50]
**Describe the Bug**
If I go to the web app, I do not see the top of the resume (first few centimetres at the top). I could see nearly the whole page of the resume (scroll-able) when I switch to the full-screen mode of my browser.

**Reproduction**
Steps to reproduce the behaviour:
1. Go to https://rxresu.me/
2. Load demo data
3. Top of the resume is not visible (it is not possible to scroll to the top of the page)
4. Switching to full-screen mode makes it possible to scroll to the top of the resume
(Different templates have the same behaviour)

**Expected Behaviour**
I want to be able to scroll through the full resume in both modes. There is a bigger margin between resume and end of the page at the bottom. A Margin like this would be good at the bottom as well.

**Screenshots**

**Normal Mode**
![image](https://user-images.githubusercontent.com/41639203/78104215-5a8aa580-7421-11ea-9613-0cd3d5a9ba92.png)

**Full-screen Mode**
![image](https://user-images.githubusercontent.com/41639203/78104443-cf5ddf80-7421-11ea-8b50-c26063bf81a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tested in Chrome and Brave

**Comment by AmruthPillai** [comment]
This issue has been recognized, and I'm currently in the works on a solution where it would let you pan-zoom the artboard. Something that I wanted to implement from the very first day, but finally got the time to do it. Below is a video on how it works, maybe this would solve your issue?

![GIF on Pan & Zoom Feature](https://s5.gifyu.com/images/ezgif.com-video-to-gif4d91e7d8adee2c6d.gif)

**Comment by felix-seifert** [comment]
This sounds/looks good. Like this, also the unattractive second scrollbar of the resume section could get removed.
