### ISSUE TITLE
Make "Field of Study" optional.

### ISSUE THREAD

**Issue by kishanhitk** [AmruthPillai/Reactive-Resume#506]
First of all thanks to all the contributors for building and maintaining this amazingly helpful tool. 
### Context
There are many developers, whose Field of Study is not technical. Hence, not important when they are applying for tech jobs. And sometimes adding it to the resume can turn out to be a negative point on the resume. Therefore, it is better to keep this field optional.

### Current Behaviour
The "Field of Study" is mandatory inside the Education section.
![image](https://user-images.githubusercontent.com/41117038/120967304-ef570480-c784-11eb-83c4-f1fe4d95afbc.png)

### Suggested Behaviour
The "Field of Study" should be optional inside the Education sections.

### Assigning
If you also think that this should be done. Then, I will be more than happy to work on this issue.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
