### ISSUE TITLE
Question about running app

### ISSUE THREAD

**Issue by EverLookNeverSee** [AmruthPillai/Reactive-Resume#507]
Hello
first of all thank you for this wonderful app.
My question is that how can i run it on my local machine?

OS: Linux

**Comment by waqar-ahmed** [comment]
I just did it. Update your node version to latest. Install gatsby using cmd: 

> node install -g gatsby-cli

, and then run: 

> npm run start

Make sure you have firebase config.

**Comment by EverLookNeverSee** [comment]
Thank you @waqar-ahmed

**Comment by EverLookNeverSee** [comment]
I ran command above and got error below:
![error](https://user-images.githubusercontent.com/57490926/121777954-e5c90480-cba9-11eb-9e1c-ddfb956747bf.png)

**Comment by EverLookNeverSee** [comment]
@waqar-ahmed Could you please give me a hint to how to solve this problem?

**Comment by coreysnodgrass** [comment]
Hey @EverLookNeverSee 

`npm install`
`npm start`

source  - https://github.com/AmruthPillai/Reactive-Resume#readme

as far as your error, if you're trying to install gatsby globally, it's `npm install -g gatsby-cli` which would give you the command `gatsby` after install.

**Comment by EverLookNeverSee** [comment]
@coreysnodgrass 
![husky error](https://user-images.githubusercontent.com/57490926/127777655-cd2ca285-9ca7-40df-b26a-a704497c24f5.png)

**Comment by coreysnodgrass** [comment]
Looks like @AmruthPillai added an npm package called husky. I'd maybe delete the node_modules folder and maybe try to `git pull` along with `npm install`

@EverLookNeverSee

**Comment by EverLookNeverSee** [comment]
@coreysnodgrass Thanks
