### ISSUE TITLE
Use datastore other than firebase

### ISSUE THREAD

**Issue by waqar-ahmed** [AmruthPillai/Reactive-Resume#508]
Hi, Thank you for making this great project.

I would like to ask, is it possible to abstract datastore so one can switch from firebase to mysql easily? or could you please point to the place where the changes can be made to use mysql instead of firebase?  Thank you.

**Comment by FlynnLives** [comment]
I agree

"No advertisements, no data sharing, no marketing emails" yet, you rely on a Google service, even sqlite would be fine

**Comment by modem7** [comment]
sqlite would also be useful to resolve these firebase API issues in the docker version ala #430

**Comment by DieterKoblenz** [comment]
Yes, this would be great change. I don't want it to be dependent on a Cloud service. Firebase is great voor large scale resume websites. I just want to use it for a couple of personal ones.

**Comment by ParaplegicRacehorse** [comment]
+1 this.

I want to self-host and avoid putting my data in a Google datacenter.

MariaDB, Postgresql, sqlite; all good options.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
