### ISSUE TITLE
Glalie.js calls ReferencesA.js even if only one reference is provided.

### ISSUE THREAD

**Issue by mrinmaydhar** [AmruthPillai/Reactive-Resume#509]
[Calling](https://github.com/AmruthPillai/Reactive-Resume/blob/79c903f02d856edff99e8b0d00eb07c44c5b9b2c/src/templates/Glalie.js#L13) [ReferencesA](https://github.com/AmruthPillai/Reactive-Resume/blob/79c903f02d856edff99e8b0d00eb07c44c5b9b2c/src/templates/blocks/References/ReferencesA.js#L24) over [ReferencesB](https://github.com/AmruthPillai/Reactive-Resume/blob/79c903f02d856edff99e8b0d00eb07c44c5b9b2c/src/templates/blocks/References/ReferencesB.js#L24) causes problems. If only one reference is provided, the block occupies the first grid only and take up vertical space, rather than dynamically using the available horizontal space.

Recommend using an alternate method for grid numbers based on number of references as input (rather than using grid-cols-_n_). Don't know much about NPM and thus errors are creeping up when I try to start a local server for testing ~(cannot find Database URL in firebase config).~ Just needed to initiate Realtime database before creating app.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
