### ISSUE TITLE
Celebi Template image adjustment

### ISSUE THREAD

**Issue by shukla567priya** [AmruthPillai/Reactive-Resume#511]
I wanted to create the resume in Celebi template but image is cropped from the head. Hence, either the option to adjust the picture should be given or simply auto-adjust it.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
