### ISSUE TITLE
doesn't create new resume

### ISSUE THREAD

**Issue by gpopesc** [AmruthPillai/Reactive-Resume#515]
I managed to build the docker version and login into my account.
I have setup also the reverse proxy for it in order to have a secure link.
Then when I press Create resume, nothing happens and stay on the same screen.

I have added in my docker compose file my PUID, PUIG, without any luck.

I suppose it is a matter of access rights access, but I don't have any clue as long I don't get any error.

![Capture](https://user-images.githubusercontent.com/11590919/122575908-db9b8000-d059-11eb-9c0f-296418293f8c.JPG)

docker log is clean:

192.168.1.100 - - [18/Jun/2021:17:17:52 +0300] "GET /page-data/index/page-data.json HTTP/1.1" 200 142 "https://mydomain.com/app/dashboard" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "109.97.39.194, 162.158.90.43"

192.168.1.100 - - [18/Jun/2021:17:19:34 +0300] "GET / HTTP/1.1" 200 148360 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "109.97.39.194, 162.158.89.206"

192.168.1.100 - - [18/Jun/2021:17:19:35 +0300] "GET /page-data/sq/d/3924866898.json HTTP/1.1" 200 3225 "https://mydomain.com/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "109.97.39.194, 162.158.89.206"

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
