### ISSUE TITLE
Editing block sizes

### ISSUE THREAD

**Issue by MahboobMMonza** [AmruthPillai/Reactive-Resume#521]
Allow users to edit the block size of the templates to allow for slightly better text fitting? Prevents cutoffs on text for something like the email.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
