### ISSUE TITLE
Not able to upload JSON file 

### ISSUE THREAD

**Issue by cibbin** [AmruthPillai/Reactive-Resume#525]
Downloaded the copy of a resume i created using this app in JSON format, and tried upload the JSON file to the React Resume app on another computer and it wont open.

**Comment by stfkolev** [comment]
Would the same thing happen on the same computer?

**Comment by cibbin** [comment]
Yes it does.

-------- Original Message --------

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
