### ISSUE TITLE
Clicking on any hyperlink in edit mode appends link to current URL when opening in new tab

### ISSUE THREAD

**Issue by sujaisubbanna** [AmruthPillai/Reactive-Resume#529]

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
