### ISSUE TITLE
Import function not working

### ISSUE THREAD

**Issue by Vinod-Romina** [AmruthPillai/Reactive-Resume#531]
Hello Team,

I like your resume builder website very much and I  want to highlight the issue that I came across. Few days back I created sample resume and downloaded on my drive. Today, I wanted to edit the resume but import feature is not working. I selected both file types i.e pdf and docx and your website is not uploading my files due to which I can't edit my resume. 

It would be great if you fix this issue as I don't want to create new resume again.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
