### ISSUE TITLE
Pikachu Template: Highlighted Name & Objective section does not grow as text increases

### ISSUE THREAD

**Issue by coreymunn3** [AmruthPillai/Reactive-Resume#532]
I had Name, Role, and Objective in that top section and when I put a second sentence on my Objective, the last line got cut off. Maybe this was intentional (to force users to keep the objective short) but I feel I should be able to have a large text size and a long sentence fit into the section without getting prematurely cut off.

As a resume creator, I would like the top section of the pikachu template that contains the name and objective to resize automatically as text increases.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
