### ISSUE TITLE
Issues while Exporting

### ISSUE THREAD

**Issue by PradipMugithe** [AmruthPillai/Reactive-Resume#533]
Hello,

I appreciate your work and very much impressed with it.I edited one template and while exporting it as PDF in single page it's poping out error box and same with multi pages export option as well.

Please look into this.
Thanks and Regards,
Pradip

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
