### ISSUE TITLE
There could be a control to adjust the vertical spacing between sectors

### ISSUE THREAD

**Issue by LucasFebatis** [AmruthPillai/Reactive-Resume#534]
I was thinking of something like it already has in font size, with a slide that can be dragged to the sides, but that modifies the spacing between sectors

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
