### ISSUE TITLE
The application is stuck after giving a name and clicking on "create resume" button.

### ISSUE THREAD

**Issue by gokulkuppan** [AmruthPillai/Reactive-Resume#535]
The application is stuck after giving a name and clicking on "create resume" button.
**Create Resume button changed to Loading.. and nothing happens.**

![image](https://user-images.githubusercontent.com/82102648/125794966-3322cd32-5e53-45cf-9d69-2383f05759eb.png)

**Comment by AmruthPillai** [comment]
Which browser are you using?

**Comment by gokulkuppan** [comment]
I have tried with most of the browsers like Chrome, Firefox, edge & IE.

**Comment by gokulkuppan** [comment]
Issue is with my office laptop.. may be firewall is blocking.

**Comment by glubsy** [comment]
I have experienced the same issue. 

There is a request to `https://source.unsplash.com/featured/400x600`. When the site is down (and it is down right now), the request fails there is an uncaught exception raised from getUnsplashPhoto().
