### ISSUE TITLE
3 suggestions on size and adding pictures

### ISSUE THREAD

**Issue by thomasbrcht** [AmruthPillai/Reactive-Resume#536]
Hey, 
Awesome tool. I have 3 suggestions, and one remark

1) I would love to zoom out or zoom in to get a general and detailed view of my resume
2) the right and left side bars of the designing tool are not very convenient: it would be great if I could make them smaller
3) I would like to add little logos of the companies next to their name, to give the employer a visual of well-known companies (like the colored G for google)

1) my profile pic changes elongates or shrinks when I change the canvas: would it be possible to lock the proportions?

Great job!

**Comment by preetamm** [comment]
I have done something for the 2nd suggestion, as the left and right are divided into 2 components, (sidebar and navbar) example - left side is divided into leftSideBar and leftNavbar. so to improve the user experience I have made a button to toggle the navbar component. after toggling the center component which is the resume component gets bigger and the user can preview in a large view.

screenshot - 
![Screenshot (16)](https://user-images.githubusercontent.com/34884487/127806060-c0fb4dfa-06f7-4e63-aa5a-c9a8dea5a2dd.png)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
