### ISSUE TITLE
cloud function not working

### ISSUE THREAD

**Issue by aman825** [AmruthPillai/Reactive-Resume#537]
when i tried to generate pdf, it showed cloud function not working

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
