### ISSUE TITLE
Website navigation issue

### ISSUE THREAD

**Issue by santhoshsivanb** [AmruthPillai/Reactive-Resume#538]
When I provide website without https:// or http://  when clicking the website in resume it is navigating to rxresu.me address.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
