### ISSUE TITLE
Regarding Current Company

### ISSUE THREAD

**Issue by Gaurav1115-dev** [AmruthPillai/Reactive-Resume#539]
There should be an option saying that Presently you are working here .

**Comment by Gaurav1115-dev** [comment]
Let's say suppose we are currently working in present company there is no option saying that presently working here

**Comment by andrewchumchal** [comment]
If you leave the end date blank. It should automatically do it.

![image](https://user-images.githubusercontent.com/8008169/126886946-3d2e87c2-12ea-4d0b-a9be-4b05889e6b0f.png)

![image](https://user-images.githubusercontent.com/8008169/126886947-e35a78aa-3e6d-470f-bbee-f7f51621d55f.png)

**Comment by Gaurav1115-dev** [comment]
Working fine .Thanks

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
