### ISSUE TITLE
Award and the awarder's name are crossed over in exported resume - 2 pages Pikachu format 

### ISSUE THREAD

**Issue by anupamsaurabh4u** [AmruthPillai/Reactive-Resume#540]
1. Choose Pikachu Format with below layout

BLOCK 1 - Skills, Languages, Certifications, Awards, Hobbies, Education
BLOCK 2 - Work Experience, References, Projects

2. Fill in enough details such that the award section starts from very bottom,
3. Try to extract the resume in 2 page layout - you get a cross overs between the award name and the awarder's name.

![image](https://user-images.githubusercontent.com/86166410/126956903-be450f76-20c7-4b1f-abb6-114476e52326.png)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
