### ISSUE TITLE
Start and end dates for experience section can have only month and year as mandatory

### ISSUE THREAD

**Issue by anupamsaurabh4u** [AmruthPillai/Reactive-Resume#541]
Duration of a particular job are usually quantified with month and year, as such having a exact day as mandatory is not required and it's tough to remember the dates . Moreover, the final output on the resume is only in terms of month and year, so that should only be asked. - Not sure if there's a react's restriction for that. If you do not provide the day - term duration is not displayed

![image](https://user-images.githubusercontent.com/86166410/126958322-283f195c-f393-460b-bb5a-061d72a9a47e.png)

![image](https://user-images.githubusercontent.com/86166410/126958373-1f9d03ad-7258-42b0-ac2f-fe656ca69179.png)

**Comment by stfkolev** [comment]
You could easily specify a relative date to when your employment was on. That would show the month itself. It sure has some complications and it's better to stay this way, rather than randomly choosing a date in the month.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
