### ISSUE TITLE
Option to delete individual entry in "Work Experience" does not prompt for confirmation of deletion

### ISSUE THREAD

**Issue by alarsama** [AmruthPillai/Reactive-Resume#542]
Hello!

The option to delete an individual entry in "Work Experience" does not prompt for confirmation of deletion. This does not help when the "delete" button is located right next to the "edit" button. An accidental swipe and tap when attempting to click "edit" can delete hours of work. This actually just happened to me, and there is no way I have found to restore what was deleted with something like cmd+z or ctrl+z. Can a prompt please be added for deletion of anything?

Additionally, if you could advise me on how to restore resume content that was accidentally deleted, I would be very grateful.

<img width="377" alt="Screen Shot 2021-07-27 at 9 58 43 PM" src="https://user-images.githubusercontent.com/10385431/127266208-fe42499b-aa8b-4829-9e13-1ba545200050.png">

Best Regards,
Alan

**Comment by preetamm** [comment]
Heyy @alarsama thank you for your feedback, we have worked on the issue, you will see the update soon :)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
