### ISSUE TITLE
[i18n] Date formatting, month names on resume

### ISSUE THREAD

**Issue by kescherCode** [AmruthPillai/Reactive-Resume#544]
Currently, month names and date formats are forced to a single English format on the resume.

Therefore, date formats and month names might need to be picked up into the localization file.
For instance, in the German language, for instance, formatting dates on the for DD.MM.YYYY is common. Therefore, the missing dots in the birth date, as well as the month name being in English is odd when the rest of the document is in German.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
