### ISSUE TITLE
Can't Export in anyway other than JSON

### ISSUE THREAD

**Issue by Dikshit28** [AmruthPillai/Reactive-Resume#546]
The resume is not exporting tried single-page, multiple pages and the browser print just cuts the information

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
