### ISSUE TITLE
user should able to add more custom section like "objectives"

### ISSUE THREAD

**Issue by sefatanam** [AmruthPillai/Reactive-Resume#550]
Because sometimes need to add personal talks like "What I want", "Extra Activites" which are not part of objectives or work experience . Please consider this. Thanks

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
