### ISSUE TITLE
Unable to import json resume

### ISSUE THREAD

**Issue by codefeast** [AmruthPillai/Reactive-Resume#552]
Thanks for the wonderful website.  Noticed that I first logged in anonymously, prepared a resume, exported it as a pdf and json. Later i switched to login via my google account and attempted to import the json resume. The  screen went black for a while and nothing happened. Hence reporting this.  Is there a work around to get back to having my prepared resume on my google account or need to fill in everything from scratch.
Thank you.

**Comment by haydar** [comment]
@codefeast  I had same issue today. I opened Chrome console and noticed there is an issue with js. 
![image](https://user-images.githubusercontent.com/6452942/129275496-d088bcbc-0376-49f6-9b16-4ca8c1dfd959.png)

I don't guess this is won't be fixed quickly. I suggest filling again.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
