### ISSUE TITLE
Linked in link in incorrect

### ISSUE THREAD

**Issue by codefeast** [AmruthPillai/Reactive-Resume#553]
The linkedin link is prepended with a rxresume link and hence renders itself incorrect. Can you please fix that. Thank you.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
