### ISSUE TITLE
Possibility to put "Present/Till now" in the end date of experience or education

### ISSUE THREAD

**Issue by SidouMania** [AmruthPillai/Reactive-Resume#554]
Hi, 

Is it possibe to put "Present/Till now" in the end date of experience or education ? Because for exemple we can add a job that we are still living of. 

Thank you for the great app !

**Comment by pronoym99** [comment]
I realised that if you don't put the end date it simply marks it as **Present**. Hope this helps.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
