### ISSUE TITLE
Pics in CV

### ISSUE THREAD

**Issue by pedroamaralm** [AmruthPillai/Reactive-Resume#555]
Hey,
I'm using rxresu.me and I like it, it's fantastic and very good. But it turns out that all the templates were created with a profile photo and if the user doesn't want to use a photo in it he will be totally misconfigured, are there templates that don't need a photo?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
