### ISSUE TITLE
Import not working with any of the given option and export is loading old data which I entered 2 days back.

### ISSUE THREAD

**Issue by Happyrajsinh** [AmruthPillai/Reactive-Resume#556]
So basically it has issues in both export and import

**Comment by shols232** [comment]
Yeah, having this issue for some days now, trying to import in json or pdf file fails, importing a rxresume fail yields `Uncaught SyntaxError: Unexpected token % in JSON at position 0` error in the console. and importing in json format yields a `TypeError: p.work.map is not a function` error in the console.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
