### ISSUE TITLE
Additional Link being added as a prefix to Social Media url

### ISSUE THREAD

**Issue by shifaaz** [AmruthPillai/Reactive-Resume#557]
When adding social media, such as linkedn and the url. When you click the link in the CV, the prefix "https://rxresu.me/app/builder/ACTUAL URL HERE" is added. When this is linked, it does not route to the actual social media link, but it just routes the rxresu.me

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
