### ISSUE TITLE
Resume is not downloaded Properly

### ISSUE THREAD

**Issue by Gaurav1115-dev** [AmruthPillai/Reactive-Resume#558]
Step:1 Export The Resume in Json Format 
Step2: Try to modify something on Resume
Step3 : select single page or Multi Page
Step: 4 Go to Print resume and try to print this resume.
Step: 5 Some fonts and data is not fitting properly on to the page.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
