### ISSUE TITLE
Option to create more sections

### ISSUE THREAD

**Issue by jhgalino** [AmruthPillai/Reactive-Resume#560]
It would be really nice if we can add more sections in case that we need to write more things in resumes

**Comment by pronoym99** [comment]
Yes...even I was looking for the same. Any leads?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
