### ISSUE TITLE
Firestore support

### ISSUE THREAD

**Issue by n-sviridenko** [AmruthPillai/Reactive-Resume#562]
Guys, first of all, thank you for creating this tool. It's amazing!

Ok, so now is the point. It'd be great to support firestore as the realtime database is a legacy thing. Thanks.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
