### ISSUE TITLE
A problem and some suggestion

### ISSUE THREAD

**Issue by hackingraphics** [AmruthPillai/Reactive-Resume#563]
The bug that I have found is with the Celebi template, when I placed the skills tab in block one it seems to get cut off.

The suggestion is the option of adding multiple job positions under one company [Example of this can be seen on page 10 of this pdf.](https://sha.cornell.edu/wp-content/uploads/sites/4/2019/04/ResumeGuide2012-13.pdf)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
