### ISSUE TITLE
Add some dials / graphs on templates

### ISSUE THREAD

**Issue by theendless22** [AmruthPillai/Reactive-Resume#564]
Hey ! Thanks for this awesome builder, really very helpful. Would love to see the addition of some dials / graphs that can be used to showcase skills and expertise.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
