### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by kumarnipun** [AmruthPillai/Reactive-Resume#565]
Unable to import resume. Nothing happened when I select file to import.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
