### ISSUE TITLE
Need to add Professional Summary section

### ISSUE THREAD

**Issue by PriyankaPoojari** [AmruthPillai/Reactive-Resume#566]
Need to add Professional Summary section. Is there any option to add new Section?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
