### ISSUE TITLE
Black screen(env variables DO NOT help)

### ISSUE THREAD

**Issue by themaster567** [AmruthPillai/Reactive-Resume#567]
I use Docker on Debian 10, running the latest version of RR.

There have been many people confused about how to get this up and running, as unlike almost any other selfhosted project, it uses Firebase. That wouldn't be a problem except for the developer not giving clear instructions on how to properly set it up. Even IF you manage to figure out that in order to get the proper env variables you need to specifically create a web app in addition to the realtime database, you may end up in may case where they still don't work for unknown reasons. 

This is compounded by the fact that RR does not appear to output any sort of error logs, I have no choice besides blindly flailing about.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
