### ISSUE TITLE
how to add currently working

### ISSUE THREAD

**Issue by atulsh1983** [AmruthPillai/Reactive-Resume#568]
Every time need to update the end date

**Comment by HristovCodes** [comment]
If you leave the end date empty it will just say _present_ as in you are still working there.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
