### ISSUE TITLE
Project doesn't run at all.

### ISSUE THREAD

**Issue by HristovCodes** [AmruthPillai/Reactive-Resume#569]
Tried both a clean install and normal install (which changes the package-lock due to different npm versions).
After installing all the packages and running `npm run start` or `npm run build`  I get the following errors after which the script just exists and can't finish.

```
 ERROR #11321  PLUGIN

"gatsby-plugin-webfonts" threw an error while running the onPreBootstrap
lifecycle:

getaddrinfo EAI_AGAIN fonts.googleapis.com



  Error: getaddrinfo EAI_AGAIN fonts.googleapis.com
```

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '/.cache/webfonts/webfonts.css' in
'/home/ivailo/Reactive-Resume/node_modules/gatsby-plugin-webfonts'

If you're trying to use a package make sure that '/.cache/webfonts/webfonts.css'
 is installed. If you're trying to use a local file make sure that the path is
correct.

File: node_modules/gatsby-plugin-webfonts/gatsby-ssr.js:24:39
```

And the [whole log](https://gist.github.com/HristovCodes/c46f6b8570c36aaa4990b3e7fbc1edaa) if it's required.

I tried my best at debugging the issue and fixing it myself but I'm out of ideas and this is why I'm posting the issue.
I was able to build the project just fine a few months ago (on Windows now on Linux so that might be why) but after doing a merge on my fork and pulling it, it just fails to build.

Editing to add that I also tried building with docker and that also fails with roughly the same log, just takes more time because it's well docker.

**Comment by HristovCodes** [comment]
From my understanding the problem is with the link "gatsby-plugin-webfonts" is using. Looking at it's source it uses fonts.googleapis.com which not valid anymore, the actual link is fonts.google.com now.

I could be totally wrong but this is the first thing I noticed and wanted to mention it.

**Comment by HristovCodes** [comment]
Switching the package to _gatsby-plugin-web-font-loader_ fixes it.
Both package do the same exact thing but the implementation is different and this one works for me. If anyone else is encountering the same issue it might be worth switching over to [web font loader](https://www.gatsbyjs.com/plugins/gatsby-plugin-web-font-loader/?=fonts#gatsby-plugin-web-font-loader).

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
