### ISSUE TITLE
Header is not available

### ISSUE THREAD

**Issue by nirjhar17** [AmruthPillai/Reactive-Resume#572]
Hi Team,

1. There is no option to add a header. So there is an issue while downloading the multipage resume. Some lines are not properly aligned.
2. There is an issue while putting the address in the first Block. it is adding on both sides on the right-hand side as well left-hand side under the name.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
