### ISSUE TITLE
Issue with Export

### ISSUE THREAD

**Issue by RAMESSESII2** [AmruthPillai/Reactive-Resume#576]
Every time I'm trying to export the resume either with the single-page or multi-page resume option, I get the following message-"Cloud function is running into some trouble......". This also means that any changes int the resume is not being saved as well.
![image](https://user-images.githubusercontent.com/54385449/138544645-61f36f8f-cd26-4743-b132-9417e600e431.png)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
