### ISSUE TITLE
Allow Lists (markdown?) under the Skills Section

### ISSUE THREAD

**Issue by NoName95x** [AmruthPillai/Reactive-Resume#584]
Hi,

It would be nice if you could allow lists underneath the Skills section. 
For example, allowing a list underneath a **AWS** section could let you categorize skills by type of service they provide.

ie

**AWS**

- **CI/CD**: Cloudformation, blah blah, foobar
- **AI**: Sagemaker, AI tool here, etc.
-

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
