### ISSUE TITLE
Support justified / aligned text in markdown areas

### ISSUE THREAD

**Issue by 3v1n0** [AmruthPillai/Reactive-Resume#585]
It's currently not possible to justify or align the text in markdown areas, while it could be nicer to show longer descriptions in such way.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
