### ISSUE TITLE
URLs for Work Experience entries

### ISSUE THREAD

**Issue by pratclot** [AmruthPillai/Reactive-Resume#588]
Hello!

Wanted to say a BIG THANK YOU for the app, I absolutely loved it and it boosts my morale while applying to new positions immensely.

Noticed that I cannot get the links for the companies I worked for displayed. Each place has a website, but then it is not appearing anywhere on the resume. I use the Pikachu template, and there are no URLs, but also switching to other templates with the same data did not solve it. Checked with the demo data and it was the same too.

Is there something I am doing wrong maybe?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
