### ISSUE TITLE
Hi, i was trying your app and i can't found scroll bar (for exemple, when i want to fill in the line website). That's all I wanted to say, thanks)

### ISSUE THREAD

**Issue by ghost** [AmruthPillai/Reactive-Resume#59]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.  
Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by felix-seifert** [comment]
The scrollbars of the two different sections at the side are not visible. Nevertheless, scrolling and the pan-zoom works. However, what about scroll bars which appear when you hover a certain section? Like this, it would be more apparent for users to see that scrolling is possible. Furthermore, this bar could be used in case the scrolling function of the screen/touchpad/mouse does not work.

**Comment by AmruthPillai** [comment]
The scrollbars are not visible, but everything is still scrollable. This has been tested on all devices, even on desktops with mice, so interactivity shouldn't be an issue. For accessibility, that's a different issue that I will definitely look into. I would want the app to be usable by everyone, so will make it easier for screen readers to use as well in the future.
