### ISSUE TITLE
skills shell should be change

### ISSUE THREAD

**Issue by Pujandave** [AmruthPillai/Reactive-Resume#591]
skill shell set skills with each other in one line . it should be in like bullet formet or in line one after another .

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
