### ISSUE TITLE
Single page/ Multi page download options not working

### ISSUE THREAD

**Issue by ajfuturistics** [AmruthPillai/Reactive-Resume#593]
Everytime I try to download pdf I am having this issue "The cloud function is running into some trouble, please try again later or use the browser print feature." And in console it shows CORS issue

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
