### ISSUE TITLE
Feature Request: Add option to add location of organization

### ISSUE THREAD

**Issue by SugamKhetrapal** [AmruthPillai/Reactive-Resume#594]
Hi Amruth,

Your app is really awesome. It is the best resume software I have come across and I use it whenever I need to create/update my resume.

I just wanted to request you to please add a feature in the Reactive Resume.

Currently the option to add the location of the organization is not available in the software.

In case it is possible and in case you can spare some time, may I request you to please add a feature which enables us to add location of the organization in the resume.

Thank you!

Regards,
Sugam Khetrapal

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
