### ISSUE TITLE
How to customize font 

### ISSUE THREAD

**Issue by TENX-S** [AmruthPillai/Reactive-Resume#595]
The 8 fonts offered are not friendly to Chinese. Is there any chance I can use my local font and run it?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
