### ISSUE TITLE
Unable to setup project locally

### ISSUE THREAD

**Issue by targhs** [AmruthPillai/Reactive-Resume#596]
Getting issues with configuration file.
I already have .env file filled with values but when trying to login it says "Configuration not found".

It works sometimes on refresh but then it says Invalid api key but i have checked it multiple times and its exactly the same provided by Firebase

**Comment by sachhu** [comment]
![image](https://user-images.githubusercontent.com/31276964/150297185-1f0e8a0e-4fd7-4a7c-a5ab-8207917cc064.png)

Go to authentication section in firebase and add google and anonymous in sign in method.
