### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by karraakhilreddy** [AmruthPillai/Reactive-Resume#597]
Awesome project. Really in love with this.

Just need two features as follows

-  Feature to change  of text Alignment (left, center, and right)
- Padding and Margin to the section selected

This is really great work and helps a lot of people.

Regards,
Akhil

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
