### ISSUE TITLE
Updated resume downlode problem

### ISSUE THREAD

**Issue by Subhadipmahapatra98** [AmruthPillai/Reactive-Resume#598]
When i am updated and want to downlode the resume that not updated old resume was downloded

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
