### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by sakshamgoyal01** [AmruthPillai/Reactive-Resume#60]
Not sure if this is a problem with this website or just how chrome works. But, when I try and print my final resume, in the header and footer of the pdf (print to pdf), I get the link to the resume builder website and page number (1/1) as well as the date. Changing the printer does not help. 

What can I do to remove this? 

Edit: This is what it looks like:
![image](https://user-images.githubusercontent.com/19929553/78193419-178bfa80-7440-11ea-94f1-02a67fe74477.png)

**Comment by AmruthPillai** [comment]
The app has now moved from the regular printing of the page system to exporting generated PDFs, so the Ctrl + P method is not really supported anymore. Instead, you could go to the Actions Tab and click on Save as PDF, or click on the Save button in the Floating Bar below. Please let me know if that helps, thank you :)

**Comment by sakshamgoyal01** [comment]
perfect! that worked beautifully
