### ISSUE TITLE
Individually edit and reformat parts of the resume

### ISSUE THREAD

**Issue by MahboobMMonza** [AmruthPillai/Reactive-Resume#600]
Hi, I love your Reactive Resume app, but I found some issues that hinder my capability to make an outstanding resume. Using the Onyx layout, my address information comes out twice, which is unnecessary. Further more, I found that my professional email address is too long to be posted beside the email icon and ends up spanning two lines, being split at an inconvenient location. However, if the icons could be shifted just a little bit over to the left I could easily make it one line. if you could consider making these changes it would be greatly appreciated.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
