### ISSUE TITLE
Lost Letters and Whacky Text Conversion

### ISSUE THREAD

**Issue by zaptrem** [AmruthPillai/Reactive-Resume#605]
When copying and pasting from the generated PDF some series of letters like fi, ll, and others are lost, resulting in blanks or unrecognized character symbols. Also, when certain ATSes like Avature convert the multi-column PDFs to text the result is an unintelligible mush of words.

**Comment by zaptrem** [comment]
How does text embedding in PDFs currently work? Could you explicitly define text boxes and their contents so ATSes can understand them better? Alternatively, make all text vector only and have a hidden text box with the entire plaintext version of the resume nicely laid out for extraction.

**Comment by zaptrem** [comment]
@AmruthPillai here's the solution to the missing characters issue (quite simple!) https://github.com/puppeteer/puppeteer/issues/4125

The text box issue is arguably more significant, though, due to the aforementioned ATS optimization problem.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :) Thank you!
