### ISSUE TITLE
Can`t download resume

### ISSUE THREAD

**Issue by Unclevladik** [AmruthPillai/Reactive-Resume#608]
https://rxresu.me/app/builder/a6zqfh

![image](https://user-images.githubusercontent.com/94788024/150765520-40e9fd46-1f0f-46fb-bff1-5febca16f7f4.png)

**Comment by sbkg0002** [comment]
Same problem here with HEAD of today. Thus on a docker-compose instance.

**Comment by AmruthPillai** [comment]
@Unclevladik I was able to download the PDF of your resume just fine. I understand that the docker instance might not be perfectly working right now, but the website is still running on the last working version.

[RxResume-a6zqfh.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/7937663/RxResume-a6zqfh.pdf)

**Comment by Unclevladik** [comment]
Hi, sorry for the temporary inconvenience, I’ll drop you a PDF form of my
resume .

Ср, 26 янв. 2022 г. в 00:36, Amruth Pillai ***@***.***>:

**Comment by Unclevladik** [comment]
sorry again
something was wrong with the website yesterday

ср, 26 янв. 2022 г. в 12:09, Влад Буркалец ***@***.***>:

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :) Thank you!
