### ISSUE TITLE
Same date displayed twice

### ISSUE THREAD

**Issue by Stan-librarian** [AmruthPillai/Reactive-Resume#612]
Hi,

This is great app for easily creating good-looking resume. Thanks a lot!

I noted a few issues, but most of them are known yet :
- the problem of website URL when you don't specify the prefix http (#307)
- the problem of mandatory day in date fields (#541 and others)
- the need for custom sections (#238 and others)

However, I didn't see anything about this:

in "Education" or "Work Experience", only month and year are displayed. But if start date and end date are in the same month, it displays for example (December 2019 - December 2019)

In this case, wouldn't it be preferable to display only one occurence of the date ? eg: (December 2019)

![2022-02-01 16_44_00-Greenshot](https://user-images.githubusercontent.com/24322625/152000988-d0f93fa5-318d-41ff-9e80-5daaa7ef23d8.png)

Also, the printing by the brower doesn't work at all for me (with template pikachu): the second block is truncated after a few letters, and no print settings change that. However, the native PDF export works well, so this is not very important...

![2022-02-01 16_37_45-Greenshot](https://user-images.githubusercontent.com/24322625/152000614-33d6e447-095b-4388-b875-7204733ce971.png)

Finally, when you switch from one language to another and back, it can happen that custom section names come back to legacy name. I had it for "Distinctions" and"projects". Strange, even though few users may be concerned...

Thanks again for your work.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :) Thank you!
