### ISSUE TITLE
Support for æøå (Norwegian letters)

### ISSUE THREAD

**Issue by Br0stein** [AmruthPillai/Reactive-Resume#619]
Trying to create a resume  in Norwegian becomes a problem when trying to display æøå

![bilde](https://user-images.githubusercontent.com/55747312/153284439-ee4958f4-86f3-4ee3-acc9-019b46a5d942.png)

Thanks for the cool app!!

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :) Thank you!
