### ISSUE TITLE
[Feature] Overlay to Show Possibility to Use Pan-zoom

### ISSUE THREAD

**Issue by felix-seifert** [AmruthPillai/Reactive-Resume#62]
**Is your feature request related to a problem? Please describe.**
#54 introduced a new function for using a pan-zoom function for the resume. For users it is not that apparent that the UI allows to use this function.

**Describe the solution you'd like**
Possibly, an overlay over the mid-section with arrows might help users to recognise the possibility to use the pan-zoom. This overlay could disappear after a short while or the first time the user enters this field with his/her cursor.

**Comment by AmruthPillai** [comment]
This is actually a very smart idea, something that could indicate to the user that he/she could move around the artboard. I'm thinking, some kind of animated GIF in the centre of the screen? Will definitely look into it and get it implemented as soon as possible, thanks for the feedback :)

**Comment by AmruthPillai** [comment]
@felix-seifert I haven't been able to find any animation or image that can depict this action, could you point me in the right direction on where I could find stock images like these? Have you come across this animation in any other website before?

**Comment by felix-seifert** [comment]
I came across an image for this before but I cannot remember where. However, I found an [icon online which you could use](https://www.iconfinder.com/icons/594413/control_magnifier_move_options_pan_tilt_zoom_icon) (you have to buy this).
I created a simple image how this could be used. This should not be meant as a version how should finally look like, just an idea. For example, the options at the bottom could disappear while this overlay is active.
![2020-04-05_RxResume Panzoom Icon](https://user-images.githubusercontent.com/41639203/78466417-76e55580-7733-11ea-8500-f54e777c9c9b.png)

**Comment by AmruthPillai** [comment]
Thank you for the suggestion, this has now been implemented :) To get the animation, I made my own using the original design and animated it using Figmotion on Figma.
