### ISSUE TITLE
Add issue templates to get more information

### ISSUE THREAD

**Issue by SelfhostedPro** [AmruthPillai/Reactive-Resume#626]
Hey, I was browsing this project (thank you by the way, résumés from this project have helped me land my past 2 jobs) and went to look at the issues and was very surprised at the lack of information people are providing. 

I think setting up issue templates may help get more information so you’ll get issues that you can actually do something about. 

The docs are here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

I am using them in my repo if you want to see the average amount of information I get: https://github.com/selfhostedpro/yacht

Thanks for making such a great tool!

**Comment by AmruthPillai** [comment]
I was just thinking about doing this before releasing the new version. Thank you for the links and link to your repository where I can see it in action. Will definitely implement these in the upcoming days.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :) Thank you!
