### ISSUE TITLE
Posgress SLL on local `V3` deployment 

### ISSUE THREAD

**Issue by martadinata666** [AmruthPillai/Reactive-Resume#630]
Can we get / disable SSL on postgres connection?

**Comment by AmruthPillai** [comment]
It's still actively in development, so I would ask to please not open any issues on `v3` as of yet :)
I'm trying to make SSL optional for sure as I'm sure many self-hosted options won't require SSL certificates. Will definitely be as user-friendly as possible when it's completed.

**Comment by martadinata666** [comment]
I see, thanks for the fast response. Just pretty curious to try but blocked by SSL postgres. Good work as always.
