### ISSUE TITLE
Feature Request: Add Download as PDF button on shared Resume page

### ISSUE THREAD

**Issue by andy-vdg** [AmruthPillai/Reactive-Resume#632]
It would be awesome if the same functionality to export as PDF was available as a button on the shared Resume page.

GIVEN I want to add download links to my online resume. 
WHEN I turn on new "Add download links to resume" slider under the "Share Resume" section
AND I open the shared Resume link
THEN a buttons should appear on the top right of the resume page "Download as PDF (Single Page)"
AND a button should appear on the top right of the resume page "Download as a PDF (Multi-page)"

GIVEN someone views my online resume and wants to download it as a PDF
WHEN someone clicks on the "Download as PDF (Single PAGE)"
OR someone clicks on the "Download as PDF (Milti-page)"
THEN the same function should be called as is used for Export as PDF in the control panel.

**Comment by AmruthPillai** [comment]
Thank you for the issue.

This has been implemented in v3, please stay tuned for updates on the repo :)
