### ISSUE TITLE
Info required in .env file for docker

### ISSUE THREAD

**Issue by esturniolo** [AmruthPillai/Reactive-Resume#636]
Hi! First thing first: Thanks for continue develop this and add an native docker option.

I see that the env file has this:

```
# Google
PUBLIC_GOOGLE_CLIENT_ID=change-me
GOOGLE_CLIENT_SECRET=change-me
GOOGLE_API_KEY=change-me
```

What kind of info should I complete here? The firebase thing?
I see that isn't optional.

Same with JWT.

And there is no way to use the service anonimously as the last version?

Thanks!

**Comment by AmruthPillai** [comment]
The Google Client ID and Client Secret are just for Google Login functionality. If you would like to deploy the app without google login, it is completely fine to skip over these.

The `GOOGLE_API_KEY` is for the Google Fonts functionality within the resume which is a required field. It is fairly easy to get an API key from Google and the fonts fetching service will cost absolutely nothing.

JWT_SECRET is indeed necessary for the working of authentication.

I will create a documentation site which outlines the importance of what env vars are required and what aren't. Thank you for the insightful question :)

As for the anonymous feature, you should be able to create an account with username/email/password but feel free to use a fake (or temporary) email address if you don't feel like providing your personal email. The app does not verify emails, so you can enter anything you want. But you would not be able to use the Forgot Password functionality to reset your password in case the email is invalid.

Hope that answers your question :)
