### ISSUE TITLE
[Bug] Skills section doesn't respect the input in Castform template

### ISSUE THREAD

**Issue by darcien** [AmruthPillai/Reactive-Resume#64]
**Describe the Bug**

In Castform template, the Skills section heading always display "Skills" instead of the input for the heading.

**Reproduction**
Steps to reproduce the behaviour:
1. Use Castform.
2. Enable Skills.
3. Rename the heading.

**Expected Behaviour**
The displayed heading should follow the input.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19742419/78217281-f1b93100-74e5-11ea-8bd7-0d2fe0ed3a0d.png">

**Comment by darcien** [comment]
I went ahead and created a fix for this in #65

**Comment by AmruthPillai** [comment]
That was brilliant, thank you so much! :) I seem to have missed that part. Thank you for finding the bug and squashing it in record time. Very very much appreciated. Please keep using the app and do let me know if you have any ideas on how we can make it better and more useful to others out there.
