### ISSUE TITLE
[FEATURE] (v3) Make importing v2 resumes possible.

### ISSUE THREAD

**Issue by VanBrugg3n** [AmruthPillai/Reactive-Resume#648]
**Is your feature request related to a problem? Please describe.**
I have a perfect resume from version 2 saved as JSON, but unfortunately I'm unable to load it. I know the main creator is aware of this, but just wanted to highlight the priority of this, as I'm sure I'm just one amongst many in identical situation.

**Describe the solution you'd like**
A built-in parser that would translate from v2 format to equivalent v3 format? Accessible as an additional option of import in the dashboard, so that there would be separate `v2 import` and `v3 import` buttons.

**Comment by AmruthPillai** [comment]
Alright, will do what I can to implement a separate parser for v2 versions of the JSON as soon as I can.

**Comment by AmruthPillai** [comment]
In addition to this, I would also like to point out that you should still be able to access the previous version if you want to, at this URL: **https://v2.rxresu.me/**

This is just to ensure no one's data goes away immediately. Access to this will always be open, and for those who prefer the old version can continue to use it for however long they please.

**Comment by VanBrugg3n** [comment]
> In addition to this, I would also like to point out that you should still be able to access the previous version if you want to, at this URL: **https://v2.rxresu.me/**
> 
> This is just to ensure no one's data goes away immediately. Access to this will always be open, and for those who prefer the old version can continue to use it for however long they please.

Oh, then that's a game changer for me! :D Totally wasn't aware of this, thank you very much! If only was this put somewhere at the top of README here and/or on the v3 site, I wouldn't even create this issue.

This puts the parser thing lower in priority IMO.

And a great thank you for the app! It's absolutely amazing :)

**Comment by AmruthPillai** [comment]
@ChristianVaughn I make time to build this project every second I get, and there have also been times where I've put my personal life and work life on the back burner to ensure that this is built in a way to help people, because I have first hand seen the impact this project has had on folks who are desperate for alternatives.

I understand that it might be difficult to use it without certain features at the moment, but they will come in time. Will keep you updated as soon as I have it available.

**Comment by AmruthPillai** [comment]
You can now import JSON files exported through https://v2.rxresu.me, as of [v3.2.3](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.2.3) 🎉
