### ISSUE TITLE
Resumes have all disappeared.

### ISSUE THREAD

**Issue by SelfhostedPro** [AmruthPillai/Reactive-Resume#651]
**Describe the bug**
All of the resumes I had previously submitted (had worked on all of them within the past month) seem to have disappeared with the latest update. I'm unsure if this is intended due to the upgrade or not. I can manually copy them back in but wanted to reach out in case this is a bug.

**To Reproduce**
1. Had account using google oauth
2. Had created reumes prior to today
3. They should be gone in the latest version.

**Expected behavior**
I would think they would still be saved somewhere.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: latest
 
**Additional context**
I have them exported as backups so it's not a big deal, just wanted to inform you in case it was unintentional.

**Comment by AmruthPillai** [comment]
**You should be able to still access the previous version by visiting https://v2.rxresu.me :)**

None of it is going away, I even have the very [first version](https://v1.rxresu.me) of the app still running.

Thank you for posting about this, it is important for folks to know that their data isn't completely vanished overnight either. It'll be safe, as long as I can keep up server costs 😄 

Please do give v3 a try though, I'm sure you'll find the new features really helpful to creating a new resume.

**Comment by SelfhostedPro** [comment]
Oh, that’s great to know! It may be a good idea to add a note to the v3 homepage. Thanks again for making such a great project!

**Comment by SelfhostedPro** [comment]
You should also be sure to post your server costs and reach out to digitalocean about sponsoring your opensource project. They give me ~$250 a year in credit for my project
