### ISSUE TITLE
Download Option is broken

### ISSUE THREAD

**Issue by prafulljain0408** [AmruthPillai/Reactive-Resume#652]
Firstly, I would love to say that your application is amazing.
When I click on Single page resume download, the downloaded file is a pdf with things related to Reactive resume. I have uploaded it on drive of how the downloaded PDF looks. The link is 
[https://drive.google.com/file/d/1SUrj7lnXB0QRIpQoapBtkD9lk4seYwbS/view?usp=sharing](url)

Also This issue prevails in V2 of the application.
Please look into it as I have to submit my CV urgently for job postings.

**Comment by shivaprasad-patil** [comment]
I am running into the same issue, not able to export the pdf file.
Help would be appreciated.
Thank you.

**Comment by filippofontana** [comment]
Same problem here.

**Comment by AmruthPillai** [comment]
Will fix this in 5 minutes, thank you for raising an issue.

**Comment by AmruthPillai** [comment]
Fixed in v3.1.3

**Comment by prafulljain0408** [comment]
Hey Amruth, 
Appreciate you fixing the bug. 

I was hoping if the bug can be fixed in V2 aswell? 
will be really helpful
thanks

**Comment by shivaprasad-patil** [comment]
Yes, I find it easy to work in version 2.0.
So, if you could fix the bug in version 2.0 that would be great.

Thanks

**Comment by AmruthPillai** [comment]
@shivaprasad-patil I am trying to implement a way to import version 2 JSONs into version 3. Until then, have you tried running the export PDF function on other browsers perhaps? Could you share the ID of the resume with me so I can try it out?

**Comment by shivaprasad-patil** [comment]
@AmruthPillai The ID is 9dr2i2. I could not download it on other browsers. 
Thank you for the help.

**Comment by AmruthPillai** [comment]
@shivaprasad-patil I was able to grab a node screenshot and generate a PDF. I agree, that the v2 export PDF is broken because of the new release. But fixing that would take a bit more time. Sharing the generated PDF here in case it helps.

[v2.rxresu.me-9dr2i2.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/8238223/v2.rxresu.me-9dr2i2.pdf)

**Comment by shivaprasad-patil** [comment]
@AmruthPillai Thank you so much for your help. It means a lot.
