### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by khantminsithu** [AmruthPillai/Reactive-Resume#661]
**Describe the bug**
Download option for both single and multiple pdf are broken.

**To Reproduce**
Click on either of the button. It will navigate to another page

**Expected behavior**
download pdf

**Screenshots**

**Desktop (please complete the following information):**
 -Window10
 -Firefox

**Additional context**
Nothing else. Very nice work

**Comment by ahmadbenos** [comment]
Exporting pdf generates a damaged or corrupted pdf, I also tried exporting a page with the just my name on it, still same issue

**Comment by AmruthPillai** [comment]
Fixing in 5 minutes, thank you for reporting!
