### ISSUE TITLE
[BUG] Adding photo Seems to fail

### ISSUE THREAD

**Issue by elightcap** [AmruthPillai/Reactive-Resume#663]
**Describe the bug**
After uploading a photo to a resume, it does not display

**To Reproduce**
1. Create new resume.
2. Upload a photo
3. When viewing the resume in either the editor or through a shareable URL, the photo is not displayed

**Expected behavior**
THe photo should show up on the resume

**Additional context**
When i try to right click and open photo in a new tab, i receive the error `"statusCode":404,"message":"Cannot GET /uploads/134/123/1647065955037.jpeg","timestamp":"2022-03-12T16:52:16.081Z","path":"/uploads/134/123/1647065955037.jpeg"}`

**Comment by AmruthPillai** [comment]
This should be fixed as of version v3.1.3, could you please check once again and try it out? I have a cypress test that ensure that it's working as well.

**Comment by elightcap** [comment]
Yep looks to be working now!
