### ISSUE TITLE
[BUG] Exported PDF does not show Present in the date ranges

### ISSUE THREAD

**Issue by filippofontana** [AmruthPillai/Reactive-Resume#664]
**Describe the bug**
The exported PDF shows an empty space in the fields where you can add a date range, and the `end date` field is leaved blank (in order to show "Present"), the PDF should instead show "Present".

Maybe this happen because in the JSON file the `end date` field is empty?

**Comment by AmruthPillai** [comment]
This should be fixed as of v3.1.3, could you please check again? If you're still facing an issue, could you please share a screenshot with me on this issue so I can understand it better?

**Comment by filippofontana** [comment]
Yes, sure. Here the screenshot:

![image](https://user-images.githubusercontent.com/55811966/158029261-118b0758-2f74-401f-aa89-77fd2ca7682c.png)

**Comment by khantminsithu** [comment]
@AmruthPillai Hi I still can't export the pdf file. It will navigation me to this link [blob:https://rxresu.me/23ecbbb8-c179-47a6-926f-b99a6fb8a3bd](url) without downloading the pdf. Its happen in firefox Window10

**Comment by AmruthPillai** [comment]
@khantminsithu Firefox handles these async downloads differently, I guess for security reasons. All you would need to do is hit Ctrl + S to save the PDF to your local while on that blob page and the resume will be saved to your computer.

**Comment by AmruthPillai** [comment]
@filippofontana Ah, gotcha. Found the issue, filing a fix for it in a few minutes.

**Comment by AmruthPillai** [comment]
Fixed as of [v3.1.4](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.1.4)

**Comment by filippofontana** [comment]
Thank you very much for this great web application and also for your hard work and responsiveness. I will consider to donate something to you!
