### ISSUE TITLE
[Bug] PDF export for longer resumes shrinks to fit on one page

### ISSUE THREAD

**Issue by rystan** [AmruthPillai/Reactive-Resume#67]
**Describe the Bug**
As the length of a resume increases, for people with extensive work histories, the UI displays the resume at full page width, but the PDF export seems to scale/shrink the content to fit to a single page based on the length, rather than spill over onto additional pages.

**Reproduction**
Steps to reproduce the behaviour:
1. Have enough content/work history to extend the page length beyond what would fit on a single page without scaling.

**Expected Behaviour**
The layout should remain at a fixed width to match expected page size, but as the length grows, it should expand onto additional pages rather than shrinking to fit on one page.

**Screenshots**
![image](https://user-images.githubusercontent.com/6609665/78275389-8e2c0500-74df-11ea-985b-76c533697ac1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional Context**

**Comment by AmruthPillai** [comment]
This has been fixed with #75, please let me know if the new features help you in your cause :)
