### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by sroyalgupta** [AmruthPillai/Reactive-Resume#670]
Hi, I am not able to export my resume into pdf.
When I am trying to convert it is giving below file
[RxResume-60cjet (2).pdf](https://github.com/AmruthPillai/Reactive-Resume/files/8239237/RxResume-60cjet.2.pdf)
.

**Comment by AmruthPillai** [comment]
The print functionality in https://v2.rxresu.me should be fixed now, deployed a new version of the cloud function to print.

**Comment by sroyalgupta** [comment]
Thanks @AmruthPillai

**Comment by AmruthPillai** [comment]
You can now import JSON files exported through https://v2.rxresu.me, as of [v3.2.3](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.2.3) 🎉
