### ISSUE TITLE
Can't able to download resume

### ISSUE THREAD

**Issue by vicky-mac** [AmruthPillai/Reactive-Resume#673]
I created all my resume details after that i export that resume to download it. It was exporting all the things except that resume..
Today only it gives me this problem before that and all it
[RxResume-6gr7om.pdf](https://github.com/AmruthPillai/Reactive-Resume/files/8239911/RxResume-6gr7om.pdf)
 works fine.

**Comment by AmruthPillai** [comment]
The print functionality in https://v2.rxresu.me should be fixed now, deployed a new version of the cloud function to print.

**Comment by AmruthPillai** [comment]
You can now import JSON files exported through https://v2.rxresu.me, as of [v3.2.3](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.2.3) 🎉
