### ISSUE TITLE
Unable to sign in/register for first time use on docker

### ISSUE THREAD

**Issue by kennnyshiwa** [AmruthPillai/Reactive-Resume#676]
Recently spun up the latest version of reactive resume via docker after upgrading from the v1 version. I have everything up and running using the docker-compose.yml and .env example files from the repo and can successfully get to the main login page but can't register or login. 

I am trying to register just with an email and password as i would rather not rely on google for sign ins but after typing in my info nothing happens. Checked logs on both the client, server and postgre instances but i don't see any attempts at it trying to register me as a user. Trying to go directly to the dashboard without logging in also fails with an application error in an attempt to bypass logins. Not sure if i am missing a step or if registration is just broken on local instances.

**Comment by kennnyshiwa** [comment]
Upon further testing i also tried to register with google after giving it my client id and secret. That flow appears to work as in i click the button, sign into google and what not but then it attempts to redirect and close the window and im left on the same page, clicking login and signing in with google at this point also continues to fail

**Comment by AmruthPillai** [comment]
I've updated the docker-compose.yml now, and you might need to modify it to add your server IP as well. But once that's done, it should be just one single command to running the project. Please do let me know if it works for you.
