### ISSUE TITLE
Resume does not export to pdf

### ISSUE THREAD

**Issue by SDimitryS** [AmruthPillai/Reactive-Resume#677]
Hello, great app! But when downloading a ready-made resume, the site page is loading, perhaps this is an error of a particular layout, please check.

**Comment by AmruthPillai** [comment]
I'll need some more information unfortunately, as I'm able to export a PDF as expected.

**Comment by SDimitryS** [comment]
Hello Amruth!
Now, when you try to download, a cloud error notification pops up. When output to the printer displays incorrectly, the screen is also attached. This is the link https://rxresu.me/r/byx77j
Thank you for your prompt response Dmitry.

Отправлено с помощью [ProtonMail](https://protonmail.com/) защищенной электронной почты.

------- Original Message -------
понедельник, 14 марта 2022 г., 8:18, Amruth Pillai ***@***.***> написал(а):

**Comment by AmruthPillai** [comment]
Unfortunately, this was one of the issues that I could not debug as it was happening on the Cloud Function side of things. This is one of the reasons why v3 was made, to have more control over action on issues.

Right now, I can only ask you to see if creating a resume from scratch on v3 would be a possibility. I am also working on a way to import v2 resumes into v3.

**Comment by SDimitryS** [comment]
Yes, of course, I need some time.

**Comment by SDimitryS** [comment]
maybe I'm doing something wrong, but I get into version v2.7.10, even if I follow your link https://www.producthunt.com/posts/reactive-resume-v3

**Comment by AmruthPillai** [comment]
v2 had a sort of aggressive caching to ensure it works even if it goes offline. You may want to clear cache and try again. Here's a quick tutorial on how you could do that: https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/

**Comment by SDimitryS** [comment]
Yes, I updated the version, it! yes, there are serious changes in it! A big plus is that it is possible to change the format of the sheet, which allows you to view the summary by scaling, the PDF shakes. The printed version is displayed correctly. The only thing missing is the JSON import.

Отправлено с помощью [ProtonMail](https://protonmail.com/) защищенной электронной почты.

------- Original Message -------
понедельник, 14 марта 2022 г., 9:14, Amruth Pillai ***@***.***> написал(а):

**Comment by AmruthPillai** [comment]
Will work towards implementing that very soon :) Thank you so much for your feedback.
