### ISSUE TITLE
[FEATURE] MIssing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [AmruthPillai/Reactive-Resume#683]
**Is your feature request related to a problem? Please describe.**
The project is currently missing the Code of Conduct. According to GitHub docs:

> A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community.

**Describe the solution you'd like**
If you want that, then I can add a PR with the md file.

**Describe alternatives you've considered**
It's completely up to you whether you want this to be added in the project or not.

**Additional context**
Not applicable.

**Comment by AmruthPillai** [comment]
Sure, a PR for that would be great :)

**Comment by AmruthPillai** [comment]
Added `CODE_OF_CONDUCT` in https://github.com/AmruthPillai/Reactive-Resume/commit/318145f007b8c3ea7a35dd42d57b96e3cd4bddb2
