### ISSUE TITLE
[BUG] Unable to load fonts

### ISSUE THREAD

**Issue by goliath888** [AmruthPillai/Reactive-Resume#684]
I have deployed reactive-resume in my server with docker-compose, and there is some problem with Google fonts.
In chrome, in the console, I can see this error:

GET | http:// < SERVER-IP> : < PORT > /api/fonts  ->  500 Internal Server Error

In the server container, I can see this error: 

> [Nest] 42  - 03/14/2022, 11:00:36 AM   ERROR [ExceptionsHandler] Request failed with status code 400
> Error: Request failed with status code 400
>     at createError (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/adapters/http.js:322:11)
>     at IncomingMessage.emit (node:events:532:35)
>     at endReadableNT (node:internal/streams/readable:1346:12)

And in the front, fonts section is not loading.

**Comment by AmruthPillai** [comment]
Did you add `GOOGLE_API_KEY` in your `.env`?

**Comment by goliath888** [comment]
Ok, that was totally my fault. I though (did not read that) that Google keys were all only related for Google Authentication. 

It is working fine now. Thanks and great job!
