### ISSUE TITLE
[BUG] FF mobile can't login with google

### ISSUE THREAD

**Issue by qw-in** [AmruthPillai/Reactive-Resume#690]
**Describe the bug**
Login/register with google does not work on ff android

**To Reproduce**
1. Go to homepage
2. Click on register
3. Click register with google
4. Login via popup
5. Redirect back and still see register modal

**Expected behavior**
Either logged in/registered or at least an error message

**Smartphone (please complete the following information):**
 - Device: op8 pro
 - OS: 11
 - Browser ff with abp
 - Version latest

**Additional context**
Have not tested chrome yet

**Comment by qw-in** [comment]
Does not work for me in chrome either. The register with Google button does nothing & login does not work (I assume bc I have not registered)

**Comment by qw-in** [comment]
> I will try to fix the error reporting mechanism so that users see whatever error is sent by Google as it is. That should help with debugging at least

Thanks for looking into it! That is weird - maybe because my account is connected to an org. If I can find a way to get to the console in ff I'll add more info

**Comment by AmruthPillai** [comment]
There could be certain features blocked on an org Google Workspace account, but if Login with Google works everywhere else, it should work here too. I just tried the same register/login process with my org's google email and it still went through. Do share if you are able to get some more insight into this. In the meantime, using email/password isn't the end of the world ;)

**Comment by qw-in** [comment]
> In the meantime, using email/password isn't the end of the world

Just registered via desktop :smile:
