### ISSUE TITLE
[BUG] Data is lost

### ISSUE THREAD

**Issue by ozanhalisilter** [AmruthPillai/Reactive-Resume#695]
**Describe the bug**
All data is gone. I cannot reach any of my resumes. I tried with 3 different accounts, we all used google to authenticate before. Is there a way to recover it?

**Comment by AmruthPillai** [comment]
Is this on v2, or on v3? Could you post a screenshot of the screen you see so I can better help?

**Comment by AmruthPillai** [comment]
If you were using the older version of Reactive Resume (v2), you should still be able to access the old interface through https://v2.rxresu.me. You should also be able to export JSONs made in the previous version and import them into the current one which lives on https://rxresu.me.

**Comment by comanbo** [comment]
> If you were using the older version of Reactive Resume (v2), you should still be able to access the old interface through https://v2.rxresu.me. You should also be able to export JSONs made in the previous version and import them into the current one which lives on https://rxresu.me.

thank you. I had the same issue and this solve it. It would be nice to post an announcement on the main page about this change.

**Comment by AmruthPillai** [comment]
If the schema is off a bit, or there's something wrong with the JSON, some sections might not appear. I don't have my JSONs to experiment with, but hope to make it better soon.

And yes, will create links to the old version in the footer.
