### ISSUE TITLE
[FEATURE] Admin console

### ISSUE THREAD

**Issue by modem7** [AmruthPillai/Reactive-Resume#696]
An admin console to keep track of users using the self-hosted platform, and to delete/disable/authorise any accounts, reset passwords (I know it can be done via email, but still useful if one hasn't set up emails/don't wish to). 

This would allow for admins to have greater control of their self-hosted platform, and to reduce any instances of bad actors creating false resumes on their platform, and/or reduces/eliminates potential abuse from anonymous users who are able to sign up. 

For this, a "signup disabled" option may be a quick and dirty workaround in the meantime, which just disables the /auth/register endpoint.

2FA via QR code during account creation would also be useful for the security aspect (although this might be best suited in a separate FR).

**Comment by AmruthPillai** [comment]
Interesting, I never thought about the idea of an admin panel before. I'm not sure it provides much use for me though, as I don't really micro-manage the users of the app, but just push features and solve their issues when they are on GitHub. But having a place to be able to manage data, look at dashboards would be quite interesting.

But I'm a believer in trying to make use of what's already out there, and there's this neat service called Retool which allows you to create admin dashboards and internal tooling with drag-drop GUI and powerful integrations with any database. If you're in the need for a quick solution, you could perhaps look into that.

Right now, admin panels are not in scope, so I hope you don't mind if I close the issue. But when I see a clearer need for it, for myself to manage the production app, I'll consider opening the issue again to track progress :)

Thank you so much for the out of the box suggestion! 🗳️
