### ISSUE TITLE
[FEATURE] Add environment variable to disable user registration

### ISSUE THREAD

**Issue by ajm1014** [AmruthPillai/Reactive-Resume#698]
To share my resume via a link (which I would like to do because the resume created by your application is awesome), I am required to open my website up to public internet access, allowing others to access the page, register an account, and host their resume on my server/domain as well.

It would be great if there were an ALLOW_REGISTRATION environment variable that could be set to true or false (true by default), so this feature could be enabled or disabled as needed!

**Comment by AmruthPillai** [comment]
Introduced the `PUBLIC_FLAG_DISABLE_SIGNUPS` flag. You should be able to set this value in your ENV which can enable or disable the registration button on the landing page.

**Comment by ajm1014** [comment]
This is great (confirmed it's all working), thank you for making the update so quickly!
