### ISSUE TITLE
Add link to this repo on website

### ISSUE THREAD

**Issue by nikolaos-spyratos** [AmruthPillai/Reactive-Resume#7]
Hi there. Found this repo by following some links after seeing it on HN. Took me a bit of digging to get to your github profile to find the project though. Had to go to your personal site, then the angular repo link at the bottom, then your profile to get here.

Mind linking to it from the demo website?

**Comment by AmruthPillai** [comment]
Ah, I'm sorry you had to go through all the trouble to find the repo. I did want to place the link somewhere on the app, but I don't know where it would be best placed. I didn't want to clutter the UI anymore.

**Comment by vishal-vvr** [comment]
Hello,
May be a about/more option(not sure about the label) next to "Actions" on top right corner.
with project repo link, licence and all possible links related to your profile and/or project. 
Don't know will that make sense, but happy to here from you.  
Thanks for adding the LICENSE was about to create an issue for the same :P
Keep working, Happy Coding!

**Comment by nikolaos-spyratos** [comment]
What @vishal-vvr mentioned works, else adding a small footer section to one/each of the sidebars would be useful for this or other future information one might need to put there.

**Comment by AmruthPillai** [comment]
I've created a branch to work on what @vishal-vvr suggested :) Will revert back here once it has been merged with the production branch.

**Comment by AmruthPillai** [comment]
This has been implemented, thanks everyone :)
