### ISSUE TITLE
[FEATURE] Block new signups 

### ISSUE THREAD

**Issue by mattlathrop** [AmruthPillai/Reactive-Resume#712]
I'd like the ability to disable registration. I think I might be able to do it with some clever traefik rules to block the /auth/register endpoint, but it'd be nice if there was a cleaner solution. Any ideas on how to accomplish this in a no-code/low-code solution?

**Comment by AmruthPillai** [comment]
Closing this as it is a duplicate of https://github.com/AmruthPillai/Reactive-Resume/issues/698, will work on it soon.
