### ISSUE TITLE
Wrong date displayed in resume

### ISSUE THREAD

**Issue by pkrolkgp** [AmruthPillai/Reactive-Resume#719]
When creating resume and adding time of work it displays in english even tho language is changed
![obraz](https://user-images.githubusercontent.com/32438012/158569148-c6ccd3c4-2c23-4a79-bfd7-7e18672dd8f5.png)
and in the resume
![obraz](https://user-images.githubusercontent.com/32438012/158569252-52362522-bdc3-4a56-8221-c4f0b7f4e1e4.png)

**Comment by AmruthPillai** [comment]
@pkrolkgp Which language is this?

**Comment by blacksoulgem95** [comment]
@AmruthPillai this is most commonly an issue when you wrongly manage timezone. from the front end the date is uploaded with the device timezone and then is saved and elaborated in UTC.
The date is saved with time 00:00:00 (TIMEZONE) and converted to UTC, hence 01/01/2022 00:00:00 CET will be converted into 31/12/2022 23:00:00 UTC.

**Comment by pkrolkgp** [comment]
> @AmruthPillai this is most commonly an issue when you wrongly manage timezone. from the front end the date is uploaded with the device timezone and then is saved and elaborated in UTC. The date is saved with time 00:00:00 (TIMEZONE) and converted to UTC, hence 01/01/2022 00:00:00 CET will be converted into 31/12/2022 23:00:00 UTC.

the problem is not translated names of months, rest seems good

> @pkrolkgp Which language is this?

it's Polish

**Comment by AmruthPillai** [comment]
@pkrolkgp Got it, I seem to have missed Polish in adding the date translations.
Will add them and fix this issue soon :)
