### ISSUE TITLE
Last name not showing up correctly.

### ISSUE THREAD

**Issue by blindtrust** [AmruthPillai/Reactive-Resume#72]
The last name and dates are not being correctly rendered in the PDF..

<img width="2636" alt="Screen Shot 2020-04-03 at 7 02 03 PM" src="https://user-images.githubusercontent.com/14252048/78411550-04af2c80-75de-11ea-817e-60c45fa5c14a.png">
<img width="556" alt="Screen Shot 2020-04-03 at 7 03 38 PM" src="https://user-images.githubusercontent.com/14252048/78411552-05e05980-75de-11ea-8cff-0bd08216bebf.png">

 being generated incorrectly in the PDF. Looks perfect on-screen but not in the PDF... 2 screenshots attached.

**Comment by AmruthPillai** [comment]
Yes, this is a known issue that only seems to be happening with Safari. There's no official fix for this out yet. If you would like to get this sorted out quickly, you could use another browser like Chrome, just to export the data.

**Comment by AmruthPillai** [comment]
For more information about this bug:  
https://stackoverflow.com/questions/60635788/html2canvas-not-wrapping-text-well-in-safari. 
https://github.com/niklasvh/html2canvas/issues/2177

**Comment by blindtrust** [comment]
Thank You! 

Scott Seifert
TEAMSPIKE
216-338-1486 iPhone
scott_m_seifert@me.com
