### ISSUE TITLE
[BUG] Error when changing colour with custom HEX

### ISSUE THREAD

**Issue by blacksoulgem95** [AmruthPillai/Reactive-Resume#725]
**Describe the bug**
The front-end crashes after colour change and the CV is not accessible anymore.

**To Reproduce**
1. Create a resume
2. Paste a HEX Colour into the colour field

**Expected behavior**
The colour to be the one I've chosen 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest stable as of 16th March 22

**Smartphone (please complete the following information):**

**Additional context**

Affected resume: https://rxresu.me/sofivic95/sofia-vicedomini

**Comment by AmruthPillai** [comment]
May I know which color you tried to enter? There's a hex pattern matcher which accepts any valid hex color. It should accept only and only when it matches. Curious to know what could have broken this check.

**Comment by blacksoulgem95** [comment]
I tried to enter #db2877

**Comment by blacksoulgem95** [comment]
I want to notify you that it still throws errors when re-opening the affected CV.

<img width="1791" alt="Schermata 2022-03-18 alle 14 15 33" src="https://user-images.githubusercontent.com/11537307/159009552-bbd162ae-63c8-4938-9ea7-16bbefde6974.png">

**Comment by AmruthPillai** [comment]
@blacksoulgem95 Your resume should be accessible again now.

**Comment by blacksoulgem95** [comment]
thanks!
