### ISSUE TITLE
[BUG] JSON export of non-ASCII characters is broken

### ISSUE THREAD

**Issue by bardo** [AmruthPillai/Reactive-Resume#726]
**Describe the bug**
When exporting a resume that contains non-ASCII characters, e.g. accented letters, they are not properly represented in the JSON and cannot be reimported back.

**To Reproduce**
1. Create a new empty resume, give it any name
2. In the Basics section, as a Full Name use `áÁÀà`
3. Export the resume as JSON
4. Note how the name in the JSON is specified as `"name": "<e1><c1><c0><e0>",`
5. If the same JSON is imported back into Reactive Resume, each character is now displayed as `����`

**Expected behavior**
The inserted characters should not change.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 98.0

**Comment by AmruthPillai** [comment]
Should be fixed as of v3.2.6
