### ISSUE TITLE
[BUG] JSON export/import not working

### ISSUE THREAD

**Issue by git-61734** [AmruthPillai/Reactive-Resume#728]
**Describe the bug**
import from JSON not working.

**To Reproduce**
1. Create new resume.
2. Load sample data.
3. Export to JSON.
4. Go to home.
5. Import From JSON.

**Expected behavior**
JSON should be imported.

**Screenshots**
![Screenshot from 2022-03-17 18-57-53](https://user-images.githubusercontent.com/69983224/158865970-53c8af1a-525b-4850-9bc1-4aee4616d3e0.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: v3.2.6

**Comment by chandiwalaaadhar** [comment]
@git-61734 If you have exported the JSON resume from Reactive Resume Dashboard, you need to **Import from Reactive Resume** as Marked in the Image Below.
![Group 3](https://user-images.githubusercontent.com/27367779/158922817-6e1bd735-a1a2-4647-9059-83de2e1e7176.png)

**Comment by chandiwalaaadhar** [comment]
@AmruthPillai Would it be more helpful and user friendly to Keep "Import From Reactive Resume" section in the middle, instead of "Import from JSON Resume"?

**Comment by AmruthPillai** [comment]
Maybe, will track this in another internal issue :) Thank you for resolving the issue @chandiwalaaadhar, and hope that clears up the question for you @git-61734.

**Comment by git-61734** [comment]
@chandiwalaaadhar You are totally right, sorry about that, I was tired. :/
