### ISSUE TITLE
[Bug] Where is the data saved when creating a resume?

### ISSUE THREAD

**Issue by BobWs** [AmruthPillai/Reactive-Resume#73]
Hi,

Where is the data saved when creating a resume? And can this folder be mounted in docker?
A password login to protect your private information would be nice

**Comment by AmruthPillai** [comment]
The data is saved in your browser, so there's nothing you need to do with Docker. If you want your data to persist, all you need to do is keep the same IP/Domain address when deploying/re-deploying. The data can be found in your Client Browser's Local Storage.
