### ISSUE TITLE
[BUG] Cannot get it to work with different domains for server and client

### ISSUE THREAD

**Issue by vitobotta** [AmruthPillai/Reactive-Resume#730]
**Describe the bug**
Hi, use Dokku for several apps so I am trying to set up Reactive Resume this way. Since Dokku doesn't support deployments of apps in subfolders, I have created two separate apps with different domains, say resume.domain.com for the server part and cv.domain.com for the client part.  In the environment variables I set PUBLIC_URL to https://cv.domain.com and PUBLIC_SERVER_URL to https://resume.domain.com but when I try to register an account, the frontend makes a request to https://cv.domain.com/api/etc kinda ignoring the environment variables. Any suggestions?

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x ] Self Hosted

**To Reproduce**
1. Deploy server and clients as separate apps each with its own domain

**Expected behavior**
I would expect the app to work.

**Desktop (please complete the following information):**
MacOS Monterey
Any
Latest official Docker image

**Comment by AmruthPillai** [comment]
The code is written in such a way that both client and server are meant to run on a single domain. Unfortunately there are no plans to change this to support different domains as the architecture decision was intentional.

It's not that difficult to set it up under one single domain, and it's also safer in terms of security as you can close down all requests from externals services to the server.

**Comment by vitobotta** [comment]
> The code is written in such a way that both client and server are meant to run on a single domain. Unfortunately there are no plans to change this to support different domains as the architecture decision was intentional.
> 
> It's not that difficult to set it up under one single domain, and it's also safer in terms of security as you can close down all requests from externals services to the server.

I understand. I was planning to switch from Dokku to plain docker compose anyway so I am doing this right now with my self hosted apps, so I have more flexibility. Thanks!
