### ISSUE TITLE
It shows all the Cv content in one page and doesn't move the next page when there is line break

### ISSUE THREAD

**Issue by anseenivasan** [AmruthPillai/Reactive-Resume#732]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmruthPillai** [comment]
You need to move sections to another page using the "Layout" section on the sidebar. It's not an automatic process.

**Comment by anseenivasan** [comment]
> You need to move sections to another page using the "Layout" section on the sidebar. It's not an automatic process.

if my work experience span across multiple pages.how i can keep it in second page

**Comment by AmruthPillai** [comment]
@anseenivasan You can create another custom section that goes on another page, and this section can contain the rest of your work experiences.

**Comment by anseenivasan** [comment]
Hi AmruthPillai,

How to create the custom section ?
Can you send me the screenshot?

Thanks
Srinivasan

**Comment by AmruthPillai** [comment]
You should be able to create a new section here:

![Screenshot 2022-03-18 at 9 51 03 AM](https://user-images.githubusercontent.com/1134738/158968140-bb4f14a8-df3e-4b53-ad77-d82b9a8baf51.png)

You can rename the section if you want here:

![Screenshot 2022-03-18 at 9 51 20 AM](https://user-images.githubusercontent.com/1134738/158968383-18dc744b-8a93-4757-b434-a39e235b0670.png)

Finally, move the section to the next page, main lane here:

![Screenshot 2022-03-18 at 9 51 30 AM](https://user-images.githubusercontent.com/1134738/158968686-6db82666-973d-486d-bb0b-a53274c52e5c.png)

**Comment by anseenivasan** [comment]
Hi AmruthPillai,

that worked for me.However i see new error when i try to drag the work exp
to the new section

Application error: a client-side exception has occurred (see the browser
console for more information).

**Comment by AmruthPillai** [comment]
I'm not able to recreate this actually, just tried it. Could you perhaps shoot a screen recording of the same and send it over to help me understand the issue better?

**Comment by anseenivasan** [comment]
Hi Amruth Pillai,

1) Have two work experience added minimum
2) create a custom section and add one work exp in that and try to move the
first under this section.I tried again it got same error

thanks
Srinivasan

**Comment by anseenivasan** [comment]
Hi Amruth pillai,

what is the difference between rxresume.web.app and rxresu.me/dashboard
.can i use the web.app to create the CV ?
That one doesn;t have the custom section or adding multiple pages.

thanks
Srinivasan

**Comment by AmruthPillai** [comment]
There are three versions you can use, https://v1.rxresu.me, https://v2.rxresu.me or the latest one, https://rxresu.me.
The last two versions don't really get any support or updates, so it's advised to use the latest when possible, but they still exist and work as expected so you can continue to use them if it suits you.

**Comment by anseenivasan** [comment]
Hi Amruth Pillai,

the issue discussed in the below topic still remains unresolved in
Version3. there is no margin for multiple page document.
Multipage Resumes do not have a header footer for page breaks #497

thanks
Srinivasan
