### ISSUE TITLE
Editable primary color with Hex code

### ISSUE THREAD

**Issue by AuthorShin** [AmruthPillai/Reactive-Resume#733]
Hello
I was interested to see that there is a field for Hex color code when we choose a color from color picker but we cannot directly add one color by Hex code manually, I'm not sure if it's a bug or an incompatibility with my browser but was wondering if you can fix/add this.
Best Regards

**Comment by AmruthPillai** [comment]
If you copy a valid hex value and paste it directly into the input field, it should allow you to change the value to whatever you want. Reactive editing on the input field itself is removed because it causes some issues with MUI at the moment which would need to be fixed upstream.
