### ISSUE TITLE
[FEATURE] Add date of birth and driving licence

### ISSUE THREAD

**Issue by git-61734** [AmruthPillai/Reactive-Resume#736]
Can you please add an input for date of birth and driving licences in basics information section (under address for exemple)?

**Comment by AmruthPillai** [comment]
Any specific reason to add date of birth within a resume? I've read multiple articles and seen cases to dispute that age shouldn't be a deciding factor when applying for a job. As explained in articles like [these](https://www.linkedin.com/pulse/should-you-put-your-agedate-birth-cv-resume-marcus-james/).

As for driving license, could you provide me with an example screenshot of some other resumes that show these type of extra information? I could implement another section to add extra info, which can just be key value pairs. But I'm curious to know how to display it in the resume.

**Comment by danfossi** [comment]
This can be helpful: https://www.indeed.com/career-advice/resumes-cover-letters/drivers-license-on-resume

**Comment by TENX-S** [comment]
Hi @AmruthPillai. Things a little different here in China. Age is an essential piece of information for a formal resume. As a fresh graduate of this year, it would be very helpful if you could make the “date of birth” field optional or disabled by default.

Thank you!

**Comment by AmruthPillai** [comment]
I've added Date of Birth as a field in basics now, as of v3.4.0 :)

**Comment by MLNW** [comment]
@AmruthPillai is it possible to hide the date of birth?

**Comment by AmruthPillai** [comment]
> @AmruthPillai is it possible to hide the date of birth?

Removing the date of birth from the builder sidebar should remove it on your resume as well.

**Comment by MLNW** [comment]
> > @AmruthPillai is it possible to hide the date of birth?
> 
> Removing the date of birth from the builder sidebar should remove it on your resume as well.

I tried clearing the field, but on clicking it the date picker is opened and when clearing the date there it does nothing. So, I seem to be unable to remove the field.

**Comment by AmruthPillai** [comment]
> > > @AmruthPillai is it possible to hide the date of birth?
> > 
> > Removing the date of birth from the builder sidebar should remove it on your resume as well.
> 
> I tried clearing the field, but on clicking it the date picker is opened and when clearing the date there it does nothing. So, I seem to be unable to remove the field.

Not using the date picker, but just using the text field and clearing out the input seems to work for me and hides the date of birth on the resume as well.

**Comment by MLNW** [comment]
> > > > @AmruthPillai is it possible to hide the date of birth?
> > > 
> > > 
> > > Removing the date of birth from the builder sidebar should remove it on your resume as well.
> > 
> > 
> > I tried clearing the field, but on clicking it the date picker is opened and when clearing the date there it does nothing. So, I seem to be unable to remove the field.
> 
> Not using the date picker, but just using the text field and clearing out the input seems to work for me and hides the date of birth on the resume as well.

When I click on the field in the basic sections and then clear the text in the opened modal it does not clear the field in the basic section for me.
