### ISSUE TITLE
[FEATURE] Letter Page size support

### ISSUE THREAD

**Issue by l418286283** [AmruthPillai/Reactive-Resume#741]
Hello,
Since many US companies use Letter page size. Is it possible to add page splitting for Letter page size? 

Thanks

**Comment by AmruthPillai** [comment]
Not stale, hope to add this feature soon.

**Comment by Death-Pact** [comment]
Is there a method to change the page size to Letter using CSS?

**Comment by AmruthPillai** [comment]
This has now been implemented in [v3.6.8](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.8).

<img width="555" alt="Screenshot 2022-10-15 at 1 08 00 AM" src="https://user-images.githubusercontent.com/1134738/195956090-a64174db-2108-418d-8665-58b0c707383a.png">
