### ISSUE TITLE
Link does not work correctly.

### ISSUE THREAD

**Issue by vicky-mac** [AmruthPillai/Reactive-Resume#747]
I added my Github profile and LinkidIn link to my resume.If i open that link that takes me to reactive resume page.Link does not work properly.

**Comment by GovindKrishnan** [comment]
The issue is only when you don't include "https://" with the URL.

@chandiwalaaadhar I hope this is very similar to your #685 fix.

**Comment by chandiwalaaadhar** [comment]
> The issue is only when you don't include "https://" with the URL.
> 
> @chandiwalaaadhar I hope this is very similar to your #685 fix.

That's correct. Will raise a PR for this :)
