### ISSUE TITLE
[BUG] Loging in issue after the new updates

### ISSUE THREAD

**Issue by Markg546** [AmruthPillai/Reactive-Resume#748]
**Describe the bug**
I was not able to login and my resume is no longer there. Is it gone forever if I did not save a json?

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**Comment by TrideepLD** [comment]
As per this issue [here](https://github.com/AmruthPillai/Reactive-Resume/issues/651),

> You should be able to still access the previous version by visiting https://v2.rxresu.me/ :)

**Comment by Markg546** [comment]
Thanks a lot, didn't find that issue!
