### ISSUE TITLE
[Bug] li is cropped

### ISSUE THREAD

**Issue by theniceangel** [AmruthPillai/Reactive-Resume#76]
**Describe the Bug**
the style of `li` is cropped

**Reproduction**
use `Onyx` template, then save as a PDF,

**Expected Behaviour**
show the correct content when saving as a PDF

**Screenshots**
![image](https://user-images.githubusercontent.com/25956811/78465563-bc048a00-7729-11ea-91dc-635f44a9a550.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional Context**
In fact, the style of `li` exceeds the page of left boundary, so it is cropped

**Comment by AmruthPillai** [comment]
This has been fixed with the successful merge of #77.

**Comment by theniceangel** [comment]
> This has been fixed with the successful merge of #77.

App should be republished, the online is still pre version

**Comment by AmruthPillai** [comment]
As soon as I push to the master branch, there is a CI/CD process put in place that publishes the latest version. You might have the cached version as I have made the app a PWA. You can fix this by clearing the cache and reloading the app (Shift + Cmd + R, in Chrome). Let me know if this resolves your issue.

**Comment by theniceangel** [comment]
@AmruthPillai It works!
