### ISSUE TITLE
Saved Resumes Are Gone after New UI Update

### ISSUE THREAD

**Issue by opensaucerer** [AmruthPillai/Reactive-Resume#761]
**Describe the bug**
I was logged out, most likely due to the update that was made and when I logged in back, I couldn't find my resumes anymore. 
All my saved resumes went missing. 

**Product Flavor**
- [ ] Managed (https://rxresu.me)

**To Reproduce**
I don't know if this can be reproduced but others might have experienced the same issue. 

**Expected behavior**
I should still see all my resumes. 

**Screenshots**

https://filebin.net/ngnwx8rwpstsa49i/Screenshot__8_.png

**Comment by AmruthPillai** [comment]
Please visit https://v2.rxresu.me and you should be able to see all your old resumes.
