### ISSUE TITLE
[FEATURE] Allow exporting to a text format

### ISSUE THREAD

**Issue by corybolar** [AmruthPillai/Reactive-Resume#762]
**Is your feature request related to a problem? Please describe.**
Many resume uploading sites/applications want a resume that can be parsed.  The current pdf exporter is image only and cannot be parsed.

**Describe the solution you'd like**
Add an exporter to a text based document with simple markdown formatting or similar to make parsing easier.  Given the input forms, this should be possible.

**Describe alternatives you've considered**
Parsing the raw html from the permanent link is not feasible

**Additional context**
N/a

**Comment by AmruthPillai** [comment]
The PDF is not image only, the text can be parsed from it. I've been able to verify this on open-source ATS platforms as well.
Text based is quite interesting, but could you provide few examples of websites that allow text-based resumes?

**Comment by comanbo** [comment]
It is common knowledge in the HR community that exporting in .doc/docx format can be better for ATS systems scanning.
e.g. https://www.resume.com/career-advice/resumes/resume-pdf-or-word/
https://www.themuse.com/advice/beat-the-robots-how-to-get-your-resume-past-the-system-into-human-hands 

So, having the option to export in word document while maintaining the format would be a nice enhancement.

**Comment by AmruthPillai** [comment]
Oh, you mean export it to a document format like MS Word? That's really difficult, even for most upscaled resume builders. The generators to make word documents from HTML/CSS templates are very difficult to get working with this. Unfortunately, out of the scope of my abilities right now.

**Comment by tallpeak** [comment]
Would an HTML or html archive be possible? I also feel that an export in some sort of text format would be nice; particularly, markdown or HTML (from which Pandoc could be used to convert to Word.)
