### ISSUE TITLE
pnpm dev get the result ' ELIFECYCLE  Command failed with exit code 1.'

### ISSUE THREAD

**Issue by Kyou12138** [AmruthPillai/Reactive-Resume#763]
env: windows 10
I follow this page https://docs.rxresu.me/source-code/docker,
but I can't run pnpm dev normally, it get me the info like these

![image](https://user-images.githubusercontent.com/35862524/159642105-da48479e-10bc-409a-acc5-d13a2a04e4a3.png)

**Comment by chandiwalaaadhar** [comment]
@Kyou12138 Looks like your user doesn't have required privileges to run ```pnpm dev``` command. Try using sudo (Unix or Mac) or Run the PowerShell as an Administrator (in Windows)
