### ISSUE TITLE
[BUG] Images disappear after a few days

### ISSUE THREAD

**Issue by blacksoulgem95** [AmruthPillai/Reactive-Resume#790]
**Describe the bug**

After some days, the image uploaded on a CV disappears

**Product Flavor**
- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Create a resume
2. Add an image (profile picture)
3. Wait a few days
4. The image will go in 404

**Expected behavior**
The image should always be available

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: Latest Production release
 
**Additional context**

**Comment by ajm1014** [comment]
I've had this happen to me as well, I found it takes place any time the container is destroyed and recreated - usually due to pulling a new docker image down. All of my other resume data is still there after it comes back up due to being saved in a volume, and it knows there should be an image, but the image remains blank until I "remove" it and add it again.

**Comment by AmruthPillai** [comment]
> I've had this happen to me as well, I found it takes place any time the container is destroyed and recreated - usually due to pulling a new docker image down. All of my other resume data is still there after it comes back up due to being saved in a volume, and it knows there should be an image, but the image remains blank until I "remove" it and add it again.

You have a good point there, the volumes are not mounted to local drives, so it could be the case that the volumes are recreated every time there's a new version.

Will require the insight of folks who better understand Docker for this. cc @modem7 @Leopere

**Comment by ajm1014** [comment]
I poked around a little bit, currently the only persistent volume configured in the docker-compose.yml file is for the postgres database, so everything other than that directory will be lost when the container is destroyed/recreated. I'm assuming the uploaded images are being saved outside that folder, so we should just need to add another persistent volume into the docker-compose.yml file which maps to the folder the images are being saved at (wherever that may be - I took a quick look through the code but wasn't able to find the path before needing to leave for work).

**Comment by modem7** [comment]
OK - so........good news and bad news.

Good news:
Adding a mapping to the server for:
`$USERDIR/ReactiveResume/uploads:/app/server/dist/assets/uploads `
works.

However......this only ever uploads a single image (replacing it):
![image](https://user-images.githubusercontent.com/4349962/160134246-48409e15-8b71-4427-8da8-9a0bbf27cf6a.png)


And an error comes up on the backend:
```
[Nest] 42  - 03/25/2022, 1:53:56 PM   ERROR [ExceptionsHandler] Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at ResumeService.deletePhoto (/app/server/dist/resume/resume.service.js:159:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Apart from the error, it seems to all be working as expected however.

**Comment by AmruthPillai** [comment]
Tracking this issue in #818, will update once there's a clear solution to it.
