### ISSUE TITLE
[BUG] 403 when uploading avatar, 404 when trying to fetch existing one

### ISSUE THREAD

**Issue by vitobotta** [AmruthPillai/Reactive-Resume#792]
**Describe the bug**
Hi! Thanks for the awesome project. I installed it with Docker on a server last week, and had some issues with uploads but I can't remember what it was and how I solved it unfortunately but anyway I managed to get it to work somehow.

Today I migrated everything to a new server, and have also updated the docker image tags to the latest version from yesterday.
Requests to fetch the avatar now return 404 (for the `https://cv.domain.com/api/assets/uploads/1/1/1648217615970.jpg` URL.
Thinking it was a permissions issue, I have even tried chmodding the bind mount for the uploads with 777 with no difference. The file exists and a local directory, containing the avatar I uploaded the other day, is mounted in the server container at /app/server/dist/assets/uploads/.

If I try to upload a new avatar, I get a 403 instead and the URL of the request for the upload is `https://cv.domain.com/api/assets/uploads/1/1/1648242415126.jpg`.

What am I missing? Thanks!

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted (Docker Compose)

**To Reproduce**

1. Try to load the page with an existing avatar or upload a new avatar

**Expected behavior**
I would expect the uploaded avatar to be fetched correctly, and to be able to change the avatar by uploading a new one.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser Chrome
 - Version 99

**Additional context**
Using the latest version v3.2.10 released yesterday.

**Comment by vitobotta** [comment]
Hi! This is really, _really_ weird: I just logged in the app to try again and my image was there! 😂 So to me the opposite of what described in that issue happened. How come?

**Comment by AmruthPillai** [comment]
Tracking this issue in #818, will update once there's a clear solution to it.
