### ISSUE TITLE
[BUG] Postgres database name

### ISSUE THREAD

**Issue by martadinata666** [AmruthPillai/Reactive-Resume#794]
**Describe the bug**
The insync name of POSTGRES make deploy hard on custom database name

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**
Change `POSTGRES_DATABASE=somecustomname`
As postgres custom database using `POSTGRES_DB=somecustomname`, the database won't be created 

**Expected behavior**
Same ENV, so POSTGRES can create database correctly.

**Comment by modem7** [comment]
Looks like this was a regression in ff8b22274fb743659f076aa1da5d85b501ef125f
