### ISSUE TITLE
[BUG] No Scroll Bar option in "Projects" section

### ISSUE THREAD

**Issue by oyeraghib** [AmruthPillai/Reactive-Resume#795]
**Describe the bug**
There is no option for scroll down while adding a new project in project section. Once you add more than few keywords and a long description for your project the "save button" get's below the window screen and there is no way to save the edited field
**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to Projects section
2. Click on Add New Projects
3. Write down a long words summary and add 10-12 keywords until the "Add new projects" button gets down below the screen.

**Expected behavior**
There should be a scroll bar which comes up as the content increases.

**Screenshots**
Screenshots attached
![res1](https://user-images.githubusercontent.com/40427461/160378728-88e80e8d-70a5-4d3a-9855-a821b7826495.png)
![res2](https://user-images.githubusercontent.com/40427461/160378745-052cbe42-150b-4baf-871f-966aaf5cdd97.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome
 - Version 99.0.4844.82 (Official Build) (64-bit)

**Additional context**

**Comment by AmruthPillai** [comment]
Thought merging the related PR would auto close this, weird. Thanks for the reminder :)
