### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ianj001** [AmruthPillai/Reactive-Resume#798]
**Describe the bug**

When creating a PDF, the profile picture is missing from the PDF output. 

**Product Flavor**
- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'Basics'
2. Click on 'Add picture'
3. Scroll down to 'Export PDF'
4. The PDF exports but the picture is missing. - This appears to be true using any of the templates.

**Expected behavior**

The PDF should include the picture that was uploaded as part of the resume
**Screenshots**

![PDFoutput](https://user-images.githubusercontent.com/15125933/160434850-7f71d4db-5ba8-4759-aed5-badcbb47b19a.png)

![Resumebuilder](https://user-images.githubusercontent.com/15125933/160434937-825ef259-053f-4ccd-9d31-354b2dab9f35.PNG)

**Desktop (please complete the following information):**
 - OS: 
 - Windows 10
 - Browser 
 - Microsoft Edge
 - Version 
 - Version 99.0.1150.46 (Official build) (64-bit)

**Additional context**

**Comment by modem7** [comment]
probably realated to https://github.com/AmruthPillai/Reactive-Resume/issues/790

**Comment by AmruthPillai** [comment]
Tracking this issue in #818, will update once there's a clear solution to it.
