### ISSUE TITLE
[Profile picture is not showing] 

### ISSUE THREAD

**Issue by anshuljain579** [AmruthPillai/Reactive-Resume#805]
**Describe the bug**
After preparing the resume, while exporting into pdf profile picture is not coming up
**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by modem7** [comment]
Probably related to https://github.com/AmruthPillai/Reactive-Resume/issues/790

Difficult to say without seeing your compose file.

**Comment by AmruthPillai** [comment]
Tracking this issue in #818, will update once there's a clear solution to it.
