### ISSUE TITLE
When the pdf is downloaded, image uploaded in the resume is not displayed / viewable[BUG] 

### ISSUE THREAD

**Issue by THEPETTA** [AmruthPillai/Reactive-Resume#807]
**Describe the bug**

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by AmruthPillai** [comment]
This should be resolved as of v3.3.3, could you please comment if this occurs again. Thank you :)
