### ISSUE TITLE
Portainer 2.11.1 Docker-Compose YAML Syntax Error

### ISSUE THREAD

**Issue by Judman** [AmruthPillai/Reactive-Resume#813]
Hello,

When copying the docker-compase.yml into Portainer stacks the below error is presented.

`There is an error in the yaml syntax: YAMLSemanticError: Map keys must be unique; "<<" is repeated`

**Comment by AmruthPillai** [comment]
Maybe it uses an older version of Docker Compose that doesn't support anchors? In that case, you should be able to just replace the anchor variables with the definitions on the top of the file. Let me know how that works out for you.

**Comment by Judman** [comment]
What version of docker compose is recommended for this project?
