### ISSUE TITLE
[BUG] 404, resume doesn't exist

### ISSUE THREAD

**Issue by MadhatterME** [AmruthPillai/Reactive-Resume#815]
**Describe the bug**

For reference my email is sre1001@jagmail.southalabama.edu. This is also what I used to sign in to your site/service. I have been using this service for some time now with much success. I logged on tonight to edit my past resume for a new opportunity and my resume doesn't exist. I had a copy bookmarked and I get the error 404 as if the page never existed. Is there a way to recover this or am I just lost. Windows 10 OS, using google chrome, the bookmarked page is rxresu.me/app/builder/9xiktz. Also I did save a JSON file and when I upload it, it just created a blank page. Any help would be marvelous!

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by AmruthPillai** [comment]
Could you try visiting https://v2.rxresu.me and logging in with your account there to check if your resume exists?

**Comment by MadhatterME** [comment]
You sir are both a scholar and a gentleman.  That worked, thanks so much!
