### ISSUE TITLE
[HELP] How to pick a Google font?

### ISSUE THREAD

**Issue by TENX-S** [AmruthPillai/Reactive-Resume#816]
![160982283-fe03a11c-dc31-4da1-80bd-ade93a4c7317](https://user-images.githubusercontent.com/40336192/162220745-8c2c7b14-0000-4b2b-8958-9df9cccefddc.png)
I only found these 8 fonts available.
I have asked this quesition at https://github.com/AmruthPillai/Reactive-Resume/discussions/803

**Comment by AmruthPillai** [comment]
In the new Reactive Resume (v3) you should be able to pick any Google Font you want. Try it out at https://rxresu.me, and remember to clear your cache. If you need access to your old data on v2, you can always access https://v2.rxresu.me and login there.
