### ISSUE TITLE
[COMPOSE FIX] Portainer: << is repeated

### ISSUE THREAD

**Issue by Pheggas** [AmruthPillai/Reactive-Resume#824]
Hello. As i'm deploying stuff in portainer, and portainer doesn't like weird techniques of compose yaml writting, could you fix references in docker-compose.yml?

It is like:
<<: *env-shared
<<: *env-server

And it has to be:
<<: [*env-shared, *env-server]

for Portainer.

**Comment by wolkenschieber** [comment]
Same here, vscode is giving me `Map keys must be unique` and services won't spin up despite env vars being set:
```
server    | Error: Config validation error: "SECRET_KEY" is required. "POSTGRES_HOST" is required. "POSTGRES_DB" is required. "POSTGRES_USER" is required. "POSTGRES_PASSWORD" is required. "JWT_SECRET" is required. "JWT_EXPIRY_TIME" is required
server    |     at Function.forRoot (/app/node_modules/.pnpm/@nestjs+config@2.0.0_7670df531e7a1503cdbe395599f41db7/node_modules/@nestjs/config/dist/config.module.js:75:23)
server    |     at Object.<anonymous> (/app/server/dist/config/config.module.js:55:35)
server    |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
server    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
server    |     at Module.load (node:internal/modules/cjs/loader:981:32)
server    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
server    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
server    |     at require (node:internal/modules/cjs/helpers:102:18)
server    |     at Object.<anonymous> (/app/server/dist/app.module.js:17:25)
server    |     at Module._compile (node:internal/modules/cjs/loader:1103:14)

```

**Comment by AmruthPillai** [comment]
Would be happy to merge a PR with this change, as Docker is not really my area of expertise. I wasn't able to find any documentation on YAML anchors either.

**Comment by wolkenschieber** [comment]
I'd love to see a composition example. Avoiding environment variable duplication is a hard task in compose files.

**Comment by Pheggas** [comment]
> Same here, vscode is giving me `Map keys must be unique` and services won't spin up despite env vars being set:
> 
> ```
> server    | Error: Config validation error: "SECRET_KEY" is required. "POSTGRES_HOST" is required. "POSTGRES_DB" is required. "POSTGRES_USER" is required. "POSTGRES_PASSWORD" is required. "JWT_SECRET" is required. "JWT_EXPIRY_TIME" is required
> server    |     at Function.forRoot (/app/node_modules/.pnpm/@nestjs+config@2.0.0_7670df531e7a1503cdbe395599f41db7/node_modules/@nestjs/config/dist/config.module.js:75:23)
> server    |     at Object.<anonymous> (/app/server/dist/config/config.module.js:55:35)
> server    |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
> server    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
> server    |     at Module.load (node:internal/modules/cjs/loader:981:32)
> server    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> server    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
> server    |     at require (node:internal/modules/cjs/helpers:102:18)
> server    |     at Object.<anonymous> (/app/server/dist/app.module.js:17:25)
> server    |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
> ```
> 
> Seems that docker-compose doesn't like this syntax. It'll only include `env-shared`, but not `env-server`. The canonical format via `docker-compse convert` show that the variables are missing:
> 
> ```yaml
>  (...)
>  server:
>     container_name: server
>     depends_on:
>       postgres:
>         condition: service_started
>       traefik:
>         condition: service_started
>     environment:
>       PUBLIC_GOOGLE_CLIENT_ID: ""
>       PUBLIC_SERVER_URL: http://localhost/api
>       PUBLIC_URL: http://localhost
>       TZ: UTC
>     image: amruthpillai/reactive-resume:server-latest
> (...)
> ```

I'm having same error that those envs are missing. Created issue #825 but didn't know it's caused by portainer / docker-compose compatibility.

**Comment by wolkenschieber** [comment]
Merging arrays in yaml-files isn't possible. Do I understand https://github.com/yaml/yaml/issues/35 correctly?
