### ISSUE TITLE
[BUG] Can't find any Resumes that were created earlier

### ISSUE THREAD

**Issue by crazyuploader** [AmruthPillai/Reactive-Resume#831]
**Describe the bug**
I've logged in Reactive-Resume after some months, and now using the same Google Account I used to log in with, shows me no resumes, I've had 2-3 resumes created earlier, not sure where they went.

**Product Flavor**
- [x] Managed (https://rxresu.me)

**To Reproduce**

1. Go to [https://rxresu.me/](https://rxresu.me/)
2. Click on 'Login'
3. Use Google Account to login
4. See no Resumes!!

**Expected behavior**
There should've been 2-3 resumes that I had created earlier.

**Screenshots**
![image](https://user-images.githubusercontent.com/49350241/162659203-927101b0-4dad-47f1-b5b1-3fc4b57c0ba8.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Browser Microsoft Edge
 - Version 100.0.1185.36

**Comment by AmruthPillai** [comment]
Please use https://v2.rxresu.me to access your older resumes :)
