### ISSUE TITLE
[FEATURE] Just like Twitter logo appering on Profiles section, it will be good if other "Coding related" sites like "CodeForces"\"Hackerrank"\"Codechef" will added then new CS Students can add it on Profiles

### ISSUE THREAD

**Issue by KunalSin9h** [AmruthPillai/Reactive-Resume#834]
**Solution : **
Just add the logo of Codeing related sites like "CodeForces" when add on Profile just like Twitter

**Comment by AmruthPillai** [comment]
Do you have a list of websites that you'd want to see? For now, I'll add CodeForces, HackerRank and CodeChef :) You should see the change as of v3.4.0

**Comment by dev-abir** [comment]
Also add GeeksforGeeks and Leetcode :)

**Comment by KunalSin9h** [comment]
**HackerEarch** & **AtCoder** is also popular among competitive coding communities, we can add that, too.

**Comment by dev-abir** [comment]
I couldn't find an icon for AtCoder in the icon packs used in this project.
There's an open [issue](https://github.com/simple-icons/simple-icons/issues/7119) related to this.

Maybe it will be better to provide an option to upload an image / SVG for a particular profile icon
