### ISSUE TITLE
[FEATURE] Download opens in a new tab

### ISSUE THREAD

**Issue by mrvaghani** [AmruthPillai/Reactive-Resume#835]
**Is your feature request related to a problem? Please describe.**
It's a little frustrating when I click download and the tab I have open goes to the rendered PDF.

**Describe the solution you'd like**
When download button is clicked, it would be nice to have it open the rendered PDF in a new tab.

**Describe alternatives you've considered**
Make the download button a link that we can click on to open in a new tab? Not sure if this is technically possible since I don't have much experience with frontend development

**Comment by AmruthPillai** [comment]
The downloaded PDF gets downloaded automatically onto your system, and not on the same tab. Could you please let me know what browser you are using, and on what machine, so I can recreate the issue better?

**Comment by mrvaghani** [comment]
Hi, thanks for following up on the issue I opened.

Firefox 99.0.1 (64-bit)
Windows 10 21H2 (OS Build 19044.1645)
