### ISSUE TITLE
Unable to create nested list in markdown

### ISSUE THREAD

**Issue by mainakk** [AmruthPillai/Reactive-Resume#840]
**Describe the bug**
I cannot create nested list using indentation in markdown syntax.

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Choose any field with markdown support in the resume builder.
2. Type:
```
- First item
- Second item
- Third item
    - Indented item
    - Indented item
- Fourth item
```
3. A flat list is generated in the output.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 100.0.4896.127

**Comment by hzchng** [comment]
It work when adding manual padding to Custom CSS.
`
div.markdown > ul > li > ul {
    padding-left: 20px;
    font-size: smaller;
}
`
