### ISSUE TITLE
[FEATURE] Roll back to old version?

### ISSUE THREAD

**Issue by ChenchaoZhao** [AmruthPillai/Reactive-Resume#845]
There are tons of bugs in the new version.
Can you roll back to the old version (v2 I think)?

**Comment by AmruthPillai** [comment]
What bugs are stopping you? As far as I've seen from most users, v3 has been a better experience for them. If you still prefer v2, you can access it at https://v2.rxresu.me

**Comment by ChenchaoZhao** [comment]
Thanks!
Often when I load my json generated by v2 into v3 it says "undefined"
Sometimes it worked but when I saved it as json and reload, it erased all the info.
Not sure new json generated by v3 got the same bug or not.
But v3 is definitely backward compatibility breaking.
