### ISSUE TITLE
Passing in env in Docker doesn't work

### ISSUE THREAD

**Issue by Tonvengo** [AmruthPillai/Reactive-Resume#848]
Hi. I am trying to setup reactive-resume v3 on my Synology NAS in a docker. I am passing environment variables but I am getting the same error as in this bug report: #436. Shell into the container shows that all variables are set (including GOOGLE_API_KEY). 

![image](https://user-images.githubusercontent.com/18616530/164069662-8b8b4a0f-31d5-483c-86fd-d5d4766a488c.png)
![image](https://user-images.githubusercontent.com/18616530/164069402-b0f664d1-8e74-4074-a469-36280d7d1c51.png)

**Comment by AmruthPillai** [comment]
Shouldn't there be a `PUBLIC_GOOGLE_CLIENT_ID` env variable as well?

**Comment by Tonvengo** [comment]
@AmruthPillai In documentation it says that PUBLIC_GOOGLE_CLIENT_ID is not required. This field is only required if the Google Login functionality is important to you. Should I still add it with empty value or documentation is wrong and it is required?

**Comment by AmruthPillai** [comment]
Oh, got it. Yes, it's not necessary. I'm wondering where this error is coming from, most probably the Google API Key. Ensure that you have enabled the Google Web Fonts API on the Cloud Console for it to work.

It's in my roadmap to make the Google API Key optional for Google Fonts as well, and just cache the result locally.

**Comment by Tonvengo** [comment]
@AmruthPillai I am still getting black screen, but I can see from chrome console that some fonts were loaded. Is this google fonts?
![image](https://user-images.githubusercontent.com/18616530/164297181-ea5e3736-f3d8-4d8f-adb5-69aab161ea0d.png)

**Comment by AmruthPillai** [comment]
As of v3.4.0, you would not require a Google API Key to fetch fonts as the response is cached on the source :)
