### ISSUE TITLE
[BUG] links in Preview not opening in new tab.

### ISSUE THREAD

**Issue by Hypernovic** [AmruthPillai/Reactive-Resume#850]
### Description
The links displayed in the preview opens within the current window, hence losing all the progress made,
Really frustrating to see hours of work getting lost due to a single mis-click.

### Reproduction
1. Create any type of link and display it on the preview,
2. Click on the link
3. Voila, There's your bug, it opens in a new window and without saving the progress

**Comment by AmruthPillai** [comment]
Which browser and template within Reactive Resume are you using? As I've checked, almost all of the templates have a target="_blank" attribute and testing the same on production, it seems that all links open in a new tab.
