### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hiramfromthechi** [AmruthPillai/Reactive-Resume#852]
**Describe the bug**
Blank screen with the following error message: `Application error: a client-side exception has occurred (see the browser console for more information).`

**Product Flavor**
- [X] Managed (https://rxresu.me)
- [] Self Hosted

**To Reproduce**

1. Drag and drop an item from the Work Experience section to the Projects section.
2. See error message.

**Expected behavior**
Work experience item drops into Projects section instead.

**Screenshots**
Video here: https://share.swyftlight.com/v/WDz8PxHGhiVJBdv5rmLJ 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 99.0.1 (64-bit)

**Additional context**
Was able to recreate the bug 3 times by quickly loading the sample data.

**Comment by AmruthPillai** [comment]
This should be fixed as of v3.4.0.
