### ISSUE TITLE
[BUG] You can't change the template in v3

### ISSUE THREAD

**Issue by JorelAli** [AmruthPillai/Reactive-Resume#854]
**Describe the bug**
Clicking on a template name in a resume doesn't do anything

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to https://rxresu.me and log in
2. Create a new (blank) resume
3. Load the sample data by going to Settings > Load sample data
4. Scroll to the top of the right panel and click any of the template names

**Expected behavior**

The resume's template changes to the template name that was clicked

**Screenshots**

![image](https://user-images.githubusercontent.com/4613171/164803845-84904049-c70d-4278-9abd-f19af77a597e.png)

**Desktop (please complete the following information):**
 - OS:  NixOS 20.03 (Linux)
 - Browser  Brave
 - Version  1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)

**Additional context**

This works flawlessly in the v2 version of RxResume

**Comment by AmruthPillai** [comment]
I was not able to reproduce this issue on my system. Does this continue to happen even now?

**Comment by JorelAli** [comment]
Can confirm this issue can't be reproduced (upgrading Chromium from 86.0.4240.111 to 96.0.4664.110 fixed this issue)
