### ISSUE TITLE
[FEATURE] 2 Factor Auth

### ISSUE THREAD

**Issue by aazam476** [AmruthPillai/Reactive-Resume#856]
**Is your feature request related to a problem? Please describe.**
Allow users to add 2FA to their accounts.

**Describe the solution you'd like**
Make a page (accessible by pressing on their name where you would usually logout) where a user can edit their username, password, or of course, add 2FA to their account if needed.

**Describe alternatives you've considered**
It would be great if you could allow MFA, for example, with Duo. A user would of course need to provide their own Duo keys.

**Comment by AzamServer** [comment]
Are there any plans for this?
