### ISSUE TITLE
[BUG] Onyx template markdown links break when word-wrapped

### ISSUE THREAD

**Issue by beans42** [AmruthPillai/Reactive-Resume#862]
**Describe the bug**
On exported Onyx template, in markdown sections, when a link is too long and has to be word-wrapped, its 'hitbox' becomes a rectangle spanning the entire wrapped-region.

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
1. Choose Onyx template
2. Load sample data
3. Replace "Summary" section with the following:
4. Export to pdf
5. The link for "web solutions for diverse industry" covers multiple lines and makes the "experience" link unclickable

```
I am a creative frontend developer offering 4+ years of [experience](https://github.com/) providing high-impact [web solutions for diverse industry](https://example.com/) organizations. Skilled in designing, developing and testing multiple web-based applications incorporating a range of technologies. Aspiring to combine broad background with strong technical skills to excel as a frontend web developer.
```

**Expected behavior**
Link "hitbox" is only as big as its display text, like it is before exporting to pdf.

**Comment by bhumit070** [comment]
Hi @beans42  can you please make a video or something I tried to reproduce this but unable to do it

**Comment by beans42** [comment]
The reproduction has changed a bit since I made this issue. You used to be able to put markdown in the text box for the sections but now you have to use the hyperlink button. Using the hyperlink button, it seems the issue is no longer present as of current release ([repro here](https://rxresu.me/bruhlmao22/then-definite-kite), export to pdf).

![image](https://github.com/AmruthPillai/Reactive-Resume/assets/53321702/699f1b5c-5ec0-4ef2-8ce6-b1e7df7b516a)
In the above image, the 'hitbox' of the link used to be the green area, which was wrong. Now it is the red area.
Closing this issue as it was already fixed.
