### ISSUE TITLE
Resume Deleted by itself

### ISSUE THREAD

**Issue by jasjyotsinghjaswal** [AmruthPillai/Reactive-Resume#864]
I logged in using my google account and could see my 2 resumes , but a moment later it disappeared and I could only see options for creating resume from scratch

**Comment by AmruthPillai** [comment]
That's weird. Could you share the ID of your resumes if you still have them, possibly? Otherwise, you could also share your username/email address (over email, im.amruth@gmail.com) so we can help each other diagnose the issue.

**Comment by jasjyotsinghjaswal** [comment]
Hi Amruth,
Sure . I used google account to login which is jasjyotsingh2007@yahoo.com . If you cant see this email id its probably jasjyotsingh2008@gmail.com or jasjyotsingh2008@gmail.com . Both these email ids point to the same . I am not sure how to share the resume id. Basically this happened after I logged in a after a long time and first time after you revamped the site and as I described the resumes appeared for a second and then disappeared

**Comment by AmruthPillai** [comment]
Could it be that you created your resumes on v2? You could check https://v2.rxresu.me and login, to see if your resumes still exist. If not, please let me open and I can reopen the issue to check how v3 resumes could get deleted.
