### ISSUE TITLE
[BUG] Build client error `'PersistGate' cannot be used as a JSX component.'`

### ISSUE THREAD

**Issue by martadinata666** [AmruthPillai/Reactive-Resume#869]
**Describe the bug**
Locally building reactive-resume failed

**Error Log**
```
Failed to compile.
./pages/_app.tsx:36:12
Type error: 'PersistGate' cannot be used as a JSX component.
  Its instance type 'PersistGate' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/builds/youWSuc7/0/dedyms/reactive-resume/reactive-resume/node_modules/.pnpm/@types+react@18.0.8/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
  34 |       <ReduxProvider store={store}>
  35 |         <LocalizationProvider dateAdapter={DateAdapter}>
> 36 |           <PersistGate loading={null} persistor={persistor}>
     |            ^
  37 |             <QueryClientProvider client={queryClient}>
  38 |               <WrapperRegistry>
  39 |                 <Loading />
undefined
```

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. git update
2. pnpm install --frozen-lockfile
3. pnpm -F schema build
4. pnpm -F server build
5. pnpm -F client build

**Expected behavior**
Building js success

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Dockerized build: node:lts

**Additional context**
Some info said that due react 18 upgrade. need further investigation.
* https://serveanswer.com/questions/react-native-persistgate-cannot-be-used-as-a-jsx-component-its-instance-type-persistgate-is-not-a-valid-jsx-element
* https://bobbyhadz.com/blog/react-cannot-be-used-as-a-jsx-component

**Comment by AmruthPillai** [comment]
So weird, and unfortunate. It's not a good day when StackOverflow suggests that the best way to solve the issue is to downgrade your versions. I'll create a commit to doing that in a bit.

**Comment by martadinata666** [comment]
The last downgrade dependencies commit fixes it, closed now.
https://github.com/AmruthPillai/Reactive-Resume/commit/9a18e74b900521f50e67a31e908d6ac2f16f3450

Thanks
