### ISSUE TITLE
[FEATURE] Toggling the visibility of individual items, instead of categories

### ISSUE THREAD

**Issue by jforseth210** [AmruthPillai/Reactive-Resume#872]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to hide a project, experience, award, etc, in order to save space on my resume or show only the most relevant information, while keeping the more important entries visible.

**Describe the solution you'd like**
An option to toggle the visibility of individual entries instead of or in addition to entire categories. 

**Describe alternatives you've considered**
Deleting the entry entirely. Works, but isn't great for quickly removing something to see how it looks. Ideally, I'd have a bunch of hidden entries that I'd be able to drop in depending on how much space I have, what seems most relevant. 

**Additional context**
Nope, I think that pretty much covers it. Huge thanks to the devs, this is a great project. I'm not sure how difficult this'd be to implement, but I'd love to see it added!

**Comment by nredick** [comment]
Would also love to see this feature

**Comment by AmruthPillai** [comment]
@nredick This feature already exists, you just need to right click on an item under any of the categories and you would see a toggle button to make an individual entry visible/invisible. I've attached a GIF showcasing this. On a laptop/PC, you would right click on an item, on the mobile or touch device, you need to long press on the item to bring up the context menu.

![Screen Recording June 1](https://github.com/AmruthPillai/Reactive-Resume/assets/1134738/b9abc90b-5450-4227-87c6-e25d5f50311b)
