### ISSUE TITLE
[BUG] Can't login with google account

### ISSUE THREAD

**Issue by kopach** [AmruthPillai/Reactive-Resume#873]
**Describe the bug**
When clicking "Login with Google" button - there is no popup to sign in with google account as it was before

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to https://rxresu.me/
2. Click on "Login"
3. Click on "Login with Google"
4. nothing happens

**Expected behavior**

I should be able to login as a user

**Screenshots**

![2022-05-05 10 07 21](https://user-images.githubusercontent.com/8749624/166884627-9bcc7846-bdf7-4c56-b07d-e22e40f35468.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser: Firefox & Chrome (including in private/incognito view)
 - Version: latest

**Comment by matheusdmm** [comment]
Try to recover your password inserting your gmail email, then change the password from the link in  your email inbox, you should be able to login with your gmail and password after that. 

It isn't the proper way to login, but at least you can. I'm trying to download some resumes in pdf and still had not any success.

**Comment by SammyM** [comment]
I have a slightly different issue. When I try to log in via Google, I see a pop-up, click the 'Continue' button, and then I get a 500 error back from Google's API so nothing happens.

**Comment by anishre** [comment]
I have the same issue. When I click the login with Google button, nothing happens at all.

**Comment by FoundTheWOUT** [comment]
Notice the right of the location, there is a eye. 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/47922588/173222559-74d315d2-c3ef-433b-8796-ea381a5039a2.png">
Click the eye, and allow the third-part Cookies. Then try to login again. 

---

I thougth we should alter some notification about the [Cookie Policy](https://stackoverflow.com/legal/cookie-policy) just like other website.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/47922588/173222753-766f332a-c185-4579-b5d4-88162ef4f0fe.png">
👆Stackoverflow did that.

**Comment by anishre** [comment]
> Notice the right of the location, there is a eye. <img alt="image" width="527" src="https://user-images.githubusercontent.com/47922588/173222559-74d315d2-c3ef-433b-8796-ea381a5039a2.png"> Click the eye, and allow the third-part Cookies. Then try to login again.
> 
> I thougth we should alter some notification about the [Cookie Policy](https://stackoverflow.com/legal/cookie-policy) just like other website. <img alt="image" width="330" src="https://user-images.githubusercontent.com/47922588/173222753-766f332a-c185-4579-b5d4-88162ef4f0fe.png"> 👆Stackoverflow did that.

So I'm on Firefox; reset and accepted the cookies to no avail, but I found a workaround -> clicked on forgot password and logged in via email and new password. Since it was the same google account it worked.

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)
