### ISSUE TITLE
[BUG]  Line breaks seems weird

### ISSUE THREAD

**Issue by jiemi** [AmruthPillai/Reactive-Resume#875]
**Describe the bug**
Line breaks seems weird

<img width="799" alt="image" src="https://user-images.githubusercontent.com/14103123/167052268-f46e1265-d067-4448-a99d-07ed8e835cb9.png">

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
1. it happens in very template

**Expected behavior**
I expected to see the line breaks is normal as the sample

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac os 12.2.1
 - Browser chrome and afari
 - Version Version Always the latest

**Additional context**

**Comment by AmruthPillai** [comment]
You'll need to change the number of columns for the section as well, depending on the template. In your case, the number is set to 2 currently, but you'll need it to be set to 1 to get the result you're looking for.

![Screenshot 2022-05-06 at 8 00 52 AM](https://user-images.githubusercontent.com/1134738/167075589-49aeeaaa-ee3e-45be-bf09-52d7e545a7ef.png)

**Comment by jiemi** [comment]
thanks！
