### ISSUE TITLE
[Feature] Support for JSONResume?

### ISSUE THREAD

**Issue by fonix232** [AmruthPillai/Reactive-Resume#88]
[JSONResume](https://jsonresume.org/) is an open specification meant to build resumes easily. I think it would be a great addition to the builder, as it would allow separating the content/metadata from the styling, and would also make your app more standard.

**Comment by AmruthPillai** [comment]
I've mentioned this before in previous issues. Basically, the structure of JSON I'm using is quite similar to JSONResume but is extended in many ways to include more customizability in terms of changing header names, specific to templates etc.

Currently, there's no plan to shift from the current structure as the app is integrated deeply with the current one, and breaking that would break older resumes that people have exported.

**Comment by binyamin** [comment]
@AmruthPillai What if you convert between the two formats on-the-fly? I think it's worth supporting import of JSON Resume, even if the initial output will be incomplete.

**Comment by AmruthPillai** [comment]
@binyamin This issue is from a long time ago. Reactive Resume v2 does support import of JSON Resume now :)

**Comment by binyamin** [comment]
@AmruthPillai do you think you could support export as well?

**Comment by AmruthPillai** [comment]
@binyamin The issue with export, is that Reactive Resume builds a lot on top of the original JSON Resume schema. On exporting, a lot of the information would be lost. But technically, it is possible. Will see if I can wedge this feature in, in one of the free weekends :)
