### ISSUE TITLE
[BUG] Wrong birth date after pdf export 

### ISSUE THREAD

**Issue by Koilanetroc** [AmruthPillai/Reactive-Resume#882]
**Describe the bug**
I set Date of birth for example to 20/06/1990(dd/mm/yyyy). When I export it to pdf the day is decreased by one for no reason - 19/06/1990

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
1. Set birthdate to value 20/06/1990(dd/mm/yyyy)
2. Export to pdf
3. The day of birthdate will be one day earlier then was provided on step 1

**Expected behavior**
Birth date should be the same as in the creator mode.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Google Chrome
 - Version 100

**Comment by linberson** [comment]
In the newest version this now happens to most dates. I just tested this in the managed app version.
It did not happen in my "certification" section, but for birthday and all dates in work experience/education/Projects/volunteering.

duplicates: 
https://github.com/AmruthPillai/Reactive-Resume/issues/890
https://github.com/AmruthPillai/Reactive-Resume/issues/962
https://github.com/AmruthPillai/Reactive-Resume/issues/929 (closed)
