### ISSUE TITLE
[BUG] Present date doesn't translate to Swedish

### ISSUE THREAD

**Issue by Danster2020** [AmruthPillai/Reactive-Resume#884]
**Describe the bug**
When editing the translation of "present" to swedish "Nuvarande" is correct. but when exporting as PDF the "present" does not translate into Swedish.

**Product Flavor**
- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Change language to "Swedish (Svenska)"
2. Create a date under education with present (no ending date).
3. See that it says "Nuvarande" (Present in Swedish).
4. Export as PDF.
5. The date has now changed to "Present"

**Expected behavior**
Should say "Nuvarande"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Firefox
 - Version 100.0

**Additional context**

**Comment by AmruthPillai** [comment]
Fixed in v3.4.5
