### ISSUE TITLE
[BUG] the PDF export does not translate the dates

### ISSUE THREAD

**Issue by kaspernine** [AmruthPillai/Reactive-Resume#893]
Dates are only exported in English in the PDF files despite the selection of a different language beforehand.

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
1. Go to the right panel
2. Select the language
3. Select the date format 
4. Click on PDF exporting button

**Expected behavior**
The DatePicker of all the Modals are well translated in the chosen language but as soon as you export in PDF, the dates are not translated anymore in the chosen language and remain in English. The PDF file must be fully translated.

**Screenshots**
In the editor (in french language) : ![image](https://user-images.githubusercontent.com/48528228/169662258-055c302a-fa6b-45fb-aac4-1feab4543a0d.png)
PDF export : ![image](https://user-images.githubusercontent.com/48528228/169662362-c62ce7db-be59-46b6-a28e-a510f42b1601.png)

**Desktop :**
 - OS: Windows 10 64 bits
 - Browser: Chrome
 - Version: 101.0.4951.67 (latest version)

**Comment by AmruthPillai** [comment]
Fixed in v3.4.5

**Comment by kaspernine** [comment]
thank you for your quick response !
