### ISSUE TITLE
[BUG] Once PDF downloaded "Present" is shown instead of selected language

### ISSUE THREAD

**Issue by Jonas-VanHaeken** [AmruthPillai/Reactive-Resume#897]
**Describe the bug**
After choosing a language in the right hand side bar the empty end dates change on screen from "Present" to "Huidig" in my case, but once i download the pdf it replaces them with "Present".

**Product Flavor**
- [ x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
1. Go To "Settings --> Global --> Language"
2. Select "Dutch (Nederlands)"
3. Enter some work experiences with an empty end date
4. Download the PDF

**Expected behavior**
The text in the pdf should say "Huidig" instead of "Present"

**Screenshots**
PDF
![image](https://user-images.githubusercontent.com/71443869/169880926-4080971e-5d9f-4951-99ba-bae663716a07.png)
WEB
![image](https://user-images.githubusercontent.com/71443869/169880982-5c710d40-2aad-4528-a91f-5b992ead951a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version 

**Additional context**

**Comment by AmruthPillai** [comment]
Fixed in v3.4.5
