### ISSUE TITLE
Client takes time for up on local[BUG] 

### ISSUE THREAD

**Issue by romilynxt** [AmruthPillai/Reactive-Resume#898]
**Describe the bug**

When running pnpm dev all folder starts running on local but the client is not getting up and is stuck at **LOG 🚀 Server is up and running!**

**Product Flavor**
- [ ] Self Hosted

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**
Sometimes it's working but most of the time it's stuck on the above error and whenever clicking on any link first it compiles all modules and which takes more than 5sec to load the page.

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)
