### ISSUE TITLE
[BUG] Generated PDF with only 1 long page instead of multiple A4 pages.

### ISSUE THREAD

**Issue by emanueol** [AmruthPillai/Reactive-Resume#899]
**Describe the bug**
I got a CV which looks like a 3 pages CV, but generated PDF is only 1 long page.

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**
Simply click generate PDF.

**Expected behavior**
Expected generated PDF to have multiple pages, and not just 1 long vertical page.

**Screenshots**
![image](https://user-images.githubusercontent.com/8422412/171025992-d2ddfad1-27d7-493b-8d77-1b9a12305a39.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 102.0.5005.63 (Official Build) (64-bit)

**Additional context**

**Comment by emanueol** [comment]
I know this is open source, but I got some urgency on having a PDF correctly generated with multiple pages, if you can please suggest workaround or fix, I would be greatly appreciated, thanks so much.

**Comment by parastuffs** [comment]
Seems like it's a "feature": https://github.com/AmruthPillai/Reactive-Resume/issues/732
In the "layout" section of the right sidebar, you can manually add pages and move relevant content over there.

Basically, there is no automatic page break, just an A4-limit notification that helps you fit everything inside an A4 page.

**Comment by zogith** [comment]
I am quite surprised and disappointed  this system works like this and the "solution" is to manually manage the pagination of the thing myself, by splitting larger sections into different sections that live on different pages.

Especially when there seems to be no easy way to do this. I just spent time adding in all my work experience.. now I have to laboriously duplicate it into a second (and third.. and .) Work Experience.. Cont. section and fit them on the next pages.. why doesn't it do it itself, when the page view inserts "page breaks" that are not used? Or at least have a "copy section" function so I can copy my "main" work experience section a few times, hide it, and edit down the copies into smaller chunks.. but this is the sort of thing I would expect pagination on a PDF generating application to deal with itself.

Hopefully the XML backup of the resume created can be imported into another tool so I just haven't entirely wasted all this effort.

Except for this pagination issue the created PDF resume and tools for managing look really good.

**Comment by lyrad87** [comment]
I totally agree with zogith and the OP. Please make this a priority, if possible, because the "Work Experience Cont." looks non-professional and it would be much easier to have simple page breaks.

**Comment by AmruthPillai** [comment]
It's easier said than done unfortunately. I spent my nights trying to figure out how to "auto magically" format layouts and ensure that page breaks occur when the user wants, and not when HTML/CSS decide it should. The most versatile solution I had that gives complete control to the user was to create sections and move sections around pages.

Also, if the words "Work Experience Cont." looks unprofessional, you could create the section with no name (or just Work Experience) and use the same section name, on the new page. Yes, in an ideal world, I wish I could add page breaks like in Microsoft Word and allow users to add a break anywhere, but the structure of how the templating engine is set up doesn't allow for this as far as I see it.

Right now, the only option to span your experience or any other section to multiple pages is to create a custom section and add the rest of your fields there and move the new section to a new page. It might seem like a hack, but it's a feature ✨
