### ISSUE TITLE
[Feature] Multiple "Work Experience" Sections

### ISSUE THREAD

**Issue by oneMadRssn** [AmruthPillai/Reactive-Resume#90]
I suggest making it possible to have multiple Experience sections. In some fields, it is common to separate out relevant experience from general experience. Currently there can only be one Work Experience section.

For example: Lawyer resumes will have sections for "Legal Experience" and "Other Experience." Teacher resumes may have sections for "Teaching Experience" and "General Experience." Project management resumes may have sections for "Technical Experience" and "Management Experience."

**Comment by AmruthPillai** [comment]
Quoted by @n-goyal on #93:

> As of now i couldn't find any functionality to customize different blocks in resume. Resume varies person to person, profession to profession and that's why customizable blocks, I think, are must to have when target is a larger audience.
> 
> There can be one Option in settings to enable or disable or to create some blocks as per the user requirement, there is no doubt this would enable a larger set of people to actually customize the resume.
> 
> Now, I know the templates have already been defined in the system. which is why i think there is no option to customizable blocks. But one or two flexible, basic templates can be added. And if user adds a new block that block can be appended in the last.
> 
> Anyway, I love your app and documentation both. <3

**Comment by AmruthPillai** [comment]
This requires a bit more research as the current template structure does not support dynamic sections. I will soon look into a new system of developing templates that can load sections dynamically, which would make this possible.

Will be keeping this issue open for further discussion, in case anyone has any ideas or wants an extension on the same feature.

Thank you, everyone, for your feedback and suggestions. You make the work I do meaningful, really appreciate it.
