### ISSUE TITLE
Sections over multiple pages

### ISSUE THREAD

**Issue by GuidoWilden** [AmruthPillai/Reactive-Resume#904]
Hello,

I'm unable to fit the Work Experience section onto one page. Is there a way to have this flow over multiple pages. I can't seem to find out how.

Thank you

**Comment by zogith** [comment]
same as this issue, in short, no.. 
https://github.com/AmruthPillai/Reactive-Resume/issues/899

**Comment by AmruthPillai** [comment]
Duplicate issue, also made a comment here explaining how this is possible at the moment:
https://github.com/AmruthPillai/Reactive-Resume/issues/899#issuecomment-1217529129
