### ISSUE TITLE
Resume up and running but cannot register

### ISSUE THREAD

**Issue by swoop124** [AmruthPillai/Reactive-Resume#909]
hello everyone,

i just have installed reactive-resume using this docker-compose wia portainer:
```
version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - /opt/resume/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  server:
    image: amruthpillai/reactive-resume:server-latest
    # build:
    #   context: .
    #   dockerfile: ./server/Dockerfile
    container_name: server
    environment:
      - TZ=CET
      - PUBLIC_URL=http://rx.domain.tld:3000
      - PUBLIC_SERVER_URL=http://rx.domain.tld:3000/api
      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SECRET_KEY=secret
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=secret
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - SENDGRID_API_KEY=
      - SENDGRID_FORGOT_PASSWORD_TEMPLATE_ID=
      - SENDGRID_FROM_NAME=
      - SENDGRID_FROM_EMAIL=
      - STORAGE_BUCKET=
      - STORAGE_REGION=DE
      - STORAGE_ENDPOINT=
      - STORAGE_URL_PREFIX=
      - STORAGE_ACCESS_KEY=
      - STORAGE_SECRET_KEY=
    depends_on:
      - postgres
    restart: always

  client:
    image: amruthpillai/reactive-resume:client-latest
    # build:
    #   context: .
    #   dockerfile: ./client/Dockerfile
    container_name: client
    ports:
      - 3000:3000
    environment:
      - TZ=CET
      - PUBLIC_URL=http://rx.domain.tld:3000
      - PUBLIC_SERVER_URL=http://rx.domain.tld:3000/api
      - PUBLIC_GOOGLE_CLIENT_ID=
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false
    depends_on:
      - server
    restart: always
```
so far so good. It is coming up and it seems to work.
But when i try to register and enter all fields then cklick register, nothing happens. No error message anywhere. It does just nothing.

Do i have to enter all Storage fields, in order to make it work, or can i just test, if i can get in?

thx

**Comment by swoop124** [comment]
hello,

ok, installed my own s3 bucket (minio), to test if this is the reason that i can not create a user. I used S3browser to test it. I could save files on this storage.
But what is the difference between these two environment variables?
STORAGE_ENDPOINT=
STORAGE_URL_PREFIX=
i put the same url in there. Is that ok or should that be different?

**Comment by swoop124** [comment]
hello guys,

realy nobody any ideas?

thx

**Comment by Death-Pact** [comment]
I am getting the same problem. I have a very similar compose file. Cannot register and the server and client seem to be running correct. 


I will attach the logs for my containers. The only one  that seems to be failing is postgres.

client:
> reactive-resume@3.4.6 start:client /app
> pnpm -F client start
> @reactive-resume/client@ start /app/client
> react-env --prefix PUBLIC -- next start
react-env: Writing runtime env /app/client/public/__ENV.js
ready - started server on 0.0.0.0:3000, url: http://localhost:3000



server:
> reactive-resume@3.4.6 start:server /app
> pnpm -F server start:prod
> @reactive-resume/server@ start:prod /app/server
> node dist/main
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [NestFactory] Starting Nest application...
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +145ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] DatabaseModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] MailModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] HttpModule dependencies initialized +2ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +2ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] ServeStaticModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
API key does not start with "SG.".
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] HealthModule dependencies initialized +3ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] MailModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] JwtModule dependencies initialized +160ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] PrinterModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:51:58 PM     LOG [InstanceLoader] FontsModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +1260ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] ResumeModule dependencies initialized +4ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [InstanceLoader] IntegrationsModule dependencies initialized +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RoutesResolver] AuthController {/auth}: +9ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth, GET} route +3ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth/google, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth/register, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth/login, POST} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth/forgot-password, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth/reset-password, POST} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/auth, DELETE} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RoutesResolver] ResumeController {/resume}: +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume, GET} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/short/:shortId, GET} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:username/:slug, GET} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id, GET} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id, PATCH} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id, DELETE} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id/duplicate, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id/sample, POST} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id/reset, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id/photo, PUT} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/resume/:id/photo, DELETE} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RoutesResolver] FontsController {/fonts}: +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/fonts, GET} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RoutesResolver] IntegrationsController {/integrations}: +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/integrations/linkedin, POST} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/integrations/json-resume, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/integrations/reactive-resume, POST} route +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/integrations/reactive-resume-v2, POST} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RoutesResolver] PrinterController {/printer}: +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/printer/:username/:slug, GET} route +1ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RoutesResolver] HealthController {/health}: +0ms
[Nest] 42  - 06/20/2022, 1:52:00 PM     LOG [RouterExplorer] Mapped {/health, GET} route +0ms
[Nest] 42  - 06/20/2022, 1:52:10 PM     LOG [NestApplication] Nest application successfully started +10463ms
[Nest] 42  - 06/20/2022, 1:52:10 PM     LOG 🚀 Server is up and running! 



Postgres:
PostgreSQL Database directory appears to contain a database; Skipping initialization
2022-06-20 17:51:41.573 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
2022-06-20 17:51:41.573 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-06-20 17:51:41.573 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-06-20 17:51:41.647 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-06-20 17:51:41.790 UTC [21] LOG:  database system was shut down at 2022-06-20 17:51:13 UTC
2022-06-20 17:51:41.981 UTC [1] LOG:  database system is ready to accept connections
2022-06-20 17:52:11.151 UTC [35] FATAL:  role "postgres" does not exist
2022-06-20 17:52:41.356 UTC [43] FATAL:  role "postgres" does not exist
2022-06-20 17:53:11.635 UTC [52] FATAL:  role "postgres" does not exist
2022-06-20 17:53:41.890 UTC [60] FATAL:  role "postgres" does not exist
2022-06-20 17:54:12.087 UTC [69] FATAL:  role "postgres" does not exist
2022-06-20 17:54:42.313 UTC [77] FATAL:  role "postgres" does not exist
2022-06-20 17:55:12.504 UTC [86] FATAL:  role "postgres" does not exist
2022-06-20 17:55:42.740 UTC [95] FATAL:  role "postgres" does not exist

**Comment by swoop124** [comment]
hello,

i think the problem is at postgres.
you could restart the whole stack, maybe it will create the database.
Or maybe delete all files and recreate the stack.

**Comment by swoop124** [comment]
hello, 

now i have recreated my resume containers, now i get the same error:
```
[36] FATAL:  role "postgres" does not exist
[45] FATAL:  role "postgres" does not exist
[54] FATAL:  role "postgres" does not exist
```

**Comment by swoop124** [comment]
hallo again,

the problem with the `FATAL:  role "postgres" does not exist` is the dbname, dbuser, dbpass.
change it all to `postgres`. That is the solution to this error.
But i am still not able to register, no error, no warning, nothing unusual.
Where are ohter logs or something that tell me where to look?

**Comment by Death-Pact** [comment]
Can confirm that deleting my volumes and resetting all those env settings to "postgres" does get rid of the errors.

Still cannot register. I am getting no errors in the logs. Everything seems to be working fine. I am at a loss.

**Comment by swoop124** [comment]
Hello,

i autoupdated my docker Image with Watchtower to 3.5.1 but i can still not register.

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)

**Comment by swoop124** [comment]
Hello,

i know, this thread is a little old but, i did manage to get some now infos.
In my opinion it has to do something with my Reverse Proxy. I have Nginx Proxy Manager runing on a different machine.

Now i run Reactive Resume 3.6.18 with pretty much the same Docker-Compose file.

```
version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw

  server:
    image: amruthpillai/reactive-resume:server-latest
    restart: always
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=http://rx.domain2.tld
      - PUBLIC_SERVER_URL=http://rx.domain.tld
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=change-me-to-something-secure
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=change-me-to-something-secure
      - JWT_EXPIRY_TIME=604800

  client:
    image: amruthpillai/reactive-resume:client-latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=http://rx.domain2.tld
      - PUBLIC_SERVER_URL=http://rx.domain.tld
```

When i run this docker-compose stack on a machine with direkt dns A record then it is working. But than i have to add ports to the urls.

**Comment by geek111** [comment]
It seems reasume-server have problem connect to database.
I try on dockler run in the same internet adapter and try ping name "postgres" and this dns record moves to correct IP address but in log in reasume-server still have error connection to database.
I install postgres to my other instance in docker and try test connect to this postgres database and its connected correctly with same username, password, host and database name so I dont kont what is going on.

> 2023-06-03T13:18:27.788547808Z server start: [Nest] 66  - 06/03/2023, 1:18:27 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
2023-06-03T13:18:27.789238048Z server start: Error: The server does not support SSL connections
2023-06-03T13:18:27.789304878Z server start:     at Socket.<anonymous> (/app/node_modules/.pnpm/pg@8.10.0/node_modules/pg/lib/connection.js:76:37)
2023-06-03T13:18:27.789354612Z server start:     at Object.onceWrapper (node:events:628:26)
2023-06-03T13:18:27.789390728Z server start:     at Socket.emit (node:events:513:28)
2023-06-03T13:18:27.789425127Z server start:     at addChunk (node:internal/streams/readable:324:12)
2023-06-03T13:18:27.789471387Z server start:     at readableAddChunk (node:internal/streams/readable:297:9)
2023-06-03T13:18:27.789505101Z server start:     at Readable.push (node:internal/streams/readable:234:10)
2023-06-03T13:18:27.789541406Z server start:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2023-06-03T13:18:27.789574851Z server start: [Nest] 66  - 06/03/2023, 1:18:27 PM   ERROR [ExceptionHandler] The server does not support SSL connections
2023-06-03T13:18:27.789623639Z server start: Error: The server does not support SSL connections
2023-06-03T13:18:27.789655614Z server start:     at Socket.<anonymous> (/app/node_modules/.pnpm/pg@8.10.0/node_modules/pg/lib/connection.js:76:37)
2023-06-03T13:18:27.789689121Z server start:     at Object.onceWrapper (node:events:628:26)
2023-06-03T13:18:27.789718343Z server start:     at Socket.emit (node:events:513:28)
2023-06-03T13:18:27.789746920Z server start:     at addChunk (node:internal/streams/readable:324:12)
2023-06-03T13:18:27.789776738Z server start:     at readableAddChunk (node:internal/streams/readable:297:9)
2023-06-03T13:18:27.789806356Z server start:     at Readable.push (node:internal/streams/readable:234:10)
2023-06-03T13:18:27.789836780Z server start:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2023-06-03T13:18:27.800445944Z server start: Failed

>
