### ISSUE TITLE
[BUG] Website automatically creates the two column if work experience is added

### ISSUE THREAD

**Issue by nainaraut** [AmruthPillai/Reactive-Resume#911]
**Describe the bug**
Website seems to create the two column if work experience is added!
So in total there are 2 columns getting created and there is no button to disable it. The formatting doesn't look good with three columns!

**Comment by lmioco** [comment]
Hello,
you can change the number of columns for every section by clicking on the icon with the columns
![image](https://user-images.githubusercontent.com/63474904/177031257-4d69f229-f01f-4ca8-9dea-2333d6b86209.png)
