### ISSUE TITLE
[BUG] Changing language only affects the editor view language

### ISSUE THREAD

**Issue by alimoncul** [AmruthPillai/Reactive-Resume#917]
**Describe the bug**
When getting export all the labels are returned to originals from English

**Product Flavor**
- [ ] Managed (https://rxresu.me)

**To Reproduce**

1. Select language as Turkish
2. Add a field
3. Export
4. See difference between export & editor

**Comment by NormalRandomPeople** [comment]
Exporting as JSON, editing it manually and then importing it again may do the trick.

**Comment by alimoncul** [comment]
Changing and refreshing before exporting works too. Another workaround.

**Comment by ayyilmaz** [comment]
I select Turkish on Editor page but it shows months as English on share link page.
