### ISSUE TITLE
[BUG] Sendgrid API key is used even when empty

### ISSUE THREAD

**Issue by michael-robbins** [AmruthPillai/Reactive-Resume#918]
**Describe the bug**
If I do not provide SENDGRID_API_KEY I see the following error message in my container logs: `API key does not start with "SG."`

This seems to be coming from here: https://github.com/AmruthPillai/Reactive-Resume/blob/main/server/src/mail/mail.service.ts#L10

Looks like we're initialising the mail service even if SendGrid tokens aren't available/are empty?

It would be nice if we only set the API Key if it's not an empty string/null.

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [X] Self Hosted

**Comment by AmruthPillai** [comment]
Got it, will fix this in an upcoming commit.
