### ISSUE TITLE
[FEATURE] Override the healthcheck domains

### ISSUE THREAD

**Issue by michael-robbins** [AmruthPillai/Reactive-Resume#919]
**Is your feature request related to a problem? Please describe.**
The current healthchecks for when self hosting reactive resume still attempt to resolve and talk to the hosted application `rxresu.me` and `docs.rxresu.me`

This can be seen here: https://github.com/AmruthPillai/Reactive-Resume/blob/main/server/src/health/health.controller.ts#L17-L18

Occasionally I will see these errors in my container logs:
```
[Nest] 42  - 06/18/2022, 8:22:33 PM   ERROR [HealthCheckService] Health Check has failed! {"docs":{"status":"down","message":"getaddrinfo ENOTFOUND docs.rxresu.me"}}
[Nest] 42  - 06/18/2022, 8:29:09 PM   ERROR [HealthCheckService] Health Check has failed! {"docs":{"status":"down","message":"getaddrinfo ENOTFOUND docs.rxresu.me"}}
```

**Describe the solution you'd like**
Ability to override these with environment variables or reference something like localhost to check if the local app is indeed up.

**Describe alternatives you've considered**
Otherwise can we disable this for the client & server healthchecks?

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)
