### ISSUE TITLE
[Bug] Photo Not Showing in PDF

### ISSUE THREAD

**Issue by thehappydinoa** [AmruthPillai/Reactive-Resume#92]
**Describe the Bug**
When I go to export my resume as a PDF, it is successful, but the photo from the photo url does not show.

**Reproduction**
Steps to reproduce the behaviour:
1. Go to Actions
2. Click on Save to PDF
3. Check PDF

**Expected Behaviour**
To see photo

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave

**Comment by AmruthPillai** [comment]
Could you provide some more information as to which template you tried using? What was the URL you input for the photo, and also have you tried uploading the image elsewhere like imgur.com and getting the link from there?

**Comment by ridzwanmidris** [comment]
Same issue here. But it only happens when I use the Celebi template.

**Comment by jamesrweb** [comment]
For me it's happening in the Onyx template and others so I think its more widespread.

**Comment by AmruthPillai** [comment]
This issue has been fixed with Celebi with PR #96, for the issue with Onyx, it can be discussed on issue #94 

Thanks for the reports and feedback everyone, really appreciate it :)
