### ISSUE TITLE
[BUG] Export to PDF broken

### ISSUE THREAD

**Issue by JPDucky** [AmruthPillai/Reactive-Resume#922]
**Describe the bug**
Export to PDF broken

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ x] Self Hosted

**To Reproduce**

1. Go to a resume
2. Click on export PDF

**Expected behavior**
PDF button acknowledges that it has been clicked, and either PDF download starts immediately or at least within the 15 seconds specified

**Actual Behavior**
PDF button acknowledges that it has been clicked, but nothing happens for any amount of time (ie waiting 20 minutes for the site to produce a PDF just in case it was being slow). Nothing shows in any of the logs for any of the containers, no error, no waiting, no acknowledgement that a PDF should be produced whatsoever.

**Desktop (please complete the following information):**
 - OS: fedora 36, kernel 5.17.4
 - Browser firefox 101.0
 - Version v3.4.5-6

**Additional context**

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)
