### ISSUE TITLE
[BUG] HTML ID should not start with a digit to be CSS compliant

### ISSUE THREAD

**Issue by parastuffs** [AmruthPillai/Reactive-Resume#923]
**Describe the bug**

The problem is that the HTML ID generated for each element can start with a number, which is not CSS compliant, making it impossible to customize the element's style.

The current workaround is to use the in-browser element inspector and generate duplicates of an element until they get an ID starting with a [a-zA-Z] character.

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

Try to change the CSS for an element through the right sidebar by specifying the ID.

**Expected behavior**
IDs should not start with a digit.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox
 - Version 101.0.1 (64-bit)

Cheers for the awesome tool anyway.

**Comment by AmruthPillai** [comment]
Should be fixed now :)
