### ISSUE TITLE
[FEATURE] An option to only show year or month+year of date.

### ISSUE THREAD

**Issue by peterpal00** [AmruthPillai/Reactive-Resume#925]
**Problem:**
The generated CV contains dates. In some cases full dates can be unnecessary or confidental. 
Example 1: I don't want to reveal my exact birthday. Furthermore except the year the other date components(month, day) are unnecessary.
![image](https://user-images.githubusercontent.com/79217606/174902053-1c27f710-faa2-4d1b-976b-bd5a66c358a3.png)

Example 2: In section work experience or education the day is completely unnecessary.
![image](https://user-images.githubusercontent.com/79217606/174902157-e1ecc39d-1e8a-49a8-b800-8762b4be5b5c.png)

 
**Solution**
To every object which has a date would belong 3 checkmarks. Year, month, day. You can check which ones would you like to display.

**Comment by fhjo3** [comment]
I'm new to reactive-resume, but here's what I did.  
You can handle the work experience dates(not sure about birthday.  That's TMI as far as I am concerned and would never show that) I found by using the right side pane(< in top right), then select settings(sprocket icon) and change format.  I currently have mine to YYYY.  I'm not even sure the specific dates is why I chose just years on mine.  I do agree that the check boxes on about every field to show/hide from the current resume would be a huge plus.  Make a master, but then select/un-select what you want for each modified resume. 

![Screen Shot 2022-06-22 at 3 39 34 PM](https://user-images.githubusercontent.com/77463595/175131943-33b171f3-2293-4adb-8353-e406b283bc2b.png)

**Comment by fhjo3** [comment]
Also I am using tealhq to manage my hunt, if it helps you.  Their resume builder is still being completed for what I want as far as resume.  the rest looks good though.
