### ISSUE TITLE
Customizable Blocks[Feature] 

### ISSUE THREAD

**Issue by n-goyal** [AmruthPillai/Reactive-Resume#93]
As of now i couldn't find any functionality to customize different blocks in resume. Resume varies person to person, profession to profession and that's why customizable blocks, I think, are must to have when target is a larger audience.

There can be one Option in settings to enable or disable or to create some blocks as per the user requirement, there is no doubt this would enable a larger set of people to actually customize the resume.

Now, I know the templates have already been defined in the system. which is why i think there is no option to customizable blocks. But one or two flexible, basic templates can be added. And if user adds a new block that block can be appended in the last.

Anyway, I love your app and documentation both. <3

**Comment by AmruthPillai** [comment]
Merging with #90 as both are quite similar in terms of implementation. Will reply to your query there, thank you so much @n-goyal :)
