### ISSUE TITLE
[FEATURE] Looking for ARM support to self host on a Raspberry pi 4

### ISSUE THREAD

**Issue by ajnasaboobacker** [AmruthPillai/Reactive-Resume#934]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmruthPillai** [comment]
Unfortunately, the printer service makes use of the playwright library, which doesn't officially support an ARM version at this time. So until this changes, I wouldn't be able to make an ARM version of Reactive Resume either.

**Comment by Kraktoos** [comment]
Now playwright does support ARM. Will Reactive Resume support ARM soon?
