### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by prashantkr006** [AmruthPillai/Reactive-Resume#940]
**Describe the bug**

In the body of resume whenever I am adding the data like when I am writing work experience and rest of the data it is just getting addd in the left part of resume only not in he whole page

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by AmruthPillai** [comment]
You would need to move your work experience section to another layout column (in the layout section on the right sidebar). This way, you can mix-match any layout design you like :)
