### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gunmax58** [AmruthPillai/Reactive-Resume#941]
**Describe the bug**
When I export my résumé dates are not the same in the PDF and JSON, they are 1 day before the date I put on my resume.
Only the first date in my jobs experiences is correct, also the other are from the day before even the birthdate.

**Product Flavor**
- https://rxresu.me

**To Reproduce**
1. Put a date
2. Export to PDF
3. See the difference between the original and the PDF

**Expected behavior**
Have the same dates as on the résumé

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home 10.0.19044 Build 19044
 - Browser: Mozilla Firefox
 - Version: 102.0.1 (64 bits)

**Additional context**

**Comment by AmruthPillai** [comment]
This should be fixed as of v3.5.0 :)
