### ISSUE TITLE
[BUG] with date of birth

### ISSUE THREAD

**Issue by RohteQ** [AmruthPillai/Reactive-Resume#943]
**Describe the bug**

When download the CV 
the date of birth in the PDF file is shown the day before. conditionally birthday June 28. a shows 27
**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'the CV editor'
2. Click on 'date of birth'
3. Scroll down to 'the button download pdf'
4. See error in date of birth

**Expected behavior**

The correct date

**Screenshots**

![image](https://user-images.githubusercontent.com/104956752/179360341-c98ac827-b23c-4717-ba83-03549d234206.png)
![image](https://user-images.githubusercontent.com/104956752/179360383-4ae43569-7006-4c58-8a4c-7a9a7f9c896b.png)

**Desktop (please complete the following information):**
 - OS:  Window
 - Browser  Chrome 
 - Version  103.0.5060.114

**Additional context**

**Comment by AmruthPillai** [comment]
This should be fixed as of v3.5.0 :)
