### ISSUE TITLE
What happened to old templates?

### ISSUE THREAD

**Issue by kameshkotwani** [AmruthPillai/Reactive-Resume#945]
I have been using rx resume for quite a while now, but my resume is built on the older version of the template which is not available in the current verison and it breaks up the layout. Is there any way we can still use old templates? please let me know if someone has information about this. 

Thanks!

**Comment by ninja-1337** [comment]
Having similar problems importing from an old .json file

**Comment by AmruthPillai** [comment]
You can make use of https://v2.rxresu.me for the time being :)

**Comment by kameshkotwani** [comment]
Thanks!

**Comment by mbertolaccini** [comment]
Hi! Could anyone tell me if there is a way i can use the previous templates? i have the same problem like @kameshkotwani
Thanks in advance.
