### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by parkel42** [AmruthPillai/Reactive-Resume#949]
**Describe the bug**
If the date is input as (example) 01 Dec 2021, it will get offset by one month to 01 Nov 2021 upon exporting to PDF. 

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Input work experience and the relevant dates.
2. Export PDF.
3. Dates get offset by one month. 

**Expected behavior**
Dates should not get offset by one month.

**Screenshots**

Screenshot from rxresu.me:
![rxresume screenshot](https://user-images.githubusercontent.com/50959479/179762519-6a3bb528-fa5c-457e-a67d-87c59c9b2d05.png)

Input data (edited category):
![input](https://user-images.githubusercontent.com/50959479/179762528-9583286e-ce8a-491d-9334-b194e6b9106d.png)

Exported PDF:
![pdf export](https://user-images.githubusercontent.com/50959479/179762531-ce8a00ae-c6a7-4521-adff-d752683b489e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser : Firefox
 - Version : 102.0.1

**Additional context**

**Comment by AmruthPillai** [comment]
This should be fixed as of v3.5.0 :)
