### ISSUE TITLE
[BUG] Export as PDF webapp dates showing weird symbols

### ISSUE THREAD

**Issue by srlach** [AmruthPillai/Reactive-Resume#954]
**Describe the bug**
When trying to export resume as PDF using the IBM Plex Sans font (I tried a couple of mono fonts) the dates are showing up as strange symbols.

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Add work experience
2. Add whatever start date
3. Leave the end date blank
4. Add
5. Set the font to "IBM Plex Sans"
6. Export as PDF

**Expected behavior**

I expected - (Month, Day, Year - Present).

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/11329679/181648140-a107abcc-30ec-4f97-a05e-9bb274117b0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Firefox Nightly 64-bit / Chrome 64-bit
 - Version 105.0a1 / 103.0.5060.134 

**Additional context**
N/A

**Comment by AmruthPillai** [comment]
What language do you have selected?

**Comment by srlach** [comment]
English

**Comment by srlach** [comment]
When i swapped from a random language and back to english, the PDF export looked good. So I was able to workaround. It only affected the (start - end dates). I tried to recreate but was unable to.

**Comment by AmruthPillai** [comment]
There must have been a mismatch in the language on your local copy and the one on the database. I was just going to suggest change the language to something else and change it back to your own and it would be synced. Glad it worked out :)
