### ISSUE TITLE
[INFO] Discontinuing the Documentation (docs.rxresu.me) due to increased usage

### ISSUE THREAD

**Issue by AmruthPillai** [AmruthPillai/Reactive-Resume#955]
Hey folks!

This is just to inform that the website on https://docs.rxresu.me would be discontinued from today as it was taking up a lot of bandwidth and incurred a lot of usage costs on the server.

I was able to cover it for a while with my own savings and the few donations that come in, but it just wasn't enough, so I had to take down the website. If you'd still like to browse through the docs, right now the only way would be to clone the repository, build the docs project and run in locally.

I understand that this is an inconvenience, but one that just had to be done.
Apologies 🙏🏻

**Comment by uhuang** [comment]
I'd like to build the docs project from source to be able to access the documentation, but unfortunately, the [Build From Source](https://github.com/AmruthPillai/Reactive-Resume#build-from-source) part of the readme links to the docs, so I'm not too sure how to do so. Would it be possible to update that part of the readme with basic instructions?

**Comment by AmruthPillai** [comment]
@uhuang You can simply clone the project, run `pnpm install`, then `pnpm run dev` and you should have the docs running on port 3200.

**Comment by AmruthPillai** [comment]
Currently exploring GitBook as an alternative to host and collaborate on documentation.

**Comment by AmruthPillai** [comment]
The docs have now been migrated to GitBook, accessible on the same link as before: https://docs.rxresu.me
