### ISSUE TITLE
[BUG] Unable to build

### ISSUE THREAD

**Issue by AlexTu2** [AmruthPillai/Reactive-Resume#959]
**Describe the bug**

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

Run docker-compose build

**Expected behavior**

Expect built containers

**Screenshots**

![image](https://user-images.githubusercontent.com/6798052/182452570-1e44a498-8857-4161-bc40-bcb216eba388.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS

**Additional context**

` at-ubuntu@ubuntu-dock  ~/Reactive-Resume   main ±  pnpm run build:client

> reactive-resume@3.5.1 build:client /home/at-ubuntu/Reactive-Resume
> pnpm -F client build

> @reactive-resume/client@ build /home/at-ubuntu/Reactive-Resume/client
> next build && npm run sitemap

info  - Linting and checking validity of types .Failed to compile.

./config/theme.ts:54:27
Type error: Expression produces a union type that is too complex to represent.

  52 | });
  53 |
> 54 | export const lightTheme = createTheme({
     |                           ^
  55 |   ...theme,
  56 |   palette: {
  57 |     mode: 'light',

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/at-ubuntu/Reactive-Resume/node_modules/.pnpm/next@12.2.3_ckhwt5v7fywslkplh6p4u2aony/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/home/at-ubuntu/Reactive-Resume/node_modules/.pnpm/next@12.2.3_ckhwt5v7fywslkplh6p4u2aony/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
info  - Linting and checking validity of types ./home/at-ubuntu/Reactive-Resume/client:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @reactive-resume/client@ build: `next build && npm run sitemap`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)
