### ISSUE TITLE
[BUG] Links to docs & FAQ are broken

### ISSUE THREAD

**Issue by filcuk** [AmruthPillai/Reactive-Resume#960]
**Describe the bug**
rxresu.me links are broken (404):
- https://rxresu.me/faq
- https://docs.rxresu.me/

**Screenshots**
Docs:
![image](https://user-images.githubusercontent.com/1339532/182455963-f350dc7a-ee24-4ff1-a278-16499d1f6831.png)
FAQ:
![image](https://user-images.githubusercontent.com/1339532/182455997-5b360461-2b9b-4105-8c88-86f333317f92.png)

**Comment by AlexTu2** [comment]
Intended, see #955

**Comment by filcuk** [comment]
Ah, understandable.
It can still be accessed through the code anyway.
