### ISSUE TITLE
[BUG] Birth date is early by one day

### ISSUE THREAD

**Issue by attapun-an** [AmruthPillai/Reactive-Resume#962]
**Describe the bug**
Date of birth shows 1 day before the actual date
**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Setting a birth date as your actual birth date  

**Expected behavior**
1. The birth date to be what has been put on the form and not one day behind 

**Screenshots**
![image](https://user-images.githubusercontent.com/22782373/182976664-da6120ef-1235-42df-98f5-aaf253720000.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 103.0.5060.134 (Official Build) (64-bit)

**Additional context**

**Comment by Artalus** [comment]
Probably this is a part of more "global" date problem. I use only month names in work experience and education, and had months there magically switched to one previous for some reaso when resume was exported to pdf. Changing the dates from `MM/01/YYYY` to `MM/02/YYYY` helped.

**Comment by AmruthPillai** [comment]
Could you verify whether this still occurs?

**Comment by Artalus** [comment]
Yes.

![изображение](https://user-images.githubusercontent.com/10381253/187191629-c7fb85d4-9393-496c-8518-999ca7a19487.png)
On the left is the section on https://rxresu.me/ , on the right - in exported PDF. The period is set to `09/01/2012 - 07/01/2016` and the date format is `MMMM YYYY`.
And here is the same section with date format set to `MM/DD/YY`:
![изображение](https://user-images.githubusercontent.com/10381253/187193587-41ec7c36-af8c-497f-a42b-0d41e27b7d9d.png)

**Comment by AmruthPillai** [comment]
@Artalus Just for debugging and trying to verify the issue: Could you possibly edit the education row, modify the date using the UI and try exporting the PDF again? Locally, I tried this on a new resume with 3 different timezones (US, Germany and India) and it worked alright. I think the change I made only affects newly created date objects.

If you could help verify this for me, I can make the appropriate migration.

**Comment by Artalus** [comment]
I tried
- re-exporting PDF as is
- switching just the end date forth and back
- switching both dates to a month further
- creating new education experience item
- hitting Ctrl+F5 and creating a brand new resume

Still no luck (left in editor, right in pdf):
![изображение](https://user-images.githubusercontent.com/10381253/187233341-b74298ae-d577-464d-acb2-7dddb753f03d.png)

**Comment by amanrajOO7** [comment]
For me the Date on Education & Experience Section is fine but the DOB is early by one day.

**Comment by attapun-an** [comment]
Aye, I think the error no longer occurs. I'll close the issue
