### ISSUE TITLE
docs.rxresu.me returning 404 and crashing self-hosted site

### ISSUE THREAD

**Issue by ajm1014** [AmruthPillai/Reactive-Resume#963]
**Describe the bug**
https://docs.rxresu.me/ is returning a 404, leading to a health check failure on the server docker container and the site throwing an error.

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [X] Self Hosted

**To Reproduce**
1. Restart docker container
2. Try to browse to site
3. View logs from server container

**Expected behavior**
Site loads without error

**Screenshots**
Server logs:

> reactive-resume@3.5.2 start:server /app
> pnpm -F server start:prod

> @reactive-resume/server@ start:prod /app/server
> node dist/main

[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [NestFactory] Starting Nest application...
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +61ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] MailModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] MulterModule dependencies initialized +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] CacheModule dependencies initialized +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ServeStaticModule dependencies initialized +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] HealthModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] MailModule dependencies initialized +2ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] JwtModule dependencies initialized +41ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] PrinterModule dependencies initialized +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] FontsModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +101ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] ResumeModule dependencies initialized +2ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [InstanceLoader] IntegrationsModule dependencies initialized +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RoutesResolver] AuthController {/auth}: +4ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth, GET} route +2ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth/google, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth/register, POST} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth/login, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth/forgot-password, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth/reset-password, POST} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/auth, DELETE} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RoutesResolver] ResumeController {/resume}: +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume, GET} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/short/:shortId, GET} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:username/:slug, GET} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id, GET} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id, PATCH} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id, DELETE} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id/duplicate, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id/sample, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id/reset, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id/photo, PUT} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/resume/:id/photo, DELETE} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RoutesResolver] FontsController {/fonts}: +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/fonts, GET} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RoutesResolver] IntegrationsController {/integrations}: +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/integrations/linkedin, POST} route +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/integrations/json-resume, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/integrations/reactive-resume, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/integrations/reactive-resume-v2, POST} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RoutesResolver] PrinterController {/printer}: +1ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/printer/:username/:slug, GET} route +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RoutesResolver] HealthController {/health}: +0ms
[Nest] 42  - 08/05/2022, 8:10:27 AM     LOG [RouterExplorer] Mapped {/health, GET} route +0ms
[Nest] 42  - 08/05/2022, 8:10:28 AM     LOG [NestApplication] Nest application successfully started +1242ms
[Nest] 42  - 08/05/2022, 8:10:28 AM     LOG 🚀 Server is up and running!
[Nest] 42  - 08/05/2022, 8:10:57 AM   ERROR [HealthCheckService] Health Check has failed! {"database":{"status":"up"},"app":{"status":"up"},"docs":{"status":"down","message":"Request failed with status code 404","statusCode":404,"statusText":"Not Found"}}

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version 1.41.100

**Comment by kgotso** [comment]
This is causing an issue on self hosted instances as the server is hardcoded to ping docs.rxresu.me and if not available it causes the server health checks to fail and render the backend unavailable. The self hosted version should not be forced to ping home

**Comment by AmruthPillai** [comment]
You're right about that, mistake on my part to include the health check to check the managed app. Should have rather been a env URL. Thank you for the PR :)

**Comment by coderhs** [comment]
@AmruthPillai Can you release new docker images, they are currently broken due to this issue.
