### ISSUE TITLE
Is this rx-resume site affiliated with Reactive Resume?

### ISSUE THREAD

**Issue by nick-walt** [AmruthPillai/Reactive-Resume#964]
Hi creators of Reactive Resume, is this domain yours?

https://rx-resume.web.app/

If so, the new-line and nested lists markdown doe not appear to be working - among other markdown functions.

Cheers, and thanks!

**Comment by pronoym99** [comment]
No, they are not associated in any way with Reactive Resume. You can import a reactive resume in rx-resume though.

**Comment by AmruthPillai** [comment]
Actually it is the same Reactive Resume, but one of the very first and initial versions of the app.

I have had 2 earlier versions, https://v1.rxresu.me and https://v2.rxresu.me

There's no more support for these versions anymore, but those who continue to maintain their resume on the platform could have a way to do so.
