### ISSUE TITLE
[BUG] Work Experience Role and Duration layout is broken

### ISSUE THREAD

**Issue by SubhadipJot** [AmruthPillai/Reactive-Resume#966]
Attaching screenshot of the issue

![rxresu_issue](https://user-images.githubusercontent.com/28902455/183947906-0b0ec1ba-605b-44e8-bc38-fb7f5e256d2b.png)

**Comment by AmruthPillai** [comment]
What do you feel is broken in the layout? It actually does look like it's supposed to. Maybe you were expecting another design?
