### ISSUE TITLE
Replace Google services with FLOSS alternatives

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [AmruthPillai/Reactive-Resume#97]
**Is your feature request related to a problem? Please describe.**
When trying to use your website with ad or script blockers, such as uBlock Origin, uMatrix or NoScript, the website breaks unless you allow GStatic and Google Fonts to work, which can be detrimental to users' privacy, and in recent years one of the main interests of open source software is to fight back mass surveillance.

**Describe the solution you'd like**
To use FLOSS alternatives that could replace G services.

**Describe alternatives you've considered**
Below you will see a list of options from where you could choose, I recommend you Fork Awesome (and maybe the Open Font Library, although I do not know if they work in the same way) in the best case scenario, and Font Awesome in a better case scenario.
https://alternativeto.net/software/google-web-fonts/?license=opensource
https://alternativeto.net/software/font-awesome/?license=opensource
https://fontlibrary.org/
https://forkaweso.me/Fork-Awesome/
https://fontawesome.com/

**Additional context**
Screenshot of how it looks: https://upload.vaa.red/3TuL4#a29e7189af55bdeb9b237c9f4686e787

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Are you considering this? I know you might be busy and that you have a life, I don't want this to be implemented right now, just to know if it will happen. After all it's not that privacy respecting if it's full of Big G services.

Thanks for your hard work!

**Comment by AmruthPillai** [comment]
Yes, I am considering this. You have raised a good point, but moving from Google Material Icons and Google Fonts do break a bit of functionality, I need to spend a bit more time on it. But it's definitely something in the pipeline. 

I'm working on my personal website right now, as well as another template for the resume, so trying to balance projects. I will keep you updated on the progress of this issue :) Thank you so much for the constant support and raising feedback through issues. It really means a lot.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Don't worry about how long does it take, as long as it is something that you think it's worth from a privacy standpoint and you support the cause.

Don't worry, when I see a good project that deserves feedback, I try to chip in!

**Comment by AmruthPillai** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe I'm happy to inform you, that after 12 days of opening the issue, this is finally resolved 🎉

Sorry that it took a while, but I hope it was worth it :) I've self-hosted everything now, the animation library, the fonts, the icons. There should be no external HTTP requests made now (except for Google Analytics, which can be blocked through using extensions and will not affect performance of the app).
