### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ehafizoglu** [AmruthPillai/Reactive-Resume#971]
**Describe the bug**

If you wrote already something on a new CV from scratch when you click the "Load Sample Data" button then
they are all gone. There isn't any option that you can save your contents. (Like Ctrl + Z)

**Product Flavor**
- [ X ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

Write something about you, your education etc.
1. Go to 'Resume' section
2. Click on 'Load Sample Data'
3. See the results.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: <!MacOS-->
 - Browser 
 - Version 

**Additional context**

**Comment by AmruthPillai** [comment]
This has been implemented now, in the latest version of the app.

**Comment by hminh2027** [comment]
> This has been implemented now, in the latest version of the app.

I'm having the same problem and still can not use Ctrl + Z or undo after selecting the 'Load Sample Data' button. Can you be more specific? Thank you
