### ISSUE TITLE
[BUG] New line is not starting after bullet point, it is starting exactly below the bullet point

### ISSUE THREAD

**Issue by keshavjha06** [AmruthPillai/Reactive-Resume#973]
Hello @AmruthPillai 

New line is not starting after bullet point, it is starting exactly below the bullet point

Previously, the new line used to start exactly below the text of previous line.Now it starting exactly below the bullet.

**See the below images for your reference**

<img width="509" alt="Screenshot 2022-08-15 at 1 37 44 PM" src="https://user-images.githubusercontent.com/64794954/184599927-9926aef3-29fb-4458-b81f-8efb7470a9aa.png">

<img width="397" alt="Screenshot 2022-08-15 at 1 39 43 PM" src="https://user-images.githubusercontent.com/64794954/184599961-a7ecf99b-8f45-4c11-b2b5-45d453ea3e42.png">

**Comment by bhavya-tech** [comment]
I found a temporary fix. Add this CSS code to the custom CSS section.

```
ul {
  list-style: none;
  margin-left: 0;
  padding-left: 1em;
  text-indent: -1.45em;
}
```

**Comment by keshavjha06** [comment]
Thank you @bhavya-tech :) Its working as expected.

**Comment by bhavya-tech** [comment]
I think the bug should be kept open as this is a temporary fix. To make it work properly, one would have to add this code to every resume.

**Comment by keshavjha06** [comment]
> 

Sure Bhavya

**Comment by AmruthPillai** [comment]
This style is now added to the base CSS styles, so you would not need to apply it manually on every resume anymore.
