### ISSUE TITLE
[BUG] Google returned an error while trying to sign in: opt_out_or_no_session.

### ISSUE THREAD

**Issue by abhijit-hota** [AmruthPillai/Reactive-Resume#975]
**Describe the bug**

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Click "Login with Google"

**Expected behavior**
Google sign-in should popup

**Screenshots**
![image](https://user-images.githubusercontent.com/8116174/185296333-44fbf540-70b1-4db5-b2a0-df77a69fe760.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser Firefox (also tried with Chrome)
 - Version 102

**Additional context**
Tried disabling NextDNS and uBlock to no avail.

**Comment by abhijit-hota** [comment]
Would be really grateful if you can look at this and suggest workarounds/solutions as I'm not able to access and edit my resume. I need to do it ASAP to apply for a position.

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)

**Comment by abhijit-hota** [comment]
Still facing the issue unfortunately.

**Comment by AmruthPillai** [comment]
I don't think the deployment went through yet. You can verify when you're on the right version by checking the site footer.

**Comment by abhijit-hota** [comment]
I see. Thanks a lot! It's fixed now (v.3.6.1)
