### ISSUE TITLE
Docs not available ?

### ISSUE THREAD

**Issue by rlabrach** [AmruthPillai/Reactive-Resume#977]
**Describe the bug**
when i click on Docs i have this message : 404: NOT_FOUND

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'https://docs.rxresu.me/'
2. Click on 'docs'

![image](https://user-images.githubusercontent.com/83596714/185754411-a3c1698b-205e-4fe8-9186-051a552dec59.png)

**Comment by AmruthPillai** [comment]
I've provided an explanation as to why the docs are no longer available here: https://github.com/AmruthPillai/Reactive-Resume/issues/955
