### ISSUE TITLE
Add an option to clasify your language knowledge with real values

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [AmruthPillai/Reactive-Resume#98]
**Is your feature request related to a problem? Please describe.**
If you are studying a language, the general hierarchy in where you are classified according to your knowledge is A1-A2 for begginers, B1-B2 for intermediate, and C1-C2 for experts. This can change a bit depending on the language, for example, Japanese uses a grading that starts at N1 and ends at N5.

**Describe the solution you'd like**
The best solution would be to allow users to choose between the current method, which is a selection button which starts at 1 and ends at 5 (for people who may have never taken an exam, but whose level could be more or less identified with a more ambiguous structure), and an option to create a text box where you can write the level you are at.

**Describe alternatives you've considered**
Does not apply.

**Additional context**
https://en.wikipedia.org/wiki/List_of_language_proficiency_tests
https://en.wikipedia.org/wiki/Japanese-Language_Proficiency_Test#Test_format

**Comment by jamesrweb** [comment]
Bumping this because it's a great point 👍!

**Comment by AmruthPillai** [comment]
Heard you guys loud and clear, this has been implemented in #105.
Hope this helps :)

![image](https://user-images.githubusercontent.com/1134738/79464599-e43c9480-8017-11ea-9ca2-ad7722646778.png)

**Comment by jamesrweb** [comment]
Nice work @AmruthPillai, very much appreciating your quick feedback to issues!

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Thanks a lot for taking so little to implement this, you are awesome!
