### ISSUE TITLE
[FEATURE] add a undo feature

### ISSUE THREAD

**Issue by Ryukendo25** [AmruthPillai/Reactive-Resume#982]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmruthPillai** [comment]
Technically, it should be possible by integrating https://github.com/omnidan/redux-undo into the app, but I'm guessing that would break a lot of the existing state accessors that are currently implemented.

I know this is quite a widely suggested feature. Will look into it this weekend and see if I can get it out there ASAP.

**Comment by AmruthPillai** [comment]
This has now been implemented in v3.6.2 🔥

**Comment by barrelltitor** [comment]
And how do you use it?

**Comment by amruthpillai** [comment]
@barrelltitor you can either press Ctrl + Z, or there's an Undo button on the floating toolbar where you see your resume.
