### ISSUE TITLE
[FEATURE] Allow dates to only be month-year, without a day (eg. April 2022)

### ISSUE THREAD

**Issue by pvinis** [AmruthPillai/Reactive-Resume#983]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmruthPillai** [comment]
Does this not work for your use case?

![Screenshot 2022-08-26 at 12 57 36 PM](https://user-images.githubusercontent.com/1134738/186889264-33116297-6ff6-4416-8e30-ffc69f9147c1.png)
