### ISSUE TITLE
[BUG] compatibility is dead

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [AmruthPillai/Reactive-Resume#984]
So I used rxresume from long time, I logged in with my google account (before even you can login with email) and now I want to edit my resume but to find out that google sign in app has changed and that goes with all of my data! when I created new account to import my exported pdf, I could not import it because the app only accept json and now I'm stuck with un-editable pdf file

I won't lie I'm super mad and I need help to solve it

**Comment by EsmailELBoBDev2** [comment]
And two things about login/signup:
* Sign up when you use already registered email it does not show error message, you have to see what google will send you in console log/tools
* login only accepts emails? tried with username but it did not work

**Comment by AmruthPillai** [comment]
It's true that the way to sign in with Google has changed, but if you were to login with the same google account, you would still get back to the same data. I was able to access my existing account, when signing in with Google.

I understand the frustration, really. Will do what I can to resolve this for you. Could you share your email address (and/or resume ID) with me over email? You can send it to im.amruth@gmail.com. I'll try to figure out if the account linking is disabled.

**Comment by EsmailELBoBDev2** [comment]
Okay so I tried to log in, but it threw me to new account not old one. And I did something I think it's worth of mention and that when both google sign in apps did not get my old data I removed them from my account (from https://myaccount.google.com/permissions) so I'm unsure did I just kill my last hope or not. 

Send the email :+1: :smile:

**Comment by EsmailELBoBDev2** [comment]
Okay will leave it for future me or someone else in same position.

You need to sign in from https://v2.rxresu.me/, go to your resume and export it as json then go to https://rxresu.me/ and import select import json but  **json v2** and yup now you have your old resume inside the new version!

Source: from emails with `@AmruthPillai `

**Comment by 3v1n0** [comment]
> You need to sign in from https://v2.rxresu.me/, go to your resume and export it as json then go to https://rxresu.me/ and select import json but json v2 (it will be last 2 buttons in bottom) and yup now you have your old resume inside the new version!

Is this still available somewhere? I would like to export an old resume that I have in PDF format and that it was possible to edit inline before.
