### ISSUE TITLE
[Birthday is not Getting displayed properly] 

### ISSUE THREAD

**Issue by Anic10x3** [AmruthPillai/Reactive-Resume#987]
**Birthdate not getting displayed properly**

**Product Flavor**
ALL Apps

- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

1) Select Birthdate , the format is MM-DD-YYYYY. 
Ex: My birthdate is 10th Oct 1995, so I need to select 10(Month)-11(Day) -1995(Year) in the app, to get the date perfect. It is always showing one day less.

**Screenshots**
![image](https://user-images.githubusercontent.com/65605001/187061451-be5ecc83-40be-472b-99f0-8e3c3595f024.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome
- Version - 104.0.5112.102

**Comment by kgotso** [comment]
![image](https://user-images.githubusercontent.com/2615701/187278161-2395ffeb-455e-4ba0-9f21-f9e6823e4124.png)
Bottom right you can set the date format

**Comment by lijie97** [comment]
Same problem, the date has one day's error sometimes

**Comment by huzheyi** [comment]
if you are running it by docker, add your own timezone to the `docker-compose.yaml` and `.env` file.

e.g.


*in `docker-compose.yaml` both server and client container section*

````
environment:
      - TZ=Asia/Shanghai
````

*in `docker-compose.yaml` prostre container section*
````
environment:
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
````

*in `.env` file*
````
- TZ=Asia/Shanghai
````
