### ISSUE TITLE
Markdown support in Work Experience - Summary doesn't work[BUG] 

### ISSUE THREAD

**Issue by selmanfarisi** [AmruthPillai/Reactive-Resume#993]
When I add indented unordered items like below
- First item
- Second item
- Third item
	- Indented item
	- Indented item
- Fourth item

It doesn't show the indented elements as indented. See the screenshot below.
https://www.markdownguide.org/basic-syntax/#unordered-lists

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Create a Work Experience
2. Fill related fields
3. Add undordered list to the summary section with markdown support
4. Go back to the preview
5. Unordered list doesn't show any indentation

**Expected behavior**
Indentation should be visible

![image](https://user-images.githubusercontent.com/15236871/188312960-55d9d994-8d31-442e-80cb-d6a073cc9003.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/15236871/188312711-b27076ec-81a4-45bb-bbed-67f9e0da1a09.png)

**Desktop (please complete the following information):**

- OS: windows 11
- Browser chrome
- Version 104.0.5112.102

**Comment by minez0** [comment]
I also have the same issue in the self-hosted version as well

**Comment by AmruthPillai** [comment]
Will look into this soon, thank you for creating an issue for it :)

**Comment by indivisionjoe** [comment]
Same issue here. I've tried spaces and tabs. It always defaults to a single list.

**Comment by Jitishcfd** [comment]
Has this issue been resolved? 
I was having a similar issue when the bullet point is multiple lines, the next line will not align with bullet point.

**Comment by AmruthPillai** [comment]
This issue has been resolved now, as of v3.6.9
