### ISSUE TITLE
[BUG] Export resulting in 404

### ISSUE THREAD

**Issue by asmaps** [AmruthPillai/Reactive-Resume#995]
**Describe the bug**

Export/Download pdf ends in 404

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Create a CV
2. Click Download PDF
3. get a pdf which actually contains html of a 404 page (network tab also shows a 404)

**Expected behavior**

Get a pdf

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Brave
- Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)

Self hosted with docker, no difference when using local storage or s3 variant

Also I checked inside the container and the export directory /app/server/dist/assets/exports/ is still empty.
No errors or log on the console/docker logs.

**Comment by Death-Pact** [comment]
Getting similar error. PDF exports to a small file displaying 404 code and will not open inside acrobat or in a browser stating it is improperly decoded. Using docker/brave/newest docker image just like OP.

My export volume is also empty. Logs do not throw error.

**Comment by AmruthPillai** [comment]
This should be fixed now, as of v3.6.6
