### ISSUE TITLE
[FEATURE] Add links directly to description of projects

### ISSUE THREAD

**Issue by MashymAli** [AmruthPillai/Reactive-Resume#999]
**Is your feature request related to a problem? Please describe.**

I can't find the feature where you can just add links to your project's description. 

**Describe the solution you'd like**

There is an option to add the link after the project description but it will look better and also save space on the resume if one can go to the link when clicking on the description.

**Comment by AmruthPillai** [comment]
You can add a link using [markdown](https://www.markdownguide.org/basic-syntax/)

The syntax is like this:
```
[Text of the link](https://website.com)
```
